/**
 * 
 */
package org.paradyne.sql.loan;

import org.paradyne.lib.SqlBase;

/**
 * @author tarunc
 *
 */
public class LoanApplicationModelSql extends SqlBase {

	public String getQuery(int id){
		switch (id) {
		case 1 : return "SELECT EMP_CENTER, NVL(HRMS_CENTER.CENTER_NAME, ' '), EMP_DEPT, NVL(HRMS_DEPT.DEPT_NAME, ' '), "
						+"EMP_RANK, NVL(HRMS_RANK.RANK_NAME, ' '), TO_CHAR(EMP_REGULAR_DATE, 'DD-MM-YYYY'), EMP_CADRE, "
						+"NVL(HRMS_CADRE.CADRE_NAME, ' '), EMP_TOKEN, HRMS_EMP_OFFC.EMP_FNAME||' '||HRMS_EMP_OFFC.EMP_MNAME||' '||"
						+"HRMS_EMP_OFFC.EMP_LNAME, HRMS_EMP_OFFC.EMP_ID,NVL(SAL_PFTRUST_FLAG,'N') ,EMP_DIV,DIV_NAME "
						+"FROM HRMS_EMP_OFFC "
						+"LEFT JOIN HRMS_CENTER ON (EMP_CENTER = HRMS_CENTER.CENTER_ID) "
						+"LEFT JOIN HRMS_DEPT ON (EMP_DEPT = HRMS_DEPT.DEPT_ID) "
						+"LEFT JOIN HRMS_RANK ON (EMP_RANK = HRMS_RANK.RANK_ID) "
						+"LEFT JOIN HRMS_CADRE ON (HRMS_EMP_OFFC.EMP_CADRE = HRMS_CADRE.CADRE_ID) "
						+"LEFT JOIN HRMS_SALARY_MISC ON(HRMS_SALARY_MISC.EMP_ID=HRMS_EMP_OFFC.EMP_ID)"
						+"LEFT JOIN HRMS_DIVISION ON (HRMS_DIVISION.DIV_ID = HRMS_EMP_OFFC.EMP_DIV)"
						+"WHERE HRMS_EMP_OFFC.EMP_ID = ?";
		
		case 2 : return "INSERT INTO HRMS_LOAN_APPLICATION (LOAN_APPL_CODE, LOAN_EMP_ID, LOAN_CODE, LOAN_APPL_DATE, "
						+"LOAN_AMOUNT, LOAN_APPL_STATUS, LOAN_RECOMMENDED_BY, LOAN_GUARANTOR_ONE, LOAN_GUARANTOR_TWO, " 
						+"LOAN_APPL_APPROVER, LOAN_APPL_LEVEL,LOAN_PF_TYPE,LOAN_PURPOSE,LOAN_APPL_ALTER_APPROVER, LOAN_APPLICANT_COMMENT) VALUES "
						+"(?, ?, ?, TO_DATE(?, 'DD-MM-YYYY'), ?, ?, ?, ?, ?, ?, 1, ?, ?,?,?)";
		
		case 3 : return "SELECT HRMS_EMP_OFFC.EMP_CENTER, HRMS_CENTER.CENTER_NAME, HRMS_EMP_OFFC.EMP_DEPT, HRMS_DEPT.DEPT_NAME, "
						+"HRMS_EMP_OFFC.EMP_RANK, HRMS_RANK.RANK_NAME, TO_CHAR(HRMS_EMP_OFFC.EMP_REGULAR_DATE, 'DD-MM-YYYY'), "
						+"HRMS_EMP_OFFC.EMP_CADRE, NVL(HRMS_CADRE.CADRE_NAME, ' '), LOAN_APPL_STATUS, HRMS_LOAN_APPLICATION.LOAN_CODE, "
						+"LOAN_NAME, LOAN_AMOUNT, LOAN_RECOMMENDED_BY, RECOM.EMP_TOKEN, RECOM.EMP_FNAME||' '||RECOM.EMP_MNAME||' '||RECOM.EMP_LNAME RECOMMENDED_BY, "
						+"LOAN_GUARANTOR_ONE, GUARANTOR1.EMP_TOKEN, GUARANTOR1.EMP_FNAME||' '||GUARANTOR1.EMP_MNAME||' '||GUARANTOR1.EMP_LNAME FIRST_GUARANTOR, "
						+"LOAN_GUARANTOR_TWO, GUARANTOR2.EMP_TOKEN, GUARANTOR2.EMP_FNAME||' '||GUARANTOR2.EMP_MNAME||' '||GUARANTOR2.EMP_LNAME SECOND_GUARANTOR, "
						+"LOAN_APPL_LEVEL, TO_CHAR(LOAN_APPL_DATE, 'DD-MM-YYYY'),LOAN_PF_TYPE, NVL(LOAN_PURPOSE,0),NVL(SAL_PFTRUST_FLAG,'N'),NVL(LOAN_APPLICANT_COMMENT,' ') ," +
								"LOAN_EMI_TYPE, LOAN_INITIATOR_CODE , "
						+ " INITIATOR.EMP_TOKEN||' '||INITIATOR.EMP_FNAME || ' ' || INITIATOR.EMP_MNAME || ' ' || INITIATOR.EMP_LNAME AS INITIATOR_NAME, "
						+ " TO_CHAR(LOAN_APPL_DATE,'DD-MM-YYYY HH24:MI') ,LOAN_TRACKING_NUMBER ,HRMS_EMP_OFFC.EMP_DIV,DIV_NAME  "
						+"FROM HRMS_LOAN_APPLICATION "
						+"LEFT JOIN HRMS_EMP_OFFC ON (HRMS_LOAN_APPLICATION.LOAN_EMP_ID = HRMS_EMP_OFFC.EMP_ID) "
						+"LEFT JOIN HRMS_EMP_OFFC RECOM ON (LOAN_RECOMMENDED_BY = RECOM.EMP_ID) "
						+"LEFT JOIN HRMS_EMP_OFFC GUARANTOR1 ON (LOAN_GUARANTOR_ONE = GUARANTOR1.EMP_ID) "
						+"LEFT JOIN HRMS_EMP_OFFC GUARANTOR2 ON (LOAN_GUARANTOR_TWO = GUARANTOR2.EMP_ID) "
						+"LEFT JOIN HRMS_CENTER ON (HRMS_EMP_OFFC.EMP_CENTER = HRMS_CENTER.CENTER_ID) "
						+"LEFT JOIN HRMS_DEPT ON (HRMS_EMP_OFFC.EMP_DEPT = HRMS_DEPT.DEPT_ID) "
						+"LEFT JOIN HRMS_RANK ON (HRMS_EMP_OFFC.EMP_RANK = HRMS_RANK.RANK_ID) "
						+"LEFT JOIN HRMS_SALARY_MISC ON(HRMS_SALARY_MISC.EMP_ID=HRMS_EMP_OFFC.EMP_ID) "
						+"INNER JOIN HRMS_LOAN_MASTER ON (HRMS_LOAN_APPLICATION.LOAN_CODE = HRMS_LOAN_MASTER.LOAN_CODE) "
						+"LEFT JOIN HRMS_CADRE ON (HRMS_EMP_OFFC.EMP_CADRE = HRMS_CADRE.CADRE_ID) "
						+ "LEFT JOIN HRMS_EMP_OFFC INITIATOR ON(INITIATOR.EMP_ID = HRMS_LOAN_APPLICATION.LOAN_INITIATOR_CODE)"
						+"LEFT JOIN HRMS_DIVISION ON (HRMS_DIVISION.DIV_ID = HRMS_EMP_OFFC.EMP_DIV)"
						+"WHERE LOAN_APPL_CODE = ?"; 
		
		case 4 : return "UPDATE HRMS_LOAN_APPLICATION SET LOAN_EMP_ID = ?, LOAN_CODE = ?, LOAN_APPL_DATE = TO_DATE(?, 'DD-MM-YYYY'), " 
						+"LOAN_AMOUNT = ?, LOAN_APPL_STATUS = ?, LOAN_RECOMMENDED_BY = ?, LOAN_GUARANTOR_ONE = ?, LOAN_GUARANTOR_TWO = ?, "
						+"LOAN_APPL_APPROVER = ?,LOAN_PF_TYPE = ?, LOAN_PURPOSE = ?, LOAN_APPL_ALTER_APPROVER=?, LOAN_APPLICANT_COMMENT=? ,LOAN_EMI_TYPE =? ,LOAN_INITIATOR_CODE = ? ,LOAN_APPL_LEVEL = 1"
						+" WHERE LOAN_APPL_CODE = ?";
		
		case 5 : return "DELETE FROM HRMS_LOAN_APPLICATION WHERE LOAN_APPL_CODE = ?";
		
		case 6 : return "SELECT NVL(SUM(CREDIT_AMT), 0) "
						+"FROM HRMS_EMP_CREDIT "
						+"LEFT JOIN HRMS_CREDIT_HEAD ON (HRMS_CREDIT_HEAD.CREDIT_CODE = HRMS_EMP_CREDIT.CREDIT_CODE) "
						+"WHERE HRMS_EMP_CREDIT.EMP_ID = ? AND HRMS_CREDIT_HEAD.CREDIT_PERIODICITY='M' AND CREDIT_PAYFLAG='Y' ";
		
		case 7 : return " SELECT TO_CHAR(TO_DATE(LOAN_INSTAL_MONTH,'MM'),'MON'),LOAN_INSTAL_YEAR,LOAN_PRINCIPLE_AMT,LOAN_INSTAL_INTEREST,LOAN_INSTAL_AMT,LOAN_BALANCE_PRINCIPAL, "
		+" NVL(LOAN_INSTALLMENT_IS_PAID,'N'),LOAN_INSTAL_DAY FROM HRMS_LOAN_INSTALMENT WHERE LOAN_APPL_CODE=? ORDER BY LOAN_INSTAL_YEAR, LOAN_INSTAL_MONTH, LOAN_PRINCIPLE_AMT";

		default : return "";
		}
	}
}
