/**
 * 
 */
package org.paradyne.sql.loan;

import org.paradyne.lib.SqlBase;

/**
 * @author mangeshj
 *
 */
public class LoanProccessModelSql extends SqlBase {
	public String getQuery(int id){
		switch (id) {
		case 1 : return " SELECT LOAN_APPL_CODE,LOAN_EMP_ID,EMP_TOKEN,(HRMS_EMP_OFFC.EMP_FNAME||' '||HRMS_EMP_OFFC.EMP_MNAME|| ' ' || HRMS_EMP_OFFC.EMP_LNAME),"
						+" CENTER_NAME, DEPT_NAME,TO_CHAR(LOAN_APPL_DATE,'DD-MM-YYYY'),LOAN_NAME,NVL(LOAN_AMOUNT,0) FROM HRMS_LOAN_APPLICATION" 
						+" INNER JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=HRMS_LOAN_APPLICATION.LOAN_EMP_ID)" 
						+" LEFT JOIN HRMS_LOAN_MASTER ON(HRMS_LOAN_MASTER.LOAN_CODE=HRMS_LOAN_APPLICATION.LOAN_CODE) "
						+" INNER JOIN HRMS_CENTER ON(HRMS_CENTER.CENTER_ID=HRMS_EMP_OFFC.EMP_CENTER)"
						+" INNER JOIN HRMS_DEPT ON(HRMS_DEPT.DEPT_ID=HRMS_EMP_OFFC.EMP_DEPT)"
						+" WHERE  LOAN_APPL_CODE =?";
		
		case 2 : return " INSERT INTO HRMS_LOAN_PROCESS (LOAN_APPL_CODE,LOAN_SANCTION_AMOUNT,LOAN_SANCTION_DATE, "
						+" LOAN_PAYMENT_DATE,LOAN_PAYMENT_MODE,LOAN_BANK_NAME,LOAN_CHEQUE_NUMBER,LOAN_INTEREST_RATE, "
						+" LOAN_INTEREST_TYPE,LOAN_INSTALLMENT_START_DATE,LOAN_INTALMENT_NUMBERS,LOAN_SECURITY_DETAILS, "
						+" LOAN_SECURITY_VALUE,LOAN_SUBMISSION_DATE,LOAN_SANCTIONED_BY,LOAN_REQ_EMI_AMOUNT,LOAN_MONHLY_PRINCIPAL,LOAN_EMP_ACCOUNT) VALUES (?,?,TO_DATE(?,'DD-MM-YYYY'),TO_DATE(?,'DD-MM-YYYY'),?,?,?,?,?,TO_DATE(?,'DD-MM-YYYY'),?,?,?,TO_DATE(?,'DD-MM-YYYY'),?,?,?,?)" ;
		
		case 3 : return " UPDATE HRMS_LOAN_PROCESS SET LOAN_SANCTION_AMOUNT=?,LOAN_SANCTION_DATE=TO_DATE(?,'DD-MM-YYYY'),LOAN_PAYMENT_DATE=TO_DATE(?,'DD-MM-YYYY'), "
						+" LOAN_PAYMENT_MODE=?,LOAN_BANK_NAME=?,LOAN_CHEQUE_NUMBER=?,LOAN_INTEREST_RATE=?,LOAN_INTEREST_TYPE=?,LOAN_INSTALLMENT_START_DATE=TO_DATE(?,'DD-MM-YYYY'), "
						+" LOAN_INTALMENT_NUMBERS=?,LOAN_SECURITY_DETAILS=?,LOAN_SECURITY_VALUE=?, "
						+" LOAN_SUBMISSION_DATE=TO_DATE(?,'DD-MM-YYYY'),LOAN_SANCTIONED_BY=?,LOAN_REQ_EMI_AMOUNT=?,LOAN_MONHLY_PRINCIPAL=? ,LOAN_EMP_ACCOUNT=? WHERE LOAN_APPL_CODE=? ";
		
		case 4 : return "SELECT HRMS_LOAN_PROCESS.LOAN_APPL_CODE,HRMS_EMP_OFFC.EMP_TOKEN,(HRMS_EMP_OFFC.EMP_FNAME||' '||HRMS_EMP_OFFC.EMP_MNAME|| ' ' || HRMS_EMP_OFFC.EMP_LNAME), " 
						+" CENTER_NAME, DEPT_NAME,LOAN_NAME,TO_CHAR(LOAN_APPL_DATE,'DD-MM-YYYY'),LOAN_EMP_ID,TO_CHAR(LOAN_SANCTION_DATE,'DD-MM-YYYY'),LOAN_SANCTION_AMOUNT, "
						+" TO_CHAR(LOAN_PAYMENT_DATE,'DD-MM-YYYY'),LOAN_PAYMENT_MODE,LOAN_BANK_NAME,LOAN_CHEQUE_NUMBER,LOAN_INTEREST_TYPE, "
						+" LOAN_INTEREST_RATE,TO_CHAR(LOAN_INSTALLMENT_START_DATE,'DD-MM-YYYY'),LOAN_INTALMENT_NUMBERS,LOAN_SECURITY_DETAILS, "
						+" LOAN_SECURITY_VALUE,TO_CHAR(LOAN_SUBMISSION_DATE,'DD-MM-YYYY'),LOAN_SANCTIONED_BY,OFFC1.EMP_TOKEN,OFFC1.EMP_FNAME||' '||OFFC1.EMP_MNAME|| ' ' || OFFC1.EMP_LNAME, "
						+" LOAN_REQ_EMI_AMOUNT,LOAN_MONHLY_PRINCIPAL,LOAN_EMI_TYPE  FROM HRMS_LOAN_PROCESS "
						+" INNER JOIN HRMS_LOAN_APPLICATION ON(HRMS_LOAN_APPLICATION.LOAN_APPL_CODE =HRMS_LOAN_PROCESS.LOAN_APPL_CODE) "
						+" INNER JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=HRMS_LOAN_APPLICATION.LOAN_EMP_ID) "
						+" INNER JOIN HRMS_CENTER ON(HRMS_CENTER.CENTER_ID=HRMS_EMP_OFFC.EMP_CENTER)"
						+" INNER JOIN HRMS_DEPT ON(HRMS_DEPT.DEPT_ID=HRMS_EMP_OFFC.EMP_DEPT)"
						+" LEFT JOIN HRMS_LOAN_MASTER ON(HRMS_LOAN_MASTER.LOAN_CODE=HRMS_LOAN_APPLICATION.LOAN_CODE)"
						+" LEFT JOIN HRMS_EMP_OFFC OFFC1 ON(OFFC1.EMP_ID=HRMS_LOAN_PROCESS.LOAN_SANCTIONED_BY) "
						+" WHERE HRMS_LOAN_PROCESS.LOAN_APPL_CODE=?";
		
		case 5 : return " DELETE FROM HRMS_LOAN_PROCESS WHERE LOAN_APPL_CODE =? ";
		
		case 6 : return "SELECT HRMS_EMP_OFFC.EMP_TOKEN,(HRMS_EMP_OFFC.EMP_FNAME||' '||HRMS_EMP_OFFC.EMP_MNAME|| ' ' || HRMS_EMP_OFFC.EMP_LNAME)," 
						+" DEPT_NAME ,CENTER_NAME,RANK_NAME FROM HRMS_LOAN_APPLICATION "
						+" INNER JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=HRMS_LOAN_APPLICATION.LOAN_GUARANTOR_ONE)"
						+" INNER JOIN HRMS_CENTER ON(HRMS_CENTER.CENTER_ID=HRMS_EMP_OFFC.EMP_CENTER)"
						+" INNER JOIN HRMS_DEPT ON(HRMS_DEPT.DEPT_ID=HRMS_EMP_OFFC.EMP_DEPT)"
						+" INNER JOIN HRMS_RANK ON(HRMS_RANK.RANK_ID=HRMS_EMP_OFFC.EMP_RANK) WHERE LOAN_APPL_CODE=?";
		
		case 7 : return "SELECT HRMS_EMP_OFFC.EMP_TOKEN,(HRMS_EMP_OFFC.EMP_FNAME||' '||HRMS_EMP_OFFC.EMP_MNAME|| ' ' || HRMS_EMP_OFFC.EMP_LNAME)," 
						+" DEPT_NAME ,CENTER_NAME,RANK_NAME FROM HRMS_LOAN_APPLICATION "
						+" INNER JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=HRMS_LOAN_APPLICATION.LOAN_GUARANTOR_TWO)"
						+" INNER JOIN HRMS_CENTER ON(HRMS_CENTER.CENTER_ID=HRMS_EMP_OFFC.EMP_CENTER)"
						+" INNER JOIN HRMS_DEPT ON(HRMS_DEPT.DEPT_ID=HRMS_EMP_OFFC.EMP_DEPT)"
						+" INNER JOIN HRMS_RANK ON(HRMS_RANK.RANK_ID=HRMS_EMP_OFFC.EMP_RANK) WHERE LOAN_APPL_CODE=?";
		
		case 8 : return "SELECT TO_CHAR(LOAN_SANCTION_DATE,'DD-MM-YYYY'),LOAN_SANCTION_AMOUNT,TO_CHAR(LOAN_PAYMENT_DATE,'DD-MM-YYYY'),DECODE(LOAN_PAYMENT_MODE,'CS','Cash','TR','Transfer','CH','Cheque'), "
						+" LOAN_BANK_NAME,LOAN_CHEQUE_NUMBER,DECODE(LOAN_INTEREST_TYPE,'F','Flat Interest','N','No Interest','R','Reducing Principal','I','Reducing Interest'),LOAN_INTEREST_RATE,LOAN_INTALMENT_NUMBERS,LOAN_SECURITY_DETAILS, " 
						+" LOAN_SECURITY_VALUE,TO_CHAR(LOAN_SUBMISSION_DATE,'DD-MM-YYYY'),OFFC1.EMP_FNAME||' '||OFFC1.EMP_MNAME|| ' ' || OFFC1.EMP_LNAME,LOAN_REQ_EMI_AMOUNT "
						+" FROM HRMS_LOAN_PROCESS "
						+" INNER JOIN HRMS_LOAN_APPLICATION ON(HRMS_LOAN_APPLICATION.LOAN_APPL_CODE =HRMS_LOAN_PROCESS.LOAN_APPL_CODE) "
						+" INNER JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=HRMS_LOAN_APPLICATION.LOAN_EMP_ID) "
						+" INNER JOIN HRMS_CENTER ON(HRMS_CENTER.CENTER_ID=HRMS_EMP_OFFC.EMP_CENTER) "
						+" INNER JOIN HRMS_DEPT ON(HRMS_DEPT.DEPT_ID=HRMS_EMP_OFFC.EMP_DEPT) "
						+" LEFT JOIN HRMS_LOAN_MASTER ON(HRMS_LOAN_MASTER.LOAN_CODE=HRMS_LOAN_APPLICATION.LOAN_CODE) "
						+" LEFT JOIN HRMS_EMP_OFFC OFFC1 ON(OFFC1.EMP_ID=HRMS_LOAN_PROCESS.LOAN_SANCTIONED_BY) "
						+" WHERE HRMS_LOAN_PROCESS.LOAN_APPL_CODE= ?";
		
		case 9 : return " SELECT TO_CHAR(TO_DATE(LOAN_INSTAL_MONTH,'MM'),'MON'),LOAN_INSTAL_YEAR,LOAN_PRINCIPLE_AMT,LOAN_INSTAL_INTEREST,LOAN_INSTAL_AMT,LOAN_BALANCE_PRINCIPAL, "
						+" NVL(LOAN_INSTALLMENT_IS_PAID,'N'),LOAN_INSTAL_DAY,LOAN_INSTAL_MONTH FROM HRMS_LOAN_INSTALMENT WHERE LOAN_APPL_CODE=? ORDER BY LOAN_INSTAL_YEAR, LOAN_INSTAL_MONTH, LOAN_PRINCIPLE_AMT";
		
		case 10 : return "INSERT INTO HRMS_LOAN_INSTALMENT (LOAN_APPL_CODE, LOAN_INSTAL_MONTH, LOAN_INSTAL_YEAR, LOAN_PRINCIPLE_AMT, "
						+" LOAN_INSTAL_INTEREST, LOAN_INSTAL_AMT, LOAN_EMP_ID,LOAN_BALANCE_PRINCIPAL,LOAN_INSTAL_DAY, LOAN_INSTALLMENT_IS_PAID) VALUES(?,?,?,?,?,?,?,?,?,?)";
		
		case 11 : return "DELETE FROM HRMS_LOAN_INSTALMENT WHERE LOAN_APPL_CODE =? ";
		
		case 12 : return "SELECT NVL(SUM(CREDIT_AMT), 0) "
						 +"FROM HRMS_EMP_CREDIT "
						 +"INNER JOIN HRMS_CREDIT_HEAD ON (HRMS_CREDIT_HEAD.CREDIT_CODE = HRMS_EMP_CREDIT.CREDIT_CODE) "
						 +"WHERE HRMS_EMP_CREDIT.EMP_ID = ? AND HRMS_CREDIT_HEAD.CREDIT_PERIODICITY='M' AND CREDIT_PAYFLAG='Y' ";
		
		case 13 : return "SELECT ROWNUM,TO_CHAR(LOAN_PREPAY_DATE,'DD-MM-YYYY'),NVL(LOAN_PREPAY_AMOUNT,0) FROM HRMS_LOAN_CLOSURE  WHERE LOAN_APPL_CODE= ? ";
		
		case 14 : return " SELECT TO_CHAR(TO_DATE(LOAN_INSTAL_MONTH,'MM'),'MON'),LOAN_INSTAL_YEAR,LOAN_PRINCIPLE_AMT,LOAN_INSTAL_INTEREST,LOAN_INSTAL_AMT,LOAN_BALANCE_PRINCIPAL, "
						+" LOAN_INSTALLMENT_IS_PAID,LOAN_INSTAL_DAY,LOAN_INSTAL_DAY||'-'||(LOAN_INSTAL_MONTH+1)||'-'||LOAN_INSTAL_YEAR,LOAN_INSTAL_MONTH FROM HRMS_LOAN_INSTALMENT WHERE LOAN_APPL_CODE=? AND LOAN_INSTALLMENT_IS_PAID ='Y' ORDER BY LOAN_INSTAL_YEAR, LOAN_INSTAL_MONTH, LOAN_PRINCIPLE_AMT";

		case 15 : return "SELECT NVL(SUM(LOAN_PREPAY_AMOUNT), 0) FROM HRMS_LOAN_CLOSURE "
		 				+" WHERE LOAN_APPL_CODE = ?";
		
		case 16 : return "UPDATE HRMS_LOAN_APPLICATION SET LOAN_APPL_STATUS = ? WHERE LOAN_APPL_CODE = ?";
		
		case 17 : return "INSERT INTO HRMS_LOAN_PATH (LOAN_PATH_ID, LOAN_APPL_CODE, LOAN_APPROVER_CODE, LOAN_APPROVED_DATE, LOAN_COMMENTS, LOAN_APPL_STATUS, "
		+"LOAN_APPLIED_BY,LOAN_APPR_AMT) VALUES((SELECT NVL(MAX(LOAN_PATH_ID),0)+1 FROM HRMS_LOAN_PATH WHERE LOAN_APPL_CODE = ?), ?, ?, "
		+"TO_DATE(TO_CHAR(SYSDATE,'DD-MM-YYYY'),'DD-MM-YYYY'), ?, ?, ?,?)";
		
		
		default: return "";
		}
	}

}
