package org.paradyne.sql.loan;

import org.paradyne.lib.SqlBase;

public class NewLoansIssuedReportModelSql extends SqlBase {
	public String getQuery(int id) {
		switch (id) {
		case 1:
			return "SELECT "
					+ "	LOAN_APPL_CODE,"
					+ "	A.LOAN_EMP_ID,"
					+ "	(EMP_FNAME || ' ' || EMP_MNAME || ' ' || EMP_LNAME) AS EMP_NAME, "
					+ "	LOAN_AMOUNT,"
					+ "	(SELECT LOAN_NAME FROM HRMS_LOAN_MASTER WHERE LOAN_CODE =	A.LOAN_CODE) AS LOAN_NAME,"
					+ "	TO_CHAR(C.LOAN_PAYMENT_DATE,'DD-MON-YYYY') AS LOAN_PAYMENT_DATE,"
					+ "	(SELECT DIV_NAME FROM HRMS_DIVISION WHERE DIV_ID = B.EMP_DIV) AS DIV_NAME ,"
					+ "	(SELECT CASE WHEN LOAN_INTALMENT_NUMBERS IS NULL  THEN LOAN_REQ_EMI_AMOUNT ELSE LOAN_SANCTION_AMOUNT/LOAN_INTALMENT_NUMBERS END FROM HRMS_LOAN_PROCESS  WHERE LOAN_APPL_CODE = A.LOAN_APPL_CODE) AS MONTHLY_INSTALLMENT, "
					+ "	NVL(TO_CHAR(C.LOAN_INTALMENT_NUMBERS),'-') AS NO_OF_INSTALLEMENT "
					+ " FROM "
					+ "	HRMS_LOAN_APPLICATION A INNER JOIN HRMS_EMP_OFFC B ON (A.LOAN_EMP_ID = B.EMP_ID) "
					+ "	INNER JOIN HRMS_LOAN_PROCESS C ON (A.LOAN_APPL_CODE = C.LOAN_APPL_CODE)"
					+ " AND C.LOAN_PAYMENT_DATE >= TO_DATE(?,'DD-MON-YYYY') AND C.LOAN_PAYMENT_DATE <= TO_DATE(?,'DD-MON-YYYY')";
		case 2:
			
			return " SELECT " + "	LOAN_CODE," + "	INITCAP(LOAN_NAME) " + " FROM "
					+ "	HRMS_LOAN_MASTER ";
		
		case 3:
			return "SELECT "
					+ "	A.LOAN_EMP_ID,"
					+ "	(EMP_FNAME || ' ' || EMP_MNAME || ' ' || EMP_LNAME) AS EMP_NAME, "
					+ "	LOAN_AMOUNT,"
					+ "	(SELECT LOAN_NAME FROM HRMS_LOAN_MASTER WHERE LOAN_CODE =	A.LOAN_CODE) AS LOAN_NAME,"
					+ "	TO_CHAR(C.LOAN_PAYMENT_DATE,'DD-MON-YYYY') AS LOAN_PAYMENT_DATE,"
					+ "	(SELECT DIV_NAME FROM HRMS_DIVISION WHERE DIV_ID = B.EMP_DIV) AS DIV_NAME ,"
					+ "	(SELECT CASE WHEN LOAN_INTALMENT_NUMBERS IS NULL  THEN LOAN_REQ_EMI_AMOUNT ELSE LOAN_SANCTION_AMOUNT/LOAN_INTALMENT_NUMBERS END FROM HRMS_LOAN_PROCESS  WHERE LOAN_APPL_CODE = A.LOAN_APPL_CODE) AS MONTHLY_INSTALLMENT, "
					+ "	NVL(TO_CHAR(C.LOAN_INTALMENT_NUMBERS),'-') AS NO_OF_INSTALLEMENT "
					+ " FROM "
					+ "	HRMS_LOAN_APPLICATION A INNER JOIN HRMS_EMP_OFFC B ON (A.LOAN_EMP_ID = B.EMP_ID) "
					+ "	INNER JOIN HRMS_LOAN_PROCESS C ON (A.LOAN_APPL_CODE = C.LOAN_APPL_CODE)"
					+ " AND C.LOAN_PAYMENT_DATE >= TO_DATE(?,'DD-MON-YYYY') AND C.LOAN_PAYMENT_DATE <= TO_DATE(?,'DD-MON-YYYY')";
		
		case 4:
			return	" SELECT LOAN_NAME FROM HRMS_LOAN_MASTER WHERE LOAN_CODE = ?";
			
		default:
			return " Framework could not the query number specified ";
		}
	}
}
