package org.paradyne.sql.voucher;

import org.paradyne.lib.SqlBase;

public class VoucherApprovalModelSql extends SqlBase {
	
	public String getQuery(int id) {
		switch(id) {
		case 1: return " SELECT VOUCHER_APPL_CODE,EMP_ID, HRMS_TITLE.TITLE_NAME||' '||EMP_FNAME||' '||EMP_MNAME||' '||EMP_LNAME,TO_CHAR(APP_DATE, 'DD-MM-YYYY'),NVL(VCH_TOTALAMT, 0),"
						+"STATUS,APPL_LEVEL,HRMS_EMP_OFFC.EMP_TOKEN "
						+" FROM HRMS_VOUCHER_APPL "
						+" INNER JOIN HRMS_EMP_OFFC ON (HRMS_EMP_OFFC.EMP_ID=HRMS_VOUCHER_APPL.EMP_CODE) "
						+ "	LEFT JOIN HRMS_TITLE ON(HRMS_EMP_OFFC.EMP_TITLE_CODE=HRMS_TITLE.TITLE_CODE)"
						+" WHERE STATUS=?  AND (APPROVED_BY=? OR ALTERNATE_APPROVER=?) ORDER BY VOUCHER_APPL_CODE DESC ";
		
  	    case 2 : return "UPDATE HRMS_VOUCHER_APPL SET STATUS = ?  WHERE VOUCHER_APPL_CODE = ?" ;
		
		case 3 : return "UPDATE HRMS_VOUCHER_APPL SET STATUS='P'  WHERE VOUCHER_APPL_CODE = ?";
		
		case 4: return "SELECT STATUS FROM HRMS_VOUCHER_APPL WHERE VOUCHER_APPL_CODE = ?";
		
		case 5:return "INSERT INTO HRMS_VOUCHER_PATH (VOUCHER_CODE,APPROVER_CODE,APPR_DATE,VOUCHER_REMARK,VOUCHER_STATUS)" 
					  + " VALUES(?,?,TO_DATE(TO_CHAR(SYSDATE,'DD-MM-YYYY'),'DD-MM-YYYY'),?,?)";
		
		case 6 :return "SELECT VOUCHER_STATUS FROM HRMS_VOUCHER_PATH WHERE VOUCHER_CODE=? AND APPROVER_CODE=?";
		
		case 7: return "UPDATE HRMS_VOUCHER_APPL SET APPL_LEVEL=? , APPROVED_BY=?, ALTERNATE_APPROVER=? WHERE VOUCHER_APPL_CODE=?";
		
		case 8: return "UPDATE HRMS_VOUCHER_APPL SET STATUS=? WHERE VOUCHER_APPL_CODE=?";
		
		case 9: return "UPDATE HRMS_VOUCHER_APPL SET STATUS = ?,APPL_LEVEL = ?,APPROVED_BY = ? WHERE VOUCHER_APPL_CODE = ?";
		
		default : return "Framework could not EXECUTE the query number specified";			
		}
	}

}
