package org.paradyne.sql.voucher;

import org.paradyne.lib.SqlBase;

public class VoucherApplicationModelSql extends SqlBase {
	public String getQuery(int id) {
		switch(id) {
		case 1: return " INSERT INTO HRMS_VOUCHER_APPL(VOUCHER_APPL_CODE,VOUCHER_TYPE,EMP_CODE,APP_DATE,STATUS, VCH_TOTALAMT,APPL_LEVEL,APPROVED_BY,VCH_DETAILS,ALTERNATE_APPROVER,DRAFT_BY) "
					  +" VALUES(?,?,?,TO_DATE(?,'DD-MM-YYYY'),?,NVL(?,0),1,?,?,?,?) ";
		
		 case 2: return " INSERT INTO HRMS_VCHDTL(VOUCHER_APPL_CODE,VCH_CODE,VCHDTL_AMOUNT,VCHDTL_REMARK,PROOF_FLAG, VCH_UPLOADED_FILE) "
					  +" VALUES(?,?,?,NVL(?,''),?, ?) ";
		
		 case 3: return "DELETE FROM HRMS_VOUCHER_APPL WHERE VOUCHER_APPL_CODE=?";
		
		 case 4: return " SELECT VCH_CODE,VCH_NAME  FROM HRMS_VCH_HD where VCH_CODE=?";
		 
		 case 5: return "SELECT HRMS_VCHDTL.VCH_CODE,VCH_NAME,VCHDTL_AMOUNT,NVL(VCHDTL_REMARK,''),PROOF_FLAG, VCH_UPLOADED_FILE "
		 				+" FROM HRMS_VCHDTL " 
		 				+" INNER JOIN HRMS_VCH_HD ON (HRMS_VCH_HD.VCH_CODE =HRMS_VCHDTL.VCH_CODE)"
		 				+" INNER JOIN HRMS_VOUCHER_APPL ON (HRMS_VOUCHER_APPL.VOUCHER_APPL_CODE=HRMS_VCHDTL.VOUCHER_APPL_CODE)"
		 				+" WHERE HRMS_VCHDTL.VOUCHER_APPL_CODE=? ";
		 
		 case 6: return "DELETE FROM HRMS_VCHDTL WHERE VOUCHER_APPL_CODE=? and VCH_CODE=? ";
		 
		 
		 case 7: return " UPDATE HRMS_VOUCHER_APPL SET VCH_DETAILS = ?, VCH_TOTALAMT = ? "
		 				+"WHERE VOUCHER_APPL_CODE = ?";
		 
		 case 8 : return "UPDATE HRMS_VOUCHER_APPL SET VOUCHER_TYPE = ?, EMP_CODE= ?, APP_DATE = TO_DATE(?,'DD-MM-YYYY'), STATUS = ?, "
		 				+"VCH_DETAILS = ?, VCH_TOTALAMT = ?, APPROVED_BY=?, ALTERNATE_APPROVER=? WHERE VOUCHER_APPL_CODE = ?";

		 case 9: return "SELECT HRMS_EMP_OFFC.EMP_ID, (HRMS_TITLE.TITLE_NAME||' '||HRMS_EMP_OFFC.EMP_FNAME||' '||HRMS_EMP_OFFC.EMP_MNAME|| ' ' || HRMS_EMP_OFFC.EMP_LNAME),"
						+ " NVL(HRMS_RANK.RANK_NAME,'  '),NVL(HRMS_DEPT.DEPT_NAME,'  '),"
						+ " NVL(CADRE_NAME,'  '),EMP_TOKEN FROM HRMS_EMP_OFFC"
						+ " LEFT JOIN HRMS_RANK ON(HRMS_EMP_OFFC.EMP_RANK=HRMS_RANK.RANK_ID)"
						+ " LEFT JOIN HRMS_CENTER ON(HRMS_EMP_OFFC.EMP_CENTER=HRMS_CENTER.CENTER_ID)"
						+ " LEFT JOIN HRMS_CADRE ON(HRMS_EMP_OFFC.EMP_CADRE=HRMS_CADRE.CADRE_ID)"
						+ "	LEFT JOIN HRMS_TITLE ON(HRMS_EMP_OFFC.EMP_TITLE_CODE=HRMS_TITLE.TITLE_CODE)"
						+ "  LEFT JOIN HRMS_DEPT ON(HRMS_EMP_OFFC.EMP_DEPT=HRMS_DEPT.DEPT_ID) WHERE EMP_ID=?";
		 
		
		 
		 
		 case 10 : return "DELETE FROM HRMS_VCHDTL WHERE VOUCHER_APPL_CODE = ?";
		 
		 case 11 :return "UPDATE HRMS_VCHDTL SET VCHDTL_AMOUNT=?,VCHDTL_REMARK=?,PROOF_FLAG=? WHERE VOUCHER_APPL_CODE=? AND VCH_CODE=? ";
		 
		 case 12 :return " SELECT NVL(STATUS,'P'), NVL(VCH_DETAILS,''),VCH_TOTALAMT ,APPL_LEVEL,"
		 				 + " NVL(VOUCHER_NO,''),TO_CHAR(APP_DATE,'DD-MM-YYYY'),VOUCHER_TYPE "
		 				 + " FROM HRMS_VOUCHER_APPL WHERE VOUCHER_APPL_CODE=?";
		 		 
		 case 13 :return "SELECT VOUCHER_APPL_CODE,VOUCHER_TYPE,EMP_CODE,(''||EMP_FNAME ||' '|| EMP_LNAME ||' '), TO_CHAR(APP_DATE,'DD-MM-YYYY'), STATUS FROM HRMS_VOUCHER_APPL"
						+ " INNER JOIN HRMS_EMP_OFFC ON (HRMS_VOUCHER_APPL.EMP_CODE= HRMS_EMP_OFFC.EMP_ID) WHERE VOUCHER_APPL_CODE= ?";
		 
		 case 14: return " UPDATE HRMS_VOUCHER_APPL SET STATUS = ? WHERE VOUCHER_APPL_CODE = ?";
		 
		 case 15: return "DELETE FROM HRMS_VOUCHER_PATH WHERE VOUCHER_CODE= ?";
		 
		 default : return "FRAMEWORK COULD NOT EXECUTE THE QUERY NUMBER SPECIFIED";		
		 
		 
		}
	}
}
