package org.paradyne.sql.WBT;

import org.paradyne.lib.SqlBase;

public class ProgrammeMasterModelSql  extends SqlBase {
	
	public String getQuery(int queryCode) {

		switch (queryCode) {

		case 1:
			return "INSERT INTO WBT_PROGRAM_HDR (PROGRAM_ID, PROGRAM_NAME, PROGRAM_TYPE, PROGRAM_DURATION,"
					+ " PROGRAM_DAYS, PROGRAM_ACTIVE) VALUES ( ?, ?, ?, ? ,?, ?) ";
		
		case 2:
			return "SELECT WBT_PROGRAM_HDR.PROGRAM_ID, WBT_PROGRAM_HDR.PROGRAM_NAME, DECODE(WBT_PROGRAM_HDR.PROGRAM_TYPE,'T','Test', 'R','Training'), "
			        +" NVL(WBT_PROGRAM_HDR.PROGRAM_DURATION,'NA'), DECODE(WBT_PROGRAM_HDR.PROGRAM_ACTIVE,'Y','Yes','N','No')"
					+" FROM WBT_PROGRAM_HDR ORDER BY WBT_PROGRAM_HDR.PROGRAM_NAME ";
			
		case 3:
			return  "SELECT WBT_PROGRAM_HDR.PROGRAM_ID, WBT_PROGRAM_HDR.PROGRAM_NAME, WBT_PROGRAM_HDR.PROGRAM_TYPE,"
					+" NVL(WBT_PROGRAM_HDR.PROGRAM_DURATION,'NA'), NVL(WBT_PROGRAM_HDR.PROGRAM_DAYS,0), WBT_PROGRAM_HDR.PROGRAM_ACTIVE "
					+" FROM WBT_PROGRAM_HDR WHERE WBT_PROGRAM_HDR.PROGRAM_ID = ?";

		case 4:
			return "SELECT WBT_PROGRAM_DTL.PROGRAM_MODULE_CODE, HRMS_REC_SUBJECT.SUBJECT_NAME,"
					+ " WBT_PROGRAM_DTL.PROGRAM_ORDER, WBT_PROGRAM_DTL.IS_PROGRAM_ORDER,"  
					+ " WBT_PROGRAM_DTL.IS_PROGRAM_CONTENT, WBT_PROGRAM_DTL.IS_PROGRAM_QUES,"
					+ " NVL(WBT_PROGRAM_DTL.PROGRAM_PASS_MARKS, 0),  NVL(WBT_PROGRAM_DTL.MODULE_NO_OF_ATTEMPT, 1)"
					+ " FROM WBT_PROGRAM_DTL" 
					+ " INNER JOIN WBT_PROGRAM_HDR ON(WBT_PROGRAM_HDR.PROGRAM_ID = WBT_PROGRAM_DTL.PROGRAM_ID)" 
					+ " INNER JOIN HRMS_REC_SUBJECT ON(HRMS_REC_SUBJECT.SUBJECT_CODE = WBT_PROGRAM_DTL.PROGRAM_MODULE_CODE)"
					//+" LEFT JOIN WBT_PROGRAM_QUES_HDR ON (WBT_PROGRAM_QUES_HDR.MODULE_ID = WBT_PROGRAM_DTL.PROGRAM_MODULE_CODE )"
					+ " WHERE HRMS_REC_SUBJECT.SUBJECT_STATUS='A' AND WBT_PROGRAM_HDR.PROGRAM_ID = ?"
					+ " ORDER BY WBT_PROGRAM_DTL.PROGRAM_ORDER";
		
		case 5:
			return "UPDATE WBT_PROGRAM_HDR SET  PROGRAM_NAME = ?, PROGRAM_TYPE = ?, "
					+" PROGRAM_DURATION = ?, PROGRAM_DAYS = ?,PROGRAM_ACTIVE = ? WHERE PROGRAM_ID =?";
		default:
			return "Query not Found";
		}
	}
}
