package org.paradyne.sql.settings;

import org.paradyne.lib.SqlBase;

public class SalarySlipConfigurationModelSql extends SqlBase {
	
	public String getQuery(int id) {
		switch(id) {
		// roleChk field inserted by abhijit
		case 1: return " INSERT INTO HRMS_SALARYSLIP_CONF (CONF_BRANCH_FLAG, CONF_DEPT_FLAG, CONF_DESG_FLAG, CONF_EMP_TYPE_FLAG, CONF_SALARY_GRADE_FLAG, CONF_BANK_FLAG, CONF_AC_FLAG, CONF_ATTN_FLAG, CONF_LEAVE_FLAG, CONF_HEADER_FLAG, CONF_LOGO_FLAG,CONF_GRADE_FLAG,CONF_ROLE_FLAG,CONF_PAYBILL_FLAG,CONF_TRADE_FLAG,SIGN_LOGO, CONF_APRIL_TO_DATE_SALARY, CONF_RECOVERY_DAYS, CONF_NET_PAY_IN_WORDS) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
		// roleChk field updated by abhijit
		case 2: return " UPDATE HRMS_SALARYSLIP_CONF SET CONF_BRANCH_FLAG=?, CONF_DEPT_FLAG=?, CONF_DESG_FLAG=?, CONF_EMP_TYPE_FLAG=?, CONF_SALARY_GRADE_FLAG=?, CONF_BANK_FLAG=?, CONF_AC_FLAG=?, CONF_ATTN_FLAG=?, CONF_LEAVE_FLAG=?, CONF_HEADER_FLAG=?, CONF_LOGO_FLAG=?,CONF_GRADE_FLAG=?, CONF_ROLE_FLAG=?,CONF_PAYBILL_FLAG=?,CONF_TRADE_FLAG=?,SIGN_LOGO=?, CONF_APRIL_TO_DATE_SALARY=?, CONF_RECOVERY_DAYS=?, CONF_NET_PAY_IN_WORDS =?";
		// roleChk field selected by abhijit
		case 3: return " SELECT CONF_BRANCH_FLAG, CONF_DEPT_FLAG, CONF_DESG_FLAG, CONF_EMP_TYPE_FLAG, CONF_SALARY_GRADE_FLAG, CONF_BANK_FLAG, CONF_AC_FLAG, CONF_ATTN_FLAG, CONF_LEAVE_FLAG, CONF_HEADER_FLAG, CONF_LOGO_FLAG,CONF_GRADE_FLAG, CONF_ROLE_FLAG,CONF_PAYBILL_FLAG,CONF_TRADE_FLAG,SIGN_LOGO, CONF_APRIL_TO_DATE_SALARY, CONF_RECOVERY_DAYS, CONF_NET_PAY_IN_WORDS "
						+ " FROM HRMS_SALARYSLIP_CONF ";

		default : return "Framework could not EXECUTE the query number specified";			
		}
	}
}
