/**
 * 
 */
package org.paradyne.sql.settings;

import org.paradyne.lib.SqlBase;

/**
 * @author Pankaj_Jain_&_Prakash_Shetkar
 * @purpose : This form is used to Save or Edit HomePage Dashlet Information
 * 			  HomePage Setting Link 
 * @Modified By AA1711 - TO view that Records According to Applicable 
 * 						Division Wise on Dashlet 
 * @Date 22-Jan-2013
 */
public class SettingMasterModelSql extends SqlBase {

	public String getQuery(int code) {

		switch (code) {
		case 1:
			return " INSERT INTO HRMS_POLL_HDR (POLL_CODE,POLL_QUESTION,POLL_DATE,EXPIRY_DATE) VALUES (NVL((SELECT MAX(POLL_CODE) FROM HRMS_POLL_HDR),0)+1, ? , SYSDATE, TO_DATE(?,'DD-MM-YYYY'))";

		case 2:
			return " INSERT INTO HRMS_POLL_DTL (poll_code,poll_option_code,poll_option_desc,POLL_OPTION_COLOR) VALUES ( ?, ?, ?, ?)";

		case 3:
			return " INSERT INTO HRMS_SETTINGS_HRCOMM(HRCOMM_CODE,HRCOMM_LINKNAME,HRCOMM_LINK,HRCOMM_FLAG,HRCOMM_DATE,HRCOMM_STATUS) "
					+ " VALUES((SELECT NVL(MAX(HRCOMM_CODE),0) + 1 FROM HRMS_SETTINGS_HRCOMM), ? , ?, ? ,SYSDATE,?) ";

		case 4:
			return " SELECT HRCOMM_CODE,HRCOMM_LINKNAME,NVL(HRCOMM_LINK,'No File Associated') FROM HRMS_SETTINGS_HRCOMM ORDER BY HRCOMM_CODE ";

		case 5:
			return " UPDATE HRMS_SETTINGS_HRCOMM SET HRCOMM_LINKNAME = ?, HRCOMM_LINK = ?,HRCOMM_STATUS = ? ,HRCOMM_FLAG = ? WHERE HRCOMM_CODE = ?";

		case 6:
			return " DELETE FROM HRMS_SETTINGS_HRCOMM WHERE HRCOMM_CODE = ?";

		case 7:
			return " INSERT INTO HRMS_SETTINGS_CORPINFO(CORPINFO_CODE,CORPINFO_LINKNAME,CORPINFO_LINK,CORPINFO_FLAG,CORPINFO_LINK_DATE,CORPINFO_STATUS,CORPINFO_DIVISION) "
					+ " VALUES((SELECT NVL(MAX(CORPINFO_CODE),0) + 1 FROM HRMS_SETTINGS_CORPINFO),? , ?, ?,SYSDATE,?,?) ";

		case 8:
			return " SELECT CORPINFO_CODE,CORPINFO_LINKNAME,NVL(CORPINFO_LINK,'No File Associated'),Decode(CORPINFO_FLAG,'Y','YES','N','NO'),CORPINFO_STATUS ,NVL(CORPINFO_DIVISION,' ') FROM HRMS_SETTINGS_CORPINFO ORDER BY CORPINFO_CODE ";

		case 9:
			return " UPDATE HRMS_SETTINGS_CORPINFO SET CORPINFO_LINKNAME = ?, CORPINFO_LINK = ?,CORPINFO_STATUS = ? ,CORPINFO_FLAG = ? ,CORPINFO_DIVISION=?  WHERE CORPINFO_CODE = ?";

		case 10:
			return " DELETE FROM HRMS_SETTINGS_CORPINFO WHERE CORPINFO_CODE = ?";

		case 11:
			return " INSERT INTO HRMS_SETTINGS_KNOWLEDGE(KNOW_CODE,KNOW_LINKNAME,KNOW_LINK,KNOW_FLAG,KNOW_DATE,KNOW_STATUS,KNOW_DIVISION,KNOW_CATEGORY) "
					+ " VALUES((SELECT NVL(MAX(KNOW_CODE),0) + 1 FROM HRMS_SETTINGS_KNOWLEDGE),?,?,?,TO_DATE(SYSDATE,'DD-MM-YYYY'),?,?,?) ";

		case 12:
			return " SELECT KNOW_CODE,KNOW_LINKNAME,NVL(KNOW_LINK,'No File Associated'),"
					+ " DECODE(KNOW_FLAG,'Y','YES','N','NO'),KNOW_STATUS, NVL(KNOW_CATEGORY,'')"
					+ " FROM HRMS_SETTINGS_KNOWLEDGE ORDER BY KNOW_CODE ";

		case 13:
			return " UPDATE HRMS_SETTINGS_KNOWLEDGE SET KNOW_LINKNAME = ?, "
					+ " KNOW_LINK = ?,KNOW_STATUS = ? ,KNOW_FLAG = ? ,KNOW_DIVISION=?, KNOW_CATEGORY=?"
					+ " WHERE KNOW_CODE = ?";

		case 14:
			return " DELETE FROM HRMS_SETTINGS_KNOWLEDGE WHERE KNOW_CODE = ? ";

		case 15:
			return " INSERT INTO HRMS_SETTINGS_CORPMSG(CORPMSG_CODE,CORPMSG_LINKNAME,CORPMSG_LINK,CORPMSG_FLAG,CORPMSG_LINK_DATE,CORPMSG_STATUS,CORPMSG_DIVISION) "
					+ " VALUES((SELECT NVL(MAX(CORPMSG_CODE),0) + 1 FROM HRMS_SETTINGS_CORPMSG),?,?,?,SYSDATE,?,?) ";

		case 16:
			return " SELECT CORPMSG_CODE,CORPMSG_LINKNAME,NVL(CORPMSG_LINK,'No File Associated'),Decode(CORPMSG_FLAG,'Y','YES','N','NO'),CORPMSG_STATUS FROM HRMS_SETTINGS_CORPMSG ORDER BY CORPMSG_CODE ";

		case 17:
			return " UPDATE HRMS_SETTINGS_CORPMSG SET CORPMSG_LINKNAME = ?, CORPMSG_LINK = ?, CORPMSG_STATUS = ? ,CORPMSG_FLAG = ? ,CORPMSG_DIVISION=? WHERE CORPMSG_CODE = ?";

		case 18:
			return " DELETE FROM HRMS_SETTINGS_CORPMSG WHERE CORPMSG_CODE = ? ";

		case 19:
			return " DELETE FROM HRMS_SETTINGS_GENERAL WHERE EMP_ID = ? ";

		case 20:
			return " INSERT INTO HRMS_SETTINGS_GENERAL(GENERAL_HOLIDAY,GENERAL_BDAY,GENERAL_NEWJOINEE,GENERAL_ADDRESS,EMP_ID) "
					+ " VALUES(?,?,?,?,?) ";

		case 21:
			return " INSERT INTO HRMS_SETTINGS_THOUGHT(THOUGHT_CODE,THOUGHT_NAME,THOUGHT_DATE,THOUGHT_FLAG) "
					+ "  VALUES((SELECT NVL(MAX(THOUGHT_CODE),0) + 1 FROM HRMS_SETTINGS_THOUGHT),?,SYSDATE,'Y') ";

		case 22:
			return " SELECT THOUGHT_CODE,THOUGHT_NAME,TO_CHAR(THOUGHT_DATE,'DD-MM-YYYY') FROM HRMS_SETTINGS_THOUGHT ORDER BY THOUGHT_CODE  ";

		case 23:
			return " UPDATE HRMS_SETTINGS_THOUGHT SET THOUGHT_NAME = ? , THOUGHT_DATE = SYSDATE WHERE THOUGHT_CODE = ? ";

		case 24:
			return " DELETE FROM HRMS_SETTINGS_THOUGHT WHERE THOUGHT_CODE = ? ";

			// case 25: return " INSERT INTO
			// HRMS_SETTINGS_MAILBOX(MAILBOX_SERVER,MAILBOX_PROTOCOL,MAILBOX_PORT,MAILBOX_USERID,MAILBOX_PASSW,MAILBOX_COMP,MAILBOX_AUTH_CHK,MAILBOX_POP_BEFORE_SMTP,MAILBOX_FLAG)
			// "+
			// " VALUES(?,?,?,?,?,1,?,?,?)";

		case 26:
			return " INSERT INTO HRMS_SETTINGS_BULLETIN(BULLETIN_CODE,BULLETIN_LINKNAME,BULLETIN_LINK,BULLETIN_FLAG,BULLETIN_LINK_DATE,BULLETIN_STATUS) "
					+ " VALUES((SELECT NVL(MAX(BULLETIN_CODE),0) + 1 FROM HRMS_SETTINGS_BULLETIN),?,?,?,SYSDATE,?) ";

		case 27:
			return " SELECT BULLETIN_CODE,BULLETIN_LINKNAME,NVL(BULLETIN_LINK,'No File Associated') FROM HRMS_SETTINGS_BULLETIN ORDER BY BULLETIN_CODE ";

		case 28:
			return " UPDATE HRMS_SETTINGS_BULLETIN SET BULLETIN_LINKNAME = ?, BULLETIN_LINK = ?, BULLETIN_STATUS = ? ,BULLETIN_FLAG = ? WHERE BULLETIN_CODE = ?";

		case 29:
			return " DELETE FROM HRMS_SETTINGS_BULLETIN WHERE BULLETIN_CODE = ?";

			// case 30 : return " UPDATE HRMS_SETTINGS_MAILBOX SET
			// MAILBOX_SERVER = ?,MAILBOX_PROTOCOL = ?,MAILBOX_PORT =
			// ?,MAILBOX_USERID = ?,MAILBOX_PASSW = ?,MAILBOX_AUTH_CHK =
			// ?,MAILBOX_POP_BEFORE_SMTP=? WHERE MAILBOX_FLAG = ?";

		case 31:
			return " INSERT INTO HRMS_SETTINGS_QUICKLINK_ADMIN(QUICK_ADMIN_CODE,QUICK_ADMIN_LINKNAME,QUICK_ADMIN_LINK,QUICK_ADMIN_STATUS) "
					+ " VALUES((SELECT NVL(MAX(QUICK_ADMIN_CODE),0) + 1 FROM HRMS_SETTINGS_QUICKLINK_ADMIN),?,?,?) ";

		case 32:
			return " SELECT QUICK_ADMIN_CODE,QUICK_ADMIN_LINKNAME,QUICK_FLAG FROM HRMS_SETTINGS_QUICKLINK_ADMIN WHERE QUICK_SUPER_FLAG = 'Y' ORDER BY QUICK_ADMIN_CODE DESC";

		case 33:
			return " UPDATE HRMS_SETTINGS_QUICKLINK_ADMIN SET QUICK_FLAG = ? WHERE QUICK_ADMIN_CODE = ?";

		case 34:
			return " DELETE FROM HRMS_SETTINGS_QUICKLINK_ADMIN WHERE QUICK_ADMIN_CODE = ?";

		case 35:
			return " SELECT HRCOMM_CODE,HRCOMM_LINKNAME,NVL(HRCOMM_LINK,'No File Associated') FROM HRMS_SETTINGS_HRCOMM where HRCOMM_FLAG = 'Y' ORDER BY HRCOMM_CODE ";

		case 36:
			return " SELECT CORPINFO_CODE,CORPINFO_LINKNAME,NVL(CORPINFO_LINK,'No File Associated') FROM HRMS_SETTINGS_CORPINFO where CORPINFO_FLAG = 'Y' ORDER BY CORPINFO_CODE ";

		case 37:
			return " SELECT KNOW_CODE,KNOW_LINKNAME,NVL(KNOW_LINK,'No File Associated') FROM HRMS_SETTINGS_KNOWLEDGE where KNOW_FLAG = 'Y' ORDER BY KNOW_CODE ";

		case 38:
			return " SELECT BULLETIN_CODE,BULLETIN_LINKNAME,NVL(BULLETIN_LINK,'No File Associated') FROM HRMS_SETTINGS_BULLETIN where BULLETIN_FLAG = 'Y' ORDER BY BULLETIN_CODE ";

		case 39:
			return " SELECT THOUGHT_CODE,THOUGHT_NAME,TO_CHAR(THOUGHT_DATE,'DD-MM-YYYY') FROM HRMS_SETTINGS_THOUGHT ORDER by THOUGHT_CODE ";
			// +" WHERE THOUGHT_CODE = (SELECT MAX(THOUGHT_CODE) FROM
			// HRMS_SETTINGS_THOUGHT ) ";

		case 40:
			return " INSERT INTO HRMS_SETTINGS_GENERAL(GENERAL_ID,GENERAL_LINK_NAME,GENERAL_LINK_PATH,GENERAL_STATUS,GENERAL_TYPE,GENERAL_VIEW_FLAG,EMP_ID) "
					+ " VALUES((SELECT MAX(NVL(GENERAL_ID,0)) + 1 FROM HRMS_SETTINGS_GENERAL),?,?,?,?,?,?) ";

		case 41:
			return " SELECT GENERAL_ID,GENERAL_LINK_NAME,GENERAL_VIEW_FLAG FROM HRMS_SETTINGS_GENERAL WHERE GENERAL_SUPERFLAG = 'Y' ORDER BY GENERAL_ID DESC ";

		case 42:
			return " UPDATE HRMS_SETTINGS_GENERAL SET GENERAL_VIEW_FLAG = ? WHERE GENERAL_ID = ?";

		case 43:
			return " UPDATE HRMS_SETTINGS_GENERAL SET GENERAL_LINK_NAME = ?, GENERAL_LINK_PATH = ?, GENERAL_STATUS = ?, GENERAL_VIEW_FLAG = ?, GENERAL_TYPE = ? WHERE GENERAL_TYPE = ?";

		case 44:
			return " DELETE FROM HRMS_SETTINGS_QUICKLINK_ADMIN WHERE QUICK_ADMIN_CODE = ? ";

		case 45:
			return " SELECT GENERAL_ID,GENERAL_LINK_NAME,nvl(GENERAL_LINK_PATH,' ') FROM HRMS_SETTINGS_GENERAL where GENERAL_VIEW_FLAG = 'Y' AND GENERAL_SUPERFLAG = 'Y' ORDER BY GENERAL_ID";

		case 46:
			return " SELECT CORPMSG_CODE,CORPMSG_LINKNAME,NVL(CORPMSG_LINK,'No File Associated') FROM HRMS_SETTINGS_CORPMSG where CORPMSG_FLAG = 'Y' ORDER BY CORPMSG_CODE ";

		case 47:
			return " DELETE FROM HRMS_SETTINGS_GENERAL WHERE GENERAL_ID = ? ";

		case 48:
			return " SELECT QUICK_ADMIN_CODE,QUICK_ADMIN_LINKNAME,QUICK_ADMIN_LINK FROM HRMS_SETTINGS_QUICKLINK_ADMIN where QUICK_FLAG = 'Y' AND QUICK_SUPER_FLAG = 'Y' ORDER BY QUICK_ADMIN_CODE";

		case 49:
			return " SELECT EMAIL_INFO_CODE,EMAIL_INFO_NAME,EMAIL_INFO_FLAG FROM HRMS_SETTING_EMAIL_INFO ORDER BY EMAIL_INFO_CODE";

		case 50:
			return "UPDATE HRMS_SETTING_EMAIL_INFO SET EMAIL_INFO_FLAG=? WHERE  EMAIL_INFO_CODE=?";

		case 51:
			return "SELECT EMAIL_INFO_CODE,EMAIL_INFO_NAME FROM HRMS_SETTING_EMAIL_INFO WHERE EMAIL_INFO_FLAG='Y'";

		case 52:
			return " INSERT INTO HRMS_SETTINGS_PWD(PWD_EXPIRY_FLAG,PWD_EXPIRY_PERIODICITY,PWD_REUSE_FLAG,PWD_REUSE_PERIODICITY,PWD_LOCK_FLAG,PWD_LOCK_PERIODICITY,PWD_LOCK_ATTEMPTS, "
					+ " PWD_INCLUDE_ALPHA,PWD_INCLUDE_SPCHAR,PWD_INCLUDE_NUM,PWD_INCLUDE_UPCASE,PWD_MIN_LENGTH,PWD_MAX_LENGTH,PWD_ENABLE_KB,PWD_ENFORCE_KB,PWD_ENABLE_TXTIMG,PWD_ENABLE_SECUREQUE ,PWD_ENABLE_FORGOT_QUES)"
					+ " VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ";

		case 53:
			return " DELETE FROM HRMS_SETTINGS_PWD ";
			
		case 54:
			return " INSERT INTO HRMS_SETTINGS_TIPS(TIP_CODE,TIP_LINKNAME,TIP_LINK,TIP_FLAG,TIP_LINK_DATE,TIP_STATUS,TIP_DIVISION) "
					+ " VALUES((SELECT NVL(MAX(TIP_CODE),0) + 1 FROM HRMS_SETTINGS_TIPS),?,?,?,SYSDATE,?,?) ";
		case 55:
			return " UPDATE HRMS_SETTINGS_TIPS SET TIP_LINKNAME = ?, TIP_LINK = ?, TIP_STATUS = ?, TIP_FLAG = ?, TIP_DIVISION=?" +
					   " WHERE TIP_CODE = ?";	
		case 56:
			return " SELECT TIP_CODE,TIP_LINKNAME,NVL(TIP_LINK,'No File Associated'),Decode(TIP_FLAG,'Y','YES','N','NO'),TIP_STATUS ,NVL(TIP_DIVISION,' ') FROM HRMS_SETTINGS_TIPS ORDER BY TIP_CODE ";
	
		case 57:
			return " DELETE FROM HRMS_SETTINGS_TIPS WHERE TIP_CODE = ?";
			
		case 58:
		     return "SELECT TIP_CODE,TIP_LINKNAME,NVL(TIP_LINK,'No File Associated') FROM HRMS_SETTINGS_TIPS WHERE TIP_FLAG = 'Y'";
			
			// case 54 : return " INSERT INTO
			// HRMS_SETTINGS_SYSMAILID(SYSMAIL_CODE,SYSMAIL_EMAIL_ID,SYSMAIL_EMAIL_PASS)
			// "
			// +" VALUES((SELECT NVL(MAX(SYSMAIL_CODE),0)+1 FROM
			// HRMS_SETTINGS_SYSMAILID),?,?)";

			// case 55 : return " UPDATE HRMS_SETTINGS_SYSMAILID SET
			// SYSMAIL_EMAIL_ID = ?, SYSMAIL_EMAIL_PASS = ? "
			// +" WHERE SYSMAIL_CODE = ?";

			// case 56 : return " SELECT SYSMAIL_CODE,SYSMAIL_EMAIL_ID FROM
			// HRMS_SETTINGS_SYSMAILID ";

		default:
			return " HI";
		}
	}

}
