/**
 * 
 */
package org.paradyne.sql.settings;

import org.paradyne.lib.SqlBase;

/**
 * @author ritac
 *
 */
public class SuggestionModelSql extends SqlBase {
	public String  getQuery(int code){
		switch(code){
		
		case 1 : return " INSERT INTO HRMS_SUGGESTION(SUGGESTION_CODE,SUGGESTION_DATE,SUGGESTION_FLAG,SUGGESTION_SUBJECT,EMP_ID) "
		+" VALUES((SELECT NVL(MAX(SUGGESTION_CODE),0) + 1 FROM HRMS_SUGGESTION),TO_DATE(SYSDATE,'DD-MM-YYYY'),'P',?,?) ";

		case 3 : return " SELECT SUGGESTION_CODE,NVL(SUGGESTION_SUBJECT,' ') FROM HRMS_SUGGESTION WHERE SUGGESTION_FLAG='A' ORDER BY SUGGESTION_CODE ";

		case 2: return " UPDATE HRMS_SUGGESTION SET SUGGESTION_SUBJECT = ? ,EMP_ID =? WHERE SUGGESTION_CODE = ?";

		case 4 : return " DELETE FROM HRMS_SUGGESTION WHERE SUGGESTION_CODE = ?";
		
		case 5 : return " SELECT SUGGESTION_CODE,NVL(SUGGESTION_SUBJECT,' ') FROM HRMS_SUGGESTION WHERE SUGGESTION_FLAG='A' ORDER BY SUGGESTION_CODE ";
		
	
		
		case 6 : return " INSERT INTO HRMS_SUGGESTION(SUGGESTION_CODE,SUGGETION_EMP_ID,SUGGESTION_DATE,SUGGESTION_FLAG,	"
                      +" SUGGESTION_SUBJECT ,SUGGETION_IMPROVE,SUGGESTION_IMPLEMENT,SUGGESTION_APPR,SUGGESTION_ALT_APPR,SUGGESTION_APPR_LEVEL) "
		+" VALUES((SELECT NVL(MAX(SUGGESTION_CODE),0) + 1 FROM HRMS_SUGGESTION),?,TO_DATE(?,'DD-MM-YYYY'),'P',?,?,?,?,?,1) ";

		case 7: return " UPDATE HRMS_SUGGESTION SET SUGGETION_EMP_ID=?, SUGGESTION_DATE=TO_DATE(?,'DD-MM-YYYY'),SUGGESTION_SUBJECT = ? ,SUGGETION_IMPROVE=?,SUGGESTION_IMPLEMENT=?,SUGGESTION_APPR=?,SUGGESTION_ALT_APPR=? WHERE SUGGESTION_CODE = ?";
		
		default : return " HI";

		
		}
	
	}

}
