/**
 * 
 */
package org.paradyne.sql.settings;

import org.paradyne.lib.SqlBase;

/**
 * @author prakashs
 *
 */
public class SuperSettingsModelSql extends SqlBase {

public String  getQuery(int code){
		
		switch(code){
				
		case 3 : return " INSERT INTO HRMS_SETTINGS_HRCOMM(HRCOMM_CODE,HRCOMM_LINKNAME,HRCOMM_LINK,HRCOMM_FLAG,HRCOMM_DATE,HRCOMM_STATUS) "
					   +" VALUES((SELECT NVL(MAX(HRCOMM_CODE),0) + 1 FROM HRMS_SETTINGS_HRCOMM), ? , ?, ? ,SYSDATE,?) ";
		
		case 4 : return " SELECT HRCOMM_CODE,HRCOMM_LINKNAME,NVL(HRCOMM_LINK,'No File Associated'),HRCOMM_STATUS,Decode(HRCOMM_FLAG,'Y','YES','N','NO') FROM HRMS_SETTINGS_HRCOMM ORDER BY HRCOMM_CODE ";
		
		case 5 : return " UPDATE HRMS_SETTINGS_HRCOMM SET HRCOMM_LINKNAME = ?, HRCOMM_LINK = ?,HRCOMM_STATUS = ? ,HRCOMM_FLAG = ? WHERE HRCOMM_CODE = ?";
		
		case 6 : return " DELETE FROM HRMS_SETTINGS_HRCOMM WHERE HRCOMM_CODE = ?  ";
		
		/*case 7 : return " INSERT INTO HRMS_SETTINGS_CORPINFO(CORPINFO_CODE,CORPINFO_LINKNAME,CORPINFO_LINK,CORPINFO_FLAG,CORPINFO_LINK_DATE,CORPINFO_STATUS) " 
					  +" VALUES((SELECT NVL(MAX(CORPINFO_CODE),0) + 1 FROM HRMS_SETTINGS_CORPINFO),? , ?, ?,TO_DATE(SYSDATE,'DD-MM-YYYY'),?) ";
		
		case 8 : return " SELECT CORPINFO_CODE,CORPINFO_LINKNAME,NVL(CORPINFO_LINK,'No File Associated') FROM HRMS_SETTINGS_CORPINFO ORDER BY CORPINFO_CODE ";  
		
		case 9 : return " UPDATE HRMS_SETTINGS_CORPINFO SET CORPINFO_LINKNAME = ?, CORPINFO_LINK = ?,CORPINFO_STATUS = ? ,CORPINFO_FLAG = ? WHERE CORPINFO_CODE = ?"; 
		
		case 10 : return " DELETE FROM HRMS_SETTINGS_CORPINFO WHERE CORPINFO_CODE = ?";
		
		case 11 : return " INSERT INTO HRMS_SETTINGS_KNOWLEDGE(KNOW_CODE,KNOW_LINKNAME,KNOW_LINK,KNOW_FLAG,KNOW_DATE,KNOW_STATUS) " 
						+" VALUES((SELECT NVL(MAX(KNOW_CODE),0) + 1 FROM HRMS_SETTINGS_KNOWLEDGE),?,?,?,TO_DATE(SYSDATE,'DD-MM-YYYY'),?) ";
		
		case 12 : return " SELECT KNOW_CODE,KNOW_LINKNAME,NVL(KNOW_LINK,'No File Associated') FROM HRMS_SETTINGS_KNOWLEDGE ORDER BY KNOW_CODE ";
		
		case 13 : return " UPDATE HRMS_SETTINGS_KNOWLEDGE SET KNOW_LINKNAME = ?, KNOW_LINK = ?,KNOW_STATUS = ? ,KNOW_FLAG = ? WHERE KNOW_CODE = ?";
		
		case 14 : return " DELETE FROM HRMS_SETTINGS_KNOWLEDGE WHERE KNOW_CODE = ? ";
		
		case 15 : return " INSERT INTO HRMS_SETTINGS_CORPMSG(CORPMSG_CODE,CORPMSG_LINKNAME,CORPMSG_LINK,CORPMSG_FLAG,CORPMSG_LINK_DATE,CORPMSG_STATUS) "
						+" VALUES((SELECT NVL(MAX(CORPMSG_CODE),0) + 1 FROM HRMS_SETTINGS_CORPMSG),?,?,?,TO_DATE(SYSDATE,'DD-MM-YYYY'),?) ";
		
		case 16 : return " SELECT CORPMSG_CODE,CORPMSG_LINKNAME,NVL(CORPMSG_LINK,'No File Associated') FROM HRMS_SETTINGS_CORPMSG ORDER BY CORPMSG_CODE ";
		
		case 17 : return " UPDATE HRMS_SETTINGS_CORPMSG SET CORPMSG_LINKNAME = ?, CORPMSG_LINK = ?, CORPMSG_STATUS = ? ,CORPMSG_FLAG = ? WHERE CORPMSG_CODE = ?";
		
		case 18 : return " DELETE FROM HRMS_SETTINGS_CORPMSG WHERE CORPMSG_CODE = ? ";
		
		case 19 : return " DELETE FROM HRMS_SETTINGS_GENERAL WHERE EMP_ID = ? ";
		
		case 20 : return " INSERT INTO HRMS_SETTINGS_GENERAL(GENERAL_HOLIDAY,GENERAL_BDAY,GENERAL_NEWJOINEE,GENERAL_ADDRESS,EMP_ID) "
						+" VALUES(?,?,?,?,?) ";
		
		case 21 : return " INSERT INTO HRMS_SETTINGS_THOUGHT(THOUGHT_CODE,THOUGHT_NAME,THOUGHT_DATE,THOUGHT_FLAG) "
					   +"  VALUES((SELECT NVL(MAX(THOUGHT_CODE),0) + 1 FROM HRMS_SETTINGS_THOUGHT),?,SYSDATE,'Y') ";
		
		case 22 : return " SELECT THOUGHT_CODE,THOUGHT_NAME,TO_CHAR(THOUGHT_DATE,'DD-MM-YYYY') FROM HRMS_SETTINGS_THOUGHT ORDER BY THOUGHT_CODE  ";
		
		case 23 : return " UPDATE HRMS_SETTINGS_THOUGHT SET THOUGHT_NAME = ? WHERE THOUGHT_CODE = ? ";
		
		case 24 : return " DELETE FROM HRMS_SETTINGS_THOUGHT WHERE THOUGHT_CODE = ? ";
		
		case 25: return " INSERT INTO HRMS_SETTINGS_MAILBOX(MAILBOX_SERVER,MAILBOX_PROTOCOL,MAILBOX_PORT,MAILBOX_USERID,MAILBOX_PASSW,MAILBOX_COMP,MAILBOX_FLAG,MAILBOX_AUTH_CHK) "+
						" VALUES(?,?,?,?,?,1,?,?)";
		
		case 26 : return " INSERT INTO HRMS_SETTINGS_BULLETIN(BULLETIN_CODE,BULLETIN_LINKNAME,BULLETIN_LINK,BULLETIN_FLAG,BULLETIN_LINK_DATE,BULLETIN_STATUS) "
						+" VALUES((SELECT NVL(MAX(BULLETIN_CODE),0) + 1 FROM HRMS_SETTINGS_BULLETIN),?,?,?,TO_DATE(SYSDATE,'DD-MM-YYYY'),?) ";

		case 27 : return " SELECT BULLETIN_CODE,BULLETIN_LINKNAME,NVL(BULLETIN_LINK,'No File Associated') FROM HRMS_SETTINGS_BULLETIN ORDER BY BULLETIN_CODE ";

		case 28 : return " UPDATE HRMS_SETTINGS_BULLETIN SET BULLETIN_LINKNAME = ?, BULLETIN_LINK = ?, BULLETIN_STATUS = ? ,BULLETIN_FLAG = ? WHERE BULLETIN_CODE = ?";

		case 29 : return " DELETE FROM HRMS_SETTINGS_BULLETIN WHERE BULLETIN_CODE = ?";
		
		case 30 : return " UPDATE HRMS_SETTINGS_MAILBOX SET MAILBOX_SERVER = ?,MAILBOX_PROTOCOL = ?,MAILBOX_PORT = ?,MAILBOX_USERID = ?,MAILBOX_PASSW = ?,MAILBOX_AUTH_CHK = ? WHERE MAILBOX_FLAG = ?";
*/
		case 31 : return " INSERT INTO HRMS_SETTINGS_QUICKLINK_ADMIN(QUICK_ADMIN_CODE,QUICK_ADMIN_LINKNAME,QUICK_ADMIN_LINK,QUICK_ADMIN_STATUS,QUICK_SUPER_FLAG) " 
						 +" VALUES((SELECT NVL(MAX(QUICK_ADMIN_CODE),0) + 1 FROM HRMS_SETTINGS_QUICKLINK_ADMIN),?,?,?,?) ";

		case 32 : return " SELECT QUICK_ADMIN_CODE,TRIM(QUICK_ADMIN_LINKNAME),NVL(QUICK_ADMIN_LINK,'No File Associated'), QUICK_ADMIN_STATUS , Decode(QUICK_SUPER_FLAG,'Y','YES','N','NO') FROM HRMS_SETTINGS_QUICKLINK_ADMIN ORDER BY UPPER(TRIM(QUICK_ADMIN_LINKNAME)) ";  

		case 33 : return " UPDATE HRMS_SETTINGS_QUICKLINK_ADMIN SET QUICK_ADMIN_LINKNAME = ?, QUICK_ADMIN_LINK = ?,QUICK_ADMIN_STATUS = ? ,QUICK_SUPER_FLAG = ? WHERE QUICK_ADMIN_CODE = ?"; 

		case 34 : return " DELETE FROM HRMS_SETTINGS_QUICKLINK_ADMIN WHERE QUICK_ADMIN_CODE = ? ";
		
		case 35 : return " SELECT HRCOMM_CODE,HRCOMM_LINKNAME,NVL(HRCOMM_LINK,'No File Associated') FROM HRMS_SETTINGS_HRCOMM where HRCOMM_FLAG = 'Y' ORDER BY HRCOMM_CODE ";
		
		/*case 36 : return " SELECT CORPINFO_CODE,CORPINFO_LINKNAME,NVL(CORPINFO_LINK,'No File Associated') FROM HRMS_SETTINGS_CORPINFO where CORPINFO_FLAG = 'Y' ORDER BY CORPINFO_CODE ";  
		
		case 37 : return " SELECT KNOW_CODE,KNOW_LINKNAME,NVL(KNOW_LINK,'No File Associated') FROM HRMS_SETTINGS_KNOWLEDGE where KNOW_FLAG = 'Y' ORDER BY KNOW_CODE ";
		
		case 38 : return " SELECT BULLETIN_CODE,BULLETIN_LINKNAME,NVL(BULLETIN_LINK,'No File Associated') FROM HRMS_SETTINGS_BULLETIN where BULLETIN_FLAG = 'Y' ORDER BY BULLETIN_CODE ";
		
		case 39 : return " SELECT THOUGHT_CODE,THOUGHT_NAME,TO_CHAR(THOUGHT_DATE,'DD-MM-YYYY') FROM HRMS_SETTINGS_THOUGHT "
						+" WHERE THOUGHT_CODE = (SELECT MAX(THOUGHT_CODE ) FROM HRMS_SETTINGS_THOUGHT )  ";
*/		
		case 40 : return " INSERT INTO HRMS_SETTINGS_GENERAL(GENERAL_ID,GENERAL_LINK_NAME,GENERAL_LINK_PATH,GENERAL_STATUS,GENERAL_SUPERFLAG,EMP_ID) "
						+" VALUES((SELECT NVL(MAX(GENERAL_ID),0) + 1 FROM HRMS_SETTINGS_GENERAL),?,?,?,?,?) ";

		case 41 : return " SELECT GENERAL_ID,GENERAL_LINK_NAME,NVL(GENERAL_LINK_PATH,'No File Associated'),GENERAL_STATUS,Decode(GENERAL_SUPERFLAG,'Y','YES','N','NO') FROM HRMS_SETTINGS_GENERAL ORDER BY GENERAL_id ";

		case 42 : return " UPDATE HRMS_SETTINGS_GENERAL SET GENERAL_LINK_NAME = ?, GENERAL_LINK_PATH = ?, GENERAL_STATUS = ?, GENERAL_SUPERFLAG = ? WHERE GENERAL_ID = ?";

		/*case 43 : return " UPDATE HRMS_SETTINGS_GENERAL SET GENERAL_LINK_NAME = ?, GENERAL_LINK_PATH = ?, GENERAL_STATUS = ?, GENERAL_VIEW_FLAG = ?  WHERE GENERAL_TYPE = ?";

		case 44 : return " DELETE FROM HRMS_SETTINGS_QUICKLINK_ADMIN WHERE QUICK_ADMIN_CODE = ? ";
		
		case 45 : return " SELECT GENERAL_ID,GENERAL_LINK_NAME,GENERAL_LINK_PATH,decode(GENERAL_TYPE,'B','Birthday','A','Address','H','Holiday','N','New Joinee') FROM HRMS_SETTINGS_GENERAL where GENERAL_VIEW_FLAG = 'Y' ORDER BY GENERAL_ID";
		
		case 46 : return " SELECT CORPMSG_CODE,CORPMSG_LINKNAME,NVL(CORPMSG_LINK,'No File Associated') FROM HRMS_SETTINGS_CORPMSG where CORPMSG_FLAG = 'Y' ORDER BY CORPMSG_CODE ";
*/		
		case 47 : return " DELETE FROM HRMS_SETTINGS_GENERAL WHERE GENERAL_ID = ? ";
		
		case 45 : return " SELECT GENERAL_ID,GENERAL_LINK_NAME,nvl(GENERAL_LINK_PATH,' ') FROM HRMS_SETTINGS_GENERAL where GENERAL_VIEW_FLAG = 'Y' AND GENERAL_SUPERFLAG = 'Y' ORDER BY GENERAL_ID ";
		
		//	case 46 : return " SELECT CORPMSG_CODE,CORPMSG_LINKNAME,NVL(CORPMSG_LINK,'No File Associated') FROM HRMS_SETTINGS_CORPMSG where CORPMSG_FLAG = 'Y' ORDER BY CORPMSG_CODE ";
			
		case 48 :  return " SELECT QUICK_ADMIN_CODE,QUICK_ADMIN_LINKNAME,QUICK_ADMIN_LINK FROM HRMS_SETTINGS_QUICKLINK_ADMIN where QUICK_FLAG = 'Y' AND QUICK_SUPER_FLAG = 'Y' ORDER BY QUICK_ADMIN_CODE";
		
		/*case 49 : return " INSERT INTO HRMS_SALARY_CONF(CONF_BRN_FLAG,CONF_DEPT_FLAG,CONF_PAYBILL_FLAG,CONF_EMPTYPE_FLAG,CONF_DIVISION_FLAG,CONF_LEAVE_MANGT_YEAR,CONF_DAILY_ATT_CONNECT_FLAG,CONF_SALARY_START_FLAG,CONF_SALARY_START_DATE,CONF_BRANCH_HOLI_FLAG,CONF_RECORDS_PER_PAGE,CONF_JOINDAYS_FLAG,CONF_LEAVEDAYS_FLAG) "
						+" VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?) ";*/

		case 49:
			return " INSERT INTO HRMS_SALARY_CONF(CONF_BRN_FLAG,CONF_DEPT_FLAG,CONF_PAYBILL_FLAG,CONF_EMPTYPE_FLAG,CONF_DIVISION_FLAG,CONF_LEAVE_MANGT_YEAR,CONF_RECORDS_PER_PAGE,CONF_JOINDAYS_FLAG,CONF_LEAVEDAYS_FLAG,CONF_RECOVERY_FLAG,CONF_SUSP_FLAG,CONF_TAX_WORKFLOW_FLAG,CONF_EPF, CONF_GPF, CONF_VPF, "
					+" CONF_PFTRUST, EXTRAWORK_FLAG,CONF_CREDIT_ROUND,CONF_TOTCREDIT_OPTION,CONF_TOTDEBIT_ROUND,CONF_NETPAY_ROUND,CONF_RECOVERY_DEBIT ) "
					+ " VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ";

		case 50 : return " DELETE  FROM HRMS_SALARY_CONF ";
		default : return " HI";
		}
	}

}
