 package org.paradyne.sql.TravelManagement;

import org.paradyne.lib.SqlBase;

public class TravelApplicationModelSql extends SqlBase {
  
	public String getQuery(int id){
		switch (id)
		{
		case 1 : return " INSERT INTO HRMS_TRAVEL(TRAVEL_ID, TRAVEL_EMPID, TRAVEL_APPDATE, TRAVEL_APPROVER,TRAVEL_APPLICANT_COMMENT,TRAVEL_ALTER_APPROVER,TRAVEL_ID_PROOF, TRAVEL_PROOF_NO ) VALUES((SELECT NVL(MAX(TRAVEL_ID),0)+1 FROM HRMS_TRAVEL),?,TO_DATE(?,'DD-MM-YYYY'),? ,? ,?,?,? ) ";
		
		case 2 : return " INSERT INTO HRMS_TRAVEL_DTL(TRAVELDTL_TRAVEL_ID,TRAVELDTL_FROM_PLACE, TRAVELDTL_TO_PLACE, TRAVELDTL_JOURNEY_MODE, TRAVELDTL_JOURNEY_CLASS, TRAVELDTL_JOURNEY_DATE, TRAVELDTL_JOURNEY_TIME ,TRAVELDTL_SCHD_JOUR_MODE, TRAVELDTL_SCHD_JOUR_CLASS ,TRAVELDTL_JOURNEY_MODEREF_NUM,TRAVELDTL_SCHD_MODEREF_NUMBER) "  
		              +  " VALUES((SELECT NVL(MAX(TRAVEL_ID),0) FROM HRMS_TRAVEL),?,?,?,?,TO_DATE(?,'DD-MM-YYYY'),?,?,?,?,?) ";
		
		case 3 : return " UPDATE HRMS_TRAVEL SET TRAVEL_EMPID = ?, TRAVEL_APPROVER =? ,TRAVEL_APPLICANT_COMMENT = ? ,TRAVEL_ALTER_APPROVER = ? ,TRAVEL_ID_PROOF = ?, TRAVEL_PROOF_NO =?  WHERE TRAVEL_ID = ? ";
		
		case 4 : return " INSERT INTO HRMS_TRAVEL_DTL(TRAVELDTL_TRAVEL_ID,TRAVELDTL_FROM_PLACE, TRAVELDTL_TO_PLACE, TRAVELDTL_JOURNEY_MODE, TRAVELDTL_JOURNEY_CLASS, TRAVELDTL_JOURNEY_DATE, TRAVELDTL_JOURNEY_TIME ,TRAVELDTL_SCHD_JOUR_MODE, TRAVELDTL_SCHD_JOUR_CLASS ,TRAVELDTL_JOURNEY_MODEREF_NUM,TRAVELDTL_SCHD_MODEREF_NUMBER ) "  
               +  " VALUES(?,?,?,?,?,TO_DATE(?,'DD-MM-YYYY'),?,?,?,?,?) ";
		
        case 5 : return " UPDATE HRMS_TRAVEL SET TRAVEL_SCHEDULE_STATUS = 'S'  WHERE TRAVEL_ID = ? ";
		
		case 6 : return " INSERT INTO HRMS_TRAVEL_DTL(TRAVELDTL_ID,TRAVELDTL_TRAVEL_ID,TRAVELDTL_FROM_PLACE, TRAVELDTL_TO_PLACE, TRAVELDTL_JOURNEY_MODE, TRAVELDTL_JOURNEY_CLASS, TRAVELDTL_JOURNEY_DATE, TRAVELDTL_JOURNEY_TIME ," 
				       + " TRAVELDTL_SCHD_JOUR_MODE, TRAVELDTL_SCHD_JOUR_CLASS, TRAVELDTL_SCHD_DATE, TRAVELDTL_SCHD_TIME, TRAVELDTL_SCHD_MODEREF_NUMBER, TRAVELDTL_SCHD_TICKET_NUMBER, TRAVELDTL_SCHD_JOUR_COST," 
				       +" TRAVELDTL_SCHD_JOUR_EXTAMT,TRAVELDTL_SCHD_JOUR_COMMENT )"  
                      +  " VALUES((SELECT NVL(MAX(TRAVELDTL_ID),0)+1 FROM HRMS_TRAVEL_DTL),?,?,?,?,?,TO_DATE(?,'DD-MM-YYYY'),? ,?,?,NVL(TO_DATE(?,'DD-MM-YYYY'),''),?,?,?,?,?,?) ";

		case 7 : return " INSERT INTO HRMS_TRAVEL_HOTEL( TRAVEL_HOTEL_ID,TRAVEL_HOTEL_TRAVEL_ID, TRAVEL_HOTEL_NAME, TRAVEL_HOTEL_ADDRESS, TRAVEL_HOTEL_CHKIN_DATE, TRAVEL_HOTEL_CHKIN_TIME, TRAVEL_HOTEL_CHKOUT_DATE, " 
				            +   " TRAVEL_HOTEL_CHKOUT_TIME, TRAVEL_HOTEL_BILL,TRAVEL_HOTEL_OTHER_BILL, TRAVEL_HOTEL_COMMENT ) "  
                           +  " VALUES((SELECT NVL(MAX(TRAVEL_HOTEL_ID),0)+1  FROM HRMS_TRAVEL_HOTEL) ,?,?,?,NVL(TO_DATE(?,'DD-MM-YYYY'),''),?,NVL(TO_DATE(?,'DD-MM-YYYY'),''),?,?,?,?) ";
		
		case 8 : return " UPDATE HRMS_TRAVEL_DTL SET TRAVELDTL_SCHD_CANCEL_AMT=? WHERE TRAVELDTL_ID=?";
		
		case 9 : return " UPDATE HRMS_TRAVEL_HOTEL SET TRAVEL_HOTEL_CANCEL_AMT=? WHERE TRAVEL_HOTEL_ID=?";
		  

		default : return "Framework could not EXECUTE the query number specified";			

		}
	 }
	
}
