package org.paradyne.sql.admin.srd;

import org.paradyne.lib.SqlBase;

/**
 * @author prajakta.bhandare
 * @date 21 Jan 2013
 */
public class AddressDetailsModelSql extends SqlBase {

	public String getQuery(int id) {
		switch (id) {

		case 1:
			return " INSERT INTO HRMS_EMP_ADDRESS(EMP_ID,ADD_TYPE,ADD_1,ADD_2,ADD_3, "
					+ " ADD_CITY,ADD_STATE,ADD_CNTRY,ADD_PH1,ADD_PH2,ADD_EXTENSION,ADD_FAX,ADD_MOBILE,ADD_EMAIL,ADD_PINCODE) "
					+ " VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
			
		case 2:
			return "UPDATE HRMS_EMP_ADDRESS SET ADD_1 = ?,ADD_2 = ? ,ADD_3 = ?, ADD_CITY =?,"
					+ " ADD_STATE = ?,ADD_CNTRY = ?,ADD_PH1 = ?, ADD_PH2=?,ADD_EXTENSION=?, ADD_FAX= ? ," +
					"ADD_MOBILE =? ,ADD_EMAIL = ?,ADD_PINCODE=? "
					+ " WHERE EMP_ID = ? and ADD_TYPE = ?" ;

		case 3:
			return " SELECT ADD_TYPE,ADD_1,ADD_2,ADD_3,HRMS_LOCATION.LOCATION_NAME,ADD_STATE,ADD_CNTRY,NVL(ADD_PH1,' '),NVL(ADD_PH2,' '),ADD_EXTENSION,NVL(ADD_FAX,' '), "
					+ " NVL(ADD_MOBILE,' '),NVL(ADD_EMAIL,' '),ADD_CITY,ADD_PINCODE FROM HRMS_EMP_ADDRESS "
					+ " LEFT JOIN HRMS_LOCATION ON(HRMS_LOCATION.LOCATION_CODE=HRMS_EMP_ADDRESS.ADD_CITY)"
					+ " INNER JOIN HRMS_EMP_OFFC ON(HRMS_EMP_ADDRESS.EMP_ID=HRMS_EMP_OFFC.EMP_ID) "
					+ " LEFT JOIN HRMS_RANK ON(HRMS_EMP_OFFC.EMP_RANK=HRMS_RANK.RANK_ID) "
					+ " LEFT JOIN HRMS_TITLE ON(HRMS_TITLE.TITLE_CODE=HRMS_EMP_OFFC.EMP_TITLE_CODE)"
					+ " INNER JOIN HRMS_CENTER ON(HRMS_CENTER.CENTER_ID=HRMS_EMP_OFFC.EMP_CENTER) "
					+ " WHERE HRMS_EMP_ADDRESS.ADD_TYPE = ? AND HRMS_EMP_ADDRESS.EMP_ID =? ";

		case 4:
			return  "SELECT getValue('addressType',ADD_TYPE),"
			 		+" (ADD_1||' '||ADD_2||' '||ADD_3),ADD_PINCODE,ADD_PH1,ADD_PH2,ADD_FAX, "
			 		+" ADD_MOBILE,NVL(ADD_EMAIL,' '),ADD_EXTENSION,ADD_TYPE,HRMS_LOCATION.LOCATION_NAME,"
			 		+" ADD_STATE,ADD_CNTRY FROM HRMS_EMP_ADDRESS "
			 		+" LEFT JOIN HRMS_LOCATION ON(HRMS_LOCATION.LOCATION_CODE=HRMS_EMP_ADDRESS.ADD_CITY)"
			 		+" INNER JOIN HRMS_EMP_OFFC ON(HRMS_EMP_ADDRESS.EMP_ID=HRMS_EMP_OFFC.EMP_ID) "
			 		+" LEFT JOIN HRMS_RANK ON(HRMS_EMP_OFFC.EMP_RANK=HRMS_RANK.RANK_ID) "
			 		+" LEFT JOIN HRMS_TITLE ON(HRMS_TITLE.TITLE_CODE=HRMS_EMP_OFFC.EMP_TITLE_CODE)"
			 		+" INNER JOIN HRMS_CENTER ON(HRMS_CENTER.CENTER_ID=HRMS_EMP_OFFC.EMP_CENTER) "
			 		+" WHERE HRMS_EMP_ADDRESS.EMP_ID =?";		

		case 5:
			return " DELETE FROM HRMS_EMP_ADDRESS WHERE EMP_ID = ? and ADD_TYPE=?";

		default:
			return "Query not found";

		}//end of switch

	}
}