package org.paradyne.sql.admin.srd;

import org.paradyne.lib.SqlBase;

/**
 *modeified by priyanka kumbhar
 * 
 */

public class AwardDetailsModelSql extends SqlBase {

	public String getQuery(int id) {
		switch (id) {

		case 1:
			return " INSERT INTO HRMS_AWARD(AWARD_ID,EMP_ID,AWARD_TYPE_ID,AWARD_REASON,AWARD_DATE,AWARD_AUTH,AWARD_AUTH_DATE,AWARD_SRLNO,AWARD_DOCUMENT , AWARD_PHOTO, AWARD_ISACTIVEINDASHLET ) "
					+ " VALUES((SELECT NVL(MAX(AWARD_ID),0)+1 FROM HRMS_AWARD),?,?,?,TO_DATE(?,'DD-MM-YYYY'),?,TO_DATE(?,'DD-MM-YYYY'),?,?,?,?)";

		case 2:
			return " UPDATE HRMS_AWARD SET AWARD_TYPE_ID = ?, AWARD_REASON = ?,AWARD_DATE = TO_DATE(?,'DD-MM-YYYY'), AWARD_AUTH = ?, "
					+ " AWARD_AUTH_DATE = TO_DATE(?,'DD-MM-YYYY'),EMP_ID = ?, AWARD_SRLNO = ?,AWARD_DOCUMENT=? ,AWARD_PHOTO=? , AWARD_ISACTIVEINDASHLET=? WHERE AWARD_ID = ? ";

		case 3:
			return " SELECT AWARD_ID,HRMS_EMP_OFFC.EMP_ID,EMP_TOKEN,(HRMS_TITLE.TITLE_NAME||' '||HRMS_EMP_OFFC.EMP_FNAME || ' ' || HRMS_EMP_OFFC.EMP_MNAME || ' ' || HRMS_EMP_OFFC.EMP_LNAME),"
					+ " AWARD_SRLNO,HRMS_AWARD_MASTER.AWARD_CODE,HRMS_AWARD_MASTER.AWARD_TYPE,AWARD_REASON,TO_CHAR(AWARD_DATE,'DD-MM-YYYY'),"
					+ " AWARD_AUTH,TO_CHAR(AWARD_AUTH_DATE,'DD-MM-YYYY'),AWARD_DOCUMENT ,AWARD_PHOTO,AWARD_ISACTIVEINDASHLET  "
					+ " FROM HRMS_AWARD"
					+ " INNER JOIN HRMS_EMP_OFFC ON(HRMS_AWARD.EMP_ID=HRMS_EMP_OFFC.EMP_ID)"
					+ " LEFT JOIN HRMS_TITLE ON HRMS_TITLE.TITLE_CODE=HRMS_EMP_OFFC.EMP_TITLE_CODE "				
					+ " LEFT JOIN HRMS_AWARD_MASTER ON(HRMS_AWARD.AWARD_TYPE_ID=HRMS_AWARD_MASTER.AWARD_CODE) "
					+ " WHERE HRMS_AWARD.EMP_ID = ? AND AWARD_ID = ?";

		case 4:
			return " SELECT AWARD_ID,HRMS_EMP_OFFC.EMP_ID,EMP_TOKEN,(HRMS_TITLE.TITLE_NAME||' '||HRMS_EMP_OFFC.EMP_FNAME || ' ' || HRMS_EMP_OFFC.EMP_MNAME || ' ' || HRMS_EMP_OFFC.EMP_LNAME),"
					+ " AWARD_SRLNO,HRMS_AWARD_MASTER.AWARD_CODE,HRMS_AWARD_MASTER.AWARD_TYPE,AWARD_REASON,TO_CHAR(AWARD_DATE,'DD-MM-YYYY'),"
					+ " AWARD_AUTH,TO_CHAR(AWARD_AUTH_DATE,'DD-MM-YYYY'),AWARD_DOCUMENT ,AWARD_PHOTO,DECODE(AWARD_ISACTIVEINDASHLET,'Y','Yes','N','No','No') "
					+ " FROM HRMS_AWARD"
					+ " INNER JOIN HRMS_EMP_OFFC ON(HRMS_AWARD.EMP_ID=HRMS_EMP_OFFC.EMP_ID)"
					+ " LEFT JOIN HRMS_TITLE ON HRMS_TITLE.TITLE_CODE=HRMS_EMP_OFFC.EMP_TITLE_CODE "				
					+ " LEFT JOIN HRMS_AWARD_MASTER ON(HRMS_AWARD.AWARD_TYPE_ID=HRMS_AWARD_MASTER.AWARD_CODE) "
					+ " WHERE HRMS_AWARD.EMP_ID = ? ";

		case 5:
			return " SELECT EMP_ID,EMP_TOKEN,(HRMS_TITLE.TITLE_NAME||' '||HRMS_EMP_OFFC.EMP_FNAME || ' ' || HRMS_EMP_OFFC.EMP_MNAME || ' ' || HRMS_EMP_OFFC.EMP_LNAME),"
					+ "	(HRMS_CENTER.CENTER_NAME),HRMS_RANK.RANK_NAME FROM HRMS_EMP_OFFC LEFT JOIN HRMS_TITLE ON (HRMS_TITLE.TITLE_CODE=HRMS_EMP_OFFC.EMP_TITLE_CODE) "
					+ "	INNER JOIN HRMS_CENTER ON (HRMS_EMP_OFFC.EMP_CENTER=HRMS_CENTER.CENTER_ID) "
					+ "  LEFT JOIN HRMS_RANK ON (HRMS_EMP_OFFC.EMP_RANK=HRMS_RANK.RANK_ID)"
					+ "  WHERE HRMS_EMP_OFFC.EMP_ID = ? ";

		case 6:
			return " DELETE FROM HRMS_AWARD WHERE AWARD_ID = ? ";

		case 7:
			return " SELECT AWARD_ID,HRMS_EMP_OFFC.EMP_ID,EMP_TOKEN,(HRMS_TITLE.TITLE_NAME||' '||HRMS_EMP_OFFC.EMP_FNAME || ' ' || HRMS_EMP_OFFC.EMP_MNAME || ' ' || HRMS_EMP_OFFC.EMP_LNAME),"
					+ " (HRMS_CENTER.CENTER_NAME),HRMS_RANK.RANK_NAME,HRMS_AWARD_MASTER.AWARD_TYPE,AWARD_REASON,TO_CHAR(AWARD_DATE,'DD-MM-YYYY'),AWARD_AUTH,TO_CHAR(AWARD_AUTH_DATE,'DD-MM-YYYY'),AWARD_SRLNO FROM HRMS_AWARD"
					+ " INNER JOIN HRMS_EMP_OFFC ON(HRMS_AWARD.EMP_ID=HRMS_EMP_OFFC.EMP_ID)"
					+ " LEFT JOIN HRMS_TITLE ON HRMS_TITLE.TITLE_CODE=HRMS_EMP_OFFC.EMP_TITLE_CODE "
					+ " LEFT JOIN HRMS_RANK ON (HRMS_EMP_OFFC.EMP_RANK=HRMS_RANK.RANK_ID)"
					+ " INNER JOIN HRMS_CENTER ON (HRMS_EMP_OFFC.EMP_CENTER=HRMS_CENTER.CENTER_ID)"
					+ " LEFT JOIN HRMS_AWARD_MASTER ON(HRMS_AWARD.AWARD_TYPE_ID=HRMS_AWARD_MASTER.AWARD_CODE) "
					+ " WHERE HRMS_AWARD.EMP_ID = ? ";

		case 8:
			return " SELECT AWARD_ID,HRMS_EMP_OFFC.EMP_ID,EMP_TOKEN,(HRMS_TITLE.TITLE_NAME||' '||HRMS_EMP_OFFC.EMP_FNAME || ' ' || HRMS_EMP_OFFC.EMP_MNAME || ' ' || HRMS_EMP_OFFC.EMP_LNAME),"
					+ " (HRMS_CENTER.CENTER_NAME),HRMS_RANK.RANK_NAME,HRMS_AWARD_MASTER.AWARD_TYPE,AWARD_REASON,TO_CHAR(AWARD_DATE,'DD-MM-YYYY'),AWARD_AUTH,TO_CHAR(AWARD_AUTH_DATE,'DD-MM-YYYY') FROM HRMS_AWARD"
					+ " INNER JOIN HRMS_EMP_OFFC ON(HRMS_AWARD.EMP_ID=HRMS_EMP_OFFC.EMP_ID)"
					+ " LEFT JOIN HRMS_TITLE ON HRMS_TITLE.TITLE_CODE=HRMS_EMP_OFFC.EMP_TITLE_CODE "
					+ " LEFT JOIN HRMS_RANK ON (HRMS_EMP_OFFC.EMP_RANK=HRMS_RANK.RANK_ID)"
					+ " INNER JOIN HRMS_CENTER ON (HRMS_EMP_OFFC.EMP_CENTER=HRMS_CENTER.CENTER_ID)"
					+ " LEFT JOIN HRMS_AWARD_MASTER ON(HRMS_AWARD.AWARD_TYPE_ID=HRMS_AWARD_MASTER.AWARD_CODE) "
					+ " WHERE HRMS_AWARD.EMP_ID = ? ";
		case 9:
			return " SELECT AWARD_ID,HRMS_EMP_OFFC.EMP_ID,EMP_TOKEN,(HRMS_TITLE.TITLE_NAME||' '||HRMS_EMP_OFFC.EMP_FNAME || ' ' || HRMS_EMP_OFFC.EMP_MNAME || ' ' || HRMS_EMP_OFFC.EMP_LNAME),"
					+ " (HRMS_CENTER.CENTER_NAME),HRMS_RANK.RANK_NAME,AWARD_SRLNO,HRMS_AWARD_MASTER.AWARD_CODE,HRMS_AWARD_MASTER.AWARD_TYPE,AWARD_REASON,TO_CHAR(AWARD_DATE,'DD-MM-YYYY'),AWARD_AUTH,TO_CHAR(AWARD_AUTH_DATE,'DD-MM-YYYY'),AWARD_DOCUMENT FROM HRMS_AWARD"
					+ " INNER JOIN HRMS_EMP_OFFC ON(HRMS_AWARD.EMP_ID=HRMS_EMP_OFFC.EMP_ID)"
					+ " LEFT JOIN HRMS_TITLE ON HRMS_TITLE.TITLE_CODE=HRMS_EMP_OFFC.EMP_TITLE_CODE "
					+ " LEFT JOIN HRMS_RANK ON (HRMS_EMP_OFFC.EMP_RANK=HRMS_RANK.RANK_ID)"
					+ " INNER JOIN HRMS_CENTER ON (HRMS_EMP_OFFC.EMP_CENTER=HRMS_CENTER.CENTER_ID)"
					+ " LEFT JOIN HRMS_AWARD_MASTER ON(HRMS_AWARD.AWARD_TYPE_ID=HRMS_AWARD_MASTER.AWARD_CODE) "
					+ " WHERE HRMS_AWARD.AWARD_ID = ? AND HRMS_AWARD.EMP_ID = ? ";
		default:
			return "Query not found ";

		}
	}

}
