/**
 * 
 */
package org.paradyne.sql.admin.srd;

import org.paradyne.lib.SqlBase;

/**
 * @author riteshr
 *
 */
public class DqeHistoryModelSql extends SqlBase {
	
public String getQuery(int id){
		
		
		
		switch (id) {
		
		case 1 :  return " INSERT INTO HRMS_DQE_HISTORY (DQE_ID,EMP_ID ,DQE_POST,DQE_TRADE,DQE_DOJ, "
				+" DQE_DC_LIST_NO,DQE_SR_NO,DQE_DC_LIST_DATE) " 
				+" VALUES((SELECT NVL(MAX(DQE_ID),0)+1 FROM HRMS_DQE_HISTORY),UPPER(?),?,?,TO_DATE(?,'DD-MM-YYYY'),?,?,TO_DATE(?,'DD-MM-YYYY')) "; 
		
		
		case 2 :  return " SELECT RANK_NAME,TRADE_NAME,TO_CHAR(DQE_DOJ,'DD-MM-YYYY'), "
				+" DQE_DC_LIST_NO,DQE_SR_NO,DQE_ID,TO_CHAR(DQE_DC_LIST_DATE,'DD-MM-YYYY') FROM HRMS_DQE_HISTORY  "
				+" INNER JOIN HRMS_RANK ON (HRMS_DQE_HISTORY.DQE_POST=HRMS_RANK.RANK_ID) "
				+" INNER JOIN HRMS_TRADE ON (HRMS_DQE_HISTORY.DQE_TRADE=HRMS_TRADE.TRADE_CODE) " 
				+" WHERE EMP_ID = ? ORDER BY DQE_ID ";
		
		case 3 :  return " SELECT RANK_NAME,TRADE_NAME,TO_CHAR(DQE_DOJ,'DD-MM-YYYY'), "
				+" DQE_DC_LIST_NO,DQE_SR_NO,EMP_ID,DQE_POST,DQE_TRADE,TO_CHAR(DQE_DC_LIST_DATE,'DD-MM-YYYY') FROM HRMS_DQE_HISTORY " 
				+" INNER JOIN HRMS_RANK ON (HRMS_DQE_HISTORY.DQE_POST=HRMS_RANK.RANK_ID) "
				+" INNER JOIN HRMS_TRADE ON (HRMS_DQE_HISTORY.DQE_TRADE=HRMS_TRADE.TRADE_CODE) "
				+" WHERE DQE_ID = ?  ";
		
		case 4 :  return " UPDATE HRMS_DQE_HISTORY  SET DQE_POST = ?,DQE_TRADE = ?,DQE_DOJ = TO_DATE(?,'DD-MM-YYYY'), "
				+" DQE_DC_LIST_NO = ?,DQE_SR_NO = ?,DQE_DC_LIST_DATE= TO_DATE(?,'DD-MM-YYYY') WHERE DQE_ID = ? "; 
		
		case 5: return  " DELETE FROM  HRMS_DQE_HISTORY  WHERE DQE_ID = ? "; 
		
		
		case 7 : return " SELECT (CENTER_ID||'-'||CENTER_NAME),RANK_NAME,EMP_ID,(HRMS_TITLE.TITLE_NAME||' '||EMP_FNAME||'  '|| EMP_MNAME|| '  ' ||EMP_LNAME),EMP_TOKEN FROM HRMS_EMP_OFFC " 
				+" LEFT JOIN HRMS_TITLE ON(HRMS_TITLE.TITLE_CODE=HRMS_EMP_OFFC.EMP_TITLE_CODE) "
				+" INNER JOIN HRMS_RANK ON HRMS_RANK.RANK_ID = HRMS_EMP_OFFC.EMP_RANK "
				+" INNER JOIN HRMS_CENTER ON HRMS_CENTER.CENTER_ID = HRMS_EMP_OFFC.EMP_CENTER "
				+" WHERE EMP_ID = ?";

		
		default: return " query no. is not specified  ";
		}
	}


}
