package org.paradyne.sql.admin.srd;

import org.paradyne.lib.SqlBase;

public class EmployeePostingModelSql  extends SqlBase{

	
	
	public String getQuery(int id) {
		switch (id) {

		case 1:
			return "INSERT INTO HRMS_EMP_POSTING (ONSITE_POSTING_ID,EMP_ID,EMP_POSTING_DATE_START, EMP_POSTING_DATE_END, EMP_POSTING_DESC)" 
					+" VALUES (?,? ,TO_DATE(?,'DD-MM-YYYY') ,TO_DATE(?,'DD-MM-YYYY'),? )";
					

		case 2: 
			    return "UPDATE HRMS_EMP_POSTING  SET ONSITE_POSTING_ID=?,EMP_POSTING_DATE_START=TO_DATE(?,'DD-MM-YYYY'), EMP_POSTING_DATE_END=TO_DATE(?,'DD-MM-YYYY'), EMP_POSTING_DESC=? WHERE EMP_ID=?";
			

		case 3:
			return " SELECT HRMS_EMP_POSTING.EMP_ID ,EMP_TOKEN,(HRMS_TITLE.TITLE_NAME||' '||EMP_FNAME||'  '||EMP_MNAME||'  '||EMP_LNAME) name ,HRMS_CENTER.CENTER_NAME,HRMS_RANK.RANK_NAME, ONSITE_POSTING_ID,EMP_POSTING_DATE_START,EMP_POSTING_DATE_END, EMP_POSTING_DESC  FROM HRMS_EMP_POSTING " +
					" INNER JOIN HRMS_EMP_OFFC ON (HRMS_EMP_OFFC.EMP_ID=HRMS_EMP_POSTING.EMP_ID)" +
					" LEFT JOIN HRMS_TITLE ON(HRMS_TITLE.TITLE_CODE=HRMS_EMP_OFFC.EMP_TITLE_CODE) " +
					" LEFT JOIN HRMS_RANK ON(HRMS_RANK.RANK_ID=HRMS_EMP_OFFC.EMP_RANK)  " +
					" LEFT JOIN HRMS_CENTER ON(HRMS_CENTER.CENTER_ID=HRMS_EMP_OFFC.EMP_CENTER) " +
					" WHERE HRMS_EMP_POSTING.EMP_ID = ?  and HRMS_EMP_POSTING.ONSITE_POSTING_ID =? ";

		case 4:
			return " SELECT  HRMS_EMP_POSTING.EMP_ID,EMP_TOKEN,HRMS_TITLE.TITLE_NAME||''||HRMS_EMP_OFFC.EMP_FNAME||''||HRMS_EMP_OFFC.EMP_MNAME||''||HRMS_EMP_OFFC.EMP_LNAME, ONSITE_POSTING_NAME,LOCATION_NAME,NVL(TO_CHAR(EMP_POSTING_DATE_START,'DD-MM-YYYY'),'  '), "
					+ " NVL(TO_CHAR(EMP_POSTING_DATE_END,'DD-MM-YYYY'),'  '),NVL( EMP_POSTING_DESC,''),ONSITE_POSTING_ID,ONSITE_POSTING_LOCATION,EMP_POSTING_ID"
					+ " FROM HRMS_EMP_POSTING"
					+ " LEFT JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=HRMS_EMP_POSTING.EMP_ID)"				
					+ " LEFT JOIN HRMS_TITLE ON (HRMS_TITLE.TITLE_CODE = HRMS_EMP_OFFC.EMP_TITLE_CODE)"
					+ " LEFT JOIN HRMS_ONSITE_POSTING ON (HRMS_ONSITE_POSTING.ONSITE_POSTING_ID = HRMS_EMP_POSTING.ONSITE_POSTING_ID)"
					+ " LEFT JOIN HRMS_LOCATION ON(HRMS_ONSITE_POSTING.ONSITE_POSTING_LOCATION = HRMS_LOCATION.LOCATION_CODE)"
					+ " WHERE HRMS_EMP_POSTING.EMP_ID = ?   ";

		case 5:
			return "";
		default:
			return "";
		}
	}
}
