package org.paradyne.sql.admin.srd;

import org.paradyne.lib.SqlBase;

/**
 * @author radha
 * 
 */

public class NomineeDetailModelSql extends SqlBase {

	public String getQuery(int id) {
		switch (id) {

		case 1:
			return "INSERT INTO HRMS_EMP_NOMINEE (NOM_ID,EMP_ID,NOM_TYPE,NOM_NOMINEE,NOM_SHARE,NOM_DATE)"
					+ " VALUES((SELECT NVL(MAX(NOM_ID),0)+1 FROM HRMS_EMP_NOMINEE),?,?,?,?,TO_DATE(?,'DD-MM-YYYY'))";

		case 2:
			return "UPDATE HRMS_EMP_NOMINEE SET NOM_TYPE=?,NOM_NOMINEE=?,NOM_SHARE=?,NOM_DATE= TO_DATE(?,'DD-MM-YYYY') WHERE NOM_ID=? ";

		case 3:
			return " SELECT EMP_TOKEN,HRMS_TITLE.TITLE_NAME||' '||HRMS_EMP_OFFC.EMP_FNAME||' '||HRMS_EMP_OFFC.EMP_MNAME||' '||HRMS_EMP_OFFC.EMP_LNAME,EMP_RANK,TO_CHAR(RANK_NAME),EMP_CENTER,TO_CHAR(CENTER_NAME), "
					+ " NOM_ID,DECODE(NOM_TYPE,'G','GRATUITY','F','PF','P','PENSION','S','ESIC'),NOM_NOMINEE,NVL(FML_FNAME ||' '||FML_MNAME || ' '||FML_LNAME,' '),NVL(NOM_SHARE,0),"
					+ " TO_CHAR(NOM_DATE,'DD-MM-YYYY'),EMP_ID"
					+ " FROM HRMS_EMP_NOMINEE "
					+ " LEFT JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=HRMS_EMP_NOMINEE.EMP_ID) "
					+ "INNER JOIN HRMS_RANK ON HRMS_RANK.RANK_ID = HRMS_EMP_OFFC.EMP_RANK "
					+ " INNER JOIN HRMS_CENTER ON(HRMS_CENTER.CENTER_ID=HRMS_EMP_OFFC.EMP_CENTER) "
					+ " LEFT JOIN HRMS_EMP_FML ON(HRMS_EMP_FML.FML_ID=HRMS_EMP_NOMINEE.NOM_NOMINEE)"
					+ "LEFT JOIN HRMS_TITLE ON HRMS_TITLE.TITLE_CODE = HRMS_EMP_OFFC.EMP_TITLE_CODE "
					+ " WHERE HRMS_EMP_NOMINEE.EMP_ID =? ORDER BY NOM_ID";

		case 4:
			return " SELECT  NOM_TYPE,NOM_NOMINEE,NVL(FML_FNAME ||' '||FML_MNAME || ' '||FML_LNAME,' '),NVL(NOM_SHARE,0), "
					+ " TO_CHAR(NOM_DATE,'DD-MM-YYYY'),NOM_ID FROM HRMS_EMP_NOMINEE	"
					+ " LEFT JOIN HRMS_EMP_FML ON(HRMS_EMP_FML.FML_ID=HRMS_EMP_NOMINEE.NOM_NOMINEE)"
					+ " WHERE NOM_ID=? AND HRMS_EMP_NOMINEE.EMP_ID =? ";

		case 5:
			return "DELETE FROM HRMS_EMP_NOMINEE WHERE NOM_ID=?";

		default:
			return "";
		}
	}
}