package org.paradyne.sql.admin.srd;
import org.paradyne.lib.SqlBase;

public class OfficialDetailModelSql extends SqlBase {

	public String getQuery(int id) {
		switch (id) {

		case 1:
			return "INSERT INTO HRMS_EMP_OFFC(EMP_ID,EMP_TITLE_CODE,EMP_FNAME,EMP_MNAME,EMP_LNAME,EMP_GENDER,EMP_DOB,"
			+ " EMP_CENTER ,EMP_DEPT ,EMP_DIV, EMP_RANK ,EMP_CADRE "
			+ " ,EMP_TRADE ,EMP_SHIFT, EMP_STATUS, EMP_REGULAR_DATE ,EMP_LEAVE_DATE, "
			+ " EMP_INCR_DATE,EMP_REPORTING_OFFICER,EMP_TOKEN,EMP_TYPE,EMP_PAYBILL,"
			+ " EMP_CONFIRM_DATE ,EMP_GROUP_JOIN_DATE, EMP_ROLE)"
			+ " VALUES((SELECT NVL(MAX(EMP_ID),0)+1 FROM HRMS_EMP_OFFC),?,?,?,?,?,"
			+ " TO_DATE(?,'DD-MM-YYYY'),?,?,?,?,?,?,?,?,TO_DATE(?,'DD-MM-YYYY'),TO_DATE(?,'DD-MM-YYYY'),"
			+ " TO_DATE(?,'DD-MM-YYYY'),?,?,?,?,TO_DATE(?,'DD-MM-YYYY'),TO_DATE(?,'DD-MM-YYYY'),?) ";

		case 2:
			return "UPDATE HRMS_EMP_OFFC SET EMP_TITLE_CODE=?,EMP_FNAME=?,EMP_MNAME=?,EMP_LNAME=?,EMP_GENDER=?,EMP_DOB=TO_DATE(?,'DD-MM-YYYY'),"
					+ " EMP_RANK=?,  EMP_CENTER=?,EMP_TRADE=?,EMP_TYPE=?,EMP_CADRE=?,EMP_SHIFT=?,EMP_STATUS=?,EMP_REGULAR_DATE=TO_DATE(?,'DD-MM-YYYY'),EMP_TOKEN=?,  "
					+ " EMP_LEAVE_DATE=TO_DATE(?,'DD-MM-YYYY'),EMP_REPORTING_OFFICER=?,EMP_INCR_DATE=TO_DATE(?,'DD-MM-YYYY'),"
					+ " EMP_DEPT=?,EMP_DIV= ?,EMP_PAYBILL= ?,EMP_CONFIRM_DATE=TO_DATE(?,'DD-MM-YYYY'),"
					+ " EMP_GROUP_JOIN_DATE =TO_DATE(?,'DD-MM-YYYY'),EMP_ROLE= ?  WHERE EMP_ID=? ";

		case 3:
			return "SELECT HRMS_EMP_OFFC.EMP_ID,NVL(HRMS_EMP_OFFC.EMP_TOKEN,' '),NVL(t1.TITLE_NAME,' '),"
					+ " NVL(HRMS_EMP_OFFC.EMP_FNAME,' '),NVL(HRMS_EMP_OFFC.EMP_MNAME,' '),NVL(HRMS_EMP_OFFC.EMP_LNAME,' ') ,HRMS_EMP_OFFC.EMP_GENDER ,NVL(TO_CHAR(HRMS_EMP_OFFC.EMP_DOB,'DD-MM-YYYY'),' '),"
					+ " DIV_ID,NVL(DIV_NAME,' '),DEPT_ID,NVL(HRMS_DEPT.DEPT_NAME,' '),HRMS_EMP_OFFC.EMP_CENTER,"
					+ "	NVL(HRMS_CENTER.CENTER_NAME,' '),HRMS_EMP_OFFC.EMP_RANK,NVL(HRMS_RANK.RANK_NAME,' '),"
					+ "	HRMS_EMP_OFFC.EMP_PHOTO,E1.EMP_CADRE,NVL(CADRE_NAME,' '),HRMS_EMP_OFFC.EMP_TRADE,"
					+ "	NVL(TRADE_NAME,' '),to_char(HRMS_EMP_OFFC.EMP_SHIFT),NVL(SHIFT_NAME,' '),"
					+ "	HRMS_EMP_OFFC.EMP_STATUS,NVL(TO_CHAR(HRMS_EMP_OFFC.EMP_REGULAR_DATE,'DD-MM-YYYY'),' ')  ,NVL(TO_CHAR(HRMS_EMP_OFFC.EMP_LEAVE_DATE,'DD-MM-YYYY'),' '),NVL(TO_CHAR(HRMS_EMP_OFFC.EMP_INCR_DATE,'DD-MM-YYYY'),' ') "
					+ "	,HRMS_EMP_OFFC.EMP_REPORTING_OFFICER,"
					+ "	NVL(T2.TITLE_NAME,' ')||' '||NVL(E1.EMP_FNAME,' ')||' '||NVL(E1.EMP_MNAME,' ')||' '||NVL(E1.EMP_LNAME,' '), "
					+ "	HRMS_EMP_OFFC.EMP_TITLE_CODE,TYPE_NAME,TYPE_ID,TO_CHAR(HRMS_EMP_OFFC.EMP_CONFIRM_DATE,'DD-MM-YYYY'), " +
					"  FLOOR(MONTHS_BETWEEN(SYSDATE,NVL( HRMS_EMP_OFFC.EMP_GROUP_JOIN_DATE,HRMS_EMP_OFFC.EMP_REGULAR_DATE))/12)||' '||'Years'||' '|| FLOOR(MONTHS_BETWEEN(SYSDATE,NVL( HRMS_EMP_OFFC.EMP_GROUP_JOIN_DATE,HRMS_EMP_OFFC.EMP_REGULAR_DATE))-FLOOR(MONTHS_BETWEEN(SYSDATE,NVL( HRMS_EMP_OFFC.EMP_GROUP_JOIN_DATE,HRMS_EMP_OFFC.EMP_REGULAR_DATE))/12) *12) ||' '||'Months' AS EXPERRIENCE," +
					"    CASE WHEN SYSDATE - NVL( HRMS_EMP_OFFC.EMP_GROUP_JOIN_DATE,HRMS_EMP_OFFC.EMP_REGULAR_DATE) > 0  THEN 1 ELSE 0 END  XX  ,TO_CHAR(HRMS_EMP_OFFC.EMP_GROUP_JOIN_DATE,'DD-MM-YYYY'),HRMS_EMP_OFFC.EMP_ROLE"+
					" FROM HRMS_EMP_OFFC "
					+ "  LEFT JOIN HRMS_CENTER ON(HRMS_CENTER.CENTER_ID=HRMS_EMP_OFFC.EMP_CENTER) "
					+ "	LEFT JOIN HRMS_DEPT ON(HRMS_DEPT.DEPT_ID=HRMS_EMP_OFFC.EMP_DEPT) "
					+ "	LEFT JOIN HRMS_DIVISION ON(HRMS_DIVISION.DIV_ID=HRMS_EMP_OFFC.EMP_DIV) "
					+ "	LEFT JOIN HRMS_RANK ON(HRMS_RANK.RANK_ID=HRMS_EMP_OFFC.EMP_RANK) "
					+ "	LEFT JOIN HRMS_TRADE ON(HRMS_TRADE.TRADE_CODE=HRMS_EMP_OFFC.EMP_TRADE) "
					+ "	LEFT JOIN HRMS_CADRE ON(HRMS_CADRE.CADRE_ID=HRMS_EMP_OFFC.EMP_CADRE)"
					+ "	LEFT JOIN HRMS_SHIFT ON(HRMS_SHIFT.SHIFT_ID=HRMS_EMP_OFFC.EMP_SHIFT) "
					+ "	LEFT JOIN HRMS_TITLE t1 ON(t1.TITLE_CODE=HRMS_EMP_OFFC.EMP_TITLE_CODE)"
					+ "	LEFT JOIN HRMS_EMP_OFFC E1 ON(E1.EMP_ID=HRMS_EMP_OFFC.EMP_REPORTING_OFFICER)"
					+ "	LEFT JOIN HRMS_TITLE T2 ON(T2.TITLE_CODE=E1.EMP_TITLE_CODE)"
					+ "  LEFT JOIN HRMS_EMP_TYPE ON(HRMS_EMP_TYPE.TYPE_ID=HRMS_EMP_OFFC.EMP_TYPE)"
					+"  Left JOIN HRMS_RANK r1 ON(r1.RANK_ID=HRMS_EMP_OFFC.EMP_EXECUTIVE_ID)"
					+ " WHERE HRMS_EMP_OFFC.EMP_ID = ? ";

		case 4:
			return " select emp_photo, emp_status,emp_paybill,nvl(paybill_group,' ') from hrms_emp_offc left join hrms_paybill on(hrms_emp_offc.emp_paybill=hrms_paybill.paybill_id)where emp_id = ? ";
		case 5:
			return " 	select NVL(cadre_id,''),NVL(cadre_name,' '),NVL(HRMS_EMP_OFFC.EMP_SHIFT,''),NVL(SHIFT_NAME,' '),nvl(HRMS_EMP_OFFC.EMP_TRADE,''),nvl(trade_name,' '),nvl(rank_id,''),nvl(rank_name,' '),NVL(TYPE_ID,''),NVL(TYPE_NAME,' ') from hrms_emp_offc "
					+ "	LEFT  JOIN HRMS_CADRE ON(HRMS_CADRE.CADRE_ID=HRMS_EMP_OFFC.EMP_CADRE)"
					+ "	LEFT  JOIN HRMS_SHIFT ON(HRMS_SHIFT.SHIFT_ID=HRMS_EMP_OFFC.EMP_SHIFT) "
					+ "	INNER JOIN HRMS_RANK ON(HRMS_RANK.RANK_ID=HRMS_EMP_OFFC.EMP_RANK) "
					+ "	LEFT  JOIN HRMS_TRADE ON(HRMS_TRADE.TRADE_CODE=HRMS_EMP_OFFC.EMP_TRADE) "
					+ "  INNER JOIN HRMS_EMP_TYPE ON(HRMS_EMP_TYPE.TYPE_ID=HRMS_EMP_OFFC.EMP_TYPE)"
					+ "  where emp_id = ?";

		case 6:
			return "SELECT EMP_TITLE_CODE FROM HRMS_EMP_OFFC WHERE EMP_ID = ? ";

		default:
			return "";
		}
	}
}