package org.paradyne.sql.admin.srd;

import org.paradyne.lib.SqlBase;

/**
 *modified by priyanka kumbhar
 */
public class PunishHistoryModelSql extends SqlBase {
	public String getQuery(int id) {

		switch (id) {

		case 1:
			return " INSERT INTO HRMS_PUNISH (PUNISH_ID,EMP_ID,DISCP_ID,PUNISH_AUTH,PUNISH_WEF,PUNISH_PERIOD,"
					+ " PUNISH_DOCUMENT,PUNISH_SUSP_STATUS,OFFENCE_DESCRIPTION,PUNISH_TODATE)  "
					+ " VALUES((SELECT NVL(MAX(PUNISH_ID),0)+1 FROM HRMS_PUNISH),?,?,?,TO_DATE(?,'DD-MM-YYYY'),?,?,?,?,TO_DATE(?,'DD-MM-YYYY'))";

		case 2:
			return " SELECT PUNISH_NAME,PUNISH_AUTH,PUNISH_LETTER_NO,TO_CHAR(PUNISH_WEF,'DD-MM-YYYY'), "
					+ " PUNISH_CEO_ORDER,TO_CHAR(PUNISH_CEO_DATE,'DD-MM-YYYY'),TO_NUMBER(PUNISH_PERIOD),NVL(TO_CHAR(PUNISH_WEF,'DD-MM-YYYY'),' '),HRMS_PUNISH.PUNISH_ID,HRMS_PUNISH.OFFENCE_DESCRIPTION, "
					+ " PUNISH_DCE_SERIAL_NO,NVL(PUNISH_DOCUMENT,' '),PUNISH_SUSP_STATUS,DISCP_ID,TO_CHAR(PUNISH_TODATE,'DD-MM-YYYY'),NVL(OFFENCE_DESCRIPTION,' ') FROM HRMS_PUNISH INNER JOIN HRMS_PUNISHMENT ON (HRMS_PUNISH.DISCP_ID = HRMS_PUNISHMENT.PUNISH_ID) "
					+ " WHERE EMP_ID = ? ORDER BY HRMS_PUNISH.PUNISH_ID";

		case 3:
			return "SELECT PUNISH_NAME,PUNISH_AUTH,PUNISH_LETTER_NO,"
			        + " PUNISH_CEO_ORDER,TO_NUMBER(PUNISH_PERIOD),"
			        + " TO_CHAR(PUNISH_WEF,'DD-MM-YYYY'),EMP_ID,"
			        + " DISCP_ID,OFFENCE_DESCRIPTION,  PUNISH_DCE_SERIAL_NO,"
			        + " PUNISH_DOCUMENT, TO_CHAR(PUNISH_TODATE,'DD-MM-YYYY')," 
			        + " PUNISH_SUSP_STATUS FROM HRMS_PUNISH "
			        + " INNER JOIN HRMS_PUNISHMENT ON (HRMS_PUNISH.DISCP_ID = HRMS_PUNISHMENT.PUNISH_ID) "
			        + " WHERE HRMS_PUNISH.PUNISH_ID =?";

		case 4:
			return " UPDATE HRMS_PUNISH  SET DISCP_ID =?, PUNISH_AUTH = ?,"
	               + " PUNISH_WEF = TO_DATE(?,'DD-MM-YYYY'),PUNISH_PERIOD =?,"
	               + " OFFENCE_DESCRIPTION =?, PUNISH_DOCUMENT =?, "
	               + " PUNISH_SUSP_STATUS=?,PUNISH_TODATE=TO_DATE(?,'DD-MM-YYYY')"
	               + " WHERE EMP_ID=? AND PUNISH_ID =?";

		case 5:
			return " DELETE FROM  HRMS_PUNISH  WHERE PUNISH_ID = ? ";

		case 7:
			return " SELECT CENTER_NAME,RANK_NAME,EMP_ID,(HRMS_TITLE.TITLE_NAME||' '||EMP_FNAME||'  '|| EMP_MNAME|| '  ' ||EMP_LNAME),EMP_TOKEN FROM HRMS_EMP_OFFC "
					+ " LEFT JOIN HRMS_TITLE ON(HRMS_TITLE.TITLE_CODE=HRMS_EMP_OFFC.EMP_TITLE_CODE) "
					+ " INNER JOIN HRMS_RANK ON HRMS_RANK.RANK_ID = HRMS_EMP_OFFC.EMP_RANK "
					+ " INNER JOIN HRMS_CENTER ON HRMS_CENTER.CENTER_ID = HRMS_EMP_OFFC.EMP_CENTER "
					+ " WHERE EMP_ID = ?";

		default:
			return " query no. is not specified  ";
		}
	}

}

