package org.paradyne.sql.admin.srd;

import org.paradyne.lib.SqlBase;

public class QualificationDetailModelSql extends SqlBase {

	public String getQuery(int id) {
		switch (id) {

		case 1:
			return "INSERT INTO HRMS_EMP_QUA (QUA_ID,EMP_ID,QUA_MAST_CODE,QUA_INST,QUA_UNIV,QUA_YEAR,QUA_GRD,QUA_PER,QUA_ISTECH)"
					+ " VALUES((SELECT NVL(MAX(QUA_ID),0)+1 FROM HRMS_EMP_QUA),?,?,?,?,TO_DATE(?,'DD-MM-YYYY'),?,?,?) ";

		case 2:
			return "UPDATE HRMS_EMP_QUA SET QUA_MAST_CODE=?,QUA_INST=?,QUA_UNIV=?,QUA_YEAR=TO_DATE(?,'DD-MM-YYYY'),QUA_GRD=?,"
					+ "QUA_PER=?,QUA_ISTECH=? WHERE QUA_ID=? AND EMP_ID=?";

		case 3:
			return " DELETE FROM HRMS_EMP_QUA WHERE QUA_ID =?";

		case 4:
			return " SELECT EMP_TOKEN,HRMS_TITLE.TITLE_NAME||' '||HRMS_EMP_OFFC.EMP_FNAME||' '||HRMS_EMP_OFFC.EMP_MNAME||' '||HRMS_EMP_OFFC.EMP_LNAME,EMP_RANK,TO_CHAR(RANK_NAME), "
					+ " EMP_CENTER,TO_CHAR(CENTER_NAME),"
					+ " HRMS_EMP_QUA.QUA_ID,QUA_MAST_CODE,NVL(QUA_NAME,' '),NVL(QUA_INST,'     '),NVL(QUA_UNIV,'  '),nvl(TO_CHAR(QUA_YEAR,'DD-MM-YYYY'),'  '), "
					+ " NVL(QUA_GRD,'  '),NVL(QUA_PER,0),DECODE(QUA_ISTECH,'Y','Yes','N','No'),HRMS_EMP_QUA.EMP_ID FROM HRMS_EMP_QUA "
					+ " LEFT JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=HRMS_EMP_QUA.EMP_ID)"
					+ "	INNER JOIN HRMS_RANK ON HRMS_RANK.RANK_ID = HRMS_EMP_OFFC.EMP_RANK "
					+ " INNER JOIN HRMS_CENTER ON(HRMS_CENTER.CENTER_ID=HRMS_EMP_OFFC.EMP_CENTER)"
					+ " LEFT JOIN HRMS_QUA ON(HRMS_QUA.QUA_ID=HRMS_EMP_QUA.QUA_MAST_CODE)"
					+ "LEFT JOIN HRMS_TITLE ON HRMS_TITLE.TITLE_CODE = HRMS_EMP_OFFC.EMP_TITLE_CODE "
					+ " WHERE HRMS_EMP_QUA.EMP_ID =? ORDER BY HRMS_EMP_QUA.QUA_ID";

		case 5:
			return " SELECT QUA_MAST_CODE,NVL(QUA_NAME,' '),NVL(QUA_INST,' '),NVL(QUA_UNIV,' '),TO_CHAR(QUA_YEAR,'DD-MM-YYYY'),"
					+ " NVL(QUA_GRD,' '),NVL(QUA_PER,0),QUA_ISTECH,HRMS_EMP_QUA.QUA_ID "
					+ " FROM HRMS_EMP_QUA "
					+ " LEFT JOIN HRMS_QUA ON(HRMS_QUA.QUA_ID=HRMS_EMP_QUA.QUA_MAST_CODE) "
					+ " WHERE HRMS_EMP_QUA.QUA_ID=? AND HRMS_EMP_QUA.EMP_ID =? ORDER BY HRMS_EMP_QUA.QUA_ID";

		default:
			return "";
		}
	}
}