package org.paradyne.sql.admin.srd;

import org.paradyne.lib.SqlBase;

public class SalaryDetailModelSql extends SqlBase {

	public String getQuery(int id) {
		switch (id) {

		case 1:
			return  " INSERT INTO HRMS_SALARY_MISC (EMP_ID,SAL_GPFNO,SAL_PANNO,SAL_ACCNO_REGULAR,SAL_MICR_REGULAR,SAL_REIMBMENT,"
					+ " SAL_REIMBANK,SAL_PENSIONABLE,SAL_PAY_MODE,SAL_ESCINUMBER,SAL_GRATUITY_ACCNO,SAL_PENSION_ACCNO,SAL_PENSION_BANK,ACCOUNT_CATEGORY_ID,COST_CENTER_ID,SUB_COST_CENTER_ID, SAL_EPF_FLAG, SAL_VPF_FLAG, SAL_GPF_FLAG, SAL_PFTRUST_FLAG,CUSTOMER_REF_NO ,SAL_OVERTIME_FLAG, SAL_PF_DATE, SAL_CAL_EMP_PF, SAL_CAL_COMP_PF, SAL_CAL_PENSION_PF, SAL_SYS_CAL_PARAMETER)"
					+ "	VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,to_date(?,'dd-mm-yyyy'),?,?,?,?)";

		case 2:
			return " UPDATE HRMS_SALARY_MISC SET SAL_PAYSCALE=?,SAL_GPFNO=?,SAL_PANNO=?,SAL_CGHSNO=?,SAL_MICR_REGULAR=?,SAL_MICR_PENSION=?,"
					+ "	SAL_ACCNO_REGULAR=?,SAL_ACCNO_PENSION=?,SAL_MICR_PENSION_SAVINGS=?,SAL_ACCNO_PENSION_SAVINGS=?,SAL_PENSIONABLE=?,"
					+ "	SAL_PAY_MODE=?,SAL_DCMAF_MEMBERSHIP=? ,SAL_ESCINUMBER=?,SAL_REIMBMENT=?,SAL_REIMBANK=?,SAL_GRATUITY_ACCNO=?,SAL_PENSION_ACCNO=?,SAL_PENSION_BANK=?,ACCOUNT_CATEGORY_ID=?,COST_CENTER_ID=?,SUB_COST_CENTER_ID=?,SAL_EPF_FLAG=?, SAL_VPF_FLAG=?, SAL_GPF_FLAG=?, SAL_PFTRUST_FLAG=?,CUSTOMER_REF_NO=? , SAL_OVERTIME_FLAG=? , SAL_PF_DATE=to_date(?,'DD-MM-YYYY') , SAL_CAL_EMP_PF=? , SAL_CAL_COMP_PF=? , SAL_CAL_PENSION_PF=? , SAL_SYS_CAL_PARAMETER=?  WHERE EMP_ID=?";

		case 3:
			return "SELECT SAL_PAYSCALE,NVL(PAYSC_NAME,' '),NVL(SAL_GPFNO,' '),NVL(SAL_PANNO,' '),NVL(SAL_CGHSNO,' '),NVL(SAL_MICR_REGULAR,0),NVL(SAL_MICR_PENSION,0),	NVL(SAL_ACCNO_REGULAR,' '),NVL(SAL_ACCNO_PENSION,' '),NVL(SAL_MICR_PENSION_SAVINGS,0),NVL(SAL_ACCNO_PENSION_SAVINGS,' '),SAL_PENSIONABLE,SAL_PAY_MODE,NVL(SAL_DCMAF_MEMBERSHIP,' '),"
					+ " NVL(HRMS_BANK.BANK_NAME,' '),nvl(SAL_ESCINUMBER,' '),SAL_REIMBMENT,SAL_REIMBANK ,NVL(B2.BANK_NAME,'') " +
					" ,SAL_GRATUITY_ACCNO,SAL_PENSION_ACCNO,SAL_PENSION_BANK,B3.BANK_NAME,HRMS_SALARY_MISC.ACCOUNT_CATEGORY_ID,ACCOUNT_CATEGORY_NAME,HRMS_SALARY_MISC.COST_CENTER_ID,COST_CENTER_NAME ,HRMS_SALARY_MISC.SUB_COST_CENTER_ID,SUB_COST_CENTER_NAME, SAL_EPF_FLAG, SAL_VPF_FLAG, SAL_GPF_FLAG, SAL_PFTRUST_FLAG,CUSTOMER_REF_NO "+
					" , SAL_OVERTIME_FLAG, TO_CHAR(SAL_PF_DATE,'DD-MM-YYYY'), SAL_CAL_EMP_PF, SAL_CAL_COMP_PF, SAL_CAL_PENSION_PF, SAL_SYS_CAL_PARAMETER" +
					" ,CADRE_NAME, TO_CHAR(EMP_REGULAR_DATE,'DD-MM-YYYY'), DEPT_NAME  FROM HRMS_EMP_OFFC 	"
					+ " LEFT JOIN HRMS_SALARY_MISC ON(HRMS_EMP_OFFC.EMP_ID=HRMS_SALARY_MISC.EMP_ID)	"
					+ " LEFT JOIN  HRMS_PAYSCALE ON(HRMS_PAYSCALE.PAYSC_ID=HRMS_SALARY_MISC.SAL_PAYSCALE)	"
					+ " LEFT JOIN HRMS_TITLE ON(HRMS_TITLE.TITLE_CODE=HRMS_EMP_OFFC.EMP_TITLE_CODE)	"
					+ " INNER JOIN HRMS_CENTER ON(HRMS_CENTER.CENTER_ID=HRMS_EMP_OFFC.EMP_CENTER)  "
					+ " INNER JOIN HRMS_RANK ON(HRMS_RANK.RANK_ID=HRMS_EMP_OFFC.EMP_RANK)	"
					+ " LEFT JOIN HRMS_BANK ON(HRMS_SALARY_MISC.SAL_MICR_REGULAR=HRMS_BANK.BANK_MICR_CODE)"
					+ "  LEFT JOIN HRMS_BANK B2 ON(HRMS_SALARY_MISC.SAL_REIMBANK =B2.BANK_MICR_CODE)"
					+"   LEFT JOIN HRMS_BANK B3 ON(HRMS_SALARY_MISC.SAL_PENSION_BANK=B3.BANK_MICR_CODE)"
					+"   LEFT JOIN HRMS_ACCOUNTING_CATEGORY ON(HRMS_ACCOUNTING_CATEGORY.ACCOUNT_CATEGORY_ID=HRMS_SALARY_MISC.ACCOUNT_CATEGORY_ID) "
					+"  LEFT JOIN HRMS_COST_CENTER ON (HRMS_COST_CENTER.COST_CENTER_ID=HRMS_SALARY_MISC.COST_CENTER_ID)  "
					+"  LEFT JOIN HRMS_SUB_COST_CENTER ON (HRMS_SUB_COST_CENTER.SUB_COST_CENTER_ID=HRMS_SALARY_MISC.SUB_COST_CENTER_ID)  "
					+" LEFT JOIN  HRMS_DEPT ON( HRMS_DEPT.DEPT_ID=HRMS_EMP_OFFC.EMP_DEPT) "
					+"  LEFT JOIN HRMS_CADRE ON (HRMS_CADRE.CADRE_ID=HRMS_EMP_OFFC.EMP_CADRE)"
					+ " WHERE HRMS_EMP_OFFC.EMP_ID = ? ";

		case 4:
			return " DELETE FROM HRMS_SALARY_MISC WHERE EMP_ID=?";

		case 5:
			return " SELECT EMP_ID FROM HRMS_SALARY_MISC WHERE EMP_ID=?";

		default:
			return "";
		}
	}
}