package org.paradyne.sql.admin.srd;

import org.paradyne.lib.SqlBase;

public class TrainingModelSql extends SqlBase {
	
public String getQuery(int id){
		
		
		
		switch (id) {
		
		case 1 :  return " INSERT INTO HRMS_EMP_TRNG (TRNG_ID,EMP_ID ,TRNG_MAST_CODE,TRNG_LOC,TRNG_STARTDATE,TRNG_ENDDATE, "
					+" TRNG_INSTITUTE,TRNG_FEES,TRNG_AUTH_LETTERNO,TRNG_AUTH_LETTERDATE) "
					+" VALUES((SELECT NVL(MAX(TRNG_ID),0)+1 FROM HRMS_EMP_TRNG),UPPER(?),?,?,TO_DATE(?,'DD-MM-YYYY'), "
					+" TO_DATE(?,'DD-MM-YYYY'),?,?,?,TO_DATE(?,'DD-MM-YYYY')) ";
		
		
		case 2 :  return " SELECT TRAINING_NAME,LOCATION_NAME,TO_CHAR(TRNG_STARTDATE,'DD-MM-YYYY'),TO_CHAR(TRNG_ENDDATE,'DD-MM-YYYY'), "
					+" TRNG_INSTITUTE,TRNG_FEES,TRNG_AUTH_LETTERNO,TO_CHAR(TRNG_AUTH_LETTERDATE,'DD-MM-YYYY'),TRNG_ID FROM HRMS_EMP_TRNG "
					+" INNER JOIN HRMS_TRAINING ON (HRMS_EMP_TRNG .TRNG_MAST_CODE = HRMS_TRAINING.TRAINING_ID) "
					+" LEFT JOIN HRMS_LOCATION ON (HRMS_EMP_TRNG .TRNG_LOC = HRMS_LOCATION.LOCATION_CODE) "
					+" WHERE EMP_ID = ? ORDER BY TRNG_ID ";
		
		case 3 :  return " SELECT TRAINING_NAME,LOCATION_NAME,TO_CHAR(TRNG_STARTDATE,'DD-MM-YYYY'),TO_CHAR(TRNG_ENDDATE,'DD-MM-YYYY'), "
					+" TRNG_INSTITUTE,TRNG_FEES,TRNG_AUTH_LETTERNO,TO_CHAR(TRNG_AUTH_LETTERDATE,'DD-MM-YYYY'),EMP_ID,TRNG_MAST_CODE,TRNG_LOC FROM HRMS_EMP_TRNG "
					+" INNER JOIN HRMS_TRAINING ON (HRMS_EMP_TRNG .TRNG_MAST_CODE = HRMS_TRAINING.TRAINING_ID) "
					+" LEFT JOIN HRMS_LOCATION ON (HRMS_EMP_TRNG .TRNG_LOC = HRMS_LOCATION.LOCATION_CODE) "
					+" WHERE  TRNG_ID = ?"; 
		
		
		case 4 :  return " UPDATE HRMS_EMP_TRNG SET TRNG_MAST_CODE = ?,TRNG_LOC = ?,TRNG_STARTDATE = TO_DATE(?,'DD-MM-YYYY'),TRNG_ENDDATE = TO_DATE(?,'DD-MM-YYYY'), "
				 +" TRNG_INSTITUTE = ?,TRNG_FEES = ?,TRNG_AUTH_LETTERNO = ?,TRNG_AUTH_LETTERDATE = TO_DATE(?,'DD-MM-YYYY') "
				 +" WHERE TRNG_ID = ? "; 
		
		case 5: return  " DELETE FROM  HRMS_EMP_TRNG WHERE TRNG_ID = ? "; 
		
		case 7 : return " SELECT (CENTER_NAME),RANK_NAME,EMP_ID,(HRMS_TITLE.TITLE_NAME||' '||EMP_FNAME||'  '|| EMP_MNAME|| '  ' ||EMP_LNAME),EMP_TOKEN FROM HRMS_EMP_OFFC " 
				+" LEFT JOIN HRMS_TITLE ON(HRMS_TITLE.TITLE_CODE=HRMS_EMP_OFFC.EMP_TITLE_CODE)"
				+" INNER JOIN HRMS_RANK ON HRMS_RANK.RANK_ID = HRMS_EMP_OFFC.EMP_RANK "
				+" INNER JOIN HRMS_CENTER ON HRMS_CENTER.CENTER_ID = HRMS_EMP_OFFC.EMP_CENTER "
				+" WHERE EMP_ID = ?";
		
		default: return " query no. is not specified  ";
		}
	}


}
