package org.paradyne.sql.admin.srd;

import org.paradyne.lib.SqlBase;

public class VisaDetailsModelSql extends SqlBase {
	public String getQuery(int id) {
		switch (id) {

		case 1:
			return "INSERT INTO HRMS_EMP_VISA_DETAILS (VISA_CODE,EMP_ID, VISA_NUMBER, VISA_COUNTRY, "
					+ "VISA_TYPE, VISA_ENTRY, VISA_ISSUE_PLACE, VISA_ISSUE_AUTH, VISA_ISSUE_DATE, "
					+ "VISA_VALID_UPTO, VISA_ADDRESS) VALUES((SELECT MAX(VISA_CODE)+1 FROM HRMS_EMP_VISA_DETAILS),?,?,?,?,?,?,?,TO_DATE(?,'DD-MM-YYYY'),TO_DATE(?,'DD-MM-YYYY'),?)";

		case 2:
			return " SELECT EMP_TOKEN,(HRMS_TITLE.TITLE_NAME||' '||EMP_FNAME||'  '||EMP_MNAME||'  '||EMP_LNAME),(CENTER_NAME),HRMS_RANK.RANK_NAME "
					+ " FROM HRMS_EMP_OFFC"
					
					+ " LEFT JOIN HRMS_RANK ON(HRMS_EMP_OFFC.EMP_RANK=HRMS_RANK.RANK_ID) "
					+ " LEFT JOIN HRMS_TITLE ON(HRMS_TITLE.TITLE_CODE=HRMS_EMP_OFFC.EMP_TITLE_CODE) "
					+ " INNER JOIN HRMS_CENTER ON(HRMS_CENTER.CENTER_ID=HRMS_EMP_OFFC.EMP_CENTER) "
					+ " WHERE HRMS_EMP_OFFC.EMP_ID =? ";			

		case 3:
			return "DELETE FROM HRMS_EMP_VISA_DETAILS WHERE VISA_CODE=? ";

		case 4:
			return "UPDATE HRMS_EMP_PERS SET EMP_PASSPORT = ?,EMP_PASSPORT_NAME = ?,EMP_PASSPORT_FATHER_NAME = ?,EMP_PASSPORT_MOTHER_NAME =?,EMP_PASSPORT_ISSUE_FROM =?,EMP_PASSPORT_ISSUE_DATE= TO_DATE(?,'dd-mm-yyyy'), EMP_PASSPORT_EXPDATE =TO_DATE(?,'dd-mm-yyyy'),EMP_UID =? where EMP_ID=?";

		case 5:
			return " SELECT EMP_PASSPORT,EMP_PASSPORT_NAME,EMP_PASSPORT_FATHER_NAME,"
					+ " EMP_PASSPORT_MOTHER_NAME,EMP_PASSPORT_ISSUE_FROM,TO_CHAR(EMP_PASSPORT_ISSUE_DATE,'DD-MM-YYYY'),"
					+ " TO_CHAR(EMP_PASSPORT_EXPDATE,'DD-MM-YYYY'),EMP_UID "
					+ " FROM HRMS_EMP_PERS "
					+" WHERE HRMS_EMP_PERS.EMP_ID =?";
			
		case 6:
			return "SELECT  EMP_ID, VISA_NUMBER, VISA_COUNTRY, "
					+" VISA_TYPE, DECODE(VISA_ENTRY,'S','Single','M','Multiple'), VISA_ISSUE_PLACE, VISA_ISSUE_AUTH," 
					+" TO_CHAR(VISA_ISSUE_DATE,'DD-MM-YYYY'), TO_CHAR(VISA_VALID_UPTO,'DD-MM-YYYY'),"
					+" VISA_ADDRESS,VISA_CODE FROM HRMS_EMP_VISA_DETAILS WHERE EMP_ID=?";
			
		case 7:
			return "SELECT VISA_NUMBER, VISA_COUNTRY, "
			       +" VISA_TYPE, DECODE(VISA_ENTRY,'S','Single','M','Multiple'), VISA_ISSUE_PLACE, VISA_ISSUE_AUTH," 
			       +" TO_CHAR(VISA_ISSUE_DATE,'DD-MM-YYYY'), TO_CHAR(VISA_VALID_UPTO,'DD-MM-YYYY'),"
			       +" VISA_ADDRESS, EMP_ID FROM HRMS_EMP_VISA_DETAILS WHERE EMP_ID=? AND VISA_CODE=?";
			
		case 8:
			 return "UPDATE HRMS_EMP_VISA_DETAILS SET VISA_NUMBER=?,VISA_COUNTRY=?,VISA_TYPE=?,"
                    +" VISA_ENTRY=?,VISA_ISSUE_PLACE=?,VISA_ISSUE_AUTH=?, VISA_ISSUE_DATE=TO_DATE(?,'DD-MM-YYYY'),"
                    +" VISA_VALID_UPTO=TO_DATE(?,'DD-MM-YYYY'),VISA_ADDRESS=? WHERE EMP_ID=? AND VISA_CODE=?";

		case 9:
			return "INSERT INTO HRMS_EMP_PERS(EMP_PASSPORT, EMP_PASSPORT_NAME, EMP_PASSPORT_FATHER_NAME,"
					+ " EMP_PASSPORT_MOTHER_NAME, EMP_PASSPORT_ISSUE_FROM, EMP_PASSPORT_ISSUE_DATE,"
					+ " EMP_PASSPORT_EXPDATE, EMP_UID, EMP_ID) VALUES(?,?,?,?,?,TO_DATE(?,'DD-MM-YYYY'),TO_DATE(?,'DD-MM-YYYY'),?,?)";
		case 10:
			  return "SELECT EMP_PASSPORT FROM HRMS_EMP_PERS WHERE EMP_ID=?";
		default:
			return "Query not found";

		}
	}
}
