package org.paradyne.sql.settlement;

import org.paradyne.lib.SqlBase;

public class ResignationDetailsModelSql extends SqlBase
{
  public String getQuery(int id)
  {
    switch (id) {
    case 1:
      return " INSERT INTO HRMS_RESIGN(RESIGN_CODE,RESIGN_EMP,RESIGN_NOTICE_PERIOD,RESIGN_STATUS,RESIGN_DATE,RESIGN_ACCEPT_DATE,RESIGN_SEPR_DATE,RESIGN_REASON,RESIGN_REMARK,RESIGN_WITHDRAWN,RESIGN_NOTICE_STATUS,RESIGN_WAVEOFF_APPROVER,RESIGN_NOTICEPERIOD_ACTUAL,RESIGN_ACCEPTED_BY,RESIGN_HR_COMMENTS ,RESIGN_APPL_STATUS ) VALUES((SELECT NVL(MAX(RESIGN_CODE),0)+1 FROM HRMS_RESIGN ),?,?,?,TO_DATE(?,'DD-MM-YYYY'),TO_DATE(?,'DD-MM-YYYY'),TO_DATE(?,'DD-MM-YYYY'),?,?,?,?,?,?,?,?,?)";
    case 2:
      return " UPDATE HRMS_RESIGN SET RESIGN_EMP=?,RESIGN_NOTICE_PERIOD=?,RESIGN_STATUS=?,RESIGN_DATE=to_date(?,'dd-mm-yyyy'),RESIGN_ACCEPT_DATE=to_date(?,'dd-mm-yyyy'),RESIGN_SEPR_DATE=to_date(?,'dd-mm-yyyy') ,RESIGN_REASON=?,RESIGN_REMARK=? ,RESIGN_WITHDRAWN=?,RESIGN_NOTICE_STATUS=?,RESIGN_WAVEOFF_APPROVER=?,RESIGN_NOTICEPERIOD_ACTUAL=?,RESIGN_ACCEPTED_BY=? ,RESIGN_HR_COMMENTS=? ,RESIGN_APPL_STATUS=?  WHERE RESIGN_CODE=? ";
    case 3:
      return " DELETE FROM HRMS_RESIGN WHERE RESIGN_CODE=? ";
    case 4:
      return "  SELECT DISTINCT HRMS_EMP_OFFC.EMP_TOKEN,(EMP_FNAME||'  '||EMP_MNAME||'  '||EMP_LNAME) \t, NVL(RANK_NAME,' '),NVL(CENTER_NAME,'')    ,NVL(TO_CHAR(HRMS_EMP_OFFC.EMP_REGULAR_DATE,'DD-MM-YYYY'),' '),HRMS_EMP_OFFC.EMP_ID FROM HRMS_EMP_OFFC   LEFT JOIN HRMS_CENTER ON(HRMS_CENTER.CENTER_ID=HRMS_EMP_OFFC.EMP_CENTER)   LEFT JOIN HRMS_EMP_QUA ON(HRMS_EMP_QUA.EMP_ID = HRMS_EMP_OFFC.EMP_ID)    LEFT JOIN HRMS_QUA ON(HRMS_QUA.QUA_ID=HRMS_EMP_QUA.QUA_MAST_CODE)     LEFT JOIN HRMS_RANK ON(HRMS_RANK.RANK_ID=HRMS_EMP_OFFC.EMP_RANK) WHERE HRMS_EMP_OFFC.EMP_ID=?   ORDER BY HRMS_EMP_OFFC.EMP_ID ";
    }

    return "";
  }
}