/**
 * 
 */
package org.paradyne.sql.settlement;

import org.paradyne.lib.SqlBase;

/**
 * 
 * @author Reeba Joseph Date: 02-July-2009
 * 
 */
public class SettlementDetailsModelSql extends SqlBase {

	public String getQuery(int id) {

		switch (id) {
		case 1:
			return "INSERT INTO HRMS_SETTL_HDR(SETTL_CODE,SETTL_RESGNO,SETTL_SETTLDT,SETTL_SEPRDT," +
					" SETTL_PAYMODE,SETTL_BANKNM,SETTL_CHEQUENO,SETTL_CHEQUEDT,SETTL_PREPBY,SETTL_CHKBYHR," +
					" SETTL_CHKBYACC,SETTL_HANDOVER,SETTL_PERMSETTLEMENT,SETTL_GRATUITY," +
					" SETTL_REIMBURSE,SETTL_LEAVE_ENCASH,SETTL_DEDUCTION,SETTL_NETAMT,SETTL_COMMENT," +
					" SETTL_NOTICEDAYS,SETTL_NOTICEMTH,SETTL_LEAVEDAYS,SETTL_LOCKFLAG,SETTL_ECODE) " +
					" VALUES ((SELECT NVL(MAX(SETTL_CODE),0)+1 FROM HRMS_SETTL_HDR),?,TO_DATE(?,'DD-MM-YYYY'),TO_DATE(?,'DD-MM-YYYY'),?,?,?,TO_DATE(?,'DD-MM-YYYY'),?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)	";

		/*case 2:
			return "UPDATE HRMS_SETTL_HDR SET SETTL_RESGNO = ?,SETTL_SETTLDT = TO_DATE(?,'DD-MM-YYYY')," +
					" SETTL_SEPRDT = TO_DATE(?,'DD-MM-YYYY'),SETTL_PAYMODE =?,SETTL_BANKNM=?,SETTL_CHEQUENO=?," +
					" SETTL_CHEQUEDT = TO_DATE(?,'DD-MM-YYYY'),SETTL_PREPBY=?,SETTL_CHKBYHR=?,SETTL_CHKBYACC=?," +
					" SETTL_HANDOVER = ?,SETTL_ELIGIBLEDAYS = ?,SETTL_PERMSETTLEMENT = ?,SETTL_GRATUITY = ?," +
					" SETTL_REIMBURSE= ?, SETTL_LEAVE_ENCASH = ?, SETTL_DEDUCTION =? , SETTL_NETAMT =? ," +
					" SETTL_COMMENT =? ,SETTL_SHORTPERIOD =?,SETTL_NOTICEDAYS=?,SETTL_NOTICEMTH=?," +
					" SETTL_SHORTPAYFLAG=?,SETTL_LEAVEDAYS=?,SETTL_LOCKFLAG=? WHERE SETTL_CODE=?";*/
			
		case 2:
			return "UPDATE HRMS_SETTL_HDR SET SETTL_RESGNO = ?," +
					" SETTL_SEPRDT = TO_DATE(?,'DD-MM-YYYY'),SETTL_GRATUITY = ?," +
					" SETTL_REIMBURSE= ?, SETTL_LEAVE_ENCASH = ?, SETTL_DEDUCTION =? , SETTL_NETAMT =? ," +
					" SETTL_NOTICEDAYS=?,SETTL_NOTICEMTH=?,SETTL_LEAVEDAYS=?,SETTL_LOCKFLAG=?,SETTL_TAX_AMT=?,SETTL_ECODE=?,SETTL_TAX_FLAG=?, SETTL_SERVICE_TENURE=?, SETTL_GRATUITY_AVG_SALARY=? ,SETTL_REIMBURSE_COMMENT=? , SETTL_DEDUCTION_COMMENT=?  WHERE SETTL_CODE=?";

		case 3:
			return "DELETE FROM HRMS_SETTL_HDR WHERE SETTL_CODE=? ";

		case 4:
			return "INSERT INTO HRMS_SETTL_LEAVEENCASH (SETTL_RESIGN_CODE,SETTL_LEAVE_CODE, SETTL_ENCASH_DAYS, SETTL_ENCASH_AMOUNT)"
					+ " VALUES ((SELECT NVL(MAX(SETTL_RESGNO),0) FROM HRMS_SETTL_HDR),?,?,?)";

		case 5:
			return "UPDATE HRMS_SETTL_LEAVEENCASH SET SETTL_LEAVE_CODE = ?,SETTL_ENCASH_DAYS = ?, SETTL_ENCASH_AMOUNT = ? WHERE SETTL_RESIGN_CODE = ?";

		default:
			return "hiiiiiiiiiiii";

		}
	}
}
