/**
 * 
 */
package org.paradyne.sql.payroll.incometax;

import org.paradyne.lib.SqlBase;

/**
 * @author Venkatesh
 *
 */
public class EmpInvestmentModelSql extends SqlBase {
	
	public String getQuery(int id){
		switch(id){
		case 1:return" INSERT INTO HRMS_EMP_INVESTMENT(INV_ID,EMP_ID,INV_FINYEAR_FROM, "
		             +" INV_FINYEAR_TO,INV_CODE,INV_AMOUNT,INV_VALID_AMOUNT,INV_PROOF_ATTACH,INV_UPLOAD)"
		             +" VALUES((SELECT NVL(MAX(INV_ID),0)+1 FROM HRMS_EMP_INVESTMENT),?,?,?,?,?,?,?,?)";
		
		case 2: return " UPDATE HRMS_EMP_INVESTMENT SET INV_AMOUNT=?,INV_VALID_AMOUNT=?,INV_PROOF_ATTACH=?,INV_UPLOAD=? WHERE INV_id=? AND EMP_ID=? AND INV_FINYEAR_FROM=? AND INV_FINYEAR_TO=?";
		
		case 3: return" SELECT INV_CODE,EMP_ID,INV_FINYEAR_FROM,INV_FINYEAR_TO,INV_AMOUNT "
		               +" FROM HRMS_EMP_INVESTMENT WHERE EMP_ID=?";
		
		case 4: return " SELECT  HRMS_EMP_INVESTMENT.INV_CODE,HRMS_TAX_INVESTMENT.INV_NAME,INV_AMOUNT,INV_VALID_AMOUNT,INV_FINYEAR_FROM,INV_FINYEAR_TO,INV_ID,DECODE(INV_PROOF_ATTACH,'N','NO','Y','YES'),NVL(INV_UPLOAD,' ')  "
		               +" FROM HRMS_EMP_INVESTMENT INNER JOIN HRMS_TAX_INVESTMENT "
		               +" ON (HRMS_EMP_INVESTMENT.INV_CODE = HRMS_TAX_INVESTMENT.INV_CODE) WHERE HRMS_EMP_INVESTMENT.EMP_ID =? and " +
		               		"INV_FINYEAR_FROM=? and INV_FINYEAR_TO=? and HRMS_TAX_INVESTMENT.INV_TYPE = 'I' ";
		
		case 5: return " SELECT  HRMS_EMP_INVESTMENT.INV_CODE,INV_NAME,INV_SECTION,INV_CHAPTER,INV_LIMIT1,INV_AMOUNT,INV_VALID_AMOUNT,INV_PROOF_ATTACH,NVL(INV_UPLOAD,' ') "
        				+" FROM HRMS_EMP_INVESTMENT INNER JOIN HRMS_TAX_INVESTMENT "
        				+" ON (HRMS_EMP_INVESTMENT.INV_CODE = HRMS_TAX_INVESTMENT.INV_CODE) WHERE HRMS_EMP_INVESTMENT.INV_ID =? AND HRMS_EMP_INVESTMENT.EMP_ID=? ";
		
		case 6: return "SELECT EMP_ID,INV_CODE,INV_FINYEAR_FROM,INV_FINYEAR_TO FROM HRMS_EMP_INVESTMENT WHERE EMP_ID=? AND INV_CODE=? AND INV_FINYEAR_FROM=? AND INV_FINYEAR_TO=?";
		
		case 7: return "DELETE FROM HRMS_EMP_INVESTMENT WHERE INV_ID=? AND EMP_ID=? AND INV_FINYEAR_FROM=? AND INV_FINYEAR_TO=? ";
		
		case 8:return "select debit_code,debit_name from hrms_debit_head where DEBIT_ISEXEMPT='Y'";
		
		case 9: return "SELECT INV_CHAPTER,INV_SECTION,INV_LIMIT1 from HRMS_TAX_INVESTMENT where INV_CODE = ? ";
		
		default:return"";
		}
	}
}
