package org.paradyne.sql.payroll.incometax;
import org.paradyne.lib.SqlBase;
/*
 * author:PK
 * Date:27.-3.2008
 */

public class HouseRentModelSql extends SqlBase {
	
	
	public String getQuery(int id){
		switch(id){
		
		case 1:return "INSERT INTO HRMS_HOUSERENT_HDR(RENT_CODE,RENT_EMPID,RENT_FROMYEAR,RENT_TOYEAR) "
					+" VALUES((SELECT NVL(MAX(RENT_CODE),0)+1 FROM HRMS_HOUSERENT_HDR),?,?,?)";	
		
		case 2:return "INSERT INTO HRMS_HOUSERENT_DTL(RENT_MONTH,RENT_AMOUNT,RENT_CODE) VALUES(?,?,?) ";
		
		/*case 3:return " SELECT RENT_MONTH,CASE WHEN RENT_MONTH=4 THEN 'April' "
					+"	WHEN RENT_MONTH=5 THEN 'May'"
					+" WHEN RENT_MONTH=6 THEN 'June'"
					+" WHEN RENT_MONTH=7 THEN 'July'"
					+" WHEN RENT_MONTH=8 THEN 'August'"
					+" WHEN RENT_MONTH=9 THEN 'September'"
					+" WHEN RENT_MONTH=10 THEN 'October'"
					+" WHEN RENT_MONTH=11 THEN 'November'"
					+" WHEN RENT_MONTH=12 THEN 'December'"
					+" WHEN RENT_MONTH=1 THEN 'January'"
					+" WHEN RENT_MONTH=2 THEN 'February'"
					+" WHEN RENT_MONTH=3 THEN 'March' END,"
					+" RENT_AMOUNT from HRMS_HOUSERENT_DTL INNER JOIN HRMS_HOUSERENT_HDR ON(HRMS_HOUSERENT_HDR.RENT_CODE=HRMS_HOUSERENT_DTL.RENT_CODE)"
					+" INNER JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=HRMS_HOUSERENT_HDR.RENT_EMPID) WHERE "
					+" RENT_FROMYEAR =? AND RENT_TOYEAR=? AND RENT_EMPID= ? ";*/
		
		case 3 :return "SELECT RENT_MONTH,TO_CHAR(TO_DATE(RENT_MONTH,'MM'),'Month')||'-'|| case when RENT_MONTH<4 then RENT_TOYEAR else RENT_FROMYEAR END AS MONTHYEAR, " 
				+"	RENT_AMOUNT from HRMS_HOUSERENT_DTL " 
				+"  INNER JOIN HRMS_HOUSERENT_HDR ON(HRMS_HOUSERENT_HDR.RENT_CODE=HRMS_HOUSERENT_DTL.RENT_CODE) " 
				+"  INNER JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=HRMS_HOUSERENT_HDR.RENT_EMPID) "
				+"  WHERE  RENT_FROMYEAR =? AND RENT_TOYEAR=? AND RENT_EMPID= ? "
				+" ORDER BY TO_DATE(RENT_MONTH||'-'|| CASE WHEN RENT_MONTH<4 THEN RENT_TOYEAR ELSE RENT_FROMYEAR END,'MM-YYYY') ";
		
		
		case 4:return " SELECT RENT_CODE FROM HRMS_HOUSERENT_HDR WHERE  RENT_FROMYEAR =? AND RENT_TOYEAR=? AND RENT_EMPID= ?" ;
		
		//case 5:return "UPDATE HRMS_HOUSERENT_DTL SET RENT_AMOUNT=?,RENT_RECEIPT_ATTACH=? WHERE RENT_CODE = ? and RENT_MONTH =?"; 
		case 5:return "UPDATE HRMS_HOUSERENT_DTL SET RENT_AMOUNT=? WHERE RENT_CODE = ? and RENT_MONTH =?"; 
		
		case 6:return "DELETE FROM HRMS_HOUSERENT_DTL WHERE RENT_CODE = ?";
		
		case 7:return "DELETE FROM HRMS_HOUSERENT_HDR WHERE RENT_CODE = ?";
		
		/*case 8:return "SELECT OWNER1_NAME, OWNER1_ADDRESS, OWNER1_AGREEMENT_ATTACH, OWNER1_PERIOD, OWNER2_NAME," 
		  +" OWNER2_ADDRESS, OWNER2_AGREEMENT_ATTACH, OWNER2_PERIOD FROM HRMS_HOUSERENT_HDR" 
		  +" WHERE  RENT_FROMYEAR=? AND RENT_TOYEAR=? AND RENT_EMPID=? ";

		case 9:return "UPDATE HRMS_HOUSERENT_HDR SET OWNER1_NAME=?, OWNER1_ADDRESS=?, OWNER1_AGREEMENT_ATTACH=?,OWNER1_PERIOD=?, OWNER2_NAME=?, OWNER2_ADDRESS=?, OWNER2_AGREEMENT_ATTACH=?, OWNER2_PERIOD=? WHERE  RENT_FROMYEAR =? AND RENT_TOYEAR=? AND RENT_EMPID= ?" ;*/

		}
		return "Query does not exist";
}
}