package org.paradyne.sql.payroll.incometax;

import org.paradyne.lib.SqlBase;

public class TaxSlabModelSql extends SqlBase {
	
	public String getQuery(int id){
		switch(id){
		case 1:return "INSERT INTO HRMS_TAX_SLAB(TAX_SLAB_ID,TAX_FROM_YEAR,TAX_TO_YEAR,TAX_EMP_TYPE,TAX_FROM_AMOUNT,TAX_TO_AMT, TAX_PERCENT) VALUES((SELECT NVL(MAX(TAX_SLAB_ID),0)+1 FROM HRMS_TAX_SLAB),?,?,?,?,?,?) ";
		
		case 2:return "SELECT HRMS_TAX_SLAB.TAX_SLAB_ID,HRMS_TAX_SLAB.TAX_FROM_AMOUNT,HRMS_TAX_SLAB.TAX_TO_AMT,HRMS_TAX_SLAB.TAX_PERCENT FROM HRMS_TAX_SLAB WHERE HRMS_TAX_SLAB.TAX_EMP_TYPE=? AND HRMS_TAX_SLAB.TAX_FROM_YEAR=? AND HRMS_TAX_SLAB.TAX_TO_YEAR=? ORDER BY HRMS_TAX_SLAB.TAX_FROM_AMOUNT";
		
		case 3:return "DELETE FROM HRMS_TAX_SLAB WHERE TAX_SLAB_ID=? ";
		
		case 4:return "UPDATE HRMS_TAX_SLAB SET TAX_FROM_AMOUNT=?,TAX_TO_AMT=?,TAX_PERCENT=? WHERE TAX_SLAB_ID=? ";
		
		case 5:return "SELECT HRMS_TAX_SLAB.TAX_SLAB_ID,HRMS_TAX_SLAB.TAX_FROM_AMOUNT,HRMS_TAX_SLAB.TAX_TO_AMT,HRMS_TAX_SLAB.TAX_PERCENT FROM HRMS_TAX_SLAB WHERE HRMS_TAX_SLAB.TAX_SLAB_ID=?  ";
		
		case 6:return "SELECT  HRMS_TAX_SLAB.TAX_FROM_AMOUNT, HRMS_TAX_SLAB.TAX_TO_AMT, HRMS_TAX_SLAB.TAX_PERCENT FROM HRMS_TAX_SLAB WHERE HRMS_TAX_SLAB.TAX_FROM_YEAR=? AND HRMS_TAX_SLAB.TAX_TO_YEAR=? AND HRMS_TAX_SLAB.TAX_EMP_TYPE=? ORDER BY HRMS_TAX_SLAB.TAX_FROM_AMOUNT";
		
		default:return"";
		}
		
	}
}


