package org.paradyne.sql.PAS.Competency;

import org.paradyne.lib.SqlBase;

public class CompetencyMasterModelSql extends SqlBase
{
  public String getQuery(int code)
  {
    switch (code) {
    case 1:
      return " INSERT INTO HRMS_COMPETENCY_HDR (COMPETENCY_CODE, COMPETENCY_TITLE, COMPETENCY_DESC, COMPETENCY_INDICATOR) VALUES (? , ? , ? , ?)";
    case 2:
      return " INSERT INTO HRMS_COMPETENCY_DTL (COMPETENCY_CODE, COMPETENCY_LEVEL, COMPETENCY_TITLE, COMPETENCY_LEVEL_DESC) VALUES ( ? ,? ,?,? )";
    case 3:
      return " DELETE FROM HRMS_COMPETENCY_DTL WHERE COMPETENCY_CODE= ? ";
    case 4:
      return " DELETE FROM HRMS_COMPETENCY_HDR WHERE COMPETENCY_CODE= ? ";
    case 5:
      return " SELECT QUESDTL_NAME, QUESDTL_VALUE FROM HRMS_QUESDTL WHERE QUES_CODE=? AND QUESDTL_CODE=?";
    case 6:
      return "SELECT HRMS_QUES.QUES_CODE,QUES_NAME,QUES_TYPE,QUESDTL_CODE,QUESDTL_NAME,QUESDTL_VALUE FROM HRMS_QUES  INNER JOIN HRMS_QUESDTL ON(HRMS_QUES.QUES_CODE=HRMS_QUESDTL.QUES_CODE) WHERE HRMS_QUES.QUES_CODE=?";
    case 7:
      return "UPDATE HRMS_QUESDTL SET QUESDTL_NAME=?, QUESDTL_VALUE=? WHERE QUES_CODE=? AND QUESDTL_CODE=? ";
    case 8:
      return "DELETE FROM HRMS_QUESDTL WHERE QUES_CODE=? AND QUESDTL_CODE=? ";
    case 9:
      return "UPDATE HRMS_COMPETENCY_HDR SET COMPETENCY_TITLE=?, COMPETENCY_DESC=?, COMPETENCY_INDICATOR=? WHERE COMPETENCY_CODE=?";
    case 10:
      return " SELECT  COMPETENCY_CODE, COMPETENCY_DESC, COMPETENCY_INDICATOR, COMPETENCY_TITLE FROM HRMS_COMPETENCY_HDR  ORDER BY COMPETENCY_CODE ";
    }

    return "HIIIIIIIIIIIIII";
  }
}