/**
 * 
 */
package org.paradyne.sql.payroll;

import org.paradyne.lib.SqlBase;


/**
 * @author Venkatesh
 *
 */
public class BonusParaModelSql extends SqlBase{
	
	public String getQuery(int id) {
		switch(id) {
		case 1: return " INSERT INTO HRMS_BONUS_PARAMETER (BONUS_CODE,BONUS_TYPE,BONUS_DAYS_DECLARED,BONUS_PERIOD_FROM,BONUS_PERIOD_TO,BONUS_EMP_TYPE,BONUS_FORMULA)" 
						+ " VALUES((SELECT NVL(MAX(BONUS_CODE),0)+1 FROM HRMS_BONUS_PARAMETER),?,?,TO_DATE(?,'DD-MM-YYYY'),TO_DATE(?,'DD-MM-YYYY'),?,?)";
		
		case 2: return " UPDATE HRMS_BONUS_PARAMETER SET BONUS_TYPE=?,BONUS_DAYS_DECLARED=?,BONUS_PERIOD_FROM=TO_DATE(?,'DD-MM-YYYY'),BONUS_PERIOD_TO=TO_DATE(?,'DD-MM-YYYY'),BONUS_EMP_TYPE=?,BONUS_FORMULA=? WHERE BONUS_CODE=?";
		
		case 3: return " DELETE FROM HRMS_BONUS_PARAMETER WHERE BONUS_CODE=?";
		
		
		case 4: return " SELECT  BONUS_CODE,BONUS_TYPE,BONUS_DAYS_DECLARED,TO_CHAR(BONUS_PERIOD_FROM,'DD-MM-YYYY'),TO_CHAR(BONUS_PERIOD_TO,'DD-MM-YYYY')," +
				"NVL(DECODE(BONUS_EMP_TYPE,'1','INDUSTRIAL','2','MINISTERIAL','3','NON INDUSTRIAL','4','SERVICE OFFICER','5','CIVILIAN OFFICER','6','CASUAL LABOUR','7','SERVICE OR'),''),BONUS_FORMULA,BONUS_EMP_TYPE FROM HRMS_BONUS_PARAMETER WHERE BONUS_CODE=?";
		
		case 5:return "SELECT BONUS_CODE,NVL(BONUS_TYPE,''),NVL(BONUS_DAYS_DECLARED,''),TO_CHAR(BONUS_PERIOD_FROM,'DD-MM-YYYY'),TO_CHAR(BONUS_PERIOD_TO,'DD-MM-YYYY')," +
				 "NVL(DECODE(BONUS_EMP_TYPE,'1','INDUSTRIAL','2','MINISTERIAL','3','NON INDUSTRIAL','4','SERVICE OFFICER','5','CIVILIAN OFFICER','6','CASUAL LABOUR','7','SERVICE OR'),''),BONUS_FORMULA FROM HRMS_BONUS_PARAMETER order by bonus_code";
			
		default : return "Framework could not EXECUTE the query number specified";			
		}
	}

}
