/**
 * 
 */
package org.paradyne.sql.payroll;

import org.paradyne.lib.SqlBase;

/**
 * @author MuzaffarS
 *
 */
public class DebitModelSql extends SqlBase{
	
	
	public String getQuery(int id) {
		switch(id) {
		/*case 1: return " INSERT INTO HRMS_DEBIT_HEAD (DEBIT_CODE,DEBIT_NAME,DEBIT_ABBR,DEBIT_TYPE,DEBIT_MAXCAP,DEBIT_MINFLOOR,DEBIT_ROUNDOFF,DEBIT_PAYFLAG) " 
						+"VALUES(SELECT NVL(MAX(DEBIT_CODE),0)+1 FROM HRMS_DEBIT_HEAD ),?,?,?,?,?,?,?)";*/
		
		case 1:return "INSERT INTO HRMS_DEBIT_HEAD (DEBIT_CODE,DEBIT_NAME,DEBIT_ABBR,DEBIT_ISEXEMPT,"					//DEBIT_BALANCE_FLAG,DEBIT_FOR_LOAN,		 "
				+ " DEBIT_PRIORITY,DEBIT_EXEMPT_INV_CODE,DEBIT_PERIODICITY,DEBIT_PAYFLAG,DEBIT_APPLICABLE_ARREARS,DEBIT_ROUND,DEBIT_TYPE,DEBIT_FORMULA) "
				+ " VALUES((SELECT NVL(MAX(DEBIT_CODE),0)+1 FROM HRMS_DEBIT_HEAD ),?,?,?,?,?,?,?,?,?,?,?)";
		
		case 2: return " UPDATE HRMS_DEBIT_HEAD SET DEBIT_NAME=?,DEBIT_ABBR=?,DEBIT_ISEXEMPT=?,DEBIT_PRIORITY=?,DEBIT_EXEMPT_INV_CODE=?,DEBIT_PERIODICITY=?,DEBIT_PAYFLAG=?,DEBIT_APPLICABLE_ARREARS=?," 
					+" DEBIT_ROUND=?,DEBIT_TYPE=?, DEBIT_FORMULA=? WHERE DEBIT_CODE=?";				//DEBIT_BALANCE_FLAG=?,DEBIT_FOR_LOAN=?
		
		case 3: return " DELETE FROM HRMS_DEBIT_HEAD WHERE DEBIT_CODE=?";
		
		case 4: return  " SELECT DEBIT_CODE,DEBIT_NAME,NVL(DEBIT_ABBR,''),NVL(DEBIT_ISEXEMPT,' '), " 
						//+" NVL(DEBIT_BALANCE_FLAG,''),NVL(DEBIT_FOR_LOAN,''), "
						+" NVL(DEBIT_PRIORITY,'0'),  "
						+" HRMS_TAX_INVESTMENT.INV_NAME,"
						+" DEBIT_PERIODICITY,DEBIT_PAYFLAG,DEBIT_APPLICABLE_ARREARS, HRMS_TAX_INVESTMENT.INV_CODE,NVL(DEBIT_ROUND,'0'),NVL(DEBIT_TYPE,'SG'),NVL(DEBIT_FORMULA,'0')  FROM HRMS_DEBIT_HEAD LEFT JOIN HRMS_TAX_INVESTMENT ON "
						+" (HRMS_DEBIT_HEAD.DEBIT_EXEMPT_INV_CODE=HRMS_TAX_INVESTMENT.INV_CODE)  WHERE DEBIT_CODE= ? " ;
		
		
		/*" SELECT NVL(DEBIT_CODE,'0'),NVL(DEBIT_NAME,''),NVL(DEBIT_ABBR,''),NVL(DEBIT_ISEXEMPT,' '), "+
					  " NVL(DEBIT_BALANCE_FLAG,''),NVL(DEBIT_FOR_LOAN,''), "+
					  " NVL(DEBIT_PRIORITY,'0'), "+ 
					  " NVL(DEBIT_EXEMPT_INV_CODE,'0'),DEBIT_IS_TABLERECOVERY  FROM HRMS_DEBIT_HEAD  Where DEBIT_CODE=trim(?)";*/
		
		
		/*case 5:return " SELECT NVL(DEBIT_CODE,'0'),NVL(DEBIT_NAME,' '),NVL(DEBIT_ABBR,' '),NVL(DECODE(DEBIT_ISEXEMPT ,'Y','Yes','N','No',' '),' ') , "+
		  " NVL( DECODE(DEBIT_BALANCE_FLAG ,'Y','Yes','N','No',' '),' '),NVL(DECODE(DEBIT_FOR_LOAN ,'Y','Yes','N','No',' '),' '), "+
		  " NVL(DEBIT_PRIORITY,'0'), "+ 
		  "  NVL(DEBIT_EXEMPT_INV_CODE,'0'),NVL( DECODE(DEBIT_IS_TABLERECOVERY ,'Y','Yes','N','No',' '),' ') FROM HRMS_DEBIT_HEAD  ORDER BY DEBIT_CODE";*/
		/*
		case 5: return  " SELECT DEBIT_CODE,DEBIT_NAME,DEBIT_ABBR,DEBIT_ISEXEMPT, " 
						+" DEBIT_BALANCE_FLAG,DEBIT_FOR_LOAN, "
						+" DEBIT_PRIORITY,  "
						+" HRMS_TAX_INVESTMENT.INV_NAME,"
						+" DEBIT_IS_TABLERECOVERY  FROM HRMS_DEBIT_HEAD LEFT JOIN HRMS_TAX_INVESTMENT ON "
						+" (HRMS_DEBIT_HEAD.DEBIT_EXEMPT_INV_CODE=HRMS_TAX_INVESTMENT.INV_CODE)  ORDER BY DEBIT_CODE " ;*/
		case 5: return  "   SELECT DEBIT_CODE,DEBIT_NAME,DEBIT_ABBR,DECODE(DEBIT_ISEXEMPT,'Y','Yes','N','No'),DEBIT_PRIORITY,  "  
						+"  HRMS_TAX_INVESTMENT.INV_NAME,   DECODE(DEBIT_PERIODICITY,'Q','Quarterly','M','Monthly','A','Annually','H','Half Yearly')      FROM HRMS_DEBIT_HEAD  "
						+"  LEFT JOIN HRMS_TAX_INVESTMENT ON  (HRMS_DEBIT_HEAD.DEBIT_EXEMPT_INV_CODE=HRMS_TAX_INVESTMENT.INV_CODE)  ORDER BY DEBIT_CODE " ;
			
		case 6: return " SELECT DEBIT_CODE,DEBIT_NAME,NVL(DEBIT_ABBR,'') FROM HRMS_DEBIT_HEAD ORDER BY DEBIT_CODE ";
		
		case 7:return " SELECT DEBIT_CODE,DEBIT_NAME,NVL(DEBIT_ABBR,''), NVL(DECODE(DEBIT_ISEXEMPT,'Y','Yes','N','No'),' '),DEBIT_PRIORITY,"  
		//+"   NVL(DECODE(DEBIT_BALANCE_FLAG,'Y','Yes','N','No'),' '),  "
		//+"   NVL(DECODE(DEBIT_FOR_LOAN,'Y','Yes','N','No'),' '),   "
		+"  	 NVL(HRMS_TAX_INVESTMENT.INV_NAME,' '),NVL(DECODE(DEBIT_PERIODICITY,'M','Monthly','Q','Quarterly','A','Annually','H','HalfYearly'),''),"
		+"  	 NVL(DECODE(DEBIT_PAYFLAG,'Y','Yes','N','No'),' ')"
		+"  	  FROM HRMS_DEBIT_HEAD "
		+"     LEFT JOIN HRMS_TAX_INVESTMENT ON "
		+"  	 (HRMS_DEBIT_HEAD.DEBIT_EXEMPT_INV_CODE=HRMS_TAX_INVESTMENT.INV_CODE) ORDER BY DEBIT_CODE ";
		
		default : return "Framework could not EXECUTE the query number specified";			
		}
	}

}
