package org.paradyne.sql.payroll;

import org.paradyne.lib.SqlBase;

import com.sun.org.apache.bcel.internal.generic.RETURN;

public class LoanInstallmentModelSql extends SqlBase {
	public String getQuery(int id){
		
		
		
		switch (id) {
		case 1 : return " INSERT INTO HRMS_EMP_INSTALLMENTS (INSTALL_CODE,LOAN_TYPE,LOAN_DATE,LOAN_RECOVERY_TYPE,LOAN_INTEREST_RATE,LOAN_AMOUNT, "
					+" LOAN_INTEREST,INSTALL_MONTHLY_PRINCIPAL,INSTALL_MONTHLY_INTEREST,LOAN_BALANCE_AMOUNT,INSTALL_TOTAL_NUMBER,INSTALL_BALANCE_NUMBER, "
					+" LOAN_PENALTY_INTEREST_AMOUNT,EMP_ID) "
					+" VALUES((SELECT NVL(MAX(INSTALL_CODE),0)+1 FROM HRMS_EMP_INSTALLMENTS),?,TO_DATE(?,'DD-MM-YYYY'),?,?,?,?,?,?,?,?,?,?,?) ";
		
		case 2 : return " SELECT DEBIT_NAME,TO_CHAR(LOAN_DATE,'DD-MM-YYYY'),DECODE(LOAN_RECOVERY_TYPE,'0','-Select-','1','Principal First','2','Interest  First','3','Both'),LOAN_INTEREST_RATE, "
					+" LOAN_AMOUNT,LOAN_INTEREST,INSTALL_MONTHLY_PRINCIPAL,INSTALL_MONTHLY_INTEREST,LOAN_BALANCE_AMOUNT,INSTALL_TOTAL_NUMBER,INSTALL_BALANCE_NUMBER, "
					+" LOAN_PENALTY_INTEREST_AMOUNT,INSTALL_CODE FROM HRMS_EMP_INSTALLMENTS "
					+" INNER JOIN HRMS_DEBIT_HEAD ON (HRMS_EMP_INSTALLMENTS.LOAN_TYPE =  HRMS_DEBIT_HEAD.DEBIT_CODE) " 
					+" WHERE EMP_ID = ? ";
		
		case 3 : return " SELECT DEBIT_NAME,TO_CHAR(LOAN_DATE,'DD-MM-YYYY'),LOAN_RECOVERY_TYPE,LOAN_INTEREST_RATE, "
					+" LOAN_AMOUNT,LOAN_INTEREST,INSTALL_MONTHLY_PRINCIPAL,INSTALL_MONTHLY_INTEREST,LOAN_BALANCE_AMOUNT,INSTALL_TOTAL_NUMBER,INSTALL_BALANCE_NUMBER, "
					+" LOAN_PENALTY_INTEREST_AMOUNT,EMP_ID,DEBIT_CODE FROM HRMS_EMP_INSTALLMENTS "
					+" INNER JOIN HRMS_DEBIT_HEAD ON (HRMS_EMP_INSTALLMENTS.LOAN_TYPE =  HRMS_DEBIT_HEAD.DEBIT_CODE) " 
					+" WHERE INSTALL_CODE = ? ";
		
		
		
		case 4: return  " UPDATE HRMS_EMP_INSTALLMENTS SET LOAN_TYPE = ?,LOAN_DATE= TO_DATE(?,'DD-MM-YYYY'),LOAN_RECOVERY_TYPE = ?, "
					+" LOAN_INTEREST_RATE = ?,LOAN_AMOUNT = ?,LOAN_INTEREST = ?,INSTALL_MONTHLY_PRINCIPAL = ?,INSTALL_MONTHLY_INTEREST = ?, "
					+" LOAN_BALANCE_AMOUNT = ?,INSTALL_TOTAL_NUMBER = ?,INSTALL_BALANCE_NUMBER = ?, "
					+" LOAN_PENALTY_INTEREST_AMOUNT = ?,EMP_ID = ? WHERE INSTALL_CODE = ?  ";
		
		case 5: return  " DELETE FROM  HRMS_EMP_INSTALLMENTS WHERE INSTALL_CODE = ? ";
		
		case 6 : return " SELECT DEBIT_NAME,TO_CHAR(LOAN_DATE,'DD-MM-YYYY'),LOAN_AMOUNT,LOAN_INTEREST,INSTALL_MONTHLY_PRINCIPAL, "
					+" INSTALL_MONTHLY_INTEREST,LOAN_BALANCE_AMOUNT,INSTALL_TOTAL_NUMBER,INSTALL_BALANCE_NUMBER FROM HRMS_EMP_INSTALLMENTS "
					+" INNER JOIN HRMS_DEBIT_HEAD ON (HRMS_EMP_INSTALLMENTS.LOAN_TYPE =  HRMS_DEBIT_HEAD.DEBIT_CODE) "
					+" WHERE EMP_ID =  ? ";
		
		case 7 : return " SELECT (CENTER_ID||'-'||CENTER_NAME),RANK_NAME,EMP_ID,(EMP_FNAME||'  '|| EMP_MNAME|| '  ' ||EMP_LNAME) FROM HRMS_EMP_OFFC " 
					+" INNER JOIN HRMS_RANK ON HRMS_RANK.RANK_ID = HRMS_EMP_OFFC.EMP_RANK "
					+" INNER JOIN HRMS_CENTER ON HRMS_CENTER.CENTER_ID = HRMS_EMP_OFFC.EMP_CENTER "
					+" WHERE EMP_ID = ?";
		
		
		
		
		default: return " query no. is not specified  ";
			
		}
		
		
	}
	
}
