package org.paradyne.sql.helpdesk;

import org.paradyne.lib.SqlBase;

public class HelpDeskMisReportModelSql extends SqlBase {

	public String getQuery(int id) {
		switch (id) {
		case 1:
			return "SELECT EMP_FNAME||' '||EMP_MNAME||' '||EMP_LNAME NAME, "
					+ "HRMS_DEPT.DEPT_NAME, TO_CHAR(HELP_APPLIED_DATE, 'DD-MM-YYYY'), HELP_SUBJECT, "
					+ "DECODE(HELP_STATUS, 'O', 'Open', 'C', 'Closed'), HELP_COMMENTS "
					+ "FROM HRMS_HELP "
					+ "INNER JOIN HRMS_EMP_OFFC ON (HRMS_EMP_OFFC.EMP_ID = HELP_EMP_CODE) "
					//+"LEFT JOIN HRMS_TITLE ON (HRMS_EMP_OFFC.EMP_TITLE_CODE = HRMS_TITLE.TITLE_CODE) "
					+ "INNER JOIN HRMS_DEPT ON (HRMS_DEPT.DEPT_ID = HRMS_HELP.HELP_APPLY_TO_DEPT) ";

		case 2:
			return " SELECT REQUEST_TOKEN,OFFC1.EMP_TOKEN ,( OFFC1.EMP_FNAME||' '||OFFC1.EMP_MNAME||' '||OFFC1.EMP_LNAME),"
					+ "	DECODE(REQUEST_APPLIED_FOR,'S','Self','O','Other','C','Client'),DEPT_NAME,( OFFC2.EMP_FNAME||' '||OFFC2.EMP_MNAME||' '||OFFC2.EMP_LNAME),REQUEST_TYPE_NAME,REQUEST_SUBTYPE_NAME,"
					+ "REQUEST_SUBJECT,TO_CHAR(REQUEST_DATE,'DD-MM-YYYY'), DECODE(REQUEST_APPL_STATUS,'O','Open','R','Resolved','I','In Process') "
					+ "FROM HELPDESK_REQUEST_HDR	"
					+ "INNER JOIN HRMS_EMP_OFFC OFFC1 ON (OFFC1.EMP_ID = HELPDESK_REQUEST_HDR.REQUEST_POSTED_FOR) "
					+ "INNER JOIN HRMS_EMP_OFFC OFFC2 ON (OFFC2.EMP_ID = HELPDESK_REQUEST_HDR.REQUEST_PENDING_WITH) "
					+ "LEFT JOIN HELPDESK_DEPT ON (HELPDESK_DEPT.DEPT_CODE = HELPDESK_REQUEST_HDR.REQUEST_APPLIED_TO_DEPT)"
					+ "LEFT JOIN HELPDESK_REQUEST_TYPE ON (HELPDESK_REQUEST_TYPE.REQUEST_TYPE_ID = HELPDESK_REQUEST_HDR.REQUEST_TYPE)"
					+ "LEFT JOIN HELPDESK_REQUEST_SUBTYPE ON (HELPDESK_REQUEST_SUBTYPE.REQUEST_SUBTYPE_ID = HELPDESK_REQUEST_HDR.REQUEST_SUBTYPE)"
					+" WHERE 1=1";
		default:
			return "";
		}
	}
}
