/**
 * 
 */
package org.paradyne.sql.helpdesk;

import org.paradyne.lib.SqlBase;

/**
 * @author Pankaj Jain
 *
 */
public class HelpdeskModelSql extends SqlBase {
	public String getQuery(int queryCode){
		
		switch(queryCode){
		case 1 : return " INSERT INTO HELPDESK_REQUEST_HDR (REQUEST_ID, REQUEST_DATE, REQUEST_APPLIED_FOR, REQUEST_POSTED_FOR, "
						+ " REQUEST_POSTED_BY, REQUEST_APPLIED_TO_DEPT, REQUEST_TYPE, REQUEST_SUBTYPE, REQUEST_SUBJECT, REQUEST_DESC, "
						+ " REQUEST_FILE_UPLOAD, REQUEST_APPL_STATUS, REQUEST_PENDING_WITH, REQUEST_CLIENT_NAME, "
						+ " REQUEST_MGR_STATUS, REQUEST_EMP_STATUS, ASSET_TYPE, ASSET_SUB_TYPE, ASSET_QUANTITY)"
						+ " VALUES ((SELECT NVL(MAX(REQUEST_ID), 0)+1 FROM HELPDESK_REQUEST_HDR), SYSDATE,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
		
		case 2 : return " UPDATE HELPDESK_REQUEST_HDR SET REQUEST_DATE = SYSDATE, REQUEST_APPLIED_FOR = ?, REQUEST_POSTED_FOR = ?, REQUEST_POSTED_BY = ?, "
						+ " REQUEST_APPLIED_TO_DEPT=?, REQUEST_TYPE=?, REQUEST_SUBTYPE=?, REQUEST_SUBJECT=?, REQUEST_DESC=?,"
						+ " REQUEST_FILE_UPLOAD=?, REQUEST_APPL_STATUS=?, REQUEST_PENDING_WITH=?, REQUEST_CLIENT_NAME=?, "
						+ " REQUEST_MGR_STATUS=?, REQUEST_EMP_STATUS=?, ASSET_TYPE=?, ASSET_SUB_TYPE=?, ASSET_QUANTITY=?"
						+ " WHERE REQUEST_ID = ?" ;
		
		case 3 : return " DELETE FROM HELPDESK_REQUEST_HDR WHERE REQUEST_ID = ? ";
		
		case 4 : return " SELECT NVL(REQUEST_TOKEN,' '), TO_CHAR(REQUEST_DATE,'DD-MM-YYYY'), REQUEST_APPLIED_FOR, REQUEST_POSTED_BY,"
						+ " POSTED_BY.EMP_TOKEN, POSTED_BY.EMP_FNAME||' '||POSTED_BY.EMP_MNAME||' '||POSTED_BY.EMP_LNAME INITIATOR,"
						+ " CENTER_ID,NVL(CENTER_NAME,' '), DEPT_ID,NVL(HRMS_DEPT.DEPT_NAME,' '), RANK_ID, NVL(RANK_NAME,' '),"
						+ " REQUEST_POSTED_FOR, POSTED_FOR.EMP_TOKEN, POSTED_FOR.EMP_FNAME||' '||POSTED_FOR.EMP_MNAME||' '||POSTED_FOR.EMP_LNAME"
						+ " APPLIED_FOR, NVL(REQUEST_CLIENT_NAME,' '), REQUEST_APPLIED_TO_DEPT, NVL(HRMS_DEPT.DEPT_NAME,' '), REQUEST_TYPE,"
						+ " NVL(REQUEST_TYPE_NAME,' '), REQUEST_SUBTYPE, NVL(REQUEST_SUBTYPE_NAME,' '), NVL(REQUEST_SUBJECT,' '),"
						+ " NVL(REQUEST_DESC,' '), NVL(REQUEST_FILE_UPLOAD, ' '), REQUEST_PENDING_WITH,  APPROVER.EMP_TOKEN,"
						+ " APPROVER.EMP_FNAME||' '||APPROVER.EMP_MNAME||' '||APPROVER.EMP_LNAME APPR_NAME,"
						+ " DECODE(REQUEST_MGR_STATUS,'N','Not Applicable','P','Pending for manager approval','A','Approved by manager',"
						+ " 'R','Rejected by manager','B','Sent back by manager'), DECODE(REQUEST_EMP_STATUS,'N','Not applicable','C','Closed',"
						+ " 'R','Reopen'),REQUEST_APPL_STATUS,DECODE(REQUEST_APPL_STATUS,'D','Draft','O','Open','I','In Process','R','Resolved','C','Closed','N','Rejected','W','Waiting for Approval','P','Waiting for Parts'), ASSET_TYPE,"
						+ " NVL(ASSET_CATEGORY_NAME,' '), ASSET_SUB_TYPE, NVL(ASSET_SUBTYPE_NAME,' '), NVL(ASSET_QUANTITY,0), REQUEST_ID, "
						+ " NVL(ADD_MOBILE,' '), NVL(ADD_EXTENSION,0), NVL(ADD_EMAIL,' ')"
						+ " FROM HELPDESK_REQUEST_HDR "
						+ " INNER JOIN HRMS_EMP_OFFC POSTED_BY ON (POSTED_BY.EMP_ID =  HELPDESK_REQUEST_HDR.REQUEST_POSTED_BY)"
						+ " LEFT JOIN HRMS_CENTER ON (HRMS_CENTER.CENTER_ID = POSTED_BY.EMP_CENTER)"
						+ " LEFT JOIN HRMS_DEPT ON (HRMS_DEPT.DEPT_ID = POSTED_BY.EMP_DEPT)"
						+ " LEFT JOIN HRMS_RANK ON (HRMS_RANK.RANK_ID = POSTED_BY.EMP_RANK)"
						+ " LEFT JOIN HRMS_EMP_OFFC POSTED_FOR ON (POSTED_FOR.EMP_ID =  HELPDESK_REQUEST_HDR.REQUEST_POSTED_FOR)"
						+ " INNER JOIN HELPDESK_DEPT ON (HELPDESK_DEPT.DEPT_CODE = HELPDESK_REQUEST_HDR.REQUEST_APPLIED_TO_DEPT)"
						+ " INNER JOIN HELPDESK_REQUEST_TYPE ON (HELPDESK_REQUEST_TYPE.REQUEST_TYPE_ID = HELPDESK_REQUEST_HDR.REQUEST_TYPE)"
						+ " INNER JOIN HELPDESK_REQUEST_SUBTYPE ON (HELPDESK_REQUEST_SUBTYPE.REQUEST_SUBTYPE_ID = HELPDESK_REQUEST_HDR.REQUEST_SUBTYPE)"
						+ " LEFT JOIN HRMS_EMP_OFFC APPROVER ON (APPROVER.EMP_ID =  HELPDESK_REQUEST_HDR.REQUEST_PENDING_WITH)"
						+ " LEFT JOIN HRMS_ASSET_CATEGORY ON (HRMS_ASSET_CATEGORY.ASSET_CATEGORY_CODE = HELPDESK_REQUEST_HDR.ASSET_TYPE)"
						+ " LEFT JOIN HRMS_ASSET_SUBTYPE ON (HRMS_ASSET_SUBTYPE.ASSET_SUBTYPE_CODE = HELPDESK_REQUEST_HDR.ASSET_SUB_TYPE)"
						+ " LEFT JOIN HRMS_EMP_ADDRESS ON(HRMS_EMP_ADDRESS.EMP_ID=HELPDESK_REQUEST_HDR.REQUEST_POSTED_BY and ADD_TYPE='P')"
						+ " WHERE REQUEST_ID = ?";
		
		case 5 : return "SELECT HELP_EMP_CODE, HRMS_EMP_OFFC.EMP_FNAME||' '||HRMS_EMP_OFFC.EMP_MNAME||' '||HRMS_EMP_OFFC.EMP_LNAME NAME, "
						+"EMP_CENTER, HRMS_CENTER.CENTER_NAME, HRMS_EMP_OFFC.EMP_DEPT, NVL(HRMS_DEPT.DEPT_NAME, ' '), "
						+"EMP_RANK, HRMS_RANK.RANK_NAME, HRMS_HELP.HELP_APPLY_TO_DEPT, HRMS_DEPT1.DEPT_NAME, "
						+"TO_CHAR(HELP_APPLIED_DATE, 'DD-MM-YYYY'), HELP_SUBJECT, HELP_STATUS, HELP_COMMENTS, NVL(TO_CHAR(HELP_ASSIGN_DATE, 'DD-MM-YYYY'), ' '), "
						+"HELP_ASSIGN_TO, HRMS_EMP_OFFC1.EMP_FNAME||' '||HRMS_EMP_OFFC1.EMP_MNAME||' '||HRMS_EMP_OFFC1.EMP_LNAME, "
						+"NVL(TO_CHAR(HELP_CLOSE_DATE, 'DD-MM-YYYY'), ' '), HRMS_EMP_OFFC.EMP_TOKEN, HRMS_EMP_OFFC1.EMP_TOKEN, NVL(HELP_ASSIGN_TIME,' '), NVL(HELP_CLOSE_TIME,' '), "
						+"NVL(HRMS_EMP_ADDRESS.ADD_PH1, ' '), HELP_LEVEL "
						+"FROM HRMS_HELP  "
						+"INNER JOIN HRMS_EMP_OFFC ON (HRMS_EMP_OFFC.EMP_ID = HRMS_HELP.HELP_EMP_CODE) "
						+"INNER JOIN HRMS_EMP_OFFC HRMS_EMP_OFFC1 ON (HRMS_EMP_OFFC1.EMP_ID = HELP_ASSIGN_TO) "
						+"INNER JOIN HRMS_RANK ON(HRMS_RANK.RANK_ID=HRMS_EMP_OFFC.EMP_RANK) "
						+"INNER JOIN HRMS_CENTER ON(HRMS_CENTER.CENTER_ID=HRMS_EMP_OFFC.EMP_CENTER) "
						+"LEFT JOIN HRMS_DEPT ON (HRMS_DEPT.DEPT_ID = HRMS_EMP_OFFC.EMP_DEPT) "
						//+"LEFT JOIN HRMS_TITLE ON (HRMS_EMP_OFFC.EMP_TITLE_CODE = HRMS_TITLE.TITLE_CODE) "
						//+"LEFT JOIN HRMS_TITLE HRMS_TITLE1 ON (HRMS_EMP_OFFC1.EMP_TITLE_CODE = HRMS_TITLE1.TITLE_CODE) "
						+"INNER JOIN HRMS_DEPT HRMS_DEPT1 ON (HRMS_DEPT1.DEPT_ID = HRMS_HELP.HELP_APPLY_TO_DEPT) "
						+"LEFT JOIN HRMS_EMP_ADDRESS ON (HRMS_EMP_OFFC.EMP_ID = HRMS_EMP_ADDRESS.EMP_ID) "
						+"WHERE HELP_CODE = ?";
		
		case 6 : return "SELECT HELP_EMP_CODE, EMP_CENTER, HRMS_CENTER.CENTER_NAME, HRMS_EMP_OFFC.EMP_DEPT, "
						+"NVL(HRMS_DEPT.DEPT_NAME, ' '), EMP_RANK, HRMS_RANK.RANK_NAME, HRMS_HELP.HELP_APPLY_TO_DEPT, HRMS_DEPT1.DEPT_NAME, "
						+"TO_CHAR(HELP_APPLIED_DATE, 'DD-MM-YYYY'), HELP_STATUS, HELP_COMMENTS, NVL(HRMS_EMP_ADDRESS.ADD_PH1, ' '), HELP_LEVEL "
						+"FROM HRMS_HELP "
						+"INNER JOIN HRMS_EMP_OFFC ON (HRMS_HELP.HELP_EMP_CODE = HRMS_EMP_OFFC.EMP_ID) "
						+"INNER JOIN HRMS_RANK ON(HRMS_RANK.RANK_ID=HRMS_EMP_OFFC.EMP_RANK) "
						+"INNER JOIN HRMS_CENTER ON(HRMS_CENTER.CENTER_ID=HRMS_EMP_OFFC.EMP_CENTER) "
						+"LEFT JOIN HRMS_EMP_ADDRESS ON (HRMS_EMP_OFFC.EMP_ID = HRMS_EMP_ADDRESS.EMP_ID ) "
						+"LEFT JOIN HRMS_DEPT ON (HRMS_DEPT.DEPT_ID = HRMS_EMP_OFFC.EMP_DEPT) "
						+"INNER JOIN HRMS_DEPT HRMS_DEPT1 ON (HRMS_DEPT1.DEPT_ID = HRMS_HELP.HELP_APPLY_TO_DEPT) "
						+"WHERE HELP_CODE = ?";
		
		case 7 : return "SELECT HRMS_EMP_OFFC.EMP_FNAME||' '||HRMS_EMP_OFFC.EMP_MNAME||' '||HRMS_EMP_OFFC.EMP_LNAME NAME, "
						+"HRMS_CENTER.CENTER_NAME, NVL(HRMS_DEPT.DEPT_NAME, ' '), HRMS_RANK.RANK_NAME, HRMS_EMP_ADDRESS.ADD_PH1, HRMS_DEPT1.DEPT_NAME, "
						+"TO_CHAR(HELP_APPLIED_DATE, 'DD-MM-YYYY'), HELP_SUBJECT, DECODE(HELP_STATUS,'C','Closed','O','Open'), "
						+"HELP_COMMENTS "
						+"FROM HRMS_HELP "
						+"INNER JOIN HRMS_EMP_OFFC ON (HRMS_HELP.HELP_EMP_CODE = HRMS_EMP_OFFC.EMP_ID) "
						//+"LEFT JOIN HRMS_TITLE ON (HRMS_EMP_OFFC.EMP_TITLE_CODE = HRMS_TITLE.TITLE_CODE) "
						+"LEFT JOIN HRMS_EMP_ADDRESS ON (HRMS_EMP_OFFC.EMP_ID = HRMS_EMP_ADDRESS.EMP_ID) "
						+"INNER JOIN HRMS_RANK ON(HRMS_RANK.RANK_ID=HRMS_EMP_OFFC.EMP_RANK) "
						+"INNER JOIN HRMS_CENTER ON(HRMS_CENTER.CENTER_ID=HRMS_EMP_OFFC.EMP_CENTER) "
						+"LEFT JOIN HRMS_DEPT ON (HRMS_DEPT.DEPT_ID = HRMS_EMP_OFFC.EMP_DEPT) "
						+"INNER JOIN HRMS_DEPT HRMS_DEPT1 ON (HRMS_DEPT1.DEPT_ID = HRMS_HELP.HELP_APPLY_TO_DEPT) "
						+"WHERE HELP_CODE = ?";
		
		case 8:
			return " SELECT  HRMS_EMP_OFFC.EMP_TOKEN,  HRMS_EMP_OFFC.EMP_FNAME||' '||HRMS_EMP_OFFC.EMP_MNAME||' '||HRMS_EMP_OFFC.EMP_LNAME, "
					+ " TO_CHAR(HELPDESK_REQUEST_HDR.REQUEST_DATE,'DD-MM-YYYY'),HELPDESK_REQUEST_HDR.REQUEST_POSTED_BY, "
					+ " HELPDESK_REQUEST_HDR.REQUEST_ID,HELPDESK_REQUEST_HDR.REQUEST_APPL_STATUS  "
					+ " FROM HELPDESK_REQUEST_HDR "
					+ " INNER JOIN HRMS_EMP_OFFC ON (HRMS_EMP_OFFC.EMP_ID  = HELPDESK_REQUEST_HDR.REQUEST_POSTED_BY) "
					+ " WHERE HELPDESK_REQUEST_HDR.REQUEST_APPL_STATUS=? AND HELPDESK_REQUEST_HDR.REQUEST_POSTED_BY=? "
					+ " ORDER BY REQUEST_ID DESC";
		
		case 9:
			return " SELECT NVL(REQUEST_APPL_STATUS,'P'),REQUEST_PENDING_WITH FROM HELPDESK_REQUEST_HDR WHERE REQUEST_ID=? ";
		
		
		default: return " Query not Found";
		}
	}

}
