/**
 * 
 */
package org.paradyne.sql.helpdesk;

import org.paradyne.lib.SqlBase;

/**
 * @author_Pankaj_Jain
 *
 */
public class HelpDeskAppModelSql extends SqlBase {
	public String getQuery(int queryCode){
		
		switch(queryCode){
			case 1 :  return "SELECT HELP_CODE, HELP_EMP_CODE, (EMP_FNAME||' ' ||EMP_MNAME||' ' ||EMP_LNAME), HELP_SUBJECT , "
							+"TO_CHAR(HELP_APPLIED_DATE,'DD-MM-YYYY'), HELP_STATUS, HELP_LEVEL "
						    +"FROM HRMS_HELP "
						    +"INNER JOIN HRMS_EMP_OFFC ON (HRMS_EMP_OFFC.EMP_ID = HRMS_HELP.HELP_EMP_CODE) "
						    //+"LEFT JOIN HRMS_TITLE ON (HRMS_EMP_OFFC.EMP_TITLE_CODE = HRMS_TITLE.TITLE_CODE) "
						    +"WHERE HELP_ASSIGN_TO = ? AND HELP_STATUS = ? ORDER BY HELP_CODE";
			
			case 2 :  return " SELECT " 
						   +" TO_CHAR(EMP_FNAME||' '||EMP_LNAME) AS NAME, " 
						   +" TO_CHAR(EMP_CENTER||'-'||CENTER_NAME) AS CENTER,TO_CHAR(RANK_NAME)  AS RANK, HRMS_DEPT.DEPT_NAME, TO_CHAR(HELP_COMMENTDT,'DD-MM-YYYY'), HELP_SUBJECT,HELP_COMMENTS,HELP_HELPCODE, "
						   +" TO_CHAR(CNDT.EMP_FNAME||' '||CNDT.EMP_LNAME), HELP_STATUS,TO_CHAR(HELP_ATTENDDT,'DD-MM-YYYY'),HELP_ATTENDTIME,HELP_STATUS "
						   +" FROM HRMS_HELP " 
						   +" INNER JOIN HRMS_DEPT ON (HRMS_DEPT.DEPT_ID = HRMS_HELP.HELP_APPLYTODEPT) "
						   +" LEFT JOIN HRMS_EMP_OFFC CNDT ON (CNDT.EMP_ID = HRMS_HELP.HELP_ASSIGNTO) "
						   +" INNER JOIN HRMS_EMP_OFFC ON (HRMS_EMP_OFFC.EMP_ID = HRMS_HELP.HELP_EMPCODE) " 
						   +" INNER JOIN HRMS_RANK ON(HRMS_RANK.RANK_ID=HRMS_EMP_OFFC.EMP_RANK) " 
						   +" INNER JOIN HRMS_CENTER ON(HRMS_CENTER.CENTER_ID=HRMS_EMP_OFFC.EMP_CENTER) " 
						   //+" LEFT JOIN HRMS_TITLE ON(HRMS_TITLE.TITLE_CODE=HRMS_EMP_OFFC.EMP_TITLE_CODE) " 
						   +" WHERE HELP_HELPCODE = ? ";
			
			case 3 :  return " UPDATE HRMS_HELP SET HELP_ASSIGN_TO = ?, HELP_STATUS = ?, HELP_ASSIGN_DATE = TO_DATE(?,'DD-MM-YYYY'), "
							+"HELP_ASSIGN_TIME =?, HELP_LEVEL = 2 WHERE HELP_CODE = ? ";
			
			case 4 : return " SELECT NVL(REQUEST_TOKEN,' '), TO_CHAR(REQUEST_DATE,'DD-MM-YYYY'), REQUEST_APPLIED_FOR, REQUEST_POSTED_BY,"
							+ " POSTED_BY.EMP_TOKEN, POSTED_BY.EMP_FNAME||' '||POSTED_BY.EMP_MNAME||' '||POSTED_BY.EMP_LNAME INITIATOR,"
							+ " CENTER_ID,NVL(CENTER_NAME,' '), DEPT_ID,NVL(HRMS_DEPT.DEPT_NAME,' '), RANK_ID, NVL(RANK_NAME,' '),"
							+ " REQUEST_POSTED_FOR, POSTED_FOR.EMP_TOKEN, POSTED_FOR.EMP_FNAME||' '||POSTED_FOR.EMP_MNAME||' '||POSTED_FOR.EMP_LNAME"
							+ " APPLIED_FOR, NVL(REQUEST_CLIENT_NAME,' '), REQUEST_APPLIED_TO_DEPT, NVL(HRMS_DEPT.DEPT_NAME,' '), REQUEST_TYPE,"
							+ " NVL(REQUEST_TYPE_NAME,' '), REQUEST_SUBTYPE, NVL(REQUEST_SUBTYPE_NAME,' '), NVL(REQUEST_SUBJECT,' '),"
							+ " NVL(REQUEST_DESC,' '), NVL(REQUEST_FILE_UPLOAD, ' '), REQUEST_PENDING_WITH,  APPROVER.EMP_TOKEN,"
							+ " APPROVER.EMP_FNAME||' '||APPROVER.EMP_MNAME||' '||APPROVER.EMP_LNAME APPR_NAME,"
							+ " DECODE(REQUEST_MGR_STATUS,'N','Not Applicable','P','Pending for manager approval','A','Approved by manager',"
							+ " 'R','Rejected by manager','B','Sent back by manager'), DECODE(REQUEST_EMP_STATUS,'N','Not applicable','C','Closed',"
							+ " 'R','Reopen'),REQUEST_APPL_STATUS,DECODE(REQUEST_APPL_STATUS,'O','Open','I','In Process','R','Resolved','N','Rejected'), ASSET_TYPE,"
							+ " NVL(ASSET_CATEGORY_NAME,' '), ASSET_SUB_TYPE, NVL(ASSET_SUBTYPE_NAME,' '), NVL(ASSET_QUANTITY,0), REQUEST_ID, "
							+ " NVL(ADD_MOBILE,' '), NVL(ADD_EXTENSION,0), NVL(ADD_EMAIL,' ')"
							+ " FROM HELPDESK_REQUEST_HDR "
							+ " INNER JOIN HRMS_EMP_OFFC POSTED_BY ON (POSTED_BY.EMP_ID =  HELPDESK_REQUEST_HDR.REQUEST_POSTED_BY)"
							+ " LEFT JOIN HRMS_CENTER ON (HRMS_CENTER.CENTER_ID = POSTED_BY.EMP_CENTER)"
							+ " LEFT JOIN HRMS_DEPT ON (HRMS_DEPT.DEPT_ID = POSTED_BY.EMP_DEPT)"
							+ " LEFT JOIN HRMS_RANK ON (HRMS_RANK.RANK_ID = POSTED_BY.EMP_RANK)"
							+ " LEFT JOIN HRMS_EMP_OFFC POSTED_FOR ON (POSTED_FOR.EMP_ID =  HELPDESK_REQUEST_HDR.REQUEST_POSTED_FOR)"
							+ " INNER JOIN HELPDESK_DEPT ON (HELPDESK_DEPT.DEPT_CODE = HELPDESK_REQUEST_HDR.REQUEST_APPLIED_TO_DEPT)"
							+ " INNER JOIN HELPDESK_REQUEST_TYPE ON (HELPDESK_REQUEST_TYPE.REQUEST_TYPE_ID = HELPDESK_REQUEST_HDR.REQUEST_TYPE)"
							+ " INNER JOIN HELPDESK_REQUEST_SUBTYPE ON (HELPDESK_REQUEST_SUBTYPE.REQUEST_SUBTYPE_ID = HELPDESK_REQUEST_HDR.REQUEST_SUBTYPE)"
							+ " LEFT JOIN HRMS_EMP_OFFC APPROVER ON (APPROVER.EMP_ID =  HELPDESK_REQUEST_HDR.REQUEST_PENDING_WITH)"
							+ " LEFT JOIN HRMS_ASSET_CATEGORY ON (HRMS_ASSET_CATEGORY.ASSET_CATEGORY_CODE = HELPDESK_REQUEST_HDR.ASSET_TYPE)"
							+ " LEFT JOIN HRMS_ASSET_SUBTYPE ON (HRMS_ASSET_SUBTYPE.ASSET_SUBTYPE_CODE = HELPDESK_REQUEST_HDR.ASSET_SUB_TYPE)"
							+ " LEFT JOIN HRMS_EMP_ADDRESS ON(HRMS_EMP_ADDRESS.EMP_ID=HELPDESK_REQUEST_HDR.REQUEST_POSTED_BY and ADD_TYPE='P')"
							+ " WHERE REQUEST_ID = ?";
			
			case 5 : return "SELECT HELP_CODE, HELP_APPLY_TO_DEPT, HELP_LEVEL FROM  HRMS_HELP "
							+"WHERE HELP_ASSIGN_TO = ? ";
			
			case 6 : return "SELECT HELP_CODE, HELP_EMP_CODE, (EMP_FNAME||' ' ||EMP_MNAME||' ' ||EMP_LNAME), HELP_SUBJECT , "
							+"TO_CHAR(HELP_APPLIED_DATE,'DD-MM-YYYY'), HELP_STATUS, HELP_LEVEL "
						    +"FROM HRMS_HELP "
						    +"INNER JOIN HRMS_EMP_OFFC ON (HRMS_EMP_OFFC.EMP_ID = HRMS_HELP.HELP_EMP_CODE) "
						    //+"LEFT JOIN HRMS_TITLE ON (HRMS_EMP_OFFC.EMP_TITLE_CODE = HRMS_TITLE.TITLE_CODE) "
						    +"WHERE HELP_APPLY_TO_DEPT = ? AND HELP_STATUS = ? AND ROWNUM <= 50 "
						    +"ORDER BY HELP_CODE DESC";
			
			case 7 :  return "UPDATE HRMS_HELP SET HELP_ASSIGN_TO = ?, HELP_STATUS = ?, HELP_CLOSE_DATE = TO_DATE(?,'DD-MM-YYYY'), "
							 +"HELP_CLOSE_TIME =?, HELP_LEVEL = 2 WHERE HELP_CODE = ? ";
			
			case 8 : return "INSERT INTO HRMS_HELP_PATH (HELP_PATH_CODE, HELP_PATH_EMP_ID, HELP_PATH_ASSIGN_DATE, HELP_PATH_STATUS) "
							+"VALUES(?, ?, TO_DATE(?, 'DD-MM-YYYY'), ?)";
			
			case 9:
				return " SELECT REQUEST_ID,HELPDESK_REQUEST_HDR.REQUEST_POSTED_FOR,EMP_FNAME||' '||EMP_MNAME||' '||EMP_LNAME,TO_CHAR(REQUEST_DATE,'DD-MM-YYYY'),"
						+ "	 REQUEST_STATUS,'',HRMS_EMP_OFFC.EMP_TOKEN "
						+ "	 FROM HELPDESK_REQUEST_HDR "
						+ "	 INNER JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=HELPDESK_REQUEST_HDR.REQUEST_POSTED_FOR)"
						+ "	 WHERE  REQUEST_STATUS=?  AND REQUEST_PENDING_WITH=? ORDER BY REQUEST_ID DESC ";
			
			default: return " Query Not Found ";
		}
	}

}
