package org.paradyne.sql.D1;

import org.paradyne.lib.SqlBase;

public class DepartmentandLocationChangeModelSql extends SqlBase {

	public String getQuery(int id) {
		switch (id) {
		
		case 1:
			return "insert into HRMS_D1_DEPT_LOC_CHANGE(DEPT_LOC_ID, DEPT_LOC_EMP_ID, DEPT_LOC_DATE, DEPT_LOC_DEPT_NO, DEPT_LOC_PHONE, DEPT_LOC_MANAGER, DEPT_LOC_TYPE, DEPT_LOC_WORK_HOME, DEPT_LOC_APPROVER,DEPT_ADD1, DEPT_ADD2, DEPT_ADD3, DEPT_PHONE, DEPT_CITY, DEPT_STATE, DEPT_COUNTRY,DEPT_APPROVER_STATUS,DEPT__APPL_DATE,DEPT_INITIATOR,DEPT_APPLICATION_DATE,DEPT_FILE_HEADER_NAME,DEPT_EXECUTIVE,DEPT_CODE) "
					+ " values((SELECT NVL(MAX(DEPT_LOC_ID),0)+1 FROM  HRMS_D1_DEPT_LOC_CHANGE),?,TO_DATE(?,'dd-mm-yyyy'),?,?,?,?,?,?,?,?,?,?,?,?,?,?,SYSDATE,?,SYSDATE,?,?,?) ";

		case 2:
			return " UPDATE HRMS_D1_DEPT_LOC_CHANGE SET DEPT_LOC_EMP_ID=?, DEPT_LOC_DATE=TO_DATE(?,'dd-mm-yyyy'), DEPT_LOC_DEPT_NO=?, DEPT_LOC_PHONE=?, DEPT_LOC_MANAGER=?, DEPT_LOC_TYPE=?, DEPT_LOC_WORK_HOME=?, DEPT_LOC_APPROVER=?,DEPT_ADD1=?, DEPT_ADD2=?, DEPT_ADD3=?, DEPT_PHONE=?, DEPT_CITY=?, DEPT_STATE=?, DEPT_COUNTRY=?, DEPT_APPROVER_STATUS=?,DEPT_INITIATOR=?,DEPT_FILE_HEADER_NAME=?,DEPT_EXECUTIVE=?,DEPT_CODE=? WHERE DEPT_LOC_ID=?  ";

		case 3:
			return " SELECT REGION_ID,REGION_NAME  FROM  HRMS_D1_DEPT_LOC_CHANGE "
					+ " ORDER BY REGION_NAME ";

		case 4:
			return " DELETE from HRMS_D1_DEPT_LOC_CHANGE WHERE DEPT_LOC_ID=?  ";

		case 5:
			return " SELECT DEPT_LOC_ID,HRMS_EMP_OFFC.EMP_TOKEN,TO_CHAR(HRMS_EMP_OFFC.EMP_FNAME ||' '||HRMS_EMP_OFFC.EMP_MNAME ||' '||HRMS_EMP_OFFC.EMP_LNAME),TO_CHAR(DPT.DEPT__APPL_DATE,'DD-MM-YYYY') "
					+ " FROM HRMS_D1_DEPT_LOC_CHANGE DPT "
					+ " Inner JOIN HRMS_EMP_OFFC ON DPT.DEPT_LOC_EMP_ID = HRMS_EMP_OFFC.EMP_ID "
					+ " WHERE DPT.DEPT_APPROVER_STATUS='D' and ORDER BY DPT.DEPT_LOC_DATE ";
		case 6:
			return " SELECT DEPT_LOC_ID,HRMS_EMP_OFFC.EMP_TOKEN,TO_CHAR(HRMS_EMP_OFFC.EMP_FNAME ||' '||HRMS_EMP_OFFC.EMP_MNAME ||' '||HRMS_EMP_OFFC.EMP_LNAME),TO_CHAR(DPT.DEPT__APPL_DATE,'DD-MM-YYYY') "
					+ " FROM HRMS_D1_DEPT_LOC_CHANGE DPT "
					+ " Inner JOIN HRMS_EMP_OFFC ON DPT.DEPT_LOC_EMP_ID = HRMS_EMP_OFFC.EMP_ID "
					+ " WHERE DPT.DEPT_APPROVER_STATUS='P' ORDER BY DPT.DEPT_LOC_DATE ";

		case 7:
			return " SELECT DEPT_LOC_ID,HRMS_EMP_OFFC.EMP_TOKEN,TO_CHAR(HRMS_EMP_OFFC.EMP_FNAME ||' '||HRMS_EMP_OFFC.EMP_MNAME ||' '||HRMS_EMP_OFFC.EMP_LNAME),TO_CHAR(DPT.DEPT__APPL_DATE,'DD-MM-YYYY') "
			+ " FROM HRMS_D1_DEPT_LOC_CHANGE DPT "
			+ " Inner JOIN HRMS_EMP_OFFC ON DPT.DEPT_LOC_EMP_ID = HRMS_EMP_OFFC.EMP_ID "
			+ " WHERE DPT.DEPT_APPROVER_STATUS='A' ORDER BY DPT.DEPT_LOC_DATE ";

		case 8:
			return " SELECT DEPT_LOC_ID,HRMS_EMP_OFFC.EMP_TOKEN,TO_CHAR(HRMS_EMP_OFFC.EMP_FNAME ||' '||HRMS_EMP_OFFC.EMP_MNAME ||' '||HRMS_EMP_OFFC.EMP_LNAME),TO_CHAR(DPT.DEPT__APPL_DATE,'DD-MM-YYYY') "
			+ " FROM HRMS_D1_DEPT_LOC_CHANGE DPT "
			+ " Inner JOIN HRMS_EMP_OFFC ON DPT.DEPT_LOC_EMP_ID = HRMS_EMP_OFFC.EMP_ID "
			+ " WHERE DPT.DEPT_APPROVER_STATUS='R' ORDER BY DPT.DEPT_LOC_DATE ";
	
		case 9:
			return " SELECT DEPT_LOC_ID,HRMS_EMP_OFFC.EMP_TOKEN,TO_CHAR(HRMS_EMP_OFFC.EMP_FNAME ||' '||HRMS_EMP_OFFC.EMP_MNAME ||' '||HRMS_EMP_OFFC.EMP_LNAME),TO_CHAR(DPT.DEPT__APPL_DATE,'DD-MM-YYYY') "
					+ " FROM HRMS_D1_DEPT_LOC_CHANGE DPT "
					+ " Inner JOIN HRMS_EMP_OFFC ON DPT.DEPT_LOC_EMP_ID = HRMS_EMP_OFFC.EMP_ID "
					+ " WHERE DPT.DEPT_APPROVER_STATUS='B' ORDER BY DPT.DEPT_LOC_DATE ";
			
		case 10:
			return " SELECT DEPT_LOC_ID,HRMS_EMP_OFFC.EMP_TOKEN,TO_CHAR(HRMS_EMP_OFFC.EMP_FNAME ||' '||HRMS_EMP_OFFC.EMP_MNAME ||' '||HRMS_EMP_OFFC.EMP_LNAME),TO_CHAR(DPT.DEPT__APPL_DATE,'DD-MM-YYYY') "
			+ " FROM HRMS_D1_DEPT_LOC_CHANGE DPT "
			+ " Inner JOIN HRMS_EMP_OFFC ON DPT.DEPT_LOC_EMP_ID = HRMS_EMP_OFFC.EMP_ID "
			+ " WHERE DPT.DEPT_APPROVER_STATUS='X' ORDER BY DPT.DEPT_LOC_DATE ";
			
		case 11:
			return " SELECT DEPT_LOC_ID,HRMS_EMP_OFFC.EMP_TOKEN,TO_CHAR(HRMS_EMP_OFFC.EMP_FNAME ||' '||HRMS_EMP_OFFC.EMP_MNAME ||' '||HRMS_EMP_OFFC.EMP_LNAME),TO_CHAR(DPT.DEPT__APPL_DATE,'DD-MM-YYYY') "
			+ " FROM HRMS_D1_DEPT_LOC_CHANGE DPT "
			+ " Inner JOIN HRMS_EMP_OFFC ON DPT.DEPT_LOC_EMP_ID = HRMS_EMP_OFFC.EMP_ID "
			+ " WHERE DPT.DEPT_APPROVER_STATUS='Z' ORDER BY DPT.DEPT_LOC_DATE ";
		case 12:
			return " SELECT DEPT_LOC_ID,HRMS_EMP_OFFC.EMP_TOKEN,TO_CHAR(HRMS_EMP_OFFC.EMP_FNAME ||' '||HRMS_EMP_OFFC.EMP_MNAME ||' '||HRMS_EMP_OFFC.EMP_LNAME),TO_CHAR(DPT.DEPT__APPL_DATE,'DD-MM-YYYY') "
			+ " FROM HRMS_D1_DEPT_LOC_CHANGE DPT "
			+ " Inner JOIN HRMS_EMP_OFFC ON DPT.DEPT_LOC_EMP_ID = HRMS_EMP_OFFC.EMP_ID "
			+ " WHERE DPT.DEPT_APPROVER_STATUS='C' ORDER BY DPT.DEPT_LOC_DATE ";
		default:
			return "Framework could not the query number specified";

		}
	}
}