package org.paradyne.sql.D1;

import org.paradyne.lib.SqlBase;

public class DepartmentNoMasterModelSql extends SqlBase{
	public String getQuery(int id) {
		switch(id) {
		case 1: return " INSERT INTO HRMS_DEPT (DEPT_ID,DEPT_NAME,DEPT_ABBR,DEPT_DIV_CODE,DEPT_DESC,DEPT_LEVEL,DEPT_PARENT_CODE,IS_ACTIVE) " 
						+ " VALUES((SELECT NVL(MAX(DEPT_ID),0)+1 FROM HRMS_DEPT ),?,?,?,?,?,?,?)";
		
		case 2: return "UPDATE HRMS_D1_DEPARTMENT SET DEPT_NUMBER = ?,DEPT_NAME=?,DEPT_ABBRIVATION=?,DEPT_DIV_CODE=?,DEPT_DESCRIPTION=?,DEPT_IS_ACTIVE=? WHERE DEPT_ID=? ";
		
		case 3: return " DELETE FROM HRMS_D1_DEPARTMENT WHERE DEPT_ID=?";
		
		case 4: return "  SELECT DEPT_ID, DEPT_NUMBER, DEPT_NAME, DEPT_ABBRIVATION, DEPT_DIV_CODE, DEPT_DESCRIPTION,DEPT_IS_ACTIVE,HRMS_DIVISION.DIV_NAME FROM HRMS_D1_DEPARTMENT "
				+ " LEFT JOIN HRMS_DIVISION ON(HRMS_DIVISION.DIV_ID=HRMS_D1_DEPARTMENT.DEPT_DIV_CODE) "
				+ " WHERE DEPT_ID= ?";
				
		case 5: return  " SELECT DEPT_ID, DEPT_NUMBER, DEPT_NAME, DEPT_ABBRIVATION, DEPT_DIV_CODE, DEPT_DESCRIPTION,DECODE(HRMS_D1_DEPARTMENT.DEPT_IS_ACTIVE,'Y','Yes','N','No')FROM HRMS_D1_DEPARTMENT "
 						+ " LEFT JOIN HRMS_DIVISION ON(HRMS_DIVISION.DIV_ID=HRMS_D1_DEPARTMENT.DEPT_DIV_CODE) "
 						+ " ORDER BY upper(DEPT_NAME)";
		case 6: return  " SELECT  DEPT_ID,nvl(DEPT_NAME,' '),nvl(DIV_NAME,' ')"
		+ " FROM HRMS_DEPT "
		+ " LEFT JOIN HRMS_DIVISION ON(HRMS_DIVISION.DIV_ID=HRMS_DEPT.DEPT_DIV_CODE)"
		+ " ORDER BY DEPT_ID";

		
		default : return "Framework could not the query number specified";			
		}
	}
}
