package org.paradyne.sql.D1;

import org.paradyne.lib.SqlBase;

public class VendorModelSql extends SqlBase {

	public String getQuery(int id) {
		switch (id) {

		case 1:

			return " INSERT INTO  HRMS_D1_VENDOR (VENDOR_ID, VENDOR_NAME, VENDOR_EIN_NUMBER, VENDOR_PO_ADDRESS, VENDOR_CITY, VENDOR_STATE, "
					+ " VENDOR_ZIP, VENDOR_PHONE_NO, VENDOR_SEND_PO, VENDOR_CONTACT_NAME, VENDOR_REMIT_NAME, VENDOR_REMIT_ADDRESS, VEDOR_DISC_PERCENT,"
					+ " VENDOR_NET_DAYS, VENDOR_COMMENTS1, VENDOR_CLASS_CODE, VENDOR_MIN_ORDER, VENDOR_FRIEGHT_MSG, VENDOR_TAX_MSG, VENDOR_SHIP_VIA, VENDOR_FOB, "
					+ " VENDOR_COMMENTS2, VENDOR_REMIT_CITY, VENDOR_REMIT_STATE, VENDOR_REMIT_ZIP, VENDOR_APPLICATION_DATE)"
					+ " values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,SYSDATE) ";
		case 2:
			return " UPDATE HRMS_D1_VENDOR SET VENDOR_NAME=?, VENDOR_EIN_NUMBER=?, VENDOR_PO_ADDRESS=?, VENDOR_CITY=?, VENDOR_STATE=?, VENDOR_ZIP=?,"
					+ " VENDOR_PHONE_NO=?, VENDOR_SEND_PO=?, VENDOR_CONTACT_NAME=?, VENDOR_REMIT_NAME=?, VENDOR_REMIT_ADDRESS=?, VEDOR_DISC_PERCENT=?, VENDOR_NET_DAYS=?,"
					+ "  VENDOR_COMMENTS1=?, VENDOR_CLASS_CODE=?, VENDOR_MIN_ORDER=?, VENDOR_FRIEGHT_MSG=?, VENDOR_TAX_MSG=?, VENDOR_SHIP_VIA=?, VENDOR_FOB=?, VENDOR_COMMENTS2=?,"
					+ " VENDOR_REMIT_CITY=?, VENDOR_REMIT_STATE=?, VENDOR_REMIT_ZIP=? WHERE VENDOR_ID=? ";

		case 3:
			return  " SELECT VENDOR_ID,VENDOR_NAME, VENDOR_EIN_NUMBER, VENDOR_PO_ADDRESS, VENDOR_CITY,HRMS_LOCATION.LOCATION_NAME, VENDOR_STATE,"
			+ " VENDOR_ZIP, VENDOR_PHONE_NO, VENDOR_SEND_PO, VENDOR_CONTACT_NAME, VENDOR_REMIT_NAME, VENDOR_REMIT_ADDRESS, VEDOR_DISC_PERCENT,"
			+ " VENDOR_NET_DAYS, VENDOR_COMMENTS1, VENDOR_CLASS_CODE, VENDOR_MIN_ORDER, VENDOR_FRIEGHT_MSG, VENDOR_TAX_MSG, VENDOR_SHIP_VIA, VENDOR_FOB,  "
			+ " VENDOR_COMMENTS2, VENDOR_REMIT_CITY,HRMS_LOCATION.LOCATION_NAME, VENDOR_REMIT_STATE, VENDOR_REMIT_ZIP,TO_CHAR(VENDOR_APPLICATION_DATE,'DD-MM-YYYY')  "
			+ " FROM HRMS_D1_VENDOR"
			+ " LEFT JOIN HRMS_LOCATION on(HRMS_LOCATION.LOCATION_CODE=HRMS_D1_VENDOR.VENDOR_CITY)";

		case 4:
			return " DELETE from HRMS_D1_VENDOR WHERE VENDOR_ID=?  ";
		
		
		
		default:
			return "Framework could not the query number specified";

		}
	}
}
