package org.paradyne.sql.leave;

import org.paradyne.lib.SqlBase;

public class LeaveEncashmentModelSql extends SqlBase {

	public String getQuery(int id) {
		switch (id) {
		case 1:
			return " SELECT TO_CHAR(LEAVE_NAME),LEAVE_BALANCE,LEAVE_ENCASHED,HRMS_LEAVE_ENCASH_DTL.ENCASH_AMOUNT  "
					+ " FROM HRMS_LEAVE_ENCASH_HDR "
					+ " LEFT JOIN HRMS_LEAVE_ENCASH_DTL ON(HRMS_LEAVE_ENCASH_DTL.ENCASH_CODE=HRMS_LEAVE_ENCASH_HDR.ENCASH_CODE) "
					+ " LEFT JOIN HRMS_LEAVE ON(HRMS_LEAVE.LEAVE_ID=HRMS_LEAVE_ENCASH_DTL.LEAVE_CODE) "
					+ " INNER JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=HRMS_LEAVE_ENCASH_HDR.EMP_ID)  "
					+ " WHERE EMP_ID=? ";

		case 2:
			return " SELECT HRMS_EMP_OFFC.EMP_TOKEN, "
					+ " HRMS_EMP_OFFC.EMP_FNAME||' '||HRMS_EMP_OFFC.EMP_MNAME||' '||HRMS_EMP_OFFC.EMP_LNAME, "
					+ " HRMS_CENTER.CENTER_NAME,HRMS_RANK.RANK_NAME,TO_CHAR(ENCASH_DATE,'DD-MM-YYYY'),HRMS_EMP_OFFC.EMP_ID,HRMS_DEPT.DEPT_NAME  "
					+ " 	FROM HRMS_EMP_OFFC "
					+ " INNER JOIN HRMS_RANK ON HRMS_RANK.RANK_ID = HRMS_EMP_OFFC.EMP_RANK "
					+ " INNER JOIN HRMS_CENTER ON HRMS_CENTER.CENTER_ID = HRMS_EMP_OFFC.EMP_CENTER "
					+ " INNER JOIN HRMS_LEAVE_ENCASH_HDR ON(HRMS_LEAVE_ENCASH_HDR.EMP_ID=HRMS_EMP_OFFC.EMP_ID)"
					+ " INNER JOIN HRMS_DEPT ON (HRMS_DEPT.DEPT_ID = HRMS_EMP_OFFC.EMP_DEPT)"
					+ " WHERE HRMS_EMP_OFFC.EMP_ID=?"
					+ " ORDER BY HRMS_EMP_OFFC.EMP_ID ";

		case 3:
			return " SELECT NVL(ENCASH_STATUS,'P'),ENCASH_LEVEL,ENCASH_APP_CODE  FROM HRMS_LEAVE_ENCASH_HDR WHERE ENCASH_CODE=?";

		case 4:
			return " SELECT HRMS_EMP_OFFC.EMP_TOKEN, "
					+ "	HRMS_EMP_OFFC.EMP_FNAME||' '||HRMS_EMP_OFFC.EMP_MNAME||' '||HRMS_EMP_OFFC.EMP_LNAME, "
					+ "	HRMS_CENTER.CENTER_NAME,HRMS_RANK.RANK_NAME,HRMS_EMP_OFFC.EMP_ID,EMP_TYPE,HRMS_DEPT.DEPT_NAME  "
					+ "	FROM HRMS_EMP_OFFC "
					+ "	INNER JOIN HRMS_RANK ON HRMS_RANK.RANK_ID = HRMS_EMP_OFFC.EMP_RANK "
					+ "	INNER JOIN HRMS_CENTER ON HRMS_CENTER.CENTER_ID = HRMS_EMP_OFFC.EMP_CENTER "
					+ " INNER JOIN HRMS_DEPT ON (HRMS_DEPT.DEPT_ID = HRMS_EMP_OFFC.EMP_DEPT)"
					+ " WHERE HRMS_EMP_OFFC.EMP_ID=?";

		default:
			return " QUERY COULD NOT FIND";
		}
	}

}
