package org.paradyne.sql.leave;

import org.paradyne.lib.SqlBase;

public class LeaveEncashApprovalModelSql extends SqlBase {

	public String getQuery(int id) {
		switch (id) {

		case 1:
			return " SELECT	ENCASH_CODE,HRMS_LEAVE_ENCASH_HDR.EMP_ID,EMP_FNAME||' '||EMP_LNAME ,"
					+ " TO_CHAR(ENCASH_DATE,'DD-MM-YYYY') "
					+ "	,ENCASH_STATUS	,ENCASH_LEVEL,HRMS_EMP_OFFC.EMP_TOKEN "
					+ "	FROM 	HRMS_LEAVE_ENCASH_HDR "
					+ " INNER JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=HRMS_LEAVE_ENCASH_HDR.EMP_ID)"
					+ "	  WHERE  ENCASH_STATUS=?  AND (APPROVED_BY=? OR LEAVE_ALTER_APPROVER=?) ORDER BY ENCASH_CODE DESC ";

		case 2:
			return " INSERT INTO HRMS_LEAVE_ENCASH_PATH(ENCASH_PATH_ID,ENCASH_CODE,ENCASH_ASSESED_BY,ENCASH_STATUS,ENCASH_ASSESS_DATE,ENCASH_COMMENTS) "
					+ "  VALUES((SELECT NVL(MAX(ENCASH_PATH_ID),0)+1 FROM HRMS_LEAVE_ENCASH_PATH),?,?,?,TO_DATE(TO_CHAR(SYSDATE,'DD-MM-YYYY'),'DD-MM-YYYY'),?) ";

		case 3:
			return " UPDATE HRMS_LEAVE_ENCASH_HDR SET ENCASH_STATUS=? WHERE ENCASH_CODE=?";

		case 4:
			return " UPDATE HRMS_LEAVE_ENCASH_HDR SET ENCASH_LEVEL=?,APPROVED_BY=?,LEAVE_ALTER_APPROVER=? WHERE ENCASH_CODE=? ";

		case 5:
			return " UPDATE HRMS_LEAVE_ENCASH_HDR SET ENCASH_STATUS=?, ENCASH_LEVEL = 0 WHERE ENCASH_CODE=?";

		default:
			return "QUERY NOT FOUND";

		}
	}
}