package org.paradyne.sql.leave;

import org.paradyne.lib.SqlBase;
/**
 * @author radha
 * 
 */

/** UpdatedBy
 * @author Prajakta.Bhandare
 * @date 26 Dec 2012
 */
public class LeaveBalanceModelSql extends SqlBase {

	public String getQuery(int id) {
		switch (id) {

		case 1:
			return "SELECT LEAVE_ID,TO_CHAR(LEAVE_NAME)  FROM HRMS_LEAVE ";

		
		case 2:
			return " SELECT LEAVE_ID,TO_CHAR(LEAVE_NAME) ,NVL(LEAVE_OPENING_BALANCE,0),NVL(LEAVE_CLOSING_BALANCE,0),NVL(LEAVE_ONHOLD,0)  "
					+ " NVL(TO_CHAR(LEAVE_HRS_OPENING_BALANCE, 'HH24:MI'),'00:00 '), NVL(TO_CHAR(LEAVE_HRS_CLOSING_BALANCE, 'HH24:MI'),'00:00 '), NVL(TO_CHAR(LEAVE_HRS_ONHOLD, 'HH24:MI'),'00:00 ') "
					+ " FROM HRMS_LEAVE "
					+ "	 LEFT JOIN HRMS_LEAVE_BALANCE ON(HRMS_LEAVE.LEAVE_ID=HRMS_LEAVE_BALANCE.LEAVE_CODE AND EMP_ID = ?)"
					+ "	  INNER JOIN HRMS_LEAVE_POLICY ON (HRMS_LEAVE.LEAVE_ID = HRMS_LEAVE_POLICY.LEAVE_CODE "
					+ "	 AND HRMS_LEAVE_POLICY.EMP_TYPE = (SELECT EMP_TYPE FROM HRMS_EMP_OFFC WHERE EMP_ID =?) )"
					+ "		 WHERE  HRMS_LEAVE_POLICY.LEAVE_APPLICABLE ='Y' ORDER BY HRMS_LEAVE.LEAVE_ID ";

		case 3:
			return "INSERT INTO HRMS_LEAVE_BALANCE (EMP_ID,LEAVE_CODE,LEAVE_OPENING_BALANCE,LEAVE_CLOSING_BALANCE,LEAVE_ONHOLD"
				+ " ,LEAVE_HRS_OPENING_BALANCE, LEAVE_HRS_CLOSING_BALANCE, LEAVE_HRS_ONHOLD )"	
				+ "VALUES(?,?,?,?,?, TO_DATE(?, 'HH24:MI'), TO_DATE(?, 'HH24:MI'), TO_DATE(?, 'HH24:MI'))";

		case 4:
			return "DELETE FROM HRMS_LEAVE_BALANCE WHERE EMP_ID=?";

		case 5:
			return "SELECT  LEAVE_ID,TO_CHAR(LEAVE_NAME) ,NVL(LEAVE_OPENING_BALANCE,0),"
					+ "	NVL(LEAVE_CLOSING_BALANCE,0),EMP_ID,TO_CHAR(HRMS_TITLE.TITLE_NAME||' '||HRMS_EMP_OFFC.EMP_FNAME||' '||HRMS_EMP_OFFC.EMP_MNAME||' '||HRMS_EMP_OFFC.EMP_LNAME),NVL(LEAVE_ONHOLD,0),  "
					+ " NVL(TO_CHAR(LEAVE_HRS_OPENING_BALANCE, 'HH24:MI'),' 00:00'), NVL(TO_CHAR(LEAVE_HRS_CLOSING_BALANCE, 'HH24:MI'),'00:00 '), NVL(TO_CHAR(LEAVE_HRS_ONHOLD, 'HH24:MI'),'00:00 ') "
					+ " FROM HRMS_LEAVE "
					+ "  LEFT JOIN HRMS_LEAVE_BALANCE ON(HRMS_LEAVE.LEAVE_ID=HRMS_LEAVE_BALANCE.LEAVE_CODE AND EMP_ID = ?)"
					+ "	LEFT JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=HRMS_LEAVE_BALANCE.EMP_ID )"
					+ "	LEFT JOIN HRMS_TITLE ON HRMS_TITLE.TITLE_CODE = HRMS_EMP_OFFC.EMP_TITLE_CODE "
					+ "	ORDER BY LEAVE_ID ";

		case 6:
			return " SELECT  DISTINCT EMP_ID,HRMS_TITLE.TITLE_NAME||' '||HRMS_EMP_OFFC.EMP_FNAME||' '||HRMS_EMP_OFFC.EMP_MNAME||' '||HRMS_EMP_OFFC.EMP_LNAME, "
					+ " EMP_RANK,TO_CHAR(RANK_NAME),EMP_CENTER,TO_CHAR(CENTER_NAME) "
					+ " FROM HRMS_EMP_OFFC  "
					+ " INNER JOIN HRMS_CENTER ON(HRMS_CENTER.CENTER_ID=HRMS_EMP_OFFC.EMP_CENTER)"
					+ "	INNER JOIN HRMS_RANK ON HRMS_RANK.RANK_ID = HRMS_EMP_OFFC.EMP_RANK "
					+ "	LEFT JOIN HRMS_TITLE ON HRMS_TITLE.TITLE_CODE = HRMS_EMP_OFFC.EMP_TITLE_CODE "
					+ " WHERE HRMS_EMP_OFFC.EMP_ID = ? ";

		default:
			return " Query could not find";
		}
	}
}