/**
 * 
 */
package org.paradyne.sql.leave;

import org.paradyne.lib.SqlBase;

/**
 * @author lakkichand and Pradeep
 * 
 */
public class LeavePolicyModelSql extends SqlBase {

	public String getQuery(int id) {
		switch (id) {
		case 1:
			return " INSERT  INTO HRMS_LEAVE_POLICY (LEAVE_CODE,LEAVE_APPLICABLE,LEAVE_CREDIT_INTERVAL,LEAVE_CARRY_FORWARD,"
					+ " LEAVE_ENCASH_FLAG,LEAVE_ENTITLEMENT,LEAVE_MAX_BALANCE,LEAVE_ENCASH_FORMULA,LEAVE_HOLIDAY_INCLUDE_FLAG,LEAVE_WEEKOFF_INCLUDE_FLAG,LEAVE_CONSECUTIVE_FLAG,LEAVE_ENCASH_MAX_LIMIT,LEAVE_POLICY_CODE,LEAVE_MIN_BALANCE,LEAVE_ZERO_BALANCE,LEAVE_ADVANCE,LEAVE_HALF_LEAVE,LEAVE_MONTH_BALANCE,LEAVE_PAID_UNPAID,LEAVE_CONSECUTIVE_NAME,LEAVE_POLICY_GENDER,LEAVE_POLICY_CREDIT_TYPE )"
					+ " VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

		case 2:
			return " UPDATE  HRMS_LEAVE_POLICY  SET LEAVE_APPLICABLE = ?, "
					+ " LEAVE_CREDIT_INTERVAL=?,LEAVE_CARRY_FORWARD=?,  LEAVE_ENCASH_FLAG =? ,LEAVE_ENTITLEMENT=?,"
					+ " LEAVE_MAX_BALANCE=?,LEAVE_ENCASH_FORMULA= ?,LEAVE_HOLIDAY_INCLUDE_FLAG =?,LEAVE_WEEKOFF_INCLUDE_FLAG=?,LEAVE_CONSECUTIVE_FLAG=?,LEAVE_ENCASH_MAX_LIMIT =? "
					+ " WHERE EMP_TYPE=? AND LEAVE_CODE=?";

		case 3:
			return " SELECT HRMS_LEAVE.LEAVE_ID, HRMS_LEAVE.LEAVE_NAME ,NVL(LEAVE_APPLICABLE,'N'),"
					+ "  LEAVE_CREDIT_INTERVAL ,"
					+ " NVL(LEAVE_CARRY_FORWARD,'N')"
					+ ",NVL(LEAVE_ENCASH_FLAG,'N'),NVL(LEAVE_ENTITLEMENT,0),NVL(LEAVE_MAX_BALANCE,0),NVL(LEAVE_MIN_BALANCE,0),NVL(LEAVE_ENCASH_FORMULA,' '),NVL(LEAVE_HOLIDAY_INCLUDE_FLAG,'N'),NVL(LEAVE_WEEKOFF_INCLUDE_FLAG,'N'),NVL(LEAVE_CONSECUTIVE_FLAG,' '),NVL(LEAVE_ENCASH_MAX_LIMIT,0), "
					+ " NVL(LEAVE_ZERO_BALANCE,'N'),NVL(LEAVE_ADVANCE,'N'), NVL(LEAVE_HALF_LEAVE,'N'),NVL(LEAVE_MONTH_BALANCE,0),LEAVE_PAID_UNPAID,NVL(LEAVE_CONSECUTIVE_NAME,' '),LEAVE_POLICY_GENDER,LEAVE_POLICY_CREDIT_TYPE FROM HRMS_LEAVE "
					+ " LEFT JOIN HRMS_LEAVE_POLICY ON (HRMS_LEAVE.LEAVE_ID=HRMS_LEAVE_POLICY.LEAVE_CODE AND HRMS_LEAVE_POLICY.LEAVE_POLICY_CODE = ? )"
					+ " ORDER BY HRMS_LEAVE.LEAVE_ID";
	case 4:
			return " SELECT EMP_TYPE FROM HRMS_LEAVE_POLICY WHERE EMP_TYPE=?";

		case 5:
			return " DELETE FROM HRMS_LEAVE_POLICY_HDR WHERE LEAVE_POLICY_CODE=?";
			
		case 6:
			return " DELETE FROM HRMS_LEAVE_POLICY_DTL WHERE LEAVE_POLICY_CODE=? ";
			
		case 7:
			return " DELETE FROM HRMS_LEAVE_POLICY_ENTITLE WHERE LEAVE_POLICY_CODE=? ";
		case 8:
			return " DELETE FROM HRMS_LEAVE_POLICY_UNPLAN_RULE WHERE LEAVE_POLICY_CODE=? ";

		default:
			return "";
		}
	}
}
