/*Bhushan Dasare Sep 8, 2009*/

package org.paradyne.sql.payroll.salary;

import org.paradyne.lib.SqlBase;

public class UploadSalaryModelSql extends SqlBase {
	public String getQuery(int queryId) {
		switch(queryId) {
			case 1 : return " INSERT INTO HRMS_UPLOAD_SALARY_SETTING (UPLOAD_COLUMN_EMP_TOKEN, UPLOAD_COLUMN_TOTAL_CREDIT, " +
			" UPLOAD_COLUMN_TOTAL_DEBIT, UPLOAD_COLUMN_NET_SALARY, UPLOAD_COLUMN_SALARY_DAYS) " + 
			" VALUES (?, ?, ?, ?, ?) ";
			
			case 2 : return " INSERT INTO HRMS_UPLOAD_SALARY_SETTING_DTL (UPLOAD_COLUMN_SALARY_HEAD, UPLOAD_COLUMN_NUMBER, " +
			" UPLOAD_COLUMN_SALARY_TYPE) VALUES (?, ?, ?) ";
			
			case 3 : return " SELECT UPLOAD_COLUMN_EMP_TOKEN, UPLOAD_COLUMN_TOTAL_CREDIT, UPLOAD_COLUMN_TOTAL_DEBIT, " +
			" UPLOAD_COLUMN_NET_SALARY, UPLOAD_COLUMN_SALARY_DAYS FROM HRMS_UPLOAD_SALARY_SETTING ";
			
			case 4 : return " SELECT UPLOAD_COLUMN_SALARY_HEAD, UPLOAD_COLUMN_NUMBER, UPLOAD_COLUMN_SALARY_TYPE " +
			" FROM HRMS_UPLOAD_SALARY_SETTING_DTL ORDER BY UPLOAD_COLUMN_SALARY_TYPE, UPLOAD_COLUMN_SALARY_HEAD ";
			
			case 5 : return " SELECT CREDIT_CODE, CREDIT_ABBR FROM HRMS_CREDIT_HEAD " +
			" WHERE CREDIT_PERIODICITY = 'M' AND CREDIT_PAYFLAG = 'Y' ORDER BY CREDIT_CODE ";
			
			case 6 : return " SELECT DEBIT_CODE, DEBIT_ABBR FROM HRMS_DEBIT_HEAD " +
			" WHERE DEBIT_PERIODICITY = 'M' AND DEBIT_PAYFLAG = 'Y' ORDER BY DEBIT_CODE ";
			
			case 7 : return " DELETE FROM HRMS_UPLOAD_SALARY_SETTING_DTL ";
			
			case 8 : return " DELETE FROM HRMS_UPLOAD_SALARY_SETTING ";
			
			case 9 : return " SELECT LEDGER_CODE FROM HRMS_SALARY_LEDGER WHERE LEDGER_MONTH = ? AND LEDGER_YEAR = ? " +
			" AND LEDGER_DIVISION = ? ";
			
			case 10 : return " SELECT NVL(MAX(LEDGER_CODE), 0) + 1 AS LEDGER_CODE FROM HRMS_SALARY_LEDGER ";
			
			case 11 : return " INSERT INTO HRMS_SALARY_LEDGER (LEDGER_CODE, LEDGER_MONTH, LEDGER_YEAR, LEDGER_DIVISION, LEDGER_STATUS) " + 
			" VALUES (?, ?, ?, ?, 'SAL_FINAL') ";
			
			case 12 : return " UPDATE HRMS_SALARY_LEDGER SET LEDGER_STATUS = 'SAL_FINAL' WHERE LEDGER_CODE = ? ";
			
			default : return "";
		}
	}
}