package org.paradyne.sql.payroll.bonus;

import org.paradyne.lib.SqlBase;

/**Created on 17th Jan 2012.
 * @author aa1380
 *
 */
public class BonusAllowanceModelSql extends SqlBase {

	/**Method : getQuery.
	 * Purpose : this method is used to execute requested query from given query ID
	 * @return String
	 * @param id : given Query ID
	 */
	public String getQuery(final int id) {
		switch (id) {
		    case 1:
			    return "SELECT HRMS_BONUS_HDR.BONUS_CODE, DECODE(HRMS_BONUS_HDR.BONUS_FROM_MONTH,'1','Jan','2','Feb','3','Mar','4','Apr','5','May','6','Jun','7','Jul','8','Aug','9','Sept','10','Oct','11','Nov','12','Dec')||''||HRMS_BONUS_HDR.BONUS_FROM_YEAR||'-'|| DECODE(HRMS_BONUS_HDR.BONUS_TO_MONTH,'1','Jan','2','Feb','3','Mar','4','Apr','5','May','6','Jun','7','Jul','8','Aug','9','Sept','10','Oct','11','Nov','12','Dec')||''||HRMS_BONUS_HDR.BONUS_TO_YEAR, " + 
					" TO_CHAR(HRMS_BONUS_HDR.BONUS_PROCESS_DATE,'DD-MM-YYYY'), HRMS_DIVISION.DIV_ID, HRMS_DIVISION.DIV_NAME, " + 
					" HRMS_BONUS_HDR.PAYBILL_CODE, NVL(HRMS_BONUS_HDR.BONUS_TOTAL_AMT,0.0) , NVL(HRMS_BONUS_HDR.BONUS_EMP_COUNT,0.0) , " + 
					" DECODE(HRMS_BONUS_HDR.PAY_MONTH,'1','Jan','2','Feb','3','Mar','4','Apr','5','May','6','Jun','7','Jul','8','Aug','9', " + 
					" 'Sept','10','Oct','11','Nov','12','Dec')||''||HRMS_BONUS_HDR.PAY_YEAR , DECODE(HRMS_BONUS_HDR.BONUS_STATUS,'L','Lock','U','Unlock') " + 
					" FROM HRMS_BONUS_HDR " + 
					" LEFT JOIN HRMS_DIVISION ON (HRMS_DIVISION.DIV_ID = HRMS_BONUS_HDR.DIV_CODE) " + 
					" ORDER BY TO_DATE(HRMS_BONUS_HDR.BONUS_PROCESS_DATE,'DD-MM-YYYY') DESC";

		    case 2:
		    	    return "INSERT INTO HRMS_BONUS_HDR(HRMS_BONUS_HDR.BONUS_CODE, HRMS_BONUS_HDR.BONUS_FROM_MONTH, HRMS_BONUS_HDR.BONUS_FROM_YEAR, " + 
					" HRMS_BONUS_HDR.BONUS_TO_MONTH, HRMS_BONUS_HDR.BONUS_TO_YEAR, HRMS_BONUS_HDR.PAY_IN_SAL, HRMS_BONUS_HDR.PAY_MONTH, HRMS_BONUS_HDR.PAY_YEAR,  " + 
					" HRMS_BONUS_HDR.PAY_CREDIT_CODE, HRMS_BONUS_HDR.DEDUCT_TAX, HRMS_BONUS_HDR.SYSTEM_CAL_FLAG, HRMS_BONUS_HDR.MANUALLY_CAL_FLAG,  " + 
					" HRMS_BONUS_HDR.PAID_DAY_FLAG, HRMS_BONUS_HDR.BONUS_FORMULA, HRMS_BONUS_HDR.SLAB_WISE_FLAG, HRMS_BONUS_HDR.INDIVIDUAL_FLAG,  " + 
					" HRMS_BONUS_HDR.FLAT_RATE_FLAG, HRMS_BONUS_HDR.FLAT_RATE, HRMS_BONUS_HDR.BONUS_MAX_AMT, HRMS_BONUS_HDR.BONUS_MIN_AMT,  " + 
					" HRMS_BONUS_HDR.BONUS_STATUS, HRMS_BONUS_HDR.DIV_CODE, HRMS_BONUS_HDR.BRANCH_CODE, HRMS_BONUS_HDR.PAYBILL_CODE, HRMS_BONUS_HDR.DEPT_CODE,  " + 
					" HRMS_BONUS_HDR.BONUS_TOTAL_AMT, HRMS_BONUS_HDR.BONUS_PROCESS_DATE,EMP_CODE)  " + 
					" VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, SYSDATE,?)";
		    case 3:
			    return "UPDATE HRMS_BONUS_HDR SET HRMS_BONUS_HDR.BONUS_FROM_MONTH=?, HRMS_BONUS_HDR.BONUS_FROM_YEAR=?, " + 
					" HRMS_BONUS_HDR.BONUS_TO_MONTH=?, HRMS_BONUS_HDR.BONUS_TO_YEAR=?, HRMS_BONUS_HDR.PAY_IN_SAL=?, HRMS_BONUS_HDR.PAY_MONTH=?, HRMS_BONUS_HDR.PAY_YEAR=?, " + 
					" HRMS_BONUS_HDR.PAY_CREDIT_CODE=?, HRMS_BONUS_HDR.DEDUCT_TAX=?, HRMS_BONUS_HDR.SYSTEM_CAL_FLAG=?, HRMS_BONUS_HDR.MANUALLY_CAL_FLAG=?, " + 
					" HRMS_BONUS_HDR.PAID_DAY_FLAG=?, HRMS_BONUS_HDR.BONUS_FORMULA=?, HRMS_BONUS_HDR.SLAB_WISE_FLAG=?, HRMS_BONUS_HDR.INDIVIDUAL_FLAG=?, " + 
					" HRMS_BONUS_HDR.FLAT_RATE_FLAG=?, HRMS_BONUS_HDR.FLAT_RATE=?, HRMS_BONUS_HDR.BONUS_MAX_AMT=?, HRMS_BONUS_HDR.BONUS_MIN_AMT=?, " + 
					" HRMS_BONUS_HDR.BONUS_STATUS=?, HRMS_BONUS_HDR.DIV_CODE=?, HRMS_BONUS_HDR.BRANCH_CODE=?, HRMS_BONUS_HDR.PAYBILL_CODE=?, HRMS_BONUS_HDR.DEPT_CODE=?, " + 
					" HRMS_BONUS_HDR.BONUS_TOTAL_AMT=?, HRMS_BONUS_HDR.BONUS_PROCESS_DATE=SYSDATE,EMP_CODE=? WHERE HRMS_BONUS_HDR.BONUS_CODE=?";
		    case 4:
		    	    return "DELETE FROM HRMS_BONUS_EMP WHERE HRMS_BONUS_EMP.EMP_ID = ? AND HRMS_BONUS_EMP.BONUS_CODE = ?";

		    case 5:
			    return "INSERT INTO HRMS_BONUS_EMP(HRMS_BONUS_EMP.BONUS_CODE, HRMS_BONUS_EMP.EMP_ID, HRMS_BONUS_EMP.EMP_BONUS_TOTAL, HRMS_BONUS_EMP.BONUS_TAX_AMT, HRMS_BONUS_EMP.EMP_BONUS_AMT,BONUS_RATING) VALUES (?, ?, ?, ?, ?,?)";

		    case 6:
		    	    return "UPDATE HRMS_BONUS_HDR SET HRMS_BONUS_HDR.BONUS_STATUS = ? WHERE HRMS_BONUS_HDR.BONUS_CODE = ?";

		    case 7:
		    	    return "SELECT HRMS_BONUS_HDR.BONUS_CODE, HRMS_BONUS_HDR.BONUS_FROM_MONTH, HRMS_BONUS_HDR.BONUS_FROM_YEAR, " + 
					" HRMS_BONUS_HDR.BONUS_TO_MONTH, HRMS_BONUS_HDR.BONUS_TO_YEAR, HRMS_BONUS_HDR.PAY_IN_SAL, " + 
					" HRMS_BONUS_HDR.PAY_MONTH, HRMS_BONUS_HDR.PAY_YEAR, HRMS_BONUS_HDR.PAY_CREDIT_CODE, HRMS_CREDIT_HEAD.CREDIT_ABBR, HRMS_CREDIT_HEAD.CREDIT_NAME, " + 
					" HRMS_BONUS_HDR.DEDUCT_TAX, HRMS_BONUS_HDR.SYSTEM_CAL_FLAG, HRMS_BONUS_HDR.MANUALLY_CAL_FLAG, " + 
					" HRMS_BONUS_HDR.PAID_DAY_FLAG, HRMS_BONUS_HDR.BONUS_FORMULA, HRMS_BONUS_HDR.SLAB_WISE_FLAG, " + 
					" HRMS_BONUS_HDR.INDIVIDUAL_FLAG, HRMS_BONUS_HDR.FLAT_RATE_FLAG, HRMS_BONUS_HDR.FLAT_RATE, " + 
					" HRMS_BONUS_HDR.BONUS_MAX_AMT, HRMS_BONUS_HDR.BONUS_MIN_AMT, " + 
					" HRMS_BONUS_HDR.BONUS_STATUS, HRMS_BONUS_HDR.DIV_CODE, HRMS_BONUS_HDR.BRANCH_CODE,  " + 
					" HRMS_BONUS_HDR.PAYBILL_CODE, HRMS_BONUS_HDR.DEPT_CODE,NVL(HRMS_BONUS_HDR.EMP_CODE,0),TO_CHAR(HRMS_EMP_OFFC.EMP_FNAME||' '||HRMS_EMP_OFFC.EMP_MNAME||'  '||HRMS_EMP_OFFC.EMP_LNAME) FROM HRMS_BONUS_HDR " + 
					" LEFT JOIN HRMS_CREDIT_HEAD ON (HRMS_CREDIT_HEAD.CREDIT_CODE = HRMS_BONUS_HDR.PAY_CREDIT_CODE) " + 
					" LEFT JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=HRMS_BONUS_HDR.EMP_CODE)  " + 
					" WHERE HRMS_BONUS_HDR.BONUS_CODE = ? ";

		    case 8:
			    return "INSERT INTO HRMS_BONUS_EMP(HRMS_BONUS_EMP.BONUS_CODE, HRMS_BONUS_EMP.EMP_ID, HRMS_BONUS_EMP.BONUS_RATING, HRMS_BONUS_EMP.BONUS_TAX_AMT, HRMS_BONUS_EMP.EMP_BONUS_TOTAL, HRMS_BONUS_EMP.EMP_BONUS_AMT) VALUES (?, ?, ?, ?, ?, ?)";

		    case 9:
			    return "INSERT INTO HRMS_BONUS_SLAB(HRMS_BONUS_SLAB.BONUS_CODE, HRMS_BONUS_SLAB.BONUS_FROM_AMT, HRMS_BONUS_SLAB.BONUS_TO_AMT, HRMS_BONUS_SLAB.BOMUS_PERSENTAGE, HRMS_BONUS_SLAB.BONUS_MIN_AMT, HRMS_BONUS_SLAB.BONUS_MAX_AMT)" + 
					" VALUES (?, ?, ?, ?, ?, ?)";

		    case 10:
			    return "SELECT HRMS_BONUS_EMP.EMP_ID, HRMS_EMP_OFFC.EMP_TOKEN, HRMS_EMP_OFFC.EMP_FNAME||' '||HRMS_EMP_OFFC.EMP_LNAME, NVL(HRMS_BONUS_EMP.EMP_BONUS_AMT,0.0), NVL(HRMS_BONUS_EMP.BONUS_TAX_AMT,0.0), NVL(HRMS_BONUS_EMP.EMP_BONUS_TOTAL,0.0) FROM HRMS_BONUS_EMP " + 
					" INNER JOIN HRMS_EMP_OFFC ON (HRMS_EMP_OFFC.EMP_ID = HRMS_BONUS_EMP.EMP_ID) " + 
					" WHERE HRMS_BONUS_EMP.BONUS_CODE = ? ORDER BY HRMS_EMP_OFFC.EMP_FNAME||' '||HRMS_EMP_OFFC.EMP_LNAME ASC";

		    case 11:
		    	    return "DELETE FROM HRMS_BONUS_EMP WHERE HRMS_BONUS_EMP.EMP_ID IN (?) AND HRMS_BONUS_EMP.BONUS_CODE = ?";

		    case 12:
		    	    return "INSERT INTO HRMS_BONUS_EMP(HRMS_BONUS_EMP.BONUS_CODE, HRMS_BONUS_EMP.EMP_ID, HRMS_BONUS_EMP.EMP_BONUS_AMT, HRMS_BONUS_EMP.BONUS_TAX_AMT, HRMS_BONUS_EMP.EMP_BONUS_TOTAL) VALUES (?, ?, ?, ?, ?)";

		    case 13:
			    return "UPDATE HRMS_BONUS_HDR SET HRMS_BONUS_HDR.BONUS_TOTAL_AMT = " + 
					"(SELECT SUM(HRMS_BONUS_EMP.EMP_BONUS_AMT) FROM HRMS_BONUS_EMP WHERE HRMS_BONUS_EMP.BONUS_CODE = ?)," + 
					" HRMS_BONUS_HDR.BONUS_EMP_COUNT = " + 
					"(SELECT COUNT(*) FROM HRMS_BONUS_EMP WHERE HRMS_BONUS_EMP.BONUS_CODE = ?)" + 
					" WHERE HRMS_BONUS_HDR.BONUS_CODE = ?";

		    default:
		    	    return "Framework could not EXECUTE the query number specified";
		}
	}

}
