/**
 * 
 */
package org.paradyne.sql.appraisal;

import org.paradyne.lib.SqlBase;

/**
 * @author prakashs
 * 
 */
public class EmpAppraisalModelSql extends SqlBase {

	public String getQuery(int code) {

		switch (code) {

		case 1:
			return " SELECT HRMS_EMP_OFFC.EMP_TOKEN ,(HRMS_TITLE.TITLE_NAME||' '||HRMS_EMP_OFFC.EMP_FNAME||' '||HRMS_EMP_OFFC.EMP_MNAME|| ' ' || HRMS_EMP_OFFC.EMP_LNAME), "
					+ " NVL(HRMS_RANK.RANK_NAME,' '),NVL(HRMS_DEPT.DEPT_NAME,' '), NVL(HRMS_CENTER.CENTER_NAME,''), "
					+ " RANK_ID,CENTER_ID ,DEPT_ID , HRMS_EMP_OFFC.EMP_ID,NVL(TO_CHAR(HRMS_EMP_OFFC.EMP_REGULAR_DATE,'DD-MM-YYYY'),' '), "
					+ " (T1.TITLE_NAME||' '||EMP1.EMP_FNAME||' '||EMP1.EMP_MNAME|| ' ' || EMP1.EMP_LNAME) FROM HRMS_EMP_OFFC "
					+ " LEFT JOIN HRMS_RANK ON(HRMS_EMP_OFFC.EMP_RANK=HRMS_RANK.RANK_ID) "
					+ " LEFT JOIN HRMS_CENTER ON(HRMS_EMP_OFFC.EMP_CENTER=HRMS_CENTER.CENTER_ID) "
					+ " LEFT JOIN HRMS_TITLE ON(HRMS_EMP_OFFC.EMP_TITLE_CODE=HRMS_TITLE.TITLE_CODE) "
					+ " INNER JOIN HRMS_EMP_OFFC EMP1 ON(EMP1. EMP_ID=HRMS_EMP_OFFC. EMP_REPORTING_OFFICER)"
					+ " LEFT JOIN HRMS_TITLE T1 ON(EMP1.EMP_TITLE_CODE=T1.TITLE_CODE) "
					+ " LEFT JOIN HRMS_DEPT ON(HRMS_EMP_OFFC.EMP_DEPT=HRMS_DEPT.DEPT_ID) "
					+ " WHERE HRMS_EMP_OFFC.EMP_ID = ?  AND HRMS_EMP_OFFC.EMP_STATUS!='R'";

		case 2:
			return " SELECT HRMS_APPRFACT.APPRFACT_CODE,APPRFACT_NAME,APPRFACT_WEIGHTAGE  FROM  HRMS_APPRFACT "
					+ " left join HRMS_APPRCONFIG_FACT on (HRMS_APPRCONFIG_FACT.APPRFACT_CODE = HRMS_APPRFACT.APPRFACT_CODE ) "
					+ " WHERE APPRFACT_TYPE = 'K' and DESG_ID = (SELECT EMP_RANK FROM HRMS_EMP_OFFC WHERE EMP_ID = ? ) order by HRMS_APPRFACT.APPRFACT_CODE ";

		case 3:
			return " SELECT RATINGS , RATINGS_VAL FROM HRMS_APPRFACT_DTL WHERE APPRFACT_CODE = ? ";

		case 4:
			return " SELECT HRMS_APPRFACT.APPRFACT_CODE,APPRFACT_NAME,APPRFACT_WEIGHTAGE  FROM  HRMS_APPRFACT "
					+ " left join HRMS_APPRCONFIG_FACT on (HRMS_APPRCONFIG_FACT.APPRFACT_CODE = HRMS_APPRFACT.APPRFACT_CODE ) "
					+ " WHERE APPRFACT_TYPE = 'P' and DESG_ID = (SELECT EMP_RANK FROM HRMS_EMP_OFFC WHERE EMP_ID = ? ) order by HRMS_APPRFACT.APPRFACT_CODE ";

		case 5:
			return " SELECT HRMS_APPRFACT.APPRFACT_CODE,APPRFACT_NAME  FROM  HRMS_APPRFACT "
					+ " left join HRMS_APPRCONFIG_FACT on (HRMS_APPRCONFIG_FACT.APPRFACT_CODE = HRMS_APPRFACT.APPRFACT_CODE ) "
					+ " WHERE APPRFACT_TYPE = 'S' and DESG_ID = (SELECT EMP_RANK FROM HRMS_EMP_OFFC WHERE EMP_ID = ? ) order by HRMS_APPRFACT.APPRFACT_CODE ";
			//return " SELECT APPRFACT_CODE,APPRFACT_NAME  FROM  HRMS_APPRFACT WHERE APPRFACT_TYPE = 'S'";

		case 6:
			return " INSERT INTO HRMS_APPRAISAL(APPR_CODE,APPR_EMP_ID,APPR_BRN,APPR_DEPT,APPR_DESG,APPR_FROM,APPR_TO,APPR_DATE ,APPR_APPRAISEES_COMMENT,CONF_CODE,APPR_STATUS,APPR_HOD_LEVEL  )"
					+ " VALUES ((SELECT NVL(MAX(APPR_CODE),0)+1 FROM HRMS_APPRAISAL ),?,  ?  , ?, ? , TO_DATE(?,'DD-MM-YYYY') ,TO_DATE(?,'DD-MM-YYYY') ,TO_DATE(?,'DD-MM-YYYY'), ? , ? ,'P','0' )";

		case 7:
			return " INSERT INTO HRMS_APPRAISAL_KRA (NET_SCORE , KRA_APPRAISERS_RATING , APPRFACT_CODE , APPR_CODE )VALUES ( ? , ? , ? , ? )";

		case 8:
			return " INSERT INTO HRMS_APPRAISAL_PERS_TRAIT (TRAIT_NETSCORE , TRAIT_APPRAISERS_RATING , APPRFACT_CODE , APPR_CODE) VALUES ( ? , ? , ? , ?  )";

		case 9:
			return " INSERT INTO HRMS_APPRAISAL_SELF( SELF_COMMENT , APPRFACT_CODE , APPR_CODE ) VALUES( ? , ? , ? )";

		case 10:
			return " UPDATE HRMS_APPRAISAL SET APPR_EMP_STRENGTH = ? ,APPR_EMP_IMPROVEMENT = ?,APPR_EMP_NEXT_ROLE = ? , APPR_TRN_TECHNICALSKILL = ? ,"
					+ " APPR_TRN_SOFTSKILL = ? , APPR_TRN_MET = ? ,APPR_APPRAISERS_COMMENT = ? ,APPR_TRN_YES = ? , APPR_TRN_NO = ?  WHERE APPR_CODE = ? ";

		case 11:
			return " INSERT INTO HRMS_APPRAISAL_TRAINING(TRAINING_TYPE,TRAINING_DESCRIPTION,TRAINING_DURATION,TRAINING_SPONSEREDBY,TRAINING_CODE,APPR_CODE) VALUES( ?,?,?,?,?,?)";

		case 12:
			return " UPDATE HRMS_APPRAISAL_KRA SET KRA_SELF_COMMENT = ? ,KRA_SELF_RATING = ?  WHERE APPRFACT_CODE = ? AND APPR_CODE = ? ";

		case 13:
			return " UPDATE HRMS_APPRAISAL_PERS_TRAIT SET TRAIT_SELF_COMMENT = ? ,TRAIT_SELF_RATING = ?  WHERE APPRFACT_CODE = ? AND APPR_CODE = ? ";

		case 14:
			return " UPDATE HRMS_APPRAISAL_SELF SET   SELF_COMMENT = ?  WHERE APPRFACT_CODE = ? AND APPR_CODE = ? ";

		case 15:
			return " UPDATE HRMS_APPRAISAL SET APPR_APPRAISEES_COMMENT = ? , APPR_DESG = ?  WHERE APPR_CODE = ? ";

		case 16:
			return " UPDATE HRMS_APPRAISAL_TRAINING set TRAINING_TYPE = ? ,TRAINING_DESCRIPTION = ? ,TRAINING_DURATION = ? ,TRAINING_SPONSEREDBY = ? where TRAINING_CODE = ? and APPR_CODE = ? ";

		case 17:
			return " UPDATE HRMS_APPRAISAL_KRA set NET_SCORE = ? , KRA_APPRAISERS_RATING = ?  where APPRFACT_CODE = ? and APPR_CODE = ? ";

		case 18:
			return " UPDATE HRMS_APPRAISAL_PERS_TRAIT set TRAIT_NETSCORE = ? ,TRAIT_APPRAISERS_RATING = ? where APPRFACT_CODE = ? and APPR_CODE = ? ";

		case 19:
			return " SELECT EMP_DESG FROM HRMS_EMP_OFFC WHERE EMP_ID = ? ";

			/*case 20 : return " SELECT PRD_START_YEAR,PRD_END_YEAR,TO_CHAR(START_DATE,'DD-MM-YYYY'),TO_CHAR(END_DATE,'DD-MM-YYYY'),CONF_CODE FROM HRMS_APPRCONFIG_PRD_HDR " 
							+" WHERE TO_DATE(SYSDATE,'DD-MM-YYYY') BETWEEN  TO_DATE(START_DATE,'DD-MM-YYYY') AND TO_DATE(END_DATE,'DD-MM-YYYY') "
							+" AND CONF_CODE = (SELECT MAX(CONF_CODE) FROM HRMS_APPRCONFIG_PRD_HDR )";
			 */

		case 20:
			return " SELECT PRD_START_YEAR,PRD_END_YEAR,TO_CHAR(HRMS_APPRAISAL_SCHEDULE.START_DATE,'DD-MM-YYYY'),TO_CHAR(HRMS_APPRAISAL_SCHEDULE.END_DATE,'DD-MM-YYYY'),HRMS_APPRCONFIG_PRD_HDR.CONF_CODE "
					+ " FROM HRMS_APPRCONFIG_PRD_HDR "
					+ " INNER join HRMS_APPRAISAL_SCHEDULE on (HRMS_APPRCONFIG_PRD_HDR.CONF_CODE =HRMS_APPRAISAL_SCHEDULE.CONF_CODE) "
					+ " WHERE TO_DATE(SYSDATE,'DD-MM-YYYY') BETWEEN  TO_DATE(HRMS_APPRAISAL_SCHEDULE.START_DATE,'DD-MM-YYYY') AND TO_DATE(HRMS_APPRAISAL_SCHEDULE.END_DATE,'DD-MM-YYYY') "
					+ " AND HRMS_APPRCONFIG_PRD_HDR.CONF_CODE = (SELECT MAX(CONF_CODE) FROM HRMS_APPRCONFIG_PRD_HDR ) and APP_TYPE =  ? ";

		case 21:
			return " INSERT INTO HRMS_APPRAISAL_PATH (APPR_CODE,APPROVER_CODE,APPR_DATE) values(?,?,TO_DATE(sysdate,'DD-MM-YYYY'))";

		case 22:
			return " SELECT HRMS_EMP_OFFC.EMP_TOKEN ,(HRMS_TITLE.TITLE_NAME||' '||HRMS_EMP_OFFC.EMP_FNAME||' '||HRMS_EMP_OFFC.EMP_MNAME|| ' ' || HRMS_EMP_OFFC.EMP_LNAME),  NVL(HRMS_RANK.RANK_NAME,' '),NVL(HRMS_DEPT.DEPT_NAME,' '), "
					+ " nvl(hrms_center.CENTER_NAME,''),RANK_ID,CENTER_ID,DEPT_ID,APPR_EMP_ID,NVL(TO_CHAR(HRMS_EMP_OFFC.EMP_REGULAR_DATE,'DD-MM-YYYY '),' ') , "
					+ " nvl(APPR_APPRAISEES_COMMENT,''),APPR_CODE ,"
					+ " NVL(APPR_EMP_STRENGTH,''),NVL(APPR_EMP_IMPROVEMENT,''),NVL(APPR_EMP_NEXT_ROLE,''),NVL(APPR_TRN_TECHNICALSKILL,''),NVL(APPR_TRN_SOFTSKILL,''),NVL(APPR_TRN_MET,''),NVL(APPR_APPRAISERS_COMMENT,''),"
					+ " HRMS_APPRAISAL.CONF_CODE,TO_CHAR(APPR_DATE,'DD-MM-YYYY'),nvl(APPR_TRN_YES,''),nvl(APPR_TRN_NO,''),(T1.TITLE_NAME||' '||EMP1.EMP_FNAME||' '||EMP1.EMP_MNAME|| ' ' || EMP1.EMP_LNAME) FROM HRMS_APPRAISAL "
					+ " left join HRMS_EMP_OFFC on(HRMS_EMP_OFFC.EMP_ID = HRMS_APPRAISAL.APPR_EMP_ID ) "
					+ " LEFT JOIN HRMS_RANK ON(HRMS_APPRAISAL.APPR_DESG=HRMS_RANK.RANK_ID) "
					+ " LEFT JOIN HRMS_CENTER ON(HRMS_APPRAISAL.APPR_BRN=HRMS_CENTER.CENTER_ID) "
					+ " LEFT JOIN HRMS_TITLE ON(HRMS_EMP_OFFC.EMP_TITLE_CODE=HRMS_TITLE.TITLE_CODE) "
					+ " LEFT JOIN HRMS_DEPT ON(HRMS_APPRAISAL.APPR_DEPT=HRMS_DEPT.DEPT_ID) "
					+ " INNER JOIN HRMS_EMP_OFFC EMP1 ON(EMP1.EMP_ID=HRMS_APPRAISAL.APPR_HOD_CODE )"
					+ " LEFT JOIN HRMS_TITLE T1 ON(EMP1.EMP_TITLE_CODE=T1.TITLE_CODE) "
					//+ " left join HRMS_APPRCONFIG_PRD_DTL on (HRMS_EMP_OFFC.EMP_ID = HRMS_APPRCONFIG_PRD_DTL.EMP_ID) "
					//+ " left join HRMS_APPRCONFIG_PRD_hdr on (HRMS_APPRCONFIG_PRD_HDR.CONF_CODE = HRMS_APPRCONFIG_PRD_DTL.CONF_CODE) "
					+ " WHERE HRMS_APPRAISAL.APPR_CODE = ? ";

		case 23 : return "INSERT INTO HRMS_APPRAISAL_LOGS (USER_EMPID,TYPE,APPR_EMP,CHANGEDATE) VALUES(?,?,?,SYSDATE)";
		
		
		default:
			return " ";
		}

	}

}
