package org.paradyne.sql.Asset;

import org.paradyne.lib.SqlBase;

public class AssetTypeModelSql extends SqlBase {
	public String getQuery(int id) {
		switch(id) {
		/*case 1: return "INSERT INTO HRMS_ASSET_CATEGORY(ASSET_CATEGORY_CODE,ASSET_CATEGORY_NAME,ASSET_CATEGORY_TYPE,ASSET_CATEGORY_UNIT)" 
                      	+"VALUES(NVL((SELECT MAX(ASSET_CATEGORY_CODE) FROM HRMS_ASSET_CATEGORY),0)+1,?,?,?)"; 
		case 2: return " UPDATE HRMS_ASSET_CATEGORY SET ASSET_CATEGORY_NAME =? ,ASSET_CATEGORY_TYPE=?,ASSET_CATEGORY_UNIT=? WHERE ASSET_CATEGORY_CODE =? " ;
 
		case 3: return " DELETE FROM HRMS_ASSET_CATEGORY WHERE ASSET_CATEGORY_CODE = ?";
		
		case 4 :return " SELECT ASSET_CATEGORY_NAME FROM HRMS_ASSET_CATEGORY";
		z
		case 5: return " DELETE FROM HRMS_ASSET_CATEGORY WHERE ASSET_CATEGORY_CODE = ?";
		
		case 6: return " SELECT ASSET_CATEGORY_CODE,ASSET_CATEGORY_NAME,DECODE(ASSET_CATEGORY_TYPE,'R','Returnable','N','Non-Returnable') FROM HRMS_ASSET_CATEGORY ORDER BY ASSET_CATEGORY_CODE ";*/
		
		case 1: return "INSERT INTO HRMS_ASSET_CATEGORY(ASSET_CATEGORY_CODE,ASSET_CATEGORY_NAME,ASSET_ISACTIVE)" 
      					+"VALUES(NVL((SELECT MAX(ASSET_CATEGORY_CODE) FROM HRMS_ASSET_CATEGORY),0)+1,?,?)"; 
		
		case 2: return " UPDATE HRMS_ASSET_CATEGORY SET ASSET_CATEGORY_NAME =?,ASSET_ISACTIVE=? WHERE ASSET_CATEGORY_CODE =? " ;

		case 3: return " DELETE FROM HRMS_ASSET_CATEGORY WHERE ASSET_CATEGORY_CODE = ?";

		case 4 :return " SELECT ASSET_CATEGORY_NAME FROM HRMS_ASSET_CATEGORY";

		case 5: return " DELETE FROM HRMS_ASSET_CATEGORY WHERE ASSET_CATEGORY_CODE = ?";

		case 6: return " SELECT ASSET_CATEGORY_CODE,ASSET_CATEGORY_NAME,CASE WHEN ASSET_ISACTIVE ='Y' THEN 'Yes' ELSE 'No' END FROM HRMS_ASSET_CATEGORY ORDER BY ASSET_CATEGORY_CODE ";
		
		default : return "Framework could not the query number specified";			
		}
	}

}
