package org.paradyne.sql.Asset;

import org.paradyne.lib.SqlBase;

public class AssetMasterModelSql extends SqlBase {
public String getQuery(int id){
	switch (id) {
	
						
	case 1: return "INSERT INTO HRMS_ASSET_MASTER(ASSET_MASTER_CODE,ASSET_PURCHASE_DATE,ASSET_CATEGORY_CODE,ASSET_PURCHASE_PRICE,ASSET_DESCRIPTION,ASSET_SUBTYPE_CODE, "
					+" ASSET_QUANTITY,ASSET_ASSIGNED,ASSET_AVAILABLE,ASSET_VENDOR,ASSET_STATUS) "
					+ " VALUES(NVL((SELECT MAX(ASSET_MASTER_CODE) FROM HRMS_ASSET_MASTER),0)+1,TO_DATE(?,'DD-MM-YYYY'),?,?,?,?,?,?,?,?,'U')";
 	
	case 2: return "  UPDATE HRMS_ASSET_MASTER SET ASSET_PURCHASE_DATE=TO_DATE(?,'DD-MM-YYYY'),"
					+ " ASSET_CATEGORY_CODE=?,ASSET_PURCHASE_PRICE=?,ASSET_DESCRIPTION=?, ASSET_SUBTYPE_CODE=?, ASSET_QUANTITY =? , "
					+" ASSET_AVAILABLE =? ,ASSET_VENDOR =? WHERE ASSET_MASTER_CODE =?  " ;
	
	case 3: return "DELETE FROM HRMS_ASSET_MASTER WHERE ASSET_MASTER_CODE=?";
	
	case 4: return "SELECT ASSET_MASTER_CODE,TO_CHAR(ASSET_PURCHASE_DATE,'DD-MM-YYYY'),HRMS_ASSET_MASTER.ASSET_CATEGORY_CODE,ASSET_CATEGORY_NAME,NVL(ASSET_PURCHASE_PRICE,'')," +
					" NVL(ASSET_DESCRIPTION,''),HRMS_ASSET_MASTER.ASSET_SUBTYPE_CODE,ASSET_SUBTYPE_NAME,ASSET_QUANTITY,ASSET_AVAILABLE,ASSET_ASSIGNED,ASSET_VENDOR,VENDOR_NAME,"
					+" ASSET_STATUS,ASSET_INVENTORY_TYPE FROM HRMS_ASSET_MASTER " 
					+" INNER JOIN HRMS_ASSET_CATEGORY ON(HRMS_ASSET_CATEGORY.ASSET_CATEGORY_CODE = HRMS_ASSET_MASTER.ASSET_CATEGORY_CODE )"
					+" LEFT JOIN HRMS_ASSET_SUBTYPE ON(HRMS_ASSET_SUBTYPE.ASSET_SUBTYPE_CODE=HRMS_ASSET_MASTER.ASSET_SUBTYPE_CODE) "
					+" LEFT JOIN HRMS_VENDOR ON(HRMS_VENDOR.VENDOR_CODE=HRMS_ASSET_MASTER.ASSET_VENDOR and VENDOR_TYPE='S' ) "
					+" WHERE ASSET_MASTER_CODE=?";
	
	case 5 : return "INSERT INTO HRMS_ASSET_MASTER_DTL(ASSET_MASTER_CODE,ASSET_INVENTORY_CODE,ASSET_WAREHOUSE_CODE,ASSET_ASSISGN_FLAG,ASSET_QUANTITY,ASSET_AVAILABLE,"
					+"ASSET_IS_ON_LEASE,ASSET_LEASE_RENEW_DATE,ASSET_IS_INSURED,ASSET_INSURANCE_RENEW_DATE ,ASSET_ITEM_CODE)"
					+" VALUES(?,?,?,?,?,?,?,TO_DATE(?,'DD-MM-YYYY'),?,TO_DATE(?,'DD-MM-YYYY'),?)";
	
	default : return "Framework could not the query number specified";			
	}
	
}

}
