/**
 * 
 */
package org.paradyne.sql.Asset;

import org.paradyne.lib.SqlBase;

/**
 * @author mangeshj
 *
 */
public class AssetApprovalModelSql extends SqlBase {
	public String getQuery(int id){
		switch (id) {
		case 1: return "SELECT ASSET_APPL_CODE,EMP_TOKEN,HRMS_EMP_OFFC.EMP_FNAME||' '||HRMS_EMP_OFFC.EMP_MNAME|| ' ' || "
						+" HRMS_EMP_OFFC.EMP_LNAME,ASSET_EMP_ID,TO_CHAR(ASSET_APPL_DATE,'DD-MM-YYYY'),ASSET_APPL_LEVEL,ASSET_STATUS " 
						+" ,ASSET_APPL_NO FROM HRMS_ASSET_APPLICATION "
						+" INNER JOIN HRMS_EMP_OFFC ON (HRMS_EMP_OFFC.EMP_ID=HRMS_ASSET_APPLICATION.ASSET_EMP_ID)"
						+" WHERE ASSET_STATUS=? AND (ASSET_APPL_APPROVER= ? OR ASSET_ALTER_APPROVER=?) ";
		case 2 : return "UPDATE HRMS_ASSET_APPLICATION SET ASSET_APPL_LEVEL = ?, ASSET_APPL_APPROVER = ? ,ASSET_ALTER_APPROVER=? WHERE ASSET_APPL_CODE = ? ";	
		
		case 3 : return "UPDATE HRMS_ASSET_APPLICATION SET ASSET_STATUS = ? WHERE ASSET_APPL_CODE = ?";
		
		case 4 : return "INSERT INTO HRMS_ASSET_PATH (ASSET_APPL_CODE, ASSET_APPROVER, ASSET_APPR_DATE, ASSET_APPL_COMMENTS, ASSET_PATH_STATUS,ASSET_PATH_ID) " 
						+" VALUES(?, ?, TO_DATE(TO_CHAR(SYSDATE,'DD-MM-YYYY'),'DD-MM-YYYY'), ?, ?,(SELECT (NVL(MAX (ASSET_PATH_ID),0)+1) FROM HRMS_ASSET_PATH WHERE ASSET_APPL_CODE=?  ))";

		case 5: return "SELECT ASSET_APPL_CODE,EMP_TOKEN,HRMS_EMP_OFFC.EMP_FNAME||' '||HRMS_EMP_OFFC.EMP_MNAME|| ' ' || "
						+" HRMS_EMP_OFFC.EMP_LNAME,ASSET_EMP_ID,TO_CHAR(ASSET_APPL_DATE,'DD-MM-YYYY'),ASSET_APPL_LEVEL,ASSET_STATUS " 
						+" ,ASSET_APPL_NO FROM HRMS_ASSET_APPLICATION "
						+" INNER JOIN HRMS_EMP_OFFC ON (HRMS_EMP_OFFC.EMP_ID=HRMS_ASSET_APPLICATION.ASSET_EMP_ID)"
						+" WHERE (ASSET_APPL_APPROVER= ? OR ASSET_ALTER_APPROVER=?) AND (ASSET_STATUS='A' OR ASSET_STATUS='S')" ;
		
		case 6 : return "UPDATE HRMS_ASSET_APPLICATION SET ASSET_STATUS = ?, ASSET_APPL_LEVEL=? WHERE ASSET_APPL_CODE = ?";

		default : return "Framework could not the query number specified";
			
		}
	}
}
