/**
 * 
 */
package org.paradyne.sql.Asset;

import org.paradyne.lib.SqlBase;

/**
 * @author mangeshj
 *
 */
public class PurchaseOrderModelSql extends SqlBase {
	public String getQuery(int id) {
		switch (id) {

		case 1:
			return "INSERT INTO HRMS_ASSET_PURCHASE_HDR(PURCHASE_CODE,PURCHASE_EMP_CODE,PURCHASE_ORDER_DATE,PURCHASE_APPROVER_ID,PURCHASE_COMMENTS,PURCHASE_STATUS,INWARD_STATUS,PURCHASE_ALTER_APPROVER,PURCHASE_VENDOR_CODE,PURCHASE_ORDER_NAME,PURCHASE_REQUIRED_DATE,PURCHASE_SHIPPING_ADDRESS,PURCHASE_BILLING_ADDRESS,PURCHASE_COST_CENTER,PURCHASE_SUBCOST_CENTER,PURCHASE_REMARKS,PURCHASE_TERMS,PURCHASE_SUBTOTAL, PURCHASE_DISCOUNT, PURCHASE_DISCOUNT_AMT, PURCHASE_AFTER_DISCOUNT, PURCHASE_SHIPPING_COST, PURCHASE_SALE_TAX_PERCENTAGE, PURCHASE_SALE_TAX_AMOUNTE, PURCHASE_ADDITIONAL_TAX_RATE, PURCHASE_ADDITIONAL_TAX_AMT, PURCHASE_PRICE_ADJUSTMENT, PURCHASE_FINAL_AMOUNT,PURCHASE_ADJUSTMENT_SIGN) VALUES "
					+ " ((SELECT NVL(MAX(PURCHASE_CODE),0)+1 FROM HRMS_ASSET_PURCHASE_HDR),?,TO_DATE(?,'DD-MM-YYYY'),?,?,?,'PE',?,?,?,TO_DATE(?,'DD-MM-YYYY'),?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

		case 2:
			return "INSERT INTO HRMS_ASSET_PURCHASE_DTL(PURCHASE_CODE,PURCHASE_ASSET_CODE,PURCHASE_ASSET_QUANTITY, "
					+ " PURCHASE_ASSET_PRICE,PURCHASE_STATUS,PURCHASE_DTL_CODE) VALUES(?,?,?,?,'PE',?)";

		case 3:
			return " UPDATE HRMS_ASSET_PURCHASE_HDR SET PURCHASE_EMP_CODE=?, PURCHASE_ORDER_DATE=TO_DATE(?,'DD-MM-YYYY'),"
					+ " PURCHASE_APPROVER_ID=?,PURCHASE_COMMENTS=?,PURCHASE_ALTER_APPROVER=?,PURCHASE_VENDOR_CODE=?,PURCHASE_STATUS=?,PURCHASE_ORDER_NAME = ?, PURCHASE_REQUIRED_DATE = TO_DATE(?,'DD-MM-YYYY'), PURCHASE_SHIPPING_ADDRESS=?, PURCHASE_BILLING_ADDRESS = ?, PURCHASE_COST_CENTER=?, PURCHASE_SUBCOST_CENTER=?, PURCHASE_REMARKS=?, PURCHASE_TERMS=?, PURCHASE_SUBTOTAL=?, PURCHASE_DISCOUNT=?, PURCHASE_DISCOUNT_AMT=?, PURCHASE_AFTER_DISCOUNT=?, PURCHASE_SHIPPING_COST=?, PURCHASE_SALE_TAX_PERCENTAGE=?, PURCHASE_SALE_TAX_AMOUNTE=?, PURCHASE_ADDITIONAL_TAX_RATE=?, PURCHASE_ADDITIONAL_TAX_AMT=?, PURCHASE_PRICE_ADJUSTMENT=?, PURCHASE_FINAL_AMOUNT=?,PURCHASE_ADJUSTMENT_SIGN=? WHERE PURCHASE_CODE=? ";

		case 4:
			return "SELECT  DISTINCT PURCHASE_ASSET_CODE,ASSET_SUBTYPE_NAME,PURCHASE_ASSET_PRICE,UNIT_NAME, "
					+ " PURCHASE_ASSET_QUANTITY FROM HRMS_ASSET_PURCHASE_DTL "
					//+" INNER JOIN HRMS_VENDOR ON(HRMS_VENDOR.VENDOR_CODE=HRMS_ASSET_PURCHASE_DTL.PURCHASE_VENDOR_CODE) "
					+ " INNER JOIN HRMS_ASSET_SUBTYPE ON(HRMS_ASSET_SUBTYPE.ASSET_SUBTYPE_CODE=HRMS_ASSET_PURCHASE_DTL.PURCHASE_ASSET_CODE) "
					+ " INNER JOIN HRMS_UNIT_MASTER ON (HRMS_UNIT_MASTER.UNIT_CODE=HRMS_ASSET_SUBTYPE.ASSET_SUBTYPE_UNIT) "
					//+" INNER JOIN HRMS_LOCATION ON (HRMS_LOCATION.LOCATION_CODE=HRMS_VENDOR.VENDOR_CITY) "
					+ " WHERE HRMS_ASSET_PURCHASE_DTL.PURCHASE_CODE=?";

		case 5:
			return "SELECT NVL(PURCHASE_COMMENTS,''),CASE WHEN PURCHASE_STATUS='P' AND PURCHASE_LEVEL!=1   THEN 'F' ELSE "
					+ "PURCHASE_STATUS END,PURCHASE_APPROVER_ID,PURCHASE_ORDER_NO,HRMS_ASSET_PURCHASE_HDR.PURCHASE_VENDOR_CODE,VENDOR_ADDRESS,VENDOR_CONTACT_NO,PURCHASE_COST_CENTER,COST_CENTER_NAME, "
					+ "SUB_COST_CENTER_ID,SUB_COST_CENTER_NAME,HRMS_ASSET_PURCHASE_HDR.PURCHASE_SHIPPING_ADDRESS, "
					+ "HRMS_ASSET_PURCHASE_HDR.PURCHASE_BILLING_ADDRESS,HRMS_ASSET_PURCHASE_HDR.PURCHASE_REMARKS, "
					+ "HRMS_ASSET_PURCHASE_HDR.PURCHASE_TERMS ,PURCHASE_ORDER_NO,PURCHASE_ORDER_NAME,TO_CHAR(PURCHASE_REQUIRED_DATE,'DD-MM-YYYY'),NVL(PURCHASE_SUBTOTAL,'0'), NVL(PURCHASE_DISCOUNT,'0'), NVL(PURCHASE_DISCOUNT_AMT,'0'), NVL(PURCHASE_AFTER_DISCOUNT,'0'), NVL(PURCHASE_SHIPPING_COST,'0'), NVL(PURCHASE_SALE_TAX_PERCENTAGE,'0'), NVL(PURCHASE_SALE_TAX_AMOUNTE,'0'), NVL(PURCHASE_ADDITIONAL_TAX_RATE,'0'), NVL(PURCHASE_ADDITIONAL_TAX_AMT,'0'), NVL(PURCHASE_PRICE_ADJUSTMENT,'0'), NVL(PURCHASE_FINAL_AMOUNT,'0'),PURCHASE_ADJUSTMENT_SIGN"
					+ " FROM HRMS_ASSET_PURCHASE_HDR "
					+ "LEFT JOIN HRMS_VENDOR ON (HRMS_ASSET_PURCHASE_HDR.PURCHASE_VENDOR_CODE=HRMS_VENDOR.VENDOR_CODE) "
					+ "LEFT JOIN HRMS_COST_CENTER ON (HRMS_ASSET_PURCHASE_HDR.PURCHASE_COST_CENTER=HRMS_COST_CENTER.COST_CENTER_ID) "
					+ "LEFT JOIN HRMS_SUB_COST_CENTER "
					+ "ON (HRMS_ASSET_PURCHASE_HDR.PURCHASE_COST_CENTER=HRMS_SUB_COST_CENTER.COST_CENTER_ID) "
					+ "WHERE PURCHASE_CODE=?	";

		case 6:
			return "SELECT PURCHASE_ASSET_CODE,ASSET_SUBTYPE_NAME,PURCHASE_ASSET_PRICE,UNIT_NAME, "
					+ " PURCHASE_ASSET_QUANTITY,PURCHASE_DTL_CODE FROM HRMS_ASSET_PURCHASE_DTL "
					//+" INNER JOIN HRMS_VENDOR ON(HRMS_VENDOR.VENDOR_CODE=HRMS_ASSET_PURCHASE_DTL.PURCHASE_VENDOR_CODE) "
					+ " INNER JOIN HRMS_ASSET_SUBTYPE ON(HRMS_ASSET_SUBTYPE.ASSET_SUBTYPE_CODE=HRMS_ASSET_PURCHASE_DTL.PURCHASE_ASSET_CODE) "
					+ " INNER JOIN HRMS_UNIT_MASTER ON (HRMS_UNIT_MASTER.UNIT_CODE=HRMS_ASSET_SUBTYPE.ASSET_SUBTYPE_UNIT) "
					//	+" INNER JOIN HRMS_LOCATION ON (HRMS_LOCATION.LOCATION_CODE=HRMS_VENDOR.VENDOR_CITY) "
					+ " WHERE HRMS_ASSET_PURCHASE_DTL.PURCHASE_CODE=? AND PURCHASE_STATUS=?";

		case 7:
			return " UPDATE HRMS_ASSET_PURCHASE_HDR SET PURCHASE_VENDOR_CODE=? WHERE PURCHASE_CODE=? ";

		case 8:
			return " UPDATE HRMS_ASSET_PURCHASE_HDR SET PURCHASE_STATUS=? WHERE PURCHASE_CODE=? ";

		default:
			return "Framework could not the query number specified";
		}

	}
}
