/**
 * 
 */
package org.paradyne.sql.Asset;

import org.paradyne.lib.SqlBase;

/**
 * @author mangeshj
 *
 */
public class WareHouseModelSql extends SqlBase {
	
	public String getQuery(int id){
		switch (id) {
		case 1: return " INSERT INTO HRMS_WAREHOUSE_MASTER(WAREHOUSE_CODE,WAREHOUSE_NAME,WAREHOUSE_RESPONSIBLE_PERSON,WAREHOUSE_IS_CENTRALIZE,WAREHOUSE_ISACTIVE) " 
						+" VALUES((SELECT NVL(MAX(WAREHOUSE_CODE),0) +1 FROM HRMS_WAREHOUSE_MASTER),?,?,?,?)";
		case 2 : return "UPDATE HRMS_WAREHOUSE_MASTER SET WAREHOUSE_NAME = ?, WAREHOUSE_RESPONSIBLE_PERSON = ?,WAREHOUSE_IS_CENTRALIZE=?,WAREHOUSE_ISACTIVE=? "
						+" WHERE WAREHOUSE_CODE = ? ";	
		
		case 3 : return "DELETE FROM HRMS_WAREHOUSE_BRANCH WHERE WAREHOUSE_CODE= ?";
		
		case 4 : return " INSERT INTO HRMS_WAREHOUSE_BRANCH (WAREHOUSE_CODE, WAREHOUSE_BRANCH) " 
						+ " VALUES(?, ?)";
		
		case 5 : return " SELECT WAREHOUSE_BRANCH,CENTER_NAME FROM HRMS_WAREHOUSE_BRANCH "
						+ " INNER JOIN HRMS_CENTER ON(HRMS_CENTER.CENTER_ID=HRMS_WAREHOUSE_BRANCH.WAREHOUSE_BRANCH) "
						+ " WHERE WAREHOUSE_CODE=?";
		
		case 6 :return " DELETE FROM HRMS_WAREHOUSE_MASTER WHERE WAREHOUSE_CODE =?";
		
		case 7 :return  " SELECT WAREHOUSE_CODE,WAREHOUSE_NAME,HRMS_EMP_OFFC.EMP_FNAME||' '||HRMS_EMP_OFFC.EMP_MNAME|| ' ' || HRMS_EMP_OFFC.EMP_LNAME,"
			+ " WAREHOUSE_RESPONSIBLE_PERSON,EMP_TOKEN,CASE WHEN WAREHOUSE_ISACTIVE ='Y' THEN 'Yes' ELSE 'No' END FROM HRMS_WAREHOUSE_MASTER "
			+ " INNER JOIN HRMS_EMP_OFFC ON (HRMS_EMP_OFFC.EMP_ID=HRMS_WAREHOUSE_MASTER.WAREHOUSE_RESPONSIBLE_PERSON) "
			+ " ORDER BY WAREHOUSE_CODE";

		default : return "Framework could not the query number specified";
			
		}
	}
}
