package org.paradyne.sql.TravelManagement.TravelClaim;

import org.paradyne.lib.SqlBase;

/**
 * @author aa0651
 * 
 */
public class TmsClaimApplicationModelSql extends SqlBase {
	public String getQuery(int id) {

		switch (id) {

		// SCHEDULED TRAVEL LIST
		/*
		 * case 1: return " SELECT DISTINCT
		 * TMS_APPLICATION.APPL_ID,TMS_APP_EMPDTL.APPL_CODE, NVL(APPL_TRVL_ID,'
		 * '), APPL_INITIATOR , " + " NVL(EMP_FNAME||' '||EMP_MNAME||'
		 * '||EMP_LNAME,' ') AS INITIATOR, NVL(C1.EMP_FNAME,' ')||'
		 * '||NVL(C1.EMP_MNAME,' ')||' '||NVL(C1.EMP_LNAME,' ') AS APPLICANT, " + "
		 * TO_CHAR(TMS_APPLICATION.APPL_DATE,'DD-MM-YYYY') ,
		 * TO_CHAR(TOUR_TRAVEL_ENDDT,'DD-MM-YYYY'), " + "
		 * TOUR_TRAVEL_REQ_NAME,TMS_APP_EMPDTL.APPL_EMP_CODE,
		 * TO_DATE(TO_CHAR(SYSDATE,'DD-MM-YYYY'),'DD-MM-YYYY') - " + "
		 * TO_DATE(TO_CHAR(TOUR_TRAVEL_ENDDT,'DD-MM-YYYY'),'DD-MM-YYYY') AS
		 * DUEDAYS ,APPL_FOR_FLAG FROM TMS_APPLICATION " + " LEFT JOIN
		 * TMS_CLAIM_APPL
		 * ON(TMS_CLAIM_APPL.EXP_TRVL_APPID=TMS_APPLICATION.APPL_ID) " + " INNER
		 * JOIN TMS_APP_EMPDTL ON(TMS_APPLICATION.APPL_ID=TMS_APP_EMPDTL.APPL_ID ) " + "
		 * INNER JOIN HRMS_EMP_OFFC C1
		 * ON(TMS_APP_EMPDTL.APPL_EMP_CODE=C1.EMP_ID) " + " INNER JOIN
		 * HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=TMS_APPLICATION.APPL_INITIATOR) " // + "
		 * INNER JOIN HRMS_CENTER
		 * ON(HRMS_EMP_OFFC.EMP_CENTER=HRMS_CENTER.CENTER_ID) " + " INNER JOIN
		 * TMS_POLICY_GRADE_DTL ON (TMS_POLICY_GRADE_DTL.POLICY_GRAD_ID =
		 * C1.EMP_CADRE ) " + " INNER JOIN TMS_TRAVEL_POLICY ON
		 * (TMS_POLICY_GRADE_DTL.POLICY_ID = TMS_TRAVEL_POLICY.POLICY_ID) " + "
		 * WHERE (EXP_APP_EMPID=? AND APPL_STATUS IN('A','C')) AND " + "
		 * TMS_APP_EMPDTL.APPL_TRVL_ID NOT IN " + " (SELECT EXP_TRVL_ID FROM
		 * TMS_CLAIM_APPL WHERE EXP_TRVL_ID IS NOT NULL) " + " AND
		 * (TO_DATE(TO_CHAR(SYSDATE,'DD-MM-YYYY'),'DD-MM-YYYY') -
		 * TO_DATE(TO_CHAR(TOUR_TRAVEL_ENDDT,'DD-MM-YYYY'),'DD-MM-YYYY')) >= 0
		 * AND (TO_DATE(TO_CHAR(SYSDATE,'DD-MM-YYYY'),'DD-MM-YYYY') - " + "
		 * TO_DATE(TO_CHAR(TOUR_TRAVEL_ENDDT,'DD-MM-YYYY'),'DD-MM-YYYY')) <=
		 * MAX_DAYS_SETTLE_TRAVEL_CLAIM ";
		 */
		case 1:
			return "SELECT DISTINCT TMS_APPLICATION.APPL_ID,TMS_APP_EMPDTL.APPL_CODE, NVL(APPL_TRVL_ID,' '),  APPL_INITIATOR , "
					+ " NVL(EMP_FNAME||' '||EMP_MNAME||' '||EMP_LNAME,' ') AS INITIATOR, "
					+ " NVL(C1.EMP_FNAME,' ')||'  '||NVL(C1.EMP_MNAME,' ')||'  '||NVL(C1.EMP_LNAME,' ')  AS APPLICANT, "
					+ " TO_CHAR(TMS_APPLICATION.APPL_DATE,'DD-MM-YYYY') , TO_CHAR(TOUR_TRAVEL_ENDDT,'DD-MM-YYYY'), "
					+ " TOUR_TRAVEL_REQ_NAME,TMS_APP_EMPDTL.APPL_EMP_CODE, "
					+ " TO_DATE(TO_CHAR(SYSDATE,'DD-MM-YYYY'),'DD-MM-YYYY') -  TO_DATE(TO_CHAR(TOUR_TRAVEL_ENDDT,'DD-MM-YYYY'),'DD-MM-YYYY') "
					+ " AS DUEDAYS ,APPL_FOR_FLAG, case when APPL_STATUS='F' then '_'||APPL_STATUS else APPL_STATUS end"
					+ " FROM TMS_APPLICATION "
					+ " INNER JOIN   TMS_APP_EMPDTL ON(TMS_APP_EMPDTL.APPL_ID = TMS_APPLICATION.APPL_ID) "
					+ " LEFT JOIN TMS_CLAIM_APPL ON(TMS_APP_EMPDTL.APPL_ID =TMS_CLAIM_APPL.EXP_TRVL_APPID AND TMS_CLAIM_APPL.EXP_APP_EMPID=TMS_APP_EMPDTL.APPL_EMP_CODE ) "
					+ " INNER JOIN HRMS_EMP_OFFC C1 ON(TMS_APP_EMPDTL.APPL_EMP_CODE=C1.EMP_ID) "
					+ " LEFT JOIN   HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=TMS_APPLICATION.APPL_INITIATOR) "
					+ " LEFT JOIN HRMS_TITLE  ON(HRMS_TITLE.TITLE_CODE=HRMS_EMP_OFFC.EMP_TITLE_CODE) "
					+ " INNER JOIN TMS_POLICY_GRADE_DTL ON (TMS_POLICY_GRADE_DTL.POLICY_GRAD_ID = C1.EMP_CADRE ) "
					+ " INNER JOIN TMS_TRAVEL_POLICY ON (TMS_POLICY_GRADE_DTL.POLICY_ID = TMS_TRAVEL_POLICY.POLICY_ID) "
					+ " WHERE APPL_STATUS IN('A','C','F') AND (APPL_EMP_CODE=? ) "
					+ " AND (TO_DATE(TO_CHAR(SYSDATE,'DD-MM-YYYY'),'DD-MM-YYYY') - TO_DATE(TO_CHAR(TOUR_TRAVEL_ENDDT,'DD-MM-YYYY'),'DD-MM-YYYY')) >= 0 "
					+ " AND (TO_DATE(TO_CHAR(SYSDATE,'DD-MM-YYYY'),'DD-MM-YYYY') -  TO_DATE(TO_CHAR(TOUR_TRAVEL_ENDDT,'DD-MM-YYYY'),'DD-MM-YYYY')) <=  NVL(MAX_DAYS_SETTLE_TRAVEL_CLAIM,0) "
					+ " AND  TMS_CLAIM_APPL.EXP_TRVL_APPID||'_'||TMS_CLAIM_APPL.EXP_APP_EMPID !=TMS_APP_EMPDTL.APPL_ID||'_'||TMS_APP_EMPDTL.APPL_EMP_CODE"
					+ " ORDER BY TO_CHAR(APPL_DATE,'DD-MM-YYYY') DESC";
			/*
			 * + " UNION " + " SELECT DISTINCT
			 * TMS_APPLICATION.APPL_ID,TMS_APP_GUEST_DTL.APPL_CODE,
			 * NVL(APPL_TRVL_ID,' '), APPL_INITIATOR , " + " NVL(EMP_FNAME||'
			 * '||EMP_MNAME||' '||EMP_LNAME,' ') AS INITIATOR, " + "
			 * NVL(GUEST_NAME,' ') AS APPLICANT, " + "
			 * TO_CHAR(TMS_APPLICATION.APPL_DATE,'DD-MM-YYYY') ,
			 * TO_CHAR(TOUR_TRAVEL_ENDDT,'DD-MM-YYYY'), " + "
			 * TOUR_TRAVEL_REQ_NAME,0, " + "
			 * TO_DATE(TO_CHAR(SYSDATE,'DD-MM-YYYY'),'DD-MM-YYYY') -
			 * TO_DATE(TO_CHAR(TOUR_TRAVEL_ENDDT,'DD-MM-YYYY'),'DD-MM-YYYY') " + "
			 * AS DUEDAYS ,APPL_FOR_FLAG " + " FROM TMS_APPLICATION " + " INNER
			 * JOIN TMS_APP_GUEST_DTL ON(TMS_APP_GUEST_DTL.APPL_ID =
			 * TMS_APPLICATION.APPL_ID) " + " LEFT JOIN TMS_CLAIM_APPL
			 * ON(TMS_APP_GUEST_DTL.APPL_ID !=TMS_CLAIM_APPL.EXP_APPID AND
			 * TMS_APP_GUEST_DTL.APPL_TRVL_ID!= TMS_CLAIM_APPL.EXP_TRVL_ID) " + "
			 * LEFT JOIN HRMS_EMP_OFFC
			 * ON(HRMS_EMP_OFFC.EMP_ID=TMS_APPLICATION.APPL_INITIATOR) " + "
			 * LEFT JOIN HRMS_TITLE
			 * ON(HRMS_TITLE.TITLE_CODE=HRMS_EMP_OFFC.EMP_TITLE_CODE) " + "
			 * INNER JOIN TMS_POLICY_GRADE_DTL ON
			 * (TMS_POLICY_GRADE_DTL.POLICY_GRAD_ID = HRMS_EMP_OFFC.EMP_CADRE ) " + "
			 * INNER JOIN TMS_TRAVEL_POLICY ON (TMS_POLICY_GRADE_DTL.POLICY_ID =
			 * TMS_TRAVEL_POLICY.POLICY_ID) " + " WHERE APPL_STATUS IN('A','C')
			 * AND TMS_APPLICATION.APPL_INITIATOR = ? " + " AND
			 * (TO_DATE(TO_CHAR(SYSDATE,'DD-MM-YYYY'),'DD-MM-YYYY') -
			 * TO_DATE(TO_CHAR(TOUR_TRAVEL_ENDDT,'DD-MM-YYYY'),'DD-MM-YYYY')) >=
			 * 0 " + " AND (TO_DATE(TO_CHAR(SYSDATE,'DD-MM-YYYY'),'DD-MM-YYYY') -
			 * TO_DATE(TO_CHAR(TOUR_TRAVEL_ENDDT,'DD-MM-YYYY'),'DD-MM-YYYY')) <=
			 * MAX_DAYS_SETTLE_TRAVEL_CLAIM " + " ORDER BY 1 DESC,2 DESC ";
			 */

		case 2:
			return "SELECT EMP_TOKEN, EMP_FNAME||' '||EMP_MNAME||' '||EMP_LNAME,CENTER_NAME AS BRANCH,DEPT_NAME,RANK_NAME,CADRE_NAME,"
					+ " HRMS_EMP_OFFC.EMP_ID,EMP_CENTER,EMP_DEPT,EMP_RANK,"
					+ " HRMS_EMP_OFFC.EMP_CADRE "
					+ " FROM HRMS_EMP_OFFC "
					+ " LEFT JOIN HRMS_CENTER ON(HRMS_CENTER.CENTER_ID=HRMS_EMP_OFFC.EMP_CENTER)"
					+ " LEFT JOIN HRMS_DEPT ON(HRMS_DEPT.DEPT_ID=HRMS_EMP_OFFC.EMP_DEPT)"
					+ " LEFT JOIN HRMS_RANK ON(HRMS_RANK.RANK_ID=HRMS_EMP_OFFC.EMP_RANK)"
					+ " LEFT JOIN HRMS_CADRE ON(HRMS_CADRE.CADRE_ID=HRMS_EMP_OFFC.EMP_CADRE)"
					+ " LEFT JOIN HRMS_EMP_ADDRESS ON(HRMS_EMP_ADDRESS.EMP_ID=HRMS_EMP_OFFC.EMP_ID AND ADD_TYPE='P')"
					+ " WHERE HRMS_EMP_OFFC.EMP_ID=?";

		case 3:
			return "INSERT INTO TMS_CLAIM_APPL (EXP_APPID,EXP_APP_DATE, EXP_APP_STATUS, EXP_ADV_AMT, EXP_APP_EMPID, EXP_TRVL_START_DATE,"
					+ " EXP_TRVL_END_DATE, EXP_TRVL_PURPOSE, EXP_TRVL_TYPE, EXP_COMMENTS, EXP_TOT_EXPAMT, EXP_TOT_ELIGBLEAMT, EXP_TRVL_APPID, EXP_TRVL_APPCODE,"
					+ " EXP_MAIN_APPRVR, EXP_ALT_APPRVR, EXP_APP_TYPE,EXP_TRVL_REQNAME,EXP_TRVL_ID,EXP_PROJECT_ID, EXP_CUSTOMER_ID, TOUR_REPORT_COMMENTS, TOUR_REPORT_PROOF, ACHIEVEMENT_COMMENTS, FOLLOWUP_COMMENTS, FOLLOWUP_DATE, EXP_ADVANCE_CURRENCY, EXP_CLAIM_CURRENCY)"
					+ " VALUES(?,TO_DATE(?,'DD-MM-YYYY'),?,?,?,TO_DATE(?,'DD-MM-YYYY'),TO_DATE(?,'DD-MM-YYYY'),?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,TO_DATE(?,'DD-MM-YYYY'),?,?)";

		case 4:
			return "INSERT INTO TMS_EXP_DTL(EXP_DTLID,EXP_APPID, EXP_DTL_DATE, EXP_DTL_EXP_TYPE, EXP_DTL_EXP_ELIGBLEAMT, EXP_DTL_EXP_AMT,"
					+ " EXP_DTL_PARTICULARS, EXP_DTL_ISPROOF, EXP_DTL_PROOF,IS_POLICY_VIOLATED, EXP_DTL_CURRENCY) VALUES(?,?,TO_DATE(?,'DD-MM-YYYY'),?,?,?,?,?,?,?,?)";

			/*
			 * case 4: return "INSERT INTO TMS_EXP_DTL(EXP_DTLID,EXP_APPID,
			 * EXP_DTL_DATE, EXP_DTL_EXP_TYPE, EXP_DTL_EXP_ELIGBLEAMT,
			 * EXP_DTL_EXP_AMT," + " EXP_DTL_PARTICULARS, EXP_DTL_ISPROOF)
			 * VALUES(?,?,TO_DATE(?,'DD-MM-YYYY'),?,?,?,?,?)";
			 */

			/*
			 * case 5: return "SELECT EXP_APPID,EXP_TRVL_ID,EMP_FNAME||'
			 * '||EMP_MNAME||' '||EMP_LNAME ,NVL(EXP_TRVL_REQNAME,'')," + "
			 * TO_CHAR(EXP_TRVL_END_DATE,'dd-mm-yyyy'), EXP_TRVL_APPID,
			 * EXP_TRVL_APPCODE , EXP_APP_STATUS, EXP_APP_EMPID" + " FROM
			 * TMS_CLAIM_APPL " + " INNER JOIN HRMS_EMP_OFFC
			 * ON(HRMS_EMP_OFFC.EMP_ID=TMS_CLAIM_APPL.EXP_APP_EMPID)" + " WHERE
			 * EXP_APP_STATUS=? AND EXP_APP_EMPID=?";
			 * 
			 */

			/*
			 * case 5: return " SELECT EXP_APPID,EXP_TRVL_ID,EMP_FNAME||'
			 * '||EMP_MNAME||' '||EMP_LNAME ,NVL(EXP_TRVL_REQNAME,''), " + "
			 * TO_CHAR(EXP_TRVL_END_DATE,'dd-mm-yyyy'), EXP_TRVL_APPID,
			 * EXP_TRVL_APPCODE , EXP_APP_STATUS, EXP_APP_EMPID,
			 * EXP_APP_ADMIN_STATUS, " + " DECODE(EXP_APP_STATUS, 'P','Pending
			 * For Manager Approval','A','Pending For Admin
			 * Approval','N','Draft') " + " FROM TMS_CLAIM_APPL " + " INNER JOIN
			 * HRMS_EMP_OFFC
			 * ON(HRMS_EMP_OFFC.EMP_ID=TMS_CLAIM_APPL.EXP_APP_EMPID) " + " LEFT
			 * JOIN TMS_APPLICATION
			 * ON(TMS_APPLICATION.APPL_ID=TMS_CLAIM_APPL.EXP_TRVL_APPID) " + "
			 * WHERE EXP_APP_STATUS IN ('P','N','B') OR (EXP_APP_STATUS='A' AND
			 * EXP_APP_ADMIN_STATUS='P') " + " AND (EXP_APP_EMPID=? OR
			 * APPL_INITIATOR=?) " + " ORDER BY EXP_TRVL_END_DATE ";
			 * 
			 */

			/*
			 * case 5 : return " SELECT EXP_APPID,EXP_TRVL_ID,EMP_FNAME||'
			 * '||EMP_MNAME||' '||EMP_LNAME ,NVL(EXP_TRVL_REQNAME,''),"+ "
			 * TO_CHAR(EXP_TRVL_END_DATE,'dd-mm-yyyy'), EXP_TRVL_APPID,
			 * EXP_TRVL_APPCODE , EXP_APP_STATUS, "+ " EXP_APP_EMPID,
			 * EXP_APP_ADMIN_STATUS, DECODE(EXP_APP_STATUS, 'P','Pending For
			 * Manager Approval','A',"+ " 'Pending For Admin
			 * Approval','N','Draft', 'B','Sent back for changes') FROM
			 * TMS_CLAIM_APPL "+ " INNER JOIN HRMS_EMP_OFFC
			 * ON(HRMS_EMP_OFFC.EMP_ID=TMS_CLAIM_APPL.EXP_APP_EMPID)"+ " INNER
			 * JOIN TMS_APPLICATION
			 * ON(TMS_APPLICATION.APPL_ID=TMS_CLAIM_APPL.EXP_TRVL_APPID AND
			 * (EXP_APP_EMPID=?))"+ " WHERE EXP_APP_STATUS IN ('P','N','B') OR
			 * (EXP_APP_STATUS='A' AND EXP_APP_ADMIN_STATUS IN('P','B')) "+ "
			 * ORDER BY EXP_TRVL_END_DATE";
			 */

		case 5:
			return "  SELECT EXP_APPID,EXP_TRVL_ID,EMP_FNAME||' '||EMP_MNAME||' '||EMP_LNAME ,NVL(EXP_TRVL_REQNAME,''), "
					+ " TO_CHAR(EXP_TRVL_END_DATE,'dd-mm-yyyy'),  EXP_TRVL_APPID, EXP_TRVL_APPCODE , case when APPL_STATUS='F' then   '_'||APPL_STATUS  else EXP_APP_STATUS end,  "
					+ " EXP_APP_EMPID, EXP_APP_ADMIN_STATUS,   "
					+ " case when APPL_STATUS='F' then   '_'||APPL_STATUS when EXP_APP_STATUS='A' AND EXP_APP_ADMIN_STATUS='B' "
					+ " then DECODE(EXP_APP_ADMIN_STATUS, 'B','Sent back for  changes by admin') "
					+ " when   EXP_APP_STATUS='A' AND EXP_APP_ADMIN_STATUS='R' "
					+ " then DECODE(EXP_APP_ADMIN_STATUS, 'R','Rejected by admin') "
					+ " else  "
					+ " DECODE(EXP_APP_STATUS, 'P','Pending For Manager Approval','A', 'Pending For Admin Approval', "
					+ " 'N','Draft', 'B','Sent back for  changes by manager','M','Sent back acknoledgement')    "
					+ " end FROM TMS_CLAIM_APPL   "
					+ "  INNER JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=TMS_CLAIM_APPL.EXP_APP_EMPID) "
					+ "  INNER JOIN  TMS_APPLICATION ON(TMS_APPLICATION.APPL_ID=TMS_CLAIM_APPL.EXP_TRVL_APPID AND (EXP_APP_EMPID=?))"
					+ "  WHERE EXP_APP_STATUS IN ('P','N','B','M') "
					+ " OR (EXP_APP_STATUS='A' AND EXP_APP_ADMIN_STATUS IN('P','B'))  "
					+ " ORDER BY TO_CHAR(APPL_DATE,'DD-MM-YYYY') DESC";

		case 6:
			return "SELECT EXP_APPID,NVL(EMP_FNAME||' '||EMP_MNAME||' '||EMP_LNAME,''), TO_CHAR(EXP_APP_DATE,'DD-MM-YYYY'), EXP_APP_STATUS, EXP_ADV_AMT, EXP_APP_EMPID,"
					+ " TO_CHAR(EXP_TRVL_START_DATE,'DD-MM-YYYY'), TO_CHAR(TOUR_TRAVEL_ENDDT,'DD-MM-YYYY'), EXP_TRVL_PURPOSE,NVL(HRMS_TMS_PURPOSE.PURPOSE_NAME,''), EXP_TRVL_TYPE, NVL(HRMS_TMS_LOCATION_TYPE.LOCATION_TYPE_NAME,''),NVL(EXP_COMMENTS,''), EXP_TOT_EXPAMT, "
					+ " EXP_TOT_ELIGBLEAMT, EXP_TRVL_APPID, EXP_TRVL_APPCODE,  EXP_APP_TYPE, EXP_APPRVD_AMT, NVL(EXP_TRVL_REQNAME,'') ,"
					+ " NVL(HRMS_CENTER.CENTER_NAME,''),CENTER_ID,NVL(DEPT_NAME,''),  NVL(RANK_NAME,''),CADRE_ID,NVL(CADRE_NAME,''),RANK_ID,DEPT_ID, NVL(TMS_TRAVEL_PROJECT.PROJECT_NAME,'') ,NVL(TMS_TRAVEL_CUSTOMER.TRAVEL_CUST_NAME,'')  "
					+ " ,NVL(JOURNEY_FROM,' '), NVL(TMS_CLAIM_APPL.EXP_ADVANCE_CURRENCY,'') FROM TMS_CLAIM_APPL "
					+ " INNER JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=TMS_CLAIM_APPL.EXP_APP_EMPID) "
					+ " LEFT JOIN HRMS_CENTER ON(HRMS_CENTER.CENTER_ID=HRMS_EMP_OFFC.EMP_CENTER) "
					+ " LEFT JOIN HRMS_DEPT ON(HRMS_DEPT.DEPT_ID=HRMS_EMP_OFFC.EMP_DEPT) "
					+ " LEFT JOIN HRMS_RANK ON(HRMS_RANK.RANK_ID=HRMS_EMP_OFFC.EMP_RANK) "
					+ " LEFT JOIN HRMS_CADRE ON(HRMS_CADRE.CADRE_ID=HRMS_EMP_OFFC.EMP_CADRE) "
					+ " LEFT JOIN HRMS_TMS_LOCATION_TYPE ON(HRMS_TMS_LOCATION_TYPE.LOCATION_TYPE_ID=TMS_CLAIM_APPL.EXP_TRVL_TYPE)"
					+ " LEFT JOIN HRMS_TMS_PURPOSE ON(HRMS_TMS_PURPOSE.PURPOSE_ID=TMS_CLAIM_APPL.EXP_TRVL_PURPOSE)"
					+ " LEFT JOIN HRMS_EMP_ADDRESS ON(HRMS_EMP_ADDRESS.EMP_ID=HRMS_EMP_OFFC.EMP_ID AND ADD_TYPE='P')"
					+ " LEFT JOIN TMS_TRAVEL_PROJECT ON(TMS_TRAVEL_PROJECT.PROJECT_ID=TMS_CLAIM_APPL.EXP_PROJECT_ID)"
					+ " LEFT JOIN TMS_TRAVEL_CUSTOMER ON(TMS_TRAVEL_CUSTOMER.TRAVEL_CUST_ID=TMS_CLAIM_APPL.EXP_CUSTOMER_ID)"
					+ " INNER JOIN TMS_JOURNEY_SRC_DEST_VIEW on (TMS_JOURNEY_SRC_DEST_VIEW.APPL_ID =TMS_CLAIM_APPL.EXP_TRVL_APPID)"
					+ " INNER JOIN TMS_APPLICATION ON (TMS_APPLICATION.APPL_ID = TMS_CLAIM_APPL.EXP_TRVL_APPID)"
					+ " WHERE EXP_APPID=?";

		case 7:
			return " SELECT TO_CHAR(EXP_DTL_DATE,'DD-MM-YYYY') AS EXP_DATE, EXP_DTL_EXP_TYPE, EXP_DTL_EXP_ELIGBLEAMT, EXP_DTL_EXP_AMT,"
					+ "	NVL(EXP_DTL_PARTICULARS,''),HRMS_TMS_EXP_CATEGORY.EXP_CATEGORY_NAME, EXP_DTL_ISPROOF, NVL(EXP_DTL_PROOF,'') "
					+ "	,EXP_DTLID,EXP_APPID,DECODE(IS_POLICY_VIOLATED,'Y','Yes','N','No'), EXP_DTL_CURRENCY  "
					+ " FROM TMS_EXP_DTL"
					+ " INNER JOIN  HRMS_TMS_EXP_CATEGORY ON(HRMS_TMS_EXP_CATEGORY.EXP_CATEGORY_ID=TMS_EXP_DTL.EXP_DTL_EXP_TYPE)"
					+ " WHERE EXP_APPID=?";

		case 8:
			return "UPDATE TMS_CLAIM_APPL SET EXP_APP_STATUS='P' WHERE EXP_APPID=?";

		case 9:
			return "DELETE FROM TMS_EXP_DTL WHERE EXP_APPID=?";

		case 10:
			/*
			 * return "UPDATE TMS_CLAIM_APPL SET EXP_ADV_AMT=?,
			 * EXP_TRVL_START_DATE=TO_DATE(?,'DD-MM-YYYY'),
			 * EXP_TRVL_END_DATE=TO_DATE(?,'DD-MM-YYYY'), EXP_TRVL_PURPOSE=?, " + "
			 * EXP_TRVL_TYPE=?, EXP_COMMENTS=?, EXP_TOT_EXPAMT=?,
			 * EXP_TOT_ELIGBLEAMT=?, EXP_TRVL_REQNAME=?, EXP_APP_STATUS=?,
			 * EXP_PROJECT_ID=?, EXP_CUSTOMER_ID=?" + " WHERE EXP_APPID=?";
			 */
			return " UPDATE TMS_CLAIM_APPL SET  EXP_COMMENTS=?, EXP_TOT_EXPAMT=?, EXP_TOT_ELIGBLEAMT=?, EXP_APP_STATUS=? "
			+",EXP_MAIN_APPRVR=?, EXP_ALT_APPRVR=? WHERE EXP_APPID = ? ";

		case 11:
			return "SELECT EMP_TOKEN,NVL(HRMS_EMP_OFFC.EMP_FNAME,' ')||'  '||NVL(HRMS_EMP_OFFC.EMP_MNAME,' ')||'  '||NVL(HRMS_EMP_OFFC.EMP_LNAME,' ') AS NAME,"
					+ " TO_CHAR(TMS_APPLICATION.APPL_DATE,'DD-MM-YYYY'),NVL(TO_CHAR(TOUR_TRAVEL_STARTDT,'DD-MM-YYYY'),' '),NVL(TO_CHAR(TOUR_TRAVEL_ENDDT,'DD-MM-YYYY'),' '),"
					+ " APPL_EMP_CODE,TMS_APPLICATION.TOUR_TRAVEL_REQ_NAME,NVL(TMS_APP_EMPDTL.APPL_APPROVED_ADVANCE_AMOUNT,0),HRMS_TMS_PURPOSE.PURPOSE_NAME,TMS_APPLICATION.TOUR_TRAVEL_PURPOSE,"
					+ " HRMS_TMS_LOCATION_TYPE.LOCATION_TYPE_ID,HRMS_TMS_LOCATION_TYPE.LOCATION_TYPE_NAME,"
					+ " CENTER_NAME AS BRANCH,DEPT_NAME,RANK_NAME,CADRE_NAME, HRMS_EMP_OFFC.EMP_CADRE, "
					+ " HRMS_EMP_OFFC.EMP_ID,EMP_CENTER,EMP_DEPT,EMP_RANK, PROJECT_ID,TRAVEL_CUST_ID,NVL(TMS_TRAVEL_PROJECT.PROJECT_NAME,'') ,NVL(TMS_TRAVEL_CUSTOMER.TRAVEL_CUST_NAME,'')"
					+ " ,NVL(JOURNEY_FROM,' '), NVL(APPL_CURRENCY,'') FROM TMS_APP_EMPDTL "
					+ " INNER JOIN TMS_APPLICATION ON(TMS_APPLICATION.APPL_ID = TMS_APP_EMPDTL.APPL_ID) "
					+ " INNER JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID = TMS_APP_EMPDTL.APPL_EMP_CODE)"
					+ " INNER JOIN HRMS_TMS_PURPOSE  ON(HRMS_TMS_PURPOSE.PURPOSE_ID=TMS_APPLICATION.TOUR_TRAVEL_PURPOSE )"
					+ " LEFT JOIN HRMS_TMS_LOCATION_TYPE ON(HRMS_TMS_LOCATION_TYPE.LOCATION_TYPE_ID=TMS_APPLICATION.TOUR_TRAVEL_TYPE)"
					+ " LEFT JOIN HRMS_DEPT ON(HRMS_DEPT.DEPT_ID=HRMS_EMP_OFFC.EMP_DEPT)"
					+ " LEFT JOIN HRMS_RANK ON(HRMS_RANK.RANK_ID=HRMS_EMP_OFFC.EMP_RANK)"
					+ " LEFT JOIN  HRMS_CENTER ON(HRMS_EMP_OFFC.EMP_CENTER=HRMS_CENTER.CENTER_ID) "
					+ " LEFT  JOIN HRMS_CADRE ON(HRMS_CADRE.CADRE_ID=HRMS_EMP_OFFC.EMP_CADRE)"
					+ " LEFT JOIN HRMS_EMP_ADDRESS ON(HRMS_EMP_ADDRESS.EMP_ID=HRMS_EMP_OFFC.EMP_ID AND ADD_TYPE='P')"
					+ "  LEFT JOIN TMS_TRAVEL_PROJECT ON(TMS_TRAVEL_PROJECT.PROJECT_ID=TMS_APPLICATION.TOUR_PROJECT)"
					+ " LEFT JOIN TMS_TRAVEL_CUSTOMER ON(TMS_TRAVEL_CUSTOMER.TRAVEL_CUST_ID=TMS_APPLICATION.TOUR_CUSTOMER)"
					+ " INNER JOIN TMS_JOURNEY_SRC_DEST_VIEW ON (TMS_JOURNEY_SRC_DEST_VIEW.APPL_ID =TMS_APP_EMPDTL.APPL_ID) "
					+ " WHERE APPL_EMP_CODE=? AND TMS_APP_EMPDTL.APPL_ID=? AND TMS_APP_EMPDTL.APPL_CODE=?";

		case 12:
			return "INSERT INTO TMS_EXP_APPROVAL_DTL( EXP_APPID, EXP_APPRVR_ID, EXP_APPRVR_LEVEL)VALUES(?,?,?)";

		case 13:
			return "SELECT EMP_TOKEN,"
					+ " NVL(INITIATOR.EMP_FNAME,' ')||'  '||NVL(INITIATOR.EMP_MNAME,' ')||'  '||NVL(INITIATOR.EMP_LNAME,' ') AS NAME,"
					+ " TO_CHAR(TMS_APPLICATION.APPL_DATE,'DD-MM-YYYY'),NVL(TO_CHAR(TOUR_TRAVEL_STARTDT,'DD-MM-YYYY'),' '),"
					+ " NVL(TO_CHAR(TOUR_TRAVEL_ENDDT,'DD-MM-YYYY'),' '), APPL_INITIATOR,TMS_APPLICATION.TOUR_TRAVEL_REQ_NAME,"
					+ " TMS_APP_GUEST_DTL.GUEST_ADVANCE_AMT,HRMS_TMS_PURPOSE.PURPOSE_NAME,TMS_APPLICATION.TOUR_TRAVEL_PURPOSE, "
					+ " HRMS_TMS_LOCATION_TYPE.LOCATION_TYPE_ID,HRMS_TMS_LOCATION_TYPE.LOCATION_TYPE_NAME, CENTER_NAME AS BRANCH,"
					+ " DEPT_NAME,RANK_NAME,CADRE_NAME, INITIATOR.EMP_CADRE,  INITIATOR.EMP_ID,EMP_CENTER,EMP_DEPT,EMP_RANK,  "
					+ " NVL(TMS_TRAVEL_PROJECT.PROJECT_NAME,'') ,NVL(TMS_TRAVEL_CUSTOMER.TRAVEL_CUST_NAME,'')"
					+ " FROM TMS_APP_GUEST_DTL "
					+ " INNER JOIN TMS_APPLICATION ON(TMS_APPLICATION.APPL_ID = TMS_APP_GUEST_DTL.APPL_ID) "
					+ " LEFT  JOIN HRMS_EMP_OFFC  INITIATOR ON(TMS_APPLICATION.APPL_INITIATOR = INITIATOR.EMP_ID )"
					+ " INNER JOIN HRMS_TMS_PURPOSE  ON(HRMS_TMS_PURPOSE.PURPOSE_ID=TMS_APPLICATION.TOUR_TRAVEL_PURPOSE )"
					+ " LEFT JOIN HRMS_TMS_LOCATION_TYPE ON(HRMS_TMS_LOCATION_TYPE.LOCATION_TYPE_ID=TMS_APPLICATION.TOUR_TRAVEL_TYPE)"
					+ " LEFT JOIN HRMS_DEPT ON(HRMS_DEPT.DEPT_ID=INITIATOR.EMP_DEPT) "
					+ " LEFT JOIN HRMS_RANK ON(HRMS_RANK.RANK_ID=INITIATOR.EMP_RANK) "
					+ " LEFT JOIN  HRMS_CENTER ON(INITIATOR.EMP_CENTER=HRMS_CENTER.CENTER_ID)  "
					+ " LEFT  JOIN HRMS_CADRE ON(HRMS_CADRE.CADRE_ID=INITIATOR.EMP_CADRE) "
					+ " LEFT JOIN HRMS_EMP_ADDRESS ON(HRMS_EMP_ADDRESS.EMP_ID=INITIATOR.EMP_ID AND ADD_TYPE='P') "
					+ "  LEFT JOIN TMS_TRAVEL_PROJECT ON(TMS_TRAVEL_PROJECT.PROJECT_ID=TMS_APPLICATION.TOUR_PROJECT)"
					+ "  LEFT JOIN TMS_TRAVEL_CUSTOMER ON(TMS_TRAVEL_CUSTOMER.TRAVEL_CUST_ID=TMS_APPLICATION.TOUR_CUSTOMER)"
					+ " WHERE APPL_INITIATOR=? AND TMS_APP_GUEST_DTL.APPL_ID=? AND TMS_APP_GUEST_DTL.APPL_CODE=?";

		/*case 15:
			return "SELECT EXP_APPID,EXP_TRVL_ID,EMP_FNAME||' '||EMP_MNAME||' '||EMP_LNAME ,NVL(EXP_TRVL_REQNAME,''),"
					+ " TO_CHAR(EXP_TRVL_END_DATE,'dd-mm-yyyy'),  EXP_TRVL_APPID, EXP_TRVL_APPCODE , Decode(EXP_APP_STATUS,'A','Approved','C','Closed','R','Rejected','Q','Acknowledged','D','Disbursed'), EXP_APP_EMPID"
					+ " FROM TMS_CLAIM_APPL "
					+ " INNER JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=TMS_CLAIM_APPL.EXP_APP_EMPID)"
					+ " LEFT JOIN  TMS_APPLICATION ON(TMS_APPLICATION.APPL_ID=TMS_CLAIM_APPL.EXP_TRVL_APPID) "
					+ " WHERE (EXP_APP_ADMIN_STATUS IN('A','C') OR EXP_APP_STATUS IN('A','C','R','Q','D')) AND (EXP_APP_EMPID=? )"; // OR
			// APPL_INITIATOR=?
			// removed
			// temporarily
*/
			
		case 15 : return "SELECT EXP_APPID,EXP_TRVL_ID,EMP_FNAME||' '||EMP_MNAME||' '||EMP_LNAME ,NVL(EXP_TRVL_REQNAME,''), "
		+ " TO_CHAR(EXP_TRVL_END_DATE,'dd-mm-yyyy'),  EXP_TRVL_APPID, EXP_TRVL_APPCODE , "
		+ " case when EXP_APP_STATUS='A' AND EXP_APP_ADMIN_STATUS='A' "
		+ "  then DECODE(EXP_APP_ADMIN_STATUS, 'A','Approved by admin') "
		+ " when   EXP_APP_STATUS='A' AND EXP_APP_ADMIN_STATUS='R' "
		+ " then DECODE(EXP_APP_ADMIN_STATUS, 'R','Rejected by admin') "
		+ " else "
		+ " Decode(EXP_APP_STATUS,'A','Approved by manager','C','Closed','R','Rejected by manager','Q','Acknowledged','D','Disbursed')"
		+ " end "
		+ " , EXP_APP_EMPID "
		+ " FROM TMS_CLAIM_APPL " 
		+ " INNER JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=TMS_CLAIM_APPL.EXP_APP_EMPID) "
		+ " LEFT JOIN  TMS_APPLICATION ON(TMS_APPLICATION.APPL_ID=TMS_CLAIM_APPL.EXP_TRVL_APPID) " 
		+ " WHERE (EXP_APP_ADMIN_STATUS IN('A','C','R') OR EXP_APP_STATUS IN('A','C','R','Q','D')) AND (EXP_APP_EMPID=?)";
		
		case 16:
			return "SELECT EXP_APPID,EXP_TRVL_ID,EMP_FNAME||' '||EMP_MNAME||' '||EMP_LNAME ,NVL(EXP_TRVL_REQNAME,''), "
					+ " TO_CHAR(EXP_TRVL_END_DATE,'dd-mm-yyyy'),  EXP_TRVL_APPID, EXP_TRVL_APPCODE , EXP_APP_STATUS, EXP_APP_EMPID  "
					+ " ,EXP_APP_ADMIN_STATUS, "
					+ " 'Pending For Manager Approval' "
					+ " FROM TMS_CLAIM_APPL "
					+ " INNER JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=TMS_CLAIM_APPL.EXP_APP_EMPID) "
					+ " LEFT JOIN  TMS_APPLICATION ON(TMS_APPLICATION.APPL_ID=TMS_CLAIM_APPL.EXP_TRVL_APPID) "
					+ " WHERE EXP_APP_STATUS='P'  AND (EXP_APP_EMPID=? OR APPL_INITIATOR=?) "
					+ " UNION  "
					+ " SELECT EXP_APPID,EXP_TRVL_ID,EMP_FNAME||' '||EMP_MNAME||' '||EMP_LNAME ,NVL(EXP_TRVL_REQNAME,''), "
					+ " TO_CHAR(EXP_TRVL_END_DATE,'dd-mm-yyyy'),  EXP_TRVL_APPID, EXP_TRVL_APPCODE , EXP_APP_STATUS, EXP_APP_EMPID "
					+ " ,EXP_APP_ADMIN_STATUS, "
					+ " 'Pending For Admin Approval' "
					+ " FROM TMS_CLAIM_APPL "
					+ " INNER JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=TMS_CLAIM_APPL.EXP_APP_EMPID) "
					+ " LEFT JOIN  TMS_APPLICATION ON(TMS_APPLICATION.APPL_ID=TMS_CLAIM_APPL.EXP_TRVL_APPID) "
					+ " WHERE EXP_APP_STATUS='A' AND EXP_APP_ADMIN_STATUS='P' AND (EXP_APP_EMPID=? OR APPL_INITIATOR=?)";

		case 17:
			return " SELECT DISTINCT TMS_APPLICATION.APPL_ID,TMS_APP_EMPDTL.APPL_CODE, NVL(APPL_TRVL_ID,' '),  APPL_INITIATOR , "
					+ " NVL(EMP_FNAME||' '||EMP_MNAME||' '||EMP_LNAME,' ') AS INITIATOR,   NVL(C1.EMP_FNAME,' ')||'  '||NVL(C1.EMP_MNAME,' ')||'  '||NVL(C1.EMP_LNAME,' ')  AS APPLICANT,  "
					+ " TO_CHAR(TMS_APPLICATION.APPL_DATE,'DD-MM-YYYY') , TO_CHAR(TOUR_TRAVEL_ENDDT,'DD-MM-YYYY'),  "
					+ " TOUR_TRAVEL_REQ_NAME,TMS_APP_EMPDTL.APPL_EMP_CODE,   TO_DATE(TO_CHAR(SYSDATE,'DD-MM-YYYY'),'DD-MM-YYYY') - "
					+ " TO_DATE(TO_CHAR(TOUR_TRAVEL_ENDDT,'DD-MM-YYYY'),'DD-MM-YYYY')  AS DUEDAYS ,APPL_FOR_FLAG , '_'||APPL_EMP_TRAVEL_APPLSTATUS   FROM TMS_APPLICATION  "
					+ " LEFT JOIN TMS_CLAIM_APPL ON(TMS_CLAIM_APPL.EXP_TRVL_APPID=TMS_APPLICATION.APPL_ID) "
					+ " INNER JOIN   TMS_APP_EMPDTL ON(TMS_APPLICATION.APPL_ID=TMS_APP_EMPDTL.APPL_ID )   "
					+ " INNER JOIN HRMS_EMP_OFFC C1 ON(TMS_APP_EMPDTL.APPL_EMP_CODE=C1.EMP_ID)    "
					+ " INNER JOIN  HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=TMS_APPLICATION.APPL_INITIATOR) "
					+ " INNER JOIN TMS_POLICY_GRADE_DTL ON (TMS_POLICY_GRADE_DTL.POLICY_GRAD_ID = C1.EMP_CADRE )   "
					+ " INNER JOIN TMS_TRAVEL_POLICY ON (TMS_POLICY_GRADE_DTL.POLICY_ID = TMS_TRAVEL_POLICY.POLICY_ID)"
					+ " WHERE (APPL_EMP_CODE= ? AND APPL_EMP_TRAVEL_APPLSTATUS IN('A','C','W','F','Z') ) AND "
					+ " TMS_APP_EMPDTL.APPL_TRVL_ID NOT IN "
					+ " (SELECT EXP_TRVL_ID FROM TMS_CLAIM_APPL WHERE EXP_TRVL_ID IS NOT NULL)  "
					+ " AND  (TO_DATE(TO_CHAR(SYSDATE,'DD-MM-YYYY'),'DD-MM-YYYY') - "
					+ " TO_DATE(TO_CHAR(TOUR_TRAVEL_ENDDT,'DD-MM-YYYY'),'DD-MM-YYYY')) >  MAX_DAYS_SETTLE_TRAVEL_CLAIM "
					+ " AND MAX_DAYS_SETTLE_TRAVEL_CLAIM!=0 ORDER BY TO_CHAR(APPL_DATE,'DD-MM-YYYY') DESC";

		default:
			return " Framework could not find query number specified";

		}

	}
}
