package org.paradyne.sql.TravelManagement.TravelClaim;

import org.paradyne.lib.SqlBase;

public class TmsUnblockApplicationModelSql extends SqlBase
{
	public String getQuery(int id) {

		switch (id) {
		case 1:
			return "SELECT DISTINCT TMS_APPLICATION.APPL_ID,TMS_APP_EMPDTL.APPL_CODE, NVL(APPL_TRVL_ID,' '),  APPL_INITIATOR , " 
					+" NVL(EMP_FNAME||' '||EMP_MNAME||' '||EMP_LNAME,' ') AS INITIATOR,   NVL(C1.EMP_FNAME,' ')||'  '||NVL(C1.EMP_MNAME,' ')||'  '||NVL(C1.EMP_LNAME,' ')  AS APPLICANT, "  
					+" TO_CHAR(TMS_APPLICATION.APPL_DATE,'DD-MM-YYYY') , TO_CHAR(TOUR_TRAVEL_ENDDT,'DD-MM-YYYY'), "  
					+" TOUR_TRAVEL_REQ_NAME,TMS_APP_EMPDTL.APPL_EMP_CODE,   TO_DATE(TO_CHAR(SYSDATE,'DD-MM-YYYY'),'DD-MM-YYYY') - " 
					+" TO_DATE(TO_CHAR(TOUR_TRAVEL_ENDDT,'DD-MM-YYYY'),'DD-MM-YYYY')  AS DUEDAYS ,APPL_FOR_FLAG , '_'||APPL_EMP_TRAVEL_APPLSTATUS    FROM TMS_APPLICATION "  
					+" LEFT JOIN TMS_CLAIM_APPL ON(TMS_CLAIM_APPL.EXP_TRVL_APPID=TMS_APPLICATION.APPL_ID) " 
					+" INNER JOIN   TMS_APP_EMPDTL ON(TMS_APPLICATION.APPL_ID=TMS_APP_EMPDTL.APPL_ID ) "   
					+" INNER JOIN HRMS_EMP_OFFC C1 ON(TMS_APP_EMPDTL.APPL_EMP_CODE=C1.EMP_ID) "    
					+" INNER JOIN  HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=TMS_APPLICATION.APPL_INITIATOR) "
					+" INNER JOIN TMS_POLICY_GRADE_DTL ON (TMS_POLICY_GRADE_DTL.POLICY_GRAD_ID = C1.EMP_CADRE ) "   
					+" INNER JOIN TMS_TRAVEL_POLICY ON (TMS_POLICY_GRADE_DTL.POLICY_ID = TMS_TRAVEL_POLICY.POLICY_ID)"
					+" WHERE (APPL_EMP_TRAVEL_APPLSTATUS IN('Z') ) AND "
					+" TMS_APP_EMPDTL.APPL_TRVL_ID NOT IN (SELECT EXP_TRVL_ID FROM TMS_CLAIM_APPL WHERE EXP_TRVL_ID IS NOT NULL)";
			
		default:
			return " Framework could not find query number specified";
		}
		
	}	
}