package org.paradyne.sql.PAS;


import org.paradyne.lib.SqlBase;

public class ApprFormTrainingDtlsModelSql extends SqlBase {

	
	public String getQuery(int i){
		 
		switch(i){
		
		
		case 1 : return " SELECT APPR_TRN_FLAG FROM PAS_APPR_TEMPLATE WHERE APPR_ID=? AND APPR_TEMPLATE_ID=?";
		
		case 2 : return " SELECT APPR_PHASE_VISIBILITY, APPR_PHASE_COMMENT FROM PAS_APPR_COMMON_SECTION "
		   				+" WHERE APPR_ID = ? AND APPR_TEMPLATE_ID= ? AND APPR_PHASE = ? AND APPR_SECTION_TYPE = 'T'";
		
		case 3 : return " SELECT APPR_SECTION_ID, APPR_QUESTION_CODE,APPR_QUES_DESC,APPR_ANSWER_CHAR_LIMIT, APPR_TRNRECOM_COMMENT,APPR_SECTION_ID FROM PAS_APPR_TRN_RECOMMEND_COMMENT"
					   +" INNER JOIN PAS_APPR_QUESTIONNAIRE ON(PAS_APPR_QUESTIONNAIRE.APPR_QUES_CODE = PAS_APPR_TRN_RECOMMEND_COMMENT.APPR_QUESTION_CODE)"
					   +" WHERE APPR_ID=? AND APPR_TEMPLATE_ID=? AND APPR_PHASE_ID=? AND APPR_EMP_ID=? AND APPR_APPRAISER_ID=?";
		
		case 4: return " SELECT APPR_QUES_DESC, APPR_ANSWER_CHAR_LIMIT, PAS_APPR_QUESTIONNAIRE.APPR_QUES_CODE FROM PAS_APPR_QUESTIONNAIRE"
		  			  +" INNER JOIN PAS_APPR_TRN_RECOMMEND ON (PAS_APPR_TRN_RECOMMEND.APPR_QUESTION_CODE = PAS_APPR_QUESTIONNAIRE.APPR_QUES_CODE)"
		              +" WHERE APPR_ID=? AND APPR_TEMPLATE_ID=?";
		
		case 5 : return " INSERT INTO PAS_APPR_TRN_RECOMMEND_COMMENT(APPR_ID, APPR_TEMPLATE_ID, APPR_SECTION_ID, APPR_PHASE_ID, APPR_EMP_ID, APPR_QUESTION_CODE, APPR_TRNRECOM_COMMENT,APPR_APPRAISER_ID)"
					   +" VALUES(?,?,(SELECT NVL(MAX(APPR_SECTION_ID), 0)+1 FROM PAS_APPR_TRN_RECOMMEND_COMMENT),?,?,?,?,?)";
		
		case 6 : return " UPDATE PAS_APPR_TRN_RECOMMEND_COMMENT SET APPR_TRNRECOM_COMMENT=? WHERE APPR_ID=? AND APPR_TEMPLATE_ID=? AND APPR_SECTION_ID=? AND APPR_PHASE_ID=? AND APPR_EMP_ID=? AND APPR_QUESTION_CODE=? AND APPR_APPRAISER_ID=?";
		
		case 7 : return " SELECT PAS_APPR_TRN_ATTENDED.APPR_TRN_CODE, APPR_TRN_DESC,APPR_TRN_DURATION, APPR_TRN_FROM, APPR_TRN_TO, APPR_TRN_SPONCER, APPR_TRNATTEN_COMMENT"
					   +" FROM PAS_APPR_TRN_ATTENDED"
					   +" LEFT JOIN PAS_APPR_TRN_ATTENDED_COMMENT ON (PAS_APPR_TRN_ATTENDED_COMMENT.APPR_TRN_CODE=PAS_APPR_TRN_ATTENDED.APPR_TRN_CODE) ORDER BY APPR_TRN_CODE ";
		
		case 8 : return " INSERT INTO PAS_APPR_TRN_ATTENDED(APPR_ID, APPR_TEMPLATE_ID, APPR_EMP_ID, APPR_TRN_CODE, APPR_TRN_DESC, APPR_TRN_FROM, APPR_TRN_TO, APPR_TRN_SPONCER, APPR_TRN_DURATION) VALUES(?,?,?,(SELECT NVL(MAX(APPR_TRN_CODE), 0)+1 FROM PAS_APPR_TRN_ATTENDED),?,TO_DATE(?,'DD-MM-YYYY'),TO_DATE(?,'DD-MM-YYYY'),?,?)";
		
		case 9 : return " UPDATE PAS_APPR_TRN_ATTENDED SET APPR_TRN_DESC=?, APPR_TRN_FROM=TO_DATE(?,'DD-MM-YYYY'), APPR_TRN_TO=TO_DATE(?,'DD-MM-YYYY'), APPR_TRN_SPONCER=?, APPR_TRN_DURATION=? WHERE APPR_ID=? AND APPR_TEMPLATE_ID=? AND APPR_EMP_ID=? AND  APPR_TRN_CODE=?";
		
		case 10 : return " SELECT APPR_TRN_CODE, APPR_TRN_DESC, TO_CHAR(APPR_TRN_FROM,'DD-MM-YYYY'), TO_CHAR(APPR_TRN_TO,'DD-MM-YYYY'), APPR_TRN_SPONCER, APPR_TRN_DURATION FROM PAS_APPR_TRN_ATTENDED WHERE APPR_ID=? AND APPR_TEMPLATE_ID=? AND APPR_EMP_ID=? ORDER BY APPR_TRN_CODE ";
		
		case 11 : return " SELECT * FROM PAS_APPR_TRN_ATTENDED_COMMENT WHERE APPR_TRN_CODE=?";
		
		case 12 : return " DELETE FROM PAS_APPR_TRN_ATTENDED WHERE APPR_TRN_CODE=?";
		
		case 13 : return " INSERT INTO PAS_APPR_TRN_ATTENDED_COMMENT(APPR_ID, APPR_TEMPLATE_ID,  APPR_PHASE_ID, APPR_EMP_ID, APPR_TRN_CODE, APPR_TRNATTEN_COMMENT,APPR_APPRAISER_ID)VALUES(?,?,?,?,?,?,?)";
		
		case 14 : return " DELETE FROM PAS_APPR_TRN_ATTENDED_COMMENT WHERE APPR_TRN_CODE=? AND APPR_APPRAISER_ID=?";
		
		case 15 : return "SELECT PAS_APPR_TRN_ATTENDED.APPR_TRN_CODE, APPR_TRN_DESC, TO_CHAR(APPR_TRN_FROM,'DD-MM-YYYY'), TO_CHAR(APPR_TRN_TO,'DD-MM-YYYY'), APPR_TRN_SPONCER, APPR_TRN_DURATION,"
						+" APPR_TRNATTEN_COMMENT FROM PAS_APPR_TRN_ATTENDED" 
						+" LEFT JOIN PAS_APPR_TRN_ATTENDED_COMMENT ON("
						+" PAS_APPR_TRN_ATTENDED.APPR_ID = PAS_APPR_TRN_ATTENDED_COMMENT.APPR_ID"  
						+" AND PAS_APPR_TRN_ATTENDED.APPR_TEMPLATE_ID = PAS_APPR_TRN_ATTENDED_COMMENT.APPR_TEMPLATE_ID" 
						+" AND PAS_APPR_TRN_ATTENDED.APPR_EMP_ID = PAS_APPR_TRN_ATTENDED_COMMENT.APPR_EMP_ID"
						+" AND PAS_APPR_TRN_ATTENDED.APPR_TRN_CODE = PAS_APPR_TRN_ATTENDED_COMMENT.APPR_TRN_CODE AND APPR_PHASE_ID = ? AND APPR_APPRAISER_ID=?)"
						+" WHERE" 
						+" PAS_APPR_TRN_ATTENDED.APPR_ID = ? AND"
						+" PAS_APPR_TRN_ATTENDED.APPR_TEMPLATE_ID = ? AND"
						+" PAS_APPR_TRN_ATTENDED.APPR_EMP_ID = ? ORDER BY APPR_TRN_CODE ";// AND"
						//+" APPR_PHASE_ID = ?";
		
		case 16: return "SELECT PAS_APPR_TRN_ATTENDED.APPR_TRN_CODE,APPR_PHASE_ID,APPR_PHASE_NAME, APPR_TRN_DESC, TO_CHAR(APPR_TRN_FROM,'DD-MM-YYYY'), TO_CHAR(APPR_TRN_TO,'DD-MM-YYYY'), APPR_TRN_SPONCER, APPR_TRN_DURATION,"
						+" APPR_TRNATTEN_COMMENT FROM PAS_APPR_TRN_ATTENDED" 
						+" INNER JOIN PAS_APPR_TRN_ATTENDED_COMMENT ON("
						+" PAS_APPR_TRN_ATTENDED.APPR_ID = PAS_APPR_TRN_ATTENDED_COMMENT.APPR_ID"  
						+" AND PAS_APPR_TRN_ATTENDED.APPR_TEMPLATE_ID = PAS_APPR_TRN_ATTENDED_COMMENT.APPR_TEMPLATE_ID" 
						+" AND PAS_APPR_TRN_ATTENDED.APPR_EMP_ID = PAS_APPR_TRN_ATTENDED_COMMENT.APPR_EMP_ID"
						+" AND PAS_APPR_TRN_ATTENDED.APPR_TRN_CODE = PAS_APPR_TRN_ATTENDED_COMMENT.APPR_TRN_CODE )"//AND APPR_PHASE_ID NOT IN (?)
						+" LEFT JOIN PAS_APPR_PHASE_CONFIG ON(PAS_APPR_PHASE_CONFIG.APPR_ID = PAS_APPR_TRN_ATTENDED_COMMENT.APPR_ID AND PAS_APPR_PHASE_CONFIG.APPR_PHASE_ID = PAS_APPR_TRN_ATTENDED_COMMENT.APPR_PHASE_ID) "
						+" WHERE" 
						+" PAS_APPR_TRN_ATTENDED.APPR_ID = ? AND"
						+" PAS_APPR_TRN_ATTENDED.APPR_TEMPLATE_ID = ? AND"
						+" PAS_APPR_TRN_ATTENDED.APPR_EMP_ID = ?"
						+" AND("
						+" PAS_APPR_PHASE_CONFIG.APPR_PHASE_ORDER<"
						+"(SELECT APPR_PHASE_ORDER FROM PAS_APPR_PHASE_CONFIG WHERE APPR_PHASE_ID=?)" 
						+"OR (PAS_APPR_PHASE_CONFIG.APPR_PHASE_ORDER="
						+"(SELECT APPR_PHASE_ORDER FROM PAS_APPR_PHASE_CONFIG WHERE APPR_PHASE_ID=?)  AND APPR_APPRAISER_ID!=?)"
						+") "
						+" ORDER BY PAS_APPR_PHASE_CONFIG.APPR_PHASE_ID,PAS_APPR_TRN_ATTENDED.APPR_TRN_CODE";
		
		case 17 : return "SELECT PAS_APPR_PHASE_CONFIG.APPR_PHASE_ID,APPR_PHASE_NAME ,NVL(APPR_QUES_DESC,''), NVL(APPR_TRNRECOM_COMMENT,' ' )  FROM PAS_APPR_TRN_RECOMMEND_COMMENT"
					    +" INNER JOIN PAS_APPR_QUESTIONNAIRE ON(PAS_APPR_QUESTIONNAIRE.APPR_QUES_CODE = PAS_APPR_TRN_RECOMMEND_COMMENT.APPR_QUESTION_CODE)"
					    +" INNER JOIN PAS_APPR_PHASE_CONFIG ON(PAS_APPR_PHASE_CONFIG.APPR_ID = PAS_APPR_TRN_RECOMMEND_COMMENT.APPR_ID AND PAS_APPR_PHASE_CONFIG.APPR_PHASE_ID = PAS_APPR_TRN_RECOMMEND_COMMENT.APPR_PHASE_ID)" 
					    +" WHERE APPR_ID=? AND"
					    +" APPR_TEMPLATE_ID=?  AND APPR_EMP_ID=? "//AND APPR_PHASE_ID NOT IN (?)
					    +" AND("
						+" PAS_APPR_PHASE_CONFIG.APPR_PHASE_ORDER<"
						+"(SELECT APPR_PHASE_ORDER FROM PAS_APPR_PHASE_CONFIG WHERE APPR_PHASE_ID=?)" 
						+"OR (PAS_APPR_PHASE_CONFIG.APPR_PHASE_ORDER="
						+"(SELECT APPR_PHASE_ORDER FROM PAS_APPR_PHASE_CONFIG WHERE APPR_PHASE_ID=?)  AND APPR_APPRAISER_ID!=?)"
						+") "
					    +" ORDER BY PAS_APPR_PHASE_CONFIG.APPR_PHASE_ID";
		
		case 18 : return "SELECT APPR_IS_SELFPHASE FROM PAS_APPR_PHASE_CONFIG WHERE APPR_ID=? AND APPR_PHASE_ID=?";
		
		case 19 : return " SELECT APPR_TRN_FLAG,APPR_AWARD_FLAG, APPR_DISCIPLINARY_FLAG, APPR_CAREER_FLAG, APPR_TRN_FLAG"
						+" FROM PAS_APPR_TEMPLATE WHERE APPR_ID=? AND APPR_TEMPLATE_ID=?";
		
		case 20 : return " SELECT APPR_PHASE_VISIBILITY, APPR_PHASE_COMMENT,APPR_SECTION_TYPE FROM PAS_APPR_COMMON_SECTION" 
						+" WHERE APPR_ID = ? AND APPR_TEMPLATE_ID= ? AND APPR_PHASE = ? AND APPR_SECTION_TYPE  IN('A','D','C')";
		
		case 21 : return "SELECT PAS_APPR_PHASE_CONFIG.APPR_PHASE_ID, PAS_APPR_PHASE_CONFIG.APPR_PHASE_NAME, PAS_APPR_PHASE_CONFIG.APPR_PHASE_ORDER,APPR_APPRAISER_LEVEL FROM PAS_APPR_APPRAISER" 
						+" INNER JOIN PAS_APPR_PHASE_CONFIG ON (PAS_APPR_PHASE_CONFIG.APPR_ID=PAS_APPR_APPRAISER.APPR_ID AND"
						+" PAS_APPR_APPRAISER.APPR_PHASE_ID=PAS_APPR_PHASE_CONFIG.APPR_PHASE_ID"
						+")WHERE PAS_APPR_PHASE_CONFIG.APPR_ID=? AND" 
						+" PAS_APPR_PHASE_CONFIG.APPR_PHASE_ID=? AND"
						+" APPR_APPRAISER_CODE=?";
		
		default: return "";
		
		}
	}
	
}
