package org.paradyne.sql.PAS;
import org.paradyne.lib.SqlBase;

public class AppraisalPhaseConfigModelSql extends SqlBase{

	
		public String getQuery(int id){
			
		
			switch (id) {
			
					case 1 : return "INSERT INTO PAS_APPR_PHASE_CONFIG(APPR_ID, APPR_PHASE_ID, APPR_PHASE_NAME, "
								   +" APPR_PHASE_ORDER, APPR_PHASE_STATUS, APPR_PHASEWISE_RATING, APPR_PHASE_WEIGHT_AGE,"
								   +" APPR_PHASE_DESCRIPTION,APPR_IS_SELFPHASE,APPR_QUESWT_DISPLAY_FLAG) "
								   +" VALUES(?,(SELECT NVL(MAX(APPR_PHASE_ID),0)+1 FROM PAS_APPR_PHASE_CONFIG ),?,?,?,?,?,?,?,?) ";
					
					case 2 : return " SELECT APPR_PHASE_ID, APPR_PHASE_NAME, APPR_PHASE_ORDER, DECODE(APPR_PHASE_STATUS,'A','Active','D','De-Active'), APPR_PHASEWISE_RATING, APPR_PHASE_WEIGHT_AGE, NVL(APPR_PHASE_DESCRIPTION,' '),APPR_CAL_CODE,TO_CHAR(APPR_CAL_START_DATE,'DD-MM-YYYY'), TO_CHAR(APPR_CAL_END_DATE,'DD-MM-YYYY'),APPR_IS_SELFPHASE,APPR_CAL_IS_STARTED,NVL(APPR_QUESWT_DISPLAY_FLAG,'N')"
								   +" FROM PAS_APPR_PHASE_CONFIG "
								   +" INNER JOIN PAS_APPR_CALENDAR ON (PAS_APPR_CALENDAR.APPR_ID = PAS_APPR_PHASE_CONFIG.APPR_ID)"  
								   +" WHERE PAS_APPR_PHASE_CONFIG.APPR_ID=? ORDER BY APPR_PHASE_ORDER";
					
					case 3 : return " UPDATE PAS_APPR_PHASE_CONFIG SET APPR_PHASE_NAME=?,APPR_PHASE_ORDER=?, APPR_PHASE_STATUS=?, APPR_PHASEWISE_RATING=?, APPR_PHASE_WEIGHT_AGE=?, APPR_PHASE_DESCRIPTION=?, APPR_IS_SELFPHASE=?,APPR_QUESWT_DISPLAY_FLAG=? WHERE APPR_ID=? AND APPR_PHASE_ID=?";
					
					case 4 : return " DELETE FROM PAS_APPR_PHASE_CONFIG WHERE APPR_ID=?";
					
					case 5 : return " DELETE FROM PAS_APPR_PHASE_CONFIG WHERE APPR_PHASE_ID=?";
					
					case 6 : return " SELECT APPR_PHASE_ID FROM PAS_APPR_PHASE_SCHEDULE WHERE APPR_PHASE_ID=?";
					
					case 7 : return " SELECT APPR_CAL_CODE, TO_CHAR(APPR_CAL_START_DATE,'DD-MM-YYYY'), TO_CHAR(APPR_CAL_END_DATE,'DD-MM-YYYY'),APPR_ID FROM PAS_APPR_CALENDAR WHERE PAS_APPR_CALENDAR.APPR_ID IN(SELECT DISTINCT APPR_ID FROM PAS_APPR_PHASE_CONFIG)";
					
					case 8 : return " SELECT APPR_TEMPLATE_ID,APPR_SECTION_ID FROM PAS_APPR_SECTION_HDR WHERE APPR_ID = ? ";
					
					case 9 : return " SELECT MAX(APPR_PHASE_ID) FROM PAS_APPR_PHASE_CONFIG WHERE APPR_ID=?";
					
					case 10 : return " INSERT INTO PAS_APPR_SECTION_DTL (APPR_ID,APPR_TEMPLATE_ID,APPR_SECTION_ID,APPR_PHASE_ID,APPR_SECTION_VISIBILITY,"
								    +" APPR_SECTION_RATING,APPR_SECTION_COMMENT) VALUES(?,?,?,?,?,?,?)";
					
					case 11 : return " SELECT * FROM PAS_APPR_SECTION_DTL WHERE APPR_ID=? AND APPR_PHASE_ID=?";
					/*case 2 : return "UPDATE HRMS_MP_EDUCATION SET EDUCATION_DEGREE=?,EDUCATION_INSTITUTE=?,EDUCATION_UNIVERSITY=?,EDUCATION_YEAR_PASSING=?,"
					      +" EDUCATION_OBT_MARKS=?,EDUCATION_OBT_PERCENTAGE=? EDUCATION_QUALIFICATION=? EDUCATION_COMP_LITER=? WHERE EDUCATION_RECRUIT_ID=?";
					
					case 3 : return "DELETE FROM HRMS_MP_EDUCATION WHERE EDUCATION_RECRUIT_ID=?";*/
					
					default: return "hi";
				
			}
			
	
	
	
		}
}
