/**
 * 
 */
package org.paradyne.sql.PAS;

import org.paradyne.lib.SqlBase;

/**
 * @author aa0554
 *
 */
public class AppraisalCalendarModelSql extends SqlBase {
		
		public String getQuery(int id) {
			switch (id) {
			case 1 : return "INSERT INTO PAS_APPR_CALENDAR(APPR_ID,APPR_CAL_CODE,APPR_CAL_VALID_DATE,APPR_CAL_START_DATE,APPR_CAL_REPEAT_FREQ,APPR_CAL_END_DATE, "
								+" APPR_CAL_CRT_GRD_FLAG,APPR_CAL_CRT_ETYP_FLAG,APPR_CAL_CRT_DOJ_FLAG,APPR_CAL_CRT_DEP_FLAG,APPR_CAL_COMMENT,APPR_CAL_AUTO_FLAG,APPR_CAL_CRT_DIV_FLAG,APPR_SCORE_FLAG)"
								+" VALUES(?,?,TO_DATE(?,'DD-MM-YYYY'),TO_DATE(?,'DD-MM-YYYY'),?,TO_DATE(?,'DD-MM-YYYY'),?,?,?,?,?,?,?,?)";
				
			case 2 : return "INSERT INTO PAS_APPR_CAL_CRT_ETYPE(APPR_ID,APPR_CRT_EMP_TYPE) VALUES(?,?)";
			
			case 3 : return "INSERT INTO PAS_APPR_CAL_CRT_GRD(APPR_ID,APPR_CRT_EMP_GRADE) VALUES(?,?)";
			
			case 4 : return "INSERT INTO PAS_APPR_CAL_CRT_DEPT(APPR_ID,APPR_CRT_EMP_DEPT) VALUES(?,?)";
			
			case 5 : return "INSERT INTO PAS_APPR_CAL_CRT_DOJ(APPR_ID,APPR_CRT_DOJ_FROM_DATE,APPR_CRT_DOJ_TO_DATE,APPR_CRT_DOJ_CONDITION)"
								+" VALUES (?,TO_DATE(?,'DD-MM-YYYY'),TO_DATE(?,'DD-MM-YYYY'),?)";
			
			case 6 : return "INSERT INTO PAS_APPR_ELIGIBLE_EMP(APPR_ID, APPR_EMP_ID, APPR_EMP_STATUS, APPR_SYS_DATE,APPR_CRT_TYPE) VALUES(?,?," 
							+" 'A',TO_DATE(TO_CHAR(SYSDATE,'DD-MM-YYYY'),'DD-MM-YYYY'),?)";
			
			case 7 : return "UPDATE PAS_APPR_CALENDAR SET APPR_CAL_CODE=?,APPR_CAL_VALID_DATE=TO_DATE(?,'DD-MM-YYYY'), "
							+" APPR_CAL_START_DATE=TO_DATE(?,'DD-MM-YYYY'),APPR_CAL_REPEAT_FREQ=? "
							+" ,APPR_CAL_END_DATE =TO_DATE(?,'DD-MM-YYYY'), APPR_CAL_CRT_GRD_FLAG =?,APPR_CAL_CRT_ETYP_FLAG =?,APPR_CAL_CRT_DOJ_FLAG =?,"
							+" APPR_CAL_CRT_DEP_FLAG =?,APPR_CAL_COMMENT =?,APPR_CAL_AUTO_FLAG =?, APPR_CAL_CRT_DIV_FLAG=?, APPR_SCORE_FLAG=? WHERE APPR_ID=?";

			case 8: return " UPDATE PAS_APPR_ELIGIBLE_EMP SET APPR_EMP_STATUS ='R', APPR_SYS_DATE=TO_DATE(TO_CHAR(SYSDATE,'DD-MM-YYYY'),'DD-MM-YYYY'),"
							+" APPR_CRT_TYPE=? WHERE APPR_ID=? AND APPR_EMP_ID=?";
			
			case 9 : return "INSERT INTO PAS_APPR_CAL_CRT_DIV(APPR_ID,APPR_CRT_EMP_DIV) VALUES(?,?)";
			
			case 10 : return " SELECT APPR_PHASE_ID, APPR_PHASE_NAME, APPR_PHASE_ORDER, DECODE(APPR_PHASE_STATUS,'A','Active','D','De-Active'), APPR_PHASEWISE_RATING, APPR_PHASE_WEIGHT_AGE, NVL(APPR_PHASE_DESCRIPTION,' '),APPR_CAL_CODE,TO_CHAR(APPR_CAL_START_DATE,'DD-MM-YYYY'), TO_CHAR(APPR_CAL_END_DATE,'DD-MM-YYYY'),APPR_IS_SELFPHASE,APPR_CAL_IS_STARTED,NVL(APPR_QUESWT_DISPLAY_FLAG,'N')"
			   +" FROM PAS_APPR_PHASE_CONFIG "
			   +" INNER JOIN PAS_APPR_CALENDAR ON (PAS_APPR_CALENDAR.APPR_ID = PAS_APPR_PHASE_CONFIG.APPR_ID)"  
			   +" WHERE PAS_APPR_PHASE_CONFIG.APPR_ID=? ORDER BY APPR_PHASE_ORDER";
			
			
			default:return "Framework could not find the query number specified";
				
			}
			
		} 
}
