package org.paradyne.sql.PAS;

import org.paradyne.lib.SqlBase;

public class AppraisalScheduleModelSql extends SqlBase {
	public String getQuery(int id){
		switch (id) {
		
		case 1: return " SELECT APPR_PHASE_ID,APPR_PHASE_NAME " 
						+" FROM PAS_APPR_PHASE_CONFIG "
						+" WHERE APPR_ID = ? AND APPR_PHASE_STATUS='A'"
						+" ORDER BY APPR_PHASE_ORDER ";
		
		case 2: return " INSERT INTO PAS_APPR_PHASE_SCHEDULE(APPR_ID,APPR_PHASE_ID,APPR_PHASE_START_DATE,APPR_PHASE_END_DATE,APPR_PHASE_LOCK)"
						+" VALUES(?,?,TO_DATE(?,'DD-MM-YYYY'),TO_DATE(?,'DD-MM-YYYY'),?)";
		

		case 3 : return " SELECT PAS_APPR_PHASE_CONFIG.APPR_PHASE_ID,PAS_APPR_PHASE_CONFIG.APPR_PHASE_NAME, "
						+" TO_CHAR(APPR_PHASE_START_DATE,'DD-MM-YYYY'),TO_CHAR(APPR_PHASE_END_DATE,'DD-MM-YYYY'),APPR_PHASE_LOCK " 
						+" FROM PAS_APPR_PHASE_CONFIG  " 
						+" LEFT JOIN PAS_APPR_PHASE_SCHEDULE ON (PAS_APPR_PHASE_CONFIG.APPR_PHASE_ID = PAS_APPR_PHASE_SCHEDULE.APPR_PHASE_ID) "
						+" WHERE PAS_APPR_PHASE_CONFIG.APPR_ID = ? AND PAS_APPR_PHASE_CONFIG.APPR_PHASE_STATUS='A' ORDER BY  PAS_APPR_PHASE_CONFIG.APPR_ID,PAS_APPR_PHASE_CONFIG.APPR_PHASE_ID "; 
		
		case 4 : return " UPDATE PAS_APPR_PHASE_SCHEDULE SET APPR_PHASE_START_DATE = TO_DATE(?,'DD-MM-YYYY'),APPR_PHASE_END_DATE = TO_DATE(?,'DD-MM-YYYY'),APPR_PHASE_LOCK = ? "
						+" WHERE APPR_PHASE_ID = ? AND APPR_ID = ? ";
		
		case 5: return " SELECT PAS_APPR_PHASE_SCHEDULE.APPR_PHASE_ID "
						+" FROM PAS_APPR_PHASE_SCHEDULE " 
						+" INNER JOIN PAS_APPR_PHASE_CONFIG ON (PAS_APPR_PHASE_SCHEDULE.APPR_PHASE_ID = PAS_APPR_PHASE_CONFIG.APPR_PHASE_ID) "
						+" WHERE PAS_APPR_PHASE_SCHEDULE.APPR_ID = ? AND PAS_APPR_PHASE_CONFIG.APPR_PHASE_STATUS='A' ORDER BY  PAS_APPR_PHASE_SCHEDULE.APPR_ID,PAS_APPR_PHASE_SCHEDULE.APPR_PHASE_ID ";
		
		case 6: return " DELETE FROM PAS_APPR_PHASE_SCHEDULE WHERE APPR_ID = ? ";
		
		case 7: return " SELECT DISTINCT PAS_APPR_PHASE_SCHEDULE.APPR_ID,APPR_CAL_CODE,TO_CHAR(APPR_CAL_START_DATE,'DD-MM-YYYY'),TO_CHAR(APPR_CAL_END_DATE,'DD-MM-YYYY'),APPR_CAL_IS_STARTED FROM PAS_APPR_PHASE_SCHEDULE "
						+" INNER JOIN PAS_APPR_CALENDAR ON (PAS_APPR_CALENDAR.APPR_ID = PAS_APPR_PHASE_SCHEDULE.APPR_ID) "
						+" ORDER BY PAS_APPR_PHASE_SCHEDULE.APPR_ID "; 
		
		case 8: return " SELECT APPR_CAL_CODE,TO_CHAR(APPR_CAL_START_DATE,'DD-MM-YYYY'),TO_CHAR(APPR_CAL_END_DATE,'DD-MM-YYYY'),APPR_CAL_IS_STARTED FROM PAS_APPR_CALENDAR WHERE APPR_ID = ? ";
		
		default : return " Framework could not the query number specified";
			
		}

}
}