package org.paradyne.sql.PAS;

import org.paradyne.lib.SqlBase;

public class ApprFormGeneralInfoModelSql extends SqlBase {
	
	public String getQuery(int i){
		
		switch(i){
		
		case 1 : return " SELECT PAS_APPR_PHASE_CONFIG.APPR_PHASE_ID,PAS_APPR_PHASE_CONFIG.APPR_PHASE_NAME,  "
						+" TO_CHAR(APPR_PHASE_START_DATE,'DD-MM-YYYY'),TO_CHAR(APPR_PHASE_END_DATE,'DD-MM-YYYY'),APPR_PHASE_LOCK, " 
						+" NVL(PHASE_FORWARD,'N'),NVL(APPR_QUESWT_DISPLAY_FLAG,'N')  FROM PAS_APPR_PHASE_CONFIG " 
						+" LEFT JOIN PAS_APPR_PHASE_SCHEDULE ON (PAS_APPR_PHASE_SCHEDULE.APPR_PHASE_ID = PAS_APPR_PHASE_CONFIG.APPR_PHASE_ID ) "
						+" LEFT JOIN PAS_APPR_TRACKING ON (PAS_APPR_PHASE_CONFIG.APPR_PHASE_ID = PAS_APPR_TRACKING.PHASE_ID AND EMP_ID = ? ) "
						+" WHERE PAS_APPR_PHASE_CONFIG.APPR_ID = ?  AND APPR_PHASE_STATUS='A' AND APPR_IS_SELFPHASE = 'Y' ORDER BY  APPR_PHASE_ORDER ";
		
		
		case 2 : return " SELECT APPR_EMP_ID,HRMS_EMP_OFFC.EMP_TOKEN,(HRMS_TITLE .TITLE_NAME||' '||HRMS_EMP_OFFC.EMP_FNAME||' '||NVL(HRMS_EMP_OFFC.EMP_MNAME,' ')|| ' ' || HRMS_EMP_OFFC.EMP_LNAME), " 
						+" NVL(HRMS_CENTER.CENTER_NAME,' '),NVL(HRMS_DEPT.DEPT_NAME,'  '),NVL(HRMS_RANK.RANK_NAME,'  '), "
						+" (AS2.TITLE_NAME||' '||AS1.EMP_FNAME||' '||NVL(AS1.EMP_MNAME,'')|| ' ' || AS1.EMP_LNAME),TO_CHAR(HRMS_EMP_OFFC.EMP_REGULAR_DATE,'DD-MM-YYYY'), "
						+" TO_CHAR(SYSDATE,'DD-MM-YYYY') "
						+" FROM PAS_APPR_ELIGIBLE_EMP "
						+" LEFT JOIN HRMS_EMP_OFFC ON (PAS_APPR_ELIGIBLE_EMP.APPR_EMP_ID = HRMS_EMP_OFFC.EMP_ID) " 
						+" LEFT JOIN HRMS_TITLE  ON(HRMS_EMP_OFFC.EMP_TITLE_CODE = HRMS_TITLE .TITLE_CODE) "
						+" LEFT JOIN HRMS_CENTER ON(HRMS_EMP_OFFC.EMP_CENTER=HRMS_CENTER.CENTER_ID) "
						+" LEFT JOIN HRMS_DEPT ON(HRMS_EMP_OFFC.EMP_DEPT=HRMS_DEPT.DEPT_ID) "
						+" LEFT JOIN HRMS_RANK ON(HRMS_EMP_OFFC.EMP_RANK=HRMS_RANK.RANK_ID) "
						+" LEFT JOIN HRMS_EMP_OFFC AS1 ON (HRMS_EMP_OFFC.EMP_REPORTING_OFFICER = AS1.EMP_ID) "
						+" LEFT JOIN HRMS_TITLE AS2  ON(AS1.EMP_TITLE_CODE = AS2.TITLE_CODE) "
						+" WHERE APPR_ID = ?  AND PAS_APPR_ELIGIBLE_EMP.APPR_EMP_ID = ? " ;	
		
		case 3: return " SELECT PAS_APPR_APPRAISER_GRP_DTL.APPR_APPRAISER_GRP_ID FROM PAS_APPR_APPRAISER_GRP_DTL "
						+" LEFT JOIN PAS_APPR_APPRAISER_GRP_HDR ON (PAS_APPR_APPRAISER_GRP_DTL.APPR_APPRAISER_GRP_ID = PAS_APPR_APPRAISER_GRP_HDR.APPR_APPRAISER_GRP_ID ) "
						+" WHERE APPR_APPRAISEE_ID = ? AND APPR_ID = ?  ";
		
				
		case 4: return " SELECT APPR_APPRAISER_CODE,(HRMS_TITLE .TITLE_NAME||' '||HRMS_EMP_OFFC.EMP_FNAME||' '||NVL(HRMS_EMP_OFFC.EMP_MNAME,' ')|| ' ' || HRMS_EMP_OFFC.EMP_LNAME), "
						+" NVL(HRMS_RANK.RANK_NAME,'  '),APPR_PHASE_NAME,APPR_APPRAISER_LEVEL " 
						+" FROM PAS_APPR_APPRAISER "
						+" LEFT JOIN HRMS_EMP_OFFC ON (PAS_APPR_APPRAISER.APPR_APPRAISER_CODE = HRMS_EMP_OFFC.EMP_ID) "
						+" LEFT JOIN HRMS_TITLE  ON(HRMS_EMP_OFFC.EMP_TITLE_CODE = HRMS_TITLE .TITLE_CODE) "
						+" LEFT JOIN PAS_APPR_PHASE_CONFIG ON (PAS_APPR_APPRAISER.APPR_PHASE_ID = PAS_APPR_PHASE_CONFIG.APPR_PHASE_ID) "
						+" LEFT JOIN HRMS_RANK ON(HRMS_EMP_OFFC.EMP_RANK=HRMS_RANK.RANK_ID)"
						+" WHERE PAS_APPR_APPRAISER.APPR_ID= ? AND APPR_APPRAISER_GRP_ID= ? AND APPR_PHASE_STATUS = 'A' " 
						+" ORDER BY APPR_PHASE_ORDER,APPR_APPRAISER_LEVEL ";
		
		case 5: return " SELECT DISTINCT PAS_APPR_EMP_GRP_HDR.APPR_TEMPLATE_ID,APPR_INSTRUCTION_FLAG FROM PAS_APPR_EMP_GRP_DTL "
						+" LEFT JOIN PAS_APPR_EMP_GRP_HDR ON (PAS_APPR_EMP_GRP_DTL.APPR_EMP_GRP_ID = PAS_APPR_EMP_GRP_HDR.APPR_EMP_GRP_ID) "
						+" LEFT JOIN PAS_APPR_QUES_MAPPING ON (PAS_APPR_EMP_GRP_DTL.APPR_EMP_GRP_ID = PAS_APPR_QUES_MAPPING.APPR_EMP_GRP_ID) "
						+" LEFT JOIN PAS_APPR_TEMPLATE ON (PAS_APPR_QUES_MAPPING.APPR_TEMPLATE_ID = PAS_APPR_TEMPLATE.APPR_TEMPLATE_ID) "
						+" WHERE APPR_EMP_GRP_EMPID = ? AND PAS_APPR_EMP_GRP_HDR.APPR_ID = ?  ";
						
		
		case 6 : return " SELECT PAS_APPR_PHASE_CONFIG.APPR_PHASE_ID,PAS_APPR_PHASE_CONFIG.APPR_PHASE_NAME,  "
						+" TO_CHAR(APPR_PHASE_START_DATE,'DD-MM-YYYY'),TO_CHAR(APPR_PHASE_END_DATE,'DD-MM-YYYY'),APPR_PHASE_LOCK,NVL(APPR_QUESWT_DISPLAY_FLAG,'N'),PAS_APPR_PHASE_CONFIG.APPR_PHASE_ORDER " 
						+" FROM PAS_APPR_PHASE_CONFIG " 
						+" LEFT JOIN PAS_APPR_PHASE_SCHEDULE ON (PAS_APPR_PHASE_SCHEDULE.APPR_PHASE_ID = PAS_APPR_PHASE_CONFIG.APPR_PHASE_ID ) "
						+" WHERE PAS_APPR_PHASE_CONFIG.APPR_ID = ? AND  APPR_PHASE_STATUS='A' AND PAS_APPR_PHASE_CONFIG.APPR_PHASE_ID = ? ORDER BY  APPR_PHASE_ORDER ";

		
		case 7 : return " SELECT APPR_CAL_CODE, TO_CHAR(APPR_CAL_START_DATE,'DD-MM-YYYY'),TO_CHAR(APPR_CAL_END_DATE,'DD-MM-YYYY'), "
						+ " TO_CHAR(APPR_CAL_VALID_DATE,'DD-MM-YYYY')  FROM PAS_APPR_CALENDAR "
						+ " WHERE PAS_APPR_CALENDAR.APPR_ID = ? ";
		
		case 8: return " UPDATE PAS_APPR_TRACKING SET PHASE_FORWARD='N'  WHERE APPR_ID = ? AND TEMPLATE_CODE = ? AND PHASE_ID = ? AND EMP_ID = ? ";
						
						
		//case 9: return " SELECT APPR_RATING_VALU,APPR_RATING_DESC from PAS_APPR_QUESTION_RATING_DTL WHERE APPR_ID = ? ";
		
		case 9: return " SELECT * FROM PAS_APPR_QUESTION_RATING_HDR WHERE APPR_ID = ? ";
		
		case 10: return  " SELECT  DISTINCT APPR_CAL_CODE, TO_CHAR(APPR_CAL_START_DATE,'DD-MM-YYYY'),TO_CHAR(APPR_CAL_END_DATE,'DD-MM-YYYY'),PAS_APPR_PHASE_SCHEDULE.APPR_ID, "
					+ " TO_CHAR(APPR_CAL_VALID_DATE,'DD-MM-YYYY')  FROM PAS_APPR_PHASE_SCHEDULE "
					+ " LEFT JOIN PAS_APPR_CALENDAR  ON (PAS_APPR_PHASE_SCHEDULE.APPR_ID = PAS_APPR_CALENDAR.APPR_ID) "
					+" INNER JOIN PAS_APPR_ELIGIBLE_EMP ON  (PAS_APPR_CALENDAR.APPR_ID = PAS_APPR_ELIGIBLE_EMP.APPR_ID AND APPR_EMP_ID =  ? )"
					+ " and  PAS_APPR_PHASE_SCHEDULE.APPR_ID = ? ";

		case 11 : return " DELETE FROM PAS_APPR_SCORE WHERE APPR_ID = ? AND TEMPLATE_CODE	= ? AND EMP_ID = ? ";
		
		case 12: return " DELETE FROM PAS_APPR_TRACKING WHERE APPR_ID = ? AND TEMPLATE_CODE	= ? AND EMP_ID = ? ";
		
		
		
		default : return "";
		}
	}

}
