package org.paradyne.sql.PAS;

import org.paradyne.lib.SqlBase;

public class ApprFormStartModelSql extends SqlBase {
	
	public String getQuery(int i){
		
		switch(i){
		
				
		/*case 1 : return " SELECT  DISTINCT APPR_CAL_CODE, TO_CHAR(APPR_CAL_START_DATE,'DD-MM-YYYY'),TO_CHAR(APPR_CAL_END_DATE,'DD-MM-YYYY'),PAS_APPR_PHASE_SCHEDULE.APPR_ID, "  
						+" TO_CHAR(APPR_CAL_VALID_DATE,'DD-MM-YYYY')  FROM PAS_APPR_PHASE_SCHEDULE "  
						+" INNER JOIN PAS_APPR_CALENDAR  ON (PAS_APPR_PHASE_SCHEDULE.APPR_ID = PAS_APPR_CALENDAR.APPR_ID) "  
						+" INNER JOIN PAS_APPR_ELIGIBLE_EMP ON  (PAS_APPR_CALENDAR.APPR_ID = PAS_APPR_ELIGIBLE_EMP.APPR_ID  AND PAS_APPR_ELIGIBLE_EMP.APPR_EMP_ID = ? ) " 
						+" LEFT JOIN PAS_APPR_TRACKING ON (PAS_APPR_TRACKING.APPR_ID = PAS_APPR_PHASE_SCHEDULE.APPR_ID ) "
						+" WHERE  PAS_APPR_PHASE_SCHEDULE.APPR_ID NOT IN (SELECT distinct PAS_APPR_COMMENTS.APPR_ID FROM PAS_APPR_COMMENTS WHERE APPR_EMP_ID = ? ) "
						+" ORDER BY PAS_APPR_PHASE_SCHEDULE.APPR_ID ";*/
		
		
		case 1 : return "  SELECT  DISTINCT APPR_CAL_CODE, TO_CHAR(APPR_CAL_START_DATE,'DD-MM-YYYY'),TO_CHAR(APPR_CAL_END_DATE,'DD-MM-YYYY'),PAS_APPR_PHASE_SCHEDULE.APPR_ID, "   
						+" TO_CHAR(APPR_CAL_VALID_DATE,'DD-MM-YYYY')  FROM PAS_APPR_PHASE_SCHEDULE "  
						+" INNER JOIN PAS_APPR_CALENDAR  ON (PAS_APPR_PHASE_SCHEDULE.APPR_ID = PAS_APPR_CALENDAR.APPR_ID) "  
						+" INNER JOIN PAS_APPR_ELIGIBLE_EMP ON  (PAS_APPR_CALENDAR.APPR_ID = PAS_APPR_ELIGIBLE_EMP.APPR_ID  AND PAS_APPR_ELIGIBLE_EMP.APPR_EMP_ID = ? )" 
						+" WHERE  PAS_APPR_PHASE_SCHEDULE.APPR_ID NOT IN (SELECT distinct PAS_APPR_TRACKING.APPR_ID FROM PAS_APPR_TRACKING WHERE EMP_ID = ? ) "
						+" ORDER BY PAS_APPR_PHASE_SCHEDULE.APPR_ID";
		
		case 2 : return " SELECT PAS_APPR_COMMENTS.APPR_ID FROM PAS_APPR_COMMENTS WHERE APPR_EMP_ID = ? ";
		
		default : return "";
		
		}
	}

}
