package org.paradyne.sql.PAS;


import org.paradyne.lib.SqlBase;

public class ApprFormCareerProgressionModelSql extends SqlBase {

	
	public String getQuery(int i){
		
		switch(i){
		
		
		case 1 : return " SELECT APPR_CAREER_FLAG FROM PAS_APPR_TEMPLATE WHERE APPR_ID=? AND APPR_TEMPLATE_ID=?";
		
		case 2 : return " SELECT APPR_PHASE_VISIBILITY, APPR_PHASE_COMMENT FROM PAS_APPR_COMMON_SECTION "
		   				+" WHERE APPR_ID = ? AND APPR_TEMPLATE_ID= ? AND APPR_PHASE = ? AND APPR_SECTION_TYPE = 'C'";
		
		case 3 : return "SELECT PAS_APPR_CAREER.APPR_QUESTION_CODE,NVL(APPR_QUES_DESC,' '),APPR_ANSWER_CHAR_LIMIT, PAS_APPR_CAREER.APPR_CAREER_ID,"
					   +" PAS_APPR_CAREER_COMMENT.APPR_CAREER_ID AS CAREER_COMMENT_CAREER_ID,NVL(APPR_CAREER_COMMENT,' '),APPR_EMP_ID FROM PAS_APPR_CAREER"
					   +" LEFT JOIN PAS_APPR_CAREER_COMMENT ON(PAS_APPR_CAREER_COMMENT.APPR_ID=PAS_APPR_CAREER.APPR_ID AND"
					   +" PAS_APPR_CAREER_COMMENT.APPR_TEMPLATE_ID = PAS_APPR_CAREER.APPR_TEMPLATE_ID AND"
					   +" PAS_APPR_CAREER_COMMENT.APPR_QUESTION_CODE = PAS_APPR_CAREER.APPR_QUESTION_CODE AND"
					   +" PAS_APPR_CAREER_COMMENT.APPR_CAREER_ID = PAS_APPR_CAREER_COMMENT.APPR_CAREER_ID AND"
					   +" APPR_PHASE=? AND APPR_EMP_ID=? AND APPR_APPRAISER_ID IS NULL)"
					   +" INNER JOIN PAS_APPR_QUESTIONNAIRE ON(PAS_APPR_QUESTIONNAIRE.APPR_QUES_CODE = PAS_APPR_CAREER.APPR_QUESTION_CODE)"
					   +" WHERE PAS_APPR_CAREER.APPR_ID=? AND"
					   +" PAS_APPR_CAREER.APPR_TEMPLATE_ID=? ORDER BY APPR_CAREER_ID";
		
		case 4 : return " INSERT INTO PAS_APPR_CAREER_COMMENT(APPR_ID, APPR_TEMPLATE_ID, APPR_PHASE, APPR_EMP_ID, APPR_QUESTION_CODE, APPR_CAREER_COMMENT, APPR_CAREER_ID,APPR_APPRAISER_ID)"
					   +" VALUES(?,?,?,?,?,?,?,?)";
		
		case 5 : return "UPDATE PAS_APPR_CAREER_COMMENT SET APPR_CAREER_COMMENT=? WHERE APPR_ID=? AND APPR_TEMPLATE_ID=? AND APPR_PHASE=? AND APPR_EMP_ID=? AND APPR_QUESTION_CODE=? AND APPR_CAREER_ID=?";
		
		case 6 : return "SELECT APPR_IS_SELFPHASE FROM PAS_APPR_PHASE_CONFIG WHERE APPR_ID=? AND APPR_PHASE_ID=?";
		
		case 7 : return "SELECT PAS_APPR_CAREER.APPR_QUESTION_CODE,NVL(APPR_QUES_DESC,' '),APPR_ANSWER_CHAR_LIMIT, PAS_APPR_CAREER.APPR_CAREER_ID,"
					   +" PAS_APPR_CAREER_COMMENT.APPR_CAREER_ID AS CAREER_COMMENT_CAREER_ID,NVL(APPR_CAREER_COMMENT,' '),APPR_EMP_ID, APPR_PHASE_NAME FROM PAS_APPR_CAREER"
					   +" LEFT JOIN PAS_APPR_CAREER_COMMENT ON(PAS_APPR_CAREER_COMMENT.APPR_ID=PAS_APPR_CAREER.APPR_ID AND"
					   +" PAS_APPR_CAREER_COMMENT.APPR_TEMPLATE_ID = PAS_APPR_CAREER.APPR_TEMPLATE_ID AND"
					   +" PAS_APPR_CAREER_COMMENT.APPR_QUESTION_CODE = PAS_APPR_CAREER.APPR_QUESTION_CODE AND"
					   +" PAS_APPR_CAREER_COMMENT.APPR_CAREER_ID = PAS_APPR_CAREER_COMMENT.APPR_CAREER_ID AND"
					   +"  APPR_EMP_ID=?)"//APPR_PHASE NOT IN(?) AND
					   +" INNER JOIN PAS_APPR_QUESTIONNAIRE ON(PAS_APPR_QUESTIONNAIRE.APPR_QUES_CODE = PAS_APPR_CAREER.APPR_QUESTION_CODE)"
					   +" INNER JOIN PAS_APPR_PHASE_CONFIG ON(PAS_APPR_PHASE_CONFIG.APPR_PHASE_ID=PAS_APPR_CAREER_COMMENT.APPR_PHASE)"
					   +" WHERE PAS_APPR_CAREER.APPR_ID=? AND"
					   +" PAS_APPR_CAREER.APPR_TEMPLATE_ID=?  "
					   +" AND("
					   +" (PAS_APPR_PHASE_CONFIG.APPR_PHASE_ORDER < "
					   +"(SELECT APPR_PHASE_ORDER FROM PAS_APPR_PHASE_CONFIG WHERE APPR_PHASE_ID=?))" 
					   +" OR (PAS_APPR_PHASE_CONFIG.APPR_PHASE_ORDER = "
					   +"(SELECT APPR_PHASE_ORDER FROM PAS_APPR_PHASE_CONFIG WHERE APPR_PHASE_ID=? AND APPR_APPRAISER_ID!=? ) )"
					   +") "
					   +" ORDER BY APPR_PHASE_ORDER,APPR_CAREER_ID";
		
		case 8 : return "SELECT PAS_APPR_CAREER.APPR_QUESTION_CODE,NVL(APPR_QUES_DESC,' '),APPR_ANSWER_CHAR_LIMIT, PAS_APPR_CAREER.APPR_CAREER_ID,"
					   +" PAS_APPR_CAREER_COMMENT.APPR_CAREER_ID AS CAREER_COMMENT_CAREER_ID,NVL(APPR_CAREER_COMMENT,' '),APPR_EMP_ID FROM PAS_APPR_CAREER"
					   +" LEFT JOIN PAS_APPR_CAREER_COMMENT ON(PAS_APPR_CAREER_COMMENT.APPR_ID=PAS_APPR_CAREER.APPR_ID AND"
					   +" PAS_APPR_CAREER_COMMENT.APPR_TEMPLATE_ID = PAS_APPR_CAREER.APPR_TEMPLATE_ID AND"
					   +" PAS_APPR_CAREER_COMMENT.APPR_QUESTION_CODE = PAS_APPR_CAREER.APPR_QUESTION_CODE AND"
					   +" PAS_APPR_CAREER_COMMENT.APPR_CAREER_ID = PAS_APPR_CAREER_COMMENT.APPR_CAREER_ID AND"
					   +" APPR_PHASE=? AND APPR_EMP_ID=? AND APPR_APPRAISER_ID=? )"
					   +" INNER JOIN PAS_APPR_QUESTIONNAIRE ON(PAS_APPR_QUESTIONNAIRE.APPR_QUES_CODE = PAS_APPR_CAREER.APPR_QUESTION_CODE)"
					   +" WHERE PAS_APPR_CAREER.APPR_ID=? AND"
					   +" PAS_APPR_CAREER.APPR_TEMPLATE_ID=? ORDER BY APPR_CAREER_ID ";
		
		case 9 : return "UPDATE PAS_APPR_CAREER_COMMENT SET APPR_CAREER_COMMENT=? WHERE APPR_ID=? AND APPR_TEMPLATE_ID=? AND APPR_PHASE=? AND APPR_EMP_ID=? AND APPR_QUESTION_CODE=? AND APPR_CAREER_ID=? AND APPR_APPRAISER_ID=?";
		

		case 10 : return "SELECT PAS_APPR_PHASE_CONFIG.APPR_PHASE_ID, PAS_APPR_PHASE_CONFIG.APPR_PHASE_NAME, PAS_APPR_PHASE_CONFIG.APPR_PHASE_ORDER,APPR_APPRAISER_LEVEL FROM PAS_APPR_APPRAISER" 
						+" INNER JOIN PAS_APPR_PHASE_CONFIG ON (PAS_APPR_PHASE_CONFIG.APPR_ID=PAS_APPR_APPRAISER.APPR_ID AND"
						+" PAS_APPR_APPRAISER.APPR_PHASE_ID=PAS_APPR_PHASE_CONFIG.APPR_PHASE_ID"
						+")WHERE PAS_APPR_PHASE_CONFIG.APPR_ID=? AND" 
						+" PAS_APPR_PHASE_CONFIG.APPR_PHASE_ID=? AND"
						+" APPR_APPRAISER_CODE=?";

		
		default: return "";
		
		}
	}
	
}
