package org.paradyne.sql.PAS;
import org.paradyne.lib.SqlBase;

public class DisciplinaryMeasuresModelSql extends SqlBase{

	public String getQuery(int id){
		
		
		switch (id) {
		
				case 1 : return " SELECT APPR_CAL_CODE, APPR_CAL_START_DATE, APPR_CAL_END_DATE,APPR_ID FROM PAS_APPR_CALENDAR WHERE APPR_ID=?";
				
				case 2 : return " SELECT APPR_TEMPLATE_NAME,APPR_TEMPLATE_ID,APPR_ID FROM PAS_APPR_TEMPLATE WHERE APPR_ID=? AND APPR_TEMPLATE_ID=?";
			
				case 3: return " SELECT APPR_PHASE_NAME, PAS_APPR_PHASE_CONFIG.APPR_ID, APPR_PHASE_ID FROM PAS_APPR_PHASE_CONFIG "
							  +" INNER JOIN PAS_APPR_CALENDAR ON(PAS_APPR_CALENDAR.APPR_ID=PAS_APPR_PHASE_CONFIG.APPR_ID)"
							  +" WHERE PAS_APPR_CALENDAR.APPR_ID=? AND APPR_PHASE_STATUS='A'";
				
				case 4 : return " UPDATE PAS_APPR_TEMPLATE SET APPR_DISCIPLINARY_FLAG=? WHERE APPR_ID=? AND APPR_TEMPLATE_ID=?";
				
				case 5 : return " INSERT INTO PAS_APPR_COMMON_SECTION(APPR_ID, APPR_TEMPLATE_ID, APPR_PHASE, APPR_SECTION_TYPE, APPR_COMMONSECTION_ID, APPR_PHASE_VISIBILITY, APPR_PHASE_COMMENT) VALUES(?,?,?,'D',(SELECT NVL(MAX(APPR_COMMONSECTION_ID),0)+1 FROM PAS_APPR_COMMON_SECTION ),?,?)";
				
				
				case 6 : return " SELECT PAS_APPR_PHASE_CONFIG.APPR_PHASE_ID,NVL(APPR_PHASE_NAME,' '),NVL(APPR_SECTION_TYPE,' '), APPR_COMMONSECTION_ID, NVL(APPR_PHASE_VISIBILITY,' '), NVL(APPR_PHASE_COMMENT,' '),NVL(PAS_APPR_COMMON_SECTION.APPR_ID,0) "
							+" FROM PAS_APPR_PHASE_CONFIG" 
							+" LEFT JOIN  PAS_APPR_COMMON_SECTION ON(PAS_APPR_PHASE_CONFIG.APPR_ID = PAS_APPR_COMMON_SECTION.APPR_ID" 
							+" AND PAS_APPR_PHASE_CONFIG.APPR_PHASE_ID = PAS_APPR_COMMON_SECTION.APPR_PHASE AND PAS_APPR_COMMON_SECTION.APPR_TEMPLATE_ID=? AND APPR_SECTION_TYPE='D')" 
							+" WHERE PAS_APPR_PHASE_CONFIG .APPR_ID=? AND APPR_PHASE_STATUS='A'";
				
				case 7 : return " SELECT APPR_DISCIPLINARY_FLAG FROM PAS_APPR_TEMPLATE WHERE APPR_ID=? AND APPR_TEMPLATE_ID=?";
				
				
				case 8 : return " UPDATE PAS_APPR_COMMON_SECTION SET APPR_PHASE_VISIBILITY=?, APPR_PHASE_COMMENT=? WHERE APPR_ID=? AND APPR_TEMPLATE_ID=? AND APPR_PHASE=? AND APPR_SECTION_TYPE=? AND APPR_COMMONSECTION_ID=?";
					
				case 9 : return " INSERT INTO PAS_APPR_AWD_NOMINATE(APPR_ID, APPR_TEMPLATE_ID, APPR_AWARD_FLAG, APPR_REASON_FLAG)VALUES(?,?,?,?)";
									
				default: return "hi";
			
		}
		



	}
	
}
