package org.paradyne.sql.Promotion;

import org.paradyne.lib.SqlBase;

/**
 * @author ritac
 *
 */
public class PromotionModelSql extends SqlBase {
	
	public String getQuery(int i){
	switch(i){
	    case 1: return "INSERT INTO HRMS_PROMOTION(PROM_CODE,EMP_CODE,BRANCH_CODE,DEPT_CODE,DESG_CODE,GRADE_CODE,DIV_CODE," +
	    				"DATE_JOINING,REPORTING_TO,PROM_DATE,EFFECT_DATE,"+
	    			" PRO_BRANCH," +
	    			" PRO_DEPT,PRO_DESG,PRO_GRADE,PRO_DIV,PRO_REPORT_TO,PROPOSED_BY,APPROVED_BY,STRENGTH,WEAKNESS,RATING,TOTAL_OLD_AMOUNT,TOTAL_NEW_AMOUNT,LOCK_FLAG,PROM_FORMULA,PROM_GR0SSAMT,PROCESS_FLAG,PROM_SALGRADE,PROM_PROMFLAG,OLD_CTC,PROM_TEMPLATE,PRO_ROLE,CURRENT_ROLE)"+
	    			" VALUES(?,?,?,?,?,?,?,"+
	    			"to_date(?,'DD-MM-YYYY'),?,to_date(?,'DD-MM-YYYY'),to_date(?,'DD-MM-YYYY'),"+
	    			" ?,?,?,?,?,?,?,?,?,?,?,?,?,'N',?,?,?,?,?,?,?,?,?)";
	    
	    case 2:return "UPDATE HRMS_PROMOTION SET EMP_CODE=?,BRANCH_CODE=?,DEPT_CODE=?,DESG_CODE=?,GRADE_CODE=?,DIV_CODE=?,DATE_JOINING=TO_DATE(?,'DD-MM-YYYY'),REPORTING_TO=?,PROM_DATE=TO_DATE(?,'DD-MM-YYYY'),EFFECT_DATE=TO_DATE(?,'DD-MM-YYYY'),"+
	    			" PRO_BRANCH=?,PRO_DEPT=?,PRO_DESG=?,PRO_GRADE=?,PRO_DIV=?,PRO_REPORT_TO=?,PROPOSED_BY=?,APPROVED_BY=?,STRENGTH=?,WEAKNESS=?,RATING=?,TOTAL_OLD_AMOUNT=?,TOTAL_NEW_AMOUNT=?,PROM_FORMULA=? , PROM_GR0SSAMT =?,PROCESS_FLAG=?,PROM_SALGRADE=?,PROM_PROMFLAG=?, OLD_CTC=?,PROM_TEMPLATE=?,PRO_ROLE=?," +
	    			" CURRENT_ROLE=? WHERE PROM_CODE=?";
	   
	    case 3: return "DELETE FROM HRMS_PROMOTION WHERE PROM_CODE=?";
	    
	    
	    case 4: return "UPDATE HRMS_EMP_OFFC SET EMP_CENTER=?,EMP_DEPT=?,EMP_DESG=?,EMP_CADRE=?,EMP_DIV=?,EMP_REPORTING_OFFICER=?,EMP_SAL_GRADE=? WHERE EMP_ID=?";
	    case 5:/* return "SELECT (SELECT EMP_FNAME FROM HRMS_EMP_OFFC WHERE EMP_REPORTING_OFFICER = ? AND EMP_ID = ?)REPTO,"+
					" DEPT_NAME,HRMS_DESG.DESG_NAME ,CADRE_NAME,DIV_NAME,EMP_CENTER,EMP_DEPT,EMP_DESG,EMP_CADRE,EMP_DIV"+
					" FROM HRMS_EMP_OFFC"+
					" LEFT JOIN HRMS_CENTER ON(HRMS_CENTER.CENTER_ID=HRMS_EMP_OFFC.EMP_CENTER)"+
					" LEFT JOIN HRMS_DESG ON(HRMS_DESG.DESG_ID=HRMS_EMP_OFFC.EMP_DESG)"+
					" LEFT JOIN HRMS_CADRE ON(HRMS_CADRE.CADRE_ID=HRMS_EMP_OFFC.EMP_CADRE)"+
					" LEFT JOIN HRMS_DEPT ON(HRMS_DEPT.DEPT_ID=HRMS_EMP_OFFC.EMP_DEPT )"+
					" LEFT JOIN HRMS_DIVISION ON(HRMS_DIVISION.DIV_ID = HRMS_EMP_OFFC.EMP_DIV)"+
					" WHERE EMP_ID=?";*/
	    
	    case 6: /*SELECT DISTINCT  (SELECT EMP_FNAME FROM HRMS_EMP_OFFC WHERE EMP_REPORTING_OFFICER = 3 AND EMP_ID = 1) REPTO,CENTER_NAME,
		 DEPT_NAME,DESG_NAME ,CADRE_NAME,DIV_NAME,REPORTING_TO,
		 E1.EMP_FNAME||' '||E1.EMP_MNAME||' '||E1.EMP_LNAME PROREP ,  E2.EMP_FNAME||' '||E2.EMP_MNAME||' '||E2.EMP_LNAME PRO_BY,E3.EMP_FNAME||' '||E3.EMP_MNAME||' '||E3.EMP_LNAME APPR_BY
		 FROM HRMS_PROMOTION
		 LEFT JOIN HRMS_EMP_OFFC  ON(HRMS_EMP_OFFC.EMP_REPORTING_OFFICER= HRMS_PROMOTION.REPORTING_TO)
		
		 LEFT JOIN HRMS_CENTER ON(HRMS_CENTER.CENTER_ID=HRMS_PROMOTION.BRANCH_CODE)
		 LEFT JOIN HRMS_DESG ON(HRMS_DESG.DESG_ID=HRMS_PROMOTION.DESG_CODE)
		 LEFT JOIN HRMS_CADRE ON(HRMS_CADRE.CADRE_ID=HRMS_PROMOTION.GRADE_CODE)
		 LEFT JOIN HRMS_DEPT ON(HRMS_DEPT.DEPT_ID=HRMS_PROMOTION.DEPT_CODE)
		 LEFT JOIN HRMS_DIVISION ON(HRMS_DIVISION.DIV_ID = HRMS_PROMOTION.DIV_CODE)
		 LEFT JOIN HRMS_EMP_OFFC E1 ON(E1.EMP_ID= HRMS_PROMOTION.PRO_REPORT_TO)
		 LEFT JOIN HRMS_EMP_OFFC E2 ON(E2.EMP_ID= HRMS_PROMOTION.PROPOSED_BY)
		 LEFT JOIN HRMS_EMP_OFFC E3 ON(E3.EMP_ID= HRMS_PROMOTION.APPROVED_BY)
					 
		 WHERE PROM_CODE=1
	    	*/
	  
	    case 7: return "DELETE FROM HRMS_PROMOTION_SALARY WHERE PROM_CODE=?";
	    
	    case 8: return  "INSERT INTO HRMS_PROMOTION_SALARY(PROM_CODE,SAL_CODE,OLD_AMT,NEW_AMT)VALUES(?,?,?,?)  ";
	    
	    case 9: return " UPDATE HRMS_PROMOTION_SALARY SET SAL_CODE=?,OLD_AMT=?,NEW_AMT=? WHERE PROM_CODE=?";
	    	
		default:return "";
		}
	}

}
