package org.paradyne.sql.attendance;

import org.paradyne.lib.SqlBase;

public class AttendanceSettingsModelSql extends SqlBase {
	public String getQuery(int id){
		switch (id) {
		case 1 : return " UPDATE HRMS_ATTENDANCE_CONF SET CONF_LEAVE_CONNECT_FLAG = ?, CONF_DAILY_ATT_CONNECT_FLAG = ?, CONF_SALARY_START_DATE = ?, " +
		" CONF_SALARY_START_FLAG = ?, CONF_COMP_OFF = ?, CONF_BRANCH_HOLI_FLAG = ?, CONF_RECORDS_PER_PAGE = ?, CONF_LEAVE_MANGT_YEAR = ?, " +
		" CONF_UPLOAD_MONTH_ATT_FLAG = ?, CONF_PAIDLEAVES_LEAVEADJUST = ?, CONF_COMP_OFF_DAYS = ? , CONF_EMP_JOIN_BEFORE = ?, " +
		" CONF_LEAVE_ALERT = ?, CONF_LOGIN_ATTENDANCE_FLAG = ?, CONF_DEFAULT_DAYS_FLAG=?, CONF_LATE_REGULARIZE=?, CONF_HD_REGULARIZE=?, CONF_ABSENT_REGULARIZE=?, CONF_REG_TIME_REGULARIZE=?, CONF_WEEKLYOF_HOLI_REGULARIZE=?, CONF_SHOW_EXTRAWORK=? ,OUTDOOR_BLOCK_AFTER_DAYS=? ";
		
		case 2 : return " INSERT INTO HRMS_ATTENDANCESETTINGS_HDR (ATTSETTINGS_CODE, ATTSETTINGS_REPORTTYPE, ATTNSETTINGS_BRANCHCODE, " +
		" ATTNSETTINGS_DIVISIONCODE, ATTSETTINGS_DATEFORMAT, ATTSETTINGS_TIMEFORMAT, ATTSETTINGS_SHEETNUMBER) " +
		" VALUES((SELECT NVL(MAX(ATTSETTINGS_CODE),0)+1 FROM HRMS_ATTENDANCESETTINGS_HDR), ?, ?, ?, ?, ?, ?) ";
		
		case 3 : return " SELECT MAX(ATTSETTINGS_CODE) FROM HRMS_ATTENDANCESETTINGS_HDR ";
		
		case 4 : return " INSERT INTO HRMS_ATTENDANCESETTINGS_DTL(ATTSETTINGS_CODE, ATTSETTINGS_DTLCODE, ATTSETTINGS_FIELDTYPE, " +
		" ATTSETTINGS_FLAG, ATTSETTINGS_CHARFROM, ATTSETTINGS_CHARTO, ATTSETTINGS_COLUMNNO) " +
		" VALUES(?, (SELECT NVL(MAX(ATTSETTINGS_DTLCODE),0) + 1 FROM HRMS_ATTENDANCESETTINGS_DTL WHERE ATTSETTINGS_CODE = ?), ?, ?, " +
		" ?, ?, ?)";
		
		case 5 : return " SELECT ATTSETTINGS_CODE, ATTSETTINGS_DATEFORMAT, ATTSETTINGS_TIMEFORMAT, ATTSETTINGS_SHEETNUMBER " +
		" FROM HRMS_ATTENDANCESETTINGS_HDR " +
		" WHERE ATTSETTINGS_REPORTTYPE = ? AND ATTNSETTINGS_BRANCHCODE = ? AND ATTNSETTINGS_DIVISIONCODE = ? ";
		
		case 6 : return " SELECT ATTSETTINGS_FIELDTYPE, ATTSETTINGS_FLAG, NVL(ATTSETTINGS_CHARFROM, ' '), " +
		" NVL(ATTSETTINGS_CHARTO, ' '), NVL(ATTSETTINGS_COLUMNNO, ' ') FROM HRMS_ATTENDANCESETTINGS_DTL " +
		" WHERE ATTSETTINGS_CODE = ? ORDER BY ATTSETTINGS_FIELDTYPE ";
		
		case 7 : return " SELECT CONF_DAILY_ATT_CONNECT_FLAG, NVL(CONF_SALARY_START_DATE, '1') AS START_DATE, CONF_SALARY_START_FLAG, " +
		" CONF_COMP_OFF, NVL(LEAVE_NAME, ' ') LEAVE, CONF_LEAVE_CONNECT_FLAG, CONF_BRANCH_HOLI_FLAG, CONF_RECORDS_PER_PAGE, CONF_LEAVE_MANGT_YEAR, " +
		" CONF_UPLOAD_MONTH_ATT_FLAG, NVL(CONF_PAIDLEAVES_LEAVEADJUST, 0), NVL(CONF_COMP_OFF_DAYS, 0), CONF_EMP_JOIN_BEFORE, " +
		" NVL(CONF_LEAVE_ALERT,0), CONF_LOGIN_ATTENDANCE_FLAG, NVL(CONF_DEFAULT_DAYS_FLAG,'A'), CONF_LATE_REGULARIZE, CONF_HD_REGULARIZE, CONF_ABSENT_REGULARIZE, CONF_REG_TIME_REGULARIZE, CONF_WEEKLYOF_HOLI_REGULARIZE, CONF_SHOW_EXTRAWORK ,NVL(OUTDOOR_BLOCK_AFTER_DAYS,0)  " +
		" FROM HRMS_ATTENDANCE_CONF " +
		" LEFT JOIN HRMS_LEAVE ON (HRMS_LEAVE.LEAVE_ID = HRMS_ATTENDANCE_CONF.CONF_COMP_OFF) ";
		
		case 8 : return " UPDATE HRMS_ATTENDANCESETTINGS_HDR SET ATTSETTINGS_REPORTTYPE = ?, ATTNSETTINGS_BRANCHCODE = ?, " +
		" ATTNSETTINGS_DIVISIONCODE = ?, ATTSETTINGS_DATEFORMAT = ?, ATTSETTINGS_TIMEFORMAT = ?, ATTSETTINGS_SHEETNUMBER = ? " +
		" WHERE ATTSETTINGS_CODE = ?";
		
		case 9 : return " DELETE FROM HRMS_ATTENDANCESETTINGS_DTL WHERE ATTSETTINGS_CODE = ? ";
		
		case 10 : return " SELECT DISTINCT LEAVE_ID, LEAVE_NAME, LEAVE_ABBR FROM HRMS_LEAVE " +
		" INNER JOIN HRMS_LEAVE_POLICY_DTL ON (HRMS_LEAVE_POLICY_DTL.LEAVE_CODE = HRMS_LEAVE.LEAVE_ID) " +
		" WHERE LEAVE_PAID_UNPAID = 'P' ORDER BY  LEAVE_ID ";
		
		case 11 : return " INSERT INTO HRMS_ATTENDANCE_CONF (CONF_LEAVE_CONNECT_FLAG, CONF_DAILY_ATT_CONNECT_FLAG, " +
		" CONF_SALARY_START_DATE, CONF_SALARY_START_FLAG, CONF_COMP_OFF, CONF_BRANCH_HOLI_FLAG, CONF_RECORDS_PER_PAGE, " +
		" CONF_LEAVE_MANGT_YEAR, CONF_UPLOAD_MONTH_ATT_FLAG, CONF_PAIDLEAVES_LEAVEADJUST, CONF_COMP_OFF_DAYS, CONF_EMP_JOIN_BEFORE, " +
		" CONF_LEAVE_ALERT, CONF_LOGIN_ATTENDANCE_FLAG, CONF_DEFAULT_DAYS_FLAG, CONF_LATE_REGULARIZE, CONF_HD_REGULARIZE, CONF_ABSENT_REGULARIZE, CONF_REG_TIME_REGULARIZE, CONF_WEEKLYOF_HOLI_REGULARIZE, CONF_SHOW_EXTRAWORK,OUTDOOR_BLOCK_AFTER_DAYS ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? , ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?) ";
		
		default: return "";

		}
	}
}