package org.paradyne.sql.attendance;

import org.paradyne.lib.SqlBase;

public class UploadAttendanceModelSql extends SqlBase {
	public String getQuery(int id) {
		switch(id) {
			case 1 : return " SELECT ATTSETTINGS_CODE, ATTSETTINGS_ROWNUMBER, ATTSETTINGS_SHEETNUMBER, ATTSETTINGS_DATEFORMAT, ATTSETTINGS_TIMEFORMAT " + 
			" FROM HRMS_ATTENDANCESETTINGS_HDR WHERE ATTNSETTINGS_BRANCHCODE = ? AND ATTNSETTINGS_DIVISIONCODE = ? AND ATTSETTINGS_REPORTTYPE = ? ";

			case 2 : return " SELECT ATTSETTINGS_FIELDTYPE, DECODE(ATTSETTINGS_FLAG, 'Y', 'true', 'N', 'false'), NVL(ATTSETTINGS_CHARFROM, ' '), " +
			" NVL(ATTSETTINGS_CHARTO, ' '), " + "NVL(ATTSETTINGS_COLUMNNO, ' ') FROM HRMS_ATTENDANCESETTINGS_DTL WHERE ATTSETTINGS_CODE = ? " +
			" ORDER BY ATTSETTINGS_DTLCODE ";

			case 3 : return " DELETE FROM HRMS_ATTENDANCE_TEMP ";

			case 4 : return " INSERT INTO HRMS_ATTENDANCE_TEMP (TEMP_ATT_EMP_CODE, TEMP_ATT_DATE, TEMP_ATT_IN_TIME, TEMP_ATT_OUT_TIME, " +
			" TEMP_ATT_WORK_HRS, TEMP_ATT_ONE_TIME, TEMP_ATT_IO_FLAG, TEMP_ATT_SHIFT, TEMP_ATT_BRANCH, TEMP_ATT_DIVISION) " +
			" VALUES (?, TO_DATE(?, 'DD-MM-YYYY'), TO_DATE(?, 'DD-MM-YYYY HH24:MI:SS'), TO_DATE(?, 'DD-MM-YYYY HH24:MI:SS'), TO_DATE(?, 'HH24:MI:SS'), " +
			" TO_DATE(?, 'HH24:MI:SS'), ?, ?, ?, ?)";

			case 5 : return " SELECT DISTINCT TEMP_ATT_EMP_CODE EMP_CODE, EMP_ID, TO_CHAR(TEMP_ATT_DATE, 'DD-MM-YYYY') ATT_DATE, EMP_SHIFT, " +
			" SHIFT_START_TIME, SHIFT_END_TIME, SHIFT_FIRST_HALF_DAY, SHIFT_SECOND_HALF_DAY, " +
			" CASE WHEN TEMP_ATT_IN_TIME IS NULL AND TEMP_ATT_OUT_TIME IS NULL THEN MIN(TEMP_ATT_ONE_TIME) ELSE TEMP_ATT_IN_TIME END IN_TIME, " +
			" CASE WHEN TEMP_ATT_IN_TIME IS NULL AND TEMP_ATT_OUT_TIME IS NULL THEN MAX(TEMP_ATT_ONE_TIME) ELSE TEMP_ATT_OUT_TIME END OUT_TIME " + 
			" FROM HRMS_ATTENDANCE_TEMP " +
			" INNER JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_TOKEN = HRMS_ATTENDANCE_TEMP.TEMP_ATT_EMP_CODE) " +
			" INNER JOIN HRMS_SHIFT ON(HRMS_SHIFT.SHIFT_ID = HRMS_EMP_OFFC.EMP_SHIFT) " +
			" GROUP BY TEMP_ATT_EMP_CODE, EMP_ID, TEMP_ATT_DATE, EMP_SHIFT, SHIFT_START_TIME, TEMP_ATT_IN_TIME, TEMP_ATT_OUT_TIME, SHIFT_END_TIME, " +
			" SHIFT_FIRST_HALF_DAY, SHIFT_SECOND_HALF_DAY ORDER BY TEMP_ATT_EMP_CODE";

			//case 9 : return " DELETE FROM HRMS_DAILY_ATTENDANCE_2007 ";

			case 12 : return " SELECT SHIFT_WEEK_1, SHIFT_WEEK_2, SHIFT_WEEK_3, SHIFT_WEEK_4, SHIFT_WEEK_5, SHIFT_WEEK_6 " +
			" FROM HRMS_SHIFT WHERE SHIFT_ID = ? ";

			case 13 : return " SELECT CASE WHEN HOLI_DATE = TO_DATE(?, 'DD-MM-YYYY') THEN 'TRUE' ELSE 'FALSE' END FROM HRMS_HOLIDAY_BRANCH " +
			" WHERE CENTER_ID = (SELECT EMP_CENTER FROM HRMS_EMP_OFFC WHERE EMP_ID = ?) AND HOLI_DATE = TO_DATE(?, 'DD-MM-YYYY') ";

			case 14 : return " SELECT CASE WHEN HOLI_DATE = TO_DATE(?, 'DD-MM-YYYY') THEN 'TRUE' ELSE 'FALSE' END FROM HRMS_HOLIDAY " +
			" WHERE HOLI_DATE = TO_DATE(?, 'DD-MM-YYYY') ";
				
			case 15 : return " SELECT AUTO_UPLOAD_ID, AUTO_UPLOAD_SERVER FROM HRMS_ATTENDANCE_AUTO_UPLOAD ORDER BY AUTO_UPLOAD_ID ";
			
			case 16 : return " SELECT AUTO_UPLOAD_DRIVER, AUTO_UPLOAD_SERVER, AUTO_UPLOAD_USER_NAME, AUTO_UPLOAD_PASSWORD, AUTO_UPLOAD_DATABASE, " +
			" AUTO_UPLOAD_PORT, AUTO_UPLOAD_TABLE FROM HRMS_ATTENDANCE_AUTO_UPLOAD WHERE AUTO_UPLOAD_ID = ? ";
			
			case 17 : return " SELECT AUTO_UPLOAD_DTL_FIELDTYPE, DECODE(AUTO_UPLOAD_DTL_FLAG, 'Y', 'true', 'N', 'false') AS AUTO_UPLOAD_DTL_FLAG, " +
			" AUTO_UPLOAD_DTL_FIELD FROM HRMS_ATT_AUTO_UPLOAD_DTL WHERE AUTO_UPLOAD_ID = ? ORDER BY AUTO_UPLOAD_DTL_ID ";

			default : return "";
		}
	}
}