package org.paradyne.sql.MPrecruitment;

import org.paradyne.lib.SqlBase;

public class OfficalDtlModelSql extends SqlBase {
	
	
	public String getQuery(int id) {
		switch (id) {

		case 1: return " INSERT INTO HRMS_MP_RECRUITMENT(RECRUITMENT_ID, RECRUITMENT_APPNO, RECRUITMENT_APPDATE,RECRUITMENT_ENTREE_FEE, "
				  +" RECRUITMENT_BANKNAME , RECRUITMENT_DRAFT_NO, RECRUITMENT_DRAFT_DATE, RECRUITMENT_FNAME, RECRUITMENT_MNAME, "
				  +" RECRUITMENT_LNAME,RECRUITMENT_TEMP_ADDRESS, RECRUITMENT_TEMP_TALUKA, RECRUITMENT_TEMP_DIST, RECRUITMENT_TEMP_PIN , " 
				  +" RECRUITMENT_TEMP_TELPHONE, RECRUITMENT_TEMP_MOBILE, RECRUITMENT_TEMP_EMAIL, RECRUITMENT_PER_ADDRESS, "
				  +" RECRUITMENT_PER_TALUKA, RECRUITMENT_PER_DIST, RECRUITMENT_PER_PIN, RECRUITMENT_PER_TELPHONE , "
				  +" RECRUITMENT_PER_MOBILE, RECRUITMENT_EMP_DOB , RECRUITMENT_DOB_LOCATION,RECRUITMENT_AGE_YEAR, "
				  +" RECRUITMENT_AGE_MONTH, RECRUITMENT_AGE_DAY, RECRUITMENT_EMP_GENDER ,RECRUITMENT_IMAGE_PATH ) "
				  +" VALUES( ? ,?,TO_DATE(?,'DD-MM-YYYY'),?,?,?,TO_DATE(?,'DD-MM-YYYY'),?,?,? ," 
				  + "?,?,?,?,?,?,?,?,?,?,?,?,?,TO_DATE(?,'DD-MM-YYYY'),?,?,?,?,?,?)  ";
		
		case 2: return " UPDATE  HRMS_MP_RECRUITMENT SET  RECRUITMENT_APPNO = ?, RECRUITMENT_APPDATE = TO_DATE(?,'DD-MM-YYYY'),RECRUITMENT_ENTREE_FEE = ?, "
		  +" RECRUITMENT_BANKNAME = ? , RECRUITMENT_DRAFT_NO  = ?, RECRUITMENT_DRAFT_DATE  = TO_DATE (?,'DD-MM-YYYY'), RECRUITMENT_FNAME  = ?, RECRUITMENT_MNAME  = ? , "
		  +" RECRUITMENT_LNAME = ?,RECRUITMENT_TEMP_ADDRESS = ?, RECRUITMENT_TEMP_TALUKA = ?, RECRUITMENT_TEMP_DIST = ?, RECRUITMENT_TEMP_PIN = ? , " 
		  +" RECRUITMENT_TEMP_TELPHONE = ?, RECRUITMENT_TEMP_MOBILE = ? , RECRUITMENT_TEMP_EMAIL = ? , RECRUITMENT_PER_ADDRESS = ? , "
		  +" RECRUITMENT_PER_TALUKA = ? , RECRUITMENT_PER_DIST = ? , RECRUITMENT_PER_PIN = ? , RECRUITMENT_PER_TELPHONE = ? , "
		  +" RECRUITMENT_PER_MOBILE = ? , RECRUITMENT_EMP_DOB = TO_DATE(?,'DD-MM-YYYY') , RECRUITMENT_DOB_LOCATION = ? ,RECRUITMENT_AGE_YEAR = ? , "
		  +" RECRUITMENT_AGE_MONTH = ?, RECRUITMENT_AGE_DAY = ? , RECRUITMENT_EMP_GENDER = ? ,RECRUITMENT_IMAGE_PATH = ? WHERE RECRUITMENT_ID = ? ";
		 
		case 3: return " DELETE FROM HRMS_MP_RECRUITMENT WHERE RECRUITMENT_ID = ? ";  
		 
		default:  return "Query Not Found";
		}
	}

}
