package org.paradyne.sql.MPrecruitment;

import org.paradyne.lib.SqlBase;

public class OtherInfoModelSql extends SqlBase {

	public String getQuery(int id) {
		switch (id) {

		case 1:
			return "INSERT INTO HRMS_MP_OTHER_INFO(OTHER_INFO_ID,OTHER_INFO_DOMICLE,OTHER_INFO_CLASS,OTHER_INFO_CLASS_HOMEGUARD,OTHER_INFO_CLASS_MILITRY, "
					+ " OTHER_INFO_CLASS_PROJECT,OTHER_INFO_CLASS_EARTHQUAKE,OTHER_INFO_SPORT,OTHER_INFO_HEAVYWT_LICENSE,OTHER_INFO_LIGHTWT_LICENSE,OTHER_INFO_JOBEXP,OTHER_INFO_SWIMMING,"
					+ "OTHER_INFO_NCC_CERT,OTHER_INFO_SERVICE_PLAN_NO,OTHER_INFO_SERVICE_PLAN_DATE,OTHER_INFO_SERVICE_RENEW_DATE,OTHER_INFO_RELOCATION,"
					+ "OTHER_INFO_ARRESTED,OTHER_INFO_RESTRICTION_EXAM,OTHER_INFO_RESTRICTION_UNIVER,OTHER_INFO_POLICE_ACTION,OTHER_INFO_COURT,OTHER_INFO_RECRUIT_ID)"
					+ " VALUES((SELECT NVL(MAX(OTHER_INFO_ID),0)+1 FROM HRMS_MP_OTHER_INFO),?,?,?,?,?,?,?,?,?,?,?,?,?,to_date(?,'DD-MM-YYYY'),to_date(?,'DD-MM-YYYY'),?,?,?,?,?,?,?)";

		case 2:
			return " UPDATE HRMS_MP_OTHER_INFO SET OTHER_INFO_DOMICLE = ?, OTHER_INFO_CLASS = ? ,OTHER_INFO_CLASS_HOMEGUARD = ? ,OTHER_INFO_CLASS_MILITRY = ?,"
					+ "OTHER_INFO_CLASS_PROJECT = ? ,OTHER_INFO_CLASS_EARTHQUAKE = ? ,OTHER_INFO_SPORT = ?,OTHER_INFO_HEAVYWT_LICENSE = ? ,OTHER_INFO_LIGHTWT_LICENSE = ? ,OTHER_INFO_JOBEXP = ?,"
					+ "OTHER_INFO_SWIMMING = ? ,OTHER_INFO_NCC_CERT = ? ,OTHER_INFO_SERVICE_PLAN_NO = ?,OTHER_INFO_SERVICE_PLAN_DATE = TO_DATE(?,'DD-MM-YYYY') ,OTHER_INFO_SERVICE_RENEW_DATE = TO_DATE(?,'DD-MM-YYYY'),OTHER_INFO_RELOCATION = ?,"
					+ " OTHER_INFO_ARRESTED = ? ,OTHER_INFO_RESTRICTION_EXAM = ? ,OTHER_INFO_RESTRICTION_UNIVER = ?,"
					+ "OTHER_INFO_POLICE_ACTION = ? ,OTHER_INFO_COURT = ? "
					+ " WHERE OTHER_INFO_ID = ? ";

		case 3: return " DELETE FROM HRMS_MP_SPORT WHERE SPORT_RECRUIT_ID=?";
		case 4: return " DELETE FROM HRMS_MP_JOB WHERE JOB_RECRUIT_ID=?";
		case 5: return " DELETE FROM HRMS_MP_NCC WHERE NCC_RECRUIT_ID=?";

		default:
			return "";		}
	}
}
