package org.paradyne.sql.recruitment;

import org.paradyne.lib.SqlBase;

public class ApplicationFormModelSql extends SqlBase {
	public String getQuery(int id) {
		switch(id) {
		
		case 1 : return "SELECT LOCATION_CODE, LOCATION_NAME, LOCATION_PARENT_CODE FROM HRMS_LOCATION "
						+"WHERE LOCATION_CODE = ? "
						+"ORDER BY LOCATION_CODE";
		
		case 2 : return "UPDATE HRMS_CANDIDATE_HDR SET CANDIDATE_HDR_POST_CODE = ?, CANDIDATE_HDR_JOB_CODE = 1, "
						+"CANDIDATE_HDR_FNAME = ?, CANDIDATE_HDR_LNAME = ?, CANDIDATE_HDR_GENDER = ?, "
						+"CANDIDATE_HDR_DOB = TO_DATE(?,'DD-MM-YYYY'), CANDIDATE_HDR_ADDRESS1 = ?, CANDIDATE_HDR_ADDRESS2 = ?, CANDIDATE_HDR_ADDRESS3 = ?, " 
						+"CANDIDATE_HDR_CITY = ?, CANDIDATE_HDR_STATE = ?, CANDIDATE_HDR_COUNTRY = ?, CANDIDATE_HDR_PIN = ?, "
						+"CANDIDATE_HDR_EMAIL = ?, CANDIDATE_HDR_MOBILE = ?, CANDIDATE_HDR_PHONE = ?, CANDIDATE_HDR_EXP_YEAR = ?, "
						+"CANDIDATE_HDR_EXP_MONTH = ?, CANDIDATE_HDR_INDUSTRY = ?, CANDIDATE_HDR_FUNCTIONAL_AREA = ?, "
						+"CANDIDATE_HDR_JOB_ROLE = ?, CANDIDATE_HDR_KEY_SKILLS = ?, CANDIDATE_HDR_UPLOAD_RESUME = ?, "
						+"CANDIDATE_HDR_PASTE_RESUME = ?, CANDIDATE_HDR_STATUS = ? "
						+"WHERE CANDIDATE_HDR_CODE = ? ";
		
		case 3 : return "INSERT INTO HRMS_CANDIDATE_HDR (CANDIDATE_HDR_CODE) "
						+"VALUES((SELECT NVL(MAX(CANDIDATE_HDR_CODE),0)+1 FROM HRMS_CANDIDATE_HDR))";
		
		case 4 : return "SELECT MAX(CANDIDATE_HDR_CODE) FROM HRMS_CANDIDATE_HDR";
		
		case 5 : return "INSERT INTO HRMS_CANDIDATE_DTL (CANDIDATE_HDR_CODE, CANDIDATE_DTL_QUALIFICATION, CANDIDATE_DTL_QUALI_TYPE, "
						+"CANDIDATE_DTL_COMPELTION_YEAR, CANDIDATE_DTL_PERCENT, CANDIDATE_DTL_COLLEGE, CANDIDATE_DTL_UNIVERSITY, "
						+"CANDIDATE_DTL_SPECIALISATION) "
						+"VALUES(?, ?, ?, ?, ?, ?, ?, ?)";
		
		case 6 : return "SELECT CANDIDATE_DTL_QUALIFICATION, HRMS_QUA.QUA_NAME, CANDIDATE_DTL_QUALI_TYPE, CANDIDATE_DTL_COMPELTION_YEAR, "
						+"CANDIDATE_DTL_PERCENT, CANDIDATE_DTL_COLLEGE, CANDIDATE_DTL_UNIVERSITY, CANDIDATE_DTL_SPECIALISATION "
						+"FROM HRMS_CANDIDATE_DTL "
						+"INNER JOIN HRMS_QUA ON (HRMS_QUA.QUA_ID = CANDIDATE_DTL_QUALIFICATION) "
						+"WHERE CANDIDATE_HDR_CODE = ?";
		
		default : return "Framework could not the query number specified";			
		}
	}

}
