/**
 * 
 */
package org.paradyne.sql.recruitment;

import org.paradyne.lib.SqlBase;

/**
 * @author aa0540
 *
 */
public class AppointmentDetailsModelSql extends SqlBase {
	public String getQuery(int id){
		switch (id) {
		
			case 1 : return "SELECT REQS_NAME, RANK_NAME, DIV_NAME, CENTER_NAME, DEPT_NAME "
							+" ,RANK_ID,DIV_ID,CENTER_ID,DEPT_ID FROM HRMS_REC_REQS_HDR "
							+"INNER JOIN HRMS_RANK ON (HRMS_REC_REQS_HDR.REQS_POSITION = HRMS_RANK.RANK_ID) " 
							+"INNER JOIN HRMS_DIVISION ON (HRMS_REC_REQS_HDR.REQS_DIVISION = HRMS_DIVISION.DIV_ID) " 
							+"INNER JOIN HRMS_CENTER ON (HRMS_REC_REQS_HDR.REQS_BRANCH = HRMS_CENTER.CENTER_ID) " 
							+"INNER JOIN HRMS_DEPT ON (HRMS_REC_REQS_HDR.REQS_DEPT = HRMS_DEPT.DEPT_ID) "
							+"WHERE REQS_CODE = ?";
	
			case 2 : return "SELECT APPOINT_CAND_CODE, CAND_FIRST_NAME||' '||CAND_MID_NAME||' '||CAND_LAST_NAME NAME, "
							+"TO_CHAR(APPOINT_JOIN_DATE, 'DD-MM-YYYY'), TO_CHAR(SYSDATE, 'DD-MM-YYYY'), "
							+"TO_CHAR(APPOINT_DATE, 'DD-MM-YYYY'), APPOINT_CURR_CTC, APPOINT_NEG_CTC, APPOINT_STATUS, "
							+"APPOINT_JD, APPOINT_ROLES_RESP, APPOINT_EMP_TYPE, TYPE_NAME, APPOINT_HIRE_MANAGER, "
							+"HIREMGR.EMP_FNAME||' '||HIREMGR.EMP_MNAME||' '||HIREMGR.EMP_LNAME, "
							+"TO_CHAR(APPOINT_EXP_JOINDATE, 'DD-MM-YYYY'), APPOINT_REPORT_TO, "
							+"REPTO.EMP_FNAME||' '||REPTO.EMP_MNAME||' '||REPTO.EMP_LNAME, APPOINT_JOIN_FORM, "
							+"APPOINT_GRADE, CADRE_NAME, APPOINT_TEMPLATE, DECODE(APPOINT_PROBATION, 'Y', 'true', 'N', 'false'), "
							+"APPOINT_PROB_MONTHS, APPOINT_SIGN_AUTH, SIGN.EMP_FNAME||' '||SIGN.EMP_MNAME||' '||SIGN.EMP_LNAME, "
							+"R2.RANK_NAME, APPOINT_REMARKS, APPOINT_CONSTRAINTS, DECODE(APPOINT_BG_REQ, 'Y', 'true', 'N', 'false'), "
							+"APPOINT_OFFERED_CTC, "
							+"DECODE(APPOINT_STATUS, 'I ', 'Issued', 'OA', 'Accepted', 'OR', 'Rejected', 'C ', 'Canceled'), "
							+"HRMS_LETTERTEMPLATE_HDR.TEMPLATE_NAME, "
							+ " APPOINT_DIVISION, APPOINT_BRANCH, APPOINT_DEPT, APPOINT_POSITION,r1.RANK_NAME, DIV_NAME, CENTER_NAME, DEPT_NAME, "
							+" APPOINT_ADMIN_REPORTING_TO, ADMINREPTO.EMP_FNAME||' '||ADMINREPTO.EMP_MNAME||' '||ADMINREPTO.EMP_LNAME, APPOINT_ATTACHED_ANNEXURE, "
							+" CAND_EMAIL_ID, NVL(APPOINT_CAND_COMMENT,''), APPOINT_LETTER_AUTO_ID "
							+"FROM HRMS_REC_APPOINT " 
							+"INNER JOIN HRMS_REC_CAND_DATABANK ON (HRMS_REC_CAND_DATABANK.CAND_CODE = HRMS_REC_APPOINT.APPOINT_CAND_CODE) "
							+"LEFT JOIN HRMS_EMP_TYPE ON (HRMS_EMP_TYPE.TYPE_ID = APPOINT_EMP_TYPE) " 
							+"LEFT JOIN HRMS_EMP_OFFC HIREMGR ON (HIREMGR.EMP_ID = HRMS_REC_APPOINT.APPOINT_HIRE_MANAGER) "
							+"LEFT JOIN HRMS_EMP_OFFC REPTO ON (REPTO.EMP_ID = HRMS_REC_APPOINT.APPOINT_REPORT_TO) "
							+"LEFT JOIN HRMS_CADRE ON (HRMS_CADRE.CADRE_ID = HRMS_REC_APPOINT.APPOINT_GRADE) "
							+"LEFT JOIN HRMS_EMP_OFFC SIGN ON (SIGN.EMP_ID = HRMS_REC_APPOINT.APPOINT_SIGN_AUTH) "
							+"LEFT JOIN HRMS_RANK R2 ON (SIGN.EMP_RANK = R2.RANK_ID) "
							+"LEFT JOIN HRMS_LETTERTEMPLATE_HDR ON (HRMS_LETTERTEMPLATE_HDR.TEMPLATE_ID = APPOINT_TEMPLATE) "
							+"LEFT JOIN HRMS_EMAILTEMPLATE_HDR ON (HRMS_EMAILTEMPLATE_HDR.TEMPLATE_ID = APPOINT_EMAIL_TEMPLATE) " +
							 " INNER JOIN HRMS_RANK r1 ON (r1.RANK_ID = HRMS_REC_APPOINT.APPOINT_POSITION) "  
							+" INNER JOIN HRMS_DIVISION ON (HRMS_DIVISION.DIV_ID = HRMS_REC_APPOINT.APPOINT_DIVISION) "
							+" INNER JOIN HRMS_CENTER ON (HRMS_CENTER.CENTER_ID = HRMS_REC_APPOINT.APPOINT_BRANCH) "
							+" INNER JOIN HRMS_DEPT ON (HRMS_DEPT.DEPT_ID = HRMS_REC_APPOINT .APPOINT_DEPT) "
							+" LEFT JOIN HRMS_EMP_OFFC ADMINREPTO ON (ADMINREPTO.EMP_ID = HRMS_REC_APPOINT.APPOINT_ADMIN_REPORTING_TO) "
							+" WHERE APPOINT_CODE = ?"; 
			
			case 3 : return "INSERT INTO HRMS_REC_APPOINT (APPOINT_CODE, APPOINT_REQS_CODE, APPOINT_CAND_CODE, APPOINT_STATUS, "
							+"APPOINT_JD, APPOINT_ROLES_RESP, APPOINT_EMP_TYPE, APPOINT_HIRE_MANAGER, APPOINT_EXP_JOINDATE, "
							+"APPOINT_REPORT_TO, APPOINT_JOIN_FORM, APPOINT_GRADE, APPOINT_TEMPLATE, APPOINT_PROBATION, "
							+"APPOINT_PROB_MONTHS, APPOINT_SIGN_AUTH, APPOINT_REMARKS, APPOINT_CONSTRAINTS, APPOINT_APPR_STATUS, "
							+"APPOINT_BG_REQ, APPOINT_JOIN_DATE, APPOINT_CURR_CTC, APPOINT_NEG_CTC, APPOINT_OFFERED_CTC, "
							+"APPOINT_DATE,APPOINT_DIVISION, APPOINT_BRANCH, APPOINT_DEPT, " 
							+"APPOINT_POSITION,APPOINT_ADMIN_REPORTING_TO, APPOINT_KEEP_INFORMED, APPOINT_ATTACHED_ANNEXURE, APPOINT_LETTER_AUTO_ID) " 
							+"VALUES ((SELECT NVL(MAX(APPOINT_CODE), 0)+1 FROM HRMS_REC_APPOINT), ?, ?, ?, ?, "
							+"?, ?, ?, TO_DATE(?, 'DD-MM-YYYY'), ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, TO_DATE(?, 'DD-MM-YYYY'), "
							+"?, ?, ?, TO_DATE(?, 'DD-MM-YYYY'),?,?,?,?,?,?,?,?)";

			case 4 : return "UPDATE HRMS_REC_APPOINT SET APPOINT_STATUS = ?, APPOINT_JD = ?, APPOINT_ROLES_RESP = ?, "
							+"APPOINT_EMP_TYPE = ?, APPOINT_HIRE_MANAGER = ?, APPOINT_EXP_JOINDATE = TO_DATE(?, 'DD-MM-YYYY'), "
							+"APPOINT_REPORT_TO = ?, APPOINT_JOIN_FORM = ?, APPOINT_GRADE = ?, APPOINT_TEMPLATE = ?, APPOINT_PROBATION = ?, "
							+"APPOINT_PROB_MONTHS = ?, APPOINT_SIGN_AUTH = ?, APPOINT_REMARKS = ?, APPOINT_CONSTRAINTS = ?, "
							+"APPOINT_APPR_STATUS = ?, APPOINT_BG_REQ = ?, APPOINT_JOIN_DATE = TO_DATE(?, 'DD-MM-YYYY'), APPOINT_CURR_CTC = ?, "
							+"APPOINT_NEG_CTC = ?, APPOINT_OFFERED_CTC = ?, APPOINT_DATE = TO_DATE(?, 'DD-MM-YYYY') ," +
							 " APPOINT_DIVISION = ?, APPOINT_BRANCH = ?, APPOINT_DEPT = ?, APPOINT_POSITION = ?  ";
	
			default: return "";
		}
	}
}
