 package org.paradyne.sql.recruitment;

import org.paradyne.lib.SqlBase;

public class AppointmentAnalysisReportModelSql extends SqlBase {

	public String getQuery(int id) {
		// TODO Auto-generated method stub
		switch(id)
		{
		
			case 1: return "INSERT INTO HRMS_REC_APPOINTREP_FILTERS ( APPOINTREP_CODE, APPOINTREP_REQ_CODE, APPOINTREP_POSITION_CODE, "
						+" APPOINTREP_DATEOPTION, APPOINTREP_REQDATE_FROM, APPOINTREP_REQSTATUS, APPOINTREP_REPOPTION, APPOINTREP_NAME," 
						+" APPOINTREP_REQDATE_TO,APPOINTREP_USEREMPID, APPOINTREP_RADIO_OPTION, APPOINTREP_SELECTED_REQ) "
						+" VALUES ((SELECT NVL(MAX(APPOINTREP_CODE),0)+1 FROM HRMS_REC_APPOINTREP_FILTERS), ?,? , ? ,TO_DATE(?,'DD-MM-YYYY') ,? ,? , ?,TO_DATE(?,'DD-MM-YYYY') ,? ,?, ? )";
			
			case 2: return "  INSERT INTO HRMS_REC_APPOINTREP_SORT (APPOINTREP_CODE, SORT_BY, SORT_BY_ORDER,SORT_THENBY, SORT_THENBY_ORDER, SORT_THENBY1, "
						 +" SORT_THENBY1_ORDER) VALUES ( (SELECT NVL(MAX(APPOINTREP_CODE),0) FROM HRMS_REC_APPOINTREP_FILTERS), ?,?,?,?,?,?) ";
			
			case 3: return " INSERT INTO HRMS_REC_APPOINTREP_COLDEF ( APPOINTREP_CODE, COL_REQNAME,COL_POSITION, "
				   		  +"  COL_REQDATE,COL_NUMVAC,COL_APPOINT_DUE, COL_APPOINT_ISSUE, COL_APPOINT_ACCP, COL_APPOINT_REJECT, COL_APPOINT_CANCEL )" 
				   		  +"  VALUES ( (SELECT NVL(MAX(APPOINTREP_CODE),0) FROM HRMS_REC_APPOINTREP_FILTERS) , ? ,? , ?, ?, ?, ?, ?,? ,? )  ";
						
			case 4: return "  INSERT INTO HRMS_REC_APPOINTREP_ADV ( APPOINTREP_CODE, APPOINTREP_NOOFVAC_OPTION, APPOINTREP_NOOFVAC, APPOINTREP_DUE_OPTION, "
						+" APPOINTREP_DUE ,   APPOINTREP_ISSUE_OPTION, APPOINTREP_ISSUE, APPOINTREP_ACCP_OPTION,  APPOINTREP_ACCP, APPOINTREP_REJ_OPTION, APPOINTREP_REJECT, "
						+" APPOINTREP_CANCEL_OPTION, APPOINTREP_CANCEL) VALUES ((SELECT NVL(MAX(APPOINTREP_CODE),0) FROM HRMS_REC_APPOINTREP_FILTERS) ,? ,? ,? , ?, ?,? ,? ,? ,? ,? ,? ,? ) ";
			
			case 5: return "UPDATE HRMS_REC_APPOINTREP_FILTERS SET  APPOINTREP_REQ_CODE = ? , APPOINTREP_POSITION_CODE =? , "
						+" APPOINTREP_DATEOPTION =? , APPOINTREP_REQDATE_FROM = TO_DATE(?,'DD-MM-YYYY') , APPOINTREP_REQSTATUS =? , APPOINTREP_REPOPTION =? , APPOINTREP_NAME =?  ," 
						+" APPOINTREP_REQDATE_TO =TO_DATE(?,'DD-MM-YYYY')  ,APPOINTREP_USEREMPID =? , APPOINTREP_RADIO_OPTION =?  , APPOINTREP_SELECTED_REQ =?   "
						+" WHERE APPOINTREP_CODE =? "; 
			
			case 6: return " UPDATE HRMS_REC_APPOINTREP_SORT  SET  SORT_BY  = ?, SORT_BY_ORDER  = ? ,SORT_THENBY  = ? , SORT_THENBY_ORDER  = ? , SORT_THENBY1  = ? , "
						+" SORT_THENBY1_ORDER  = ? WHERE APPOINTREP_CODE = ? ";
			
			case 7: return "  UPDATE HRMS_REC_APPOINTREP_COLDEF  SET  COL_REQNAME = ? ,COL_POSITION = ? , "
				   		  +"  COL_REQDATE = ? ,COL_NUMVAC = ? ,COL_APPOINT_DUE = ? , COL_APPOINT_ISSUE = ? , COL_APPOINT_ACCP = ? , COL_APPOINT_REJECT = ?, COL_APPOINT_CANCEL = ? " 
				   		  +" WHERE APPOINTREP_CODE = ? ";
						
			case 8: return " UPDATE  HRMS_REC_APPOINTREP_ADV SET APPOINTREP_NOOFVAC_OPTION = ? , APPOINTREP_NOOFVAC = ? , APPOINTREP_DUE_OPTION  = ? , "
						+" APPOINTREP_DUE  = ?, APPOINTREP_ISSUE_OPTION  = ? , APPOINTREP_ISSUE  = ? , APPOINTREP_ACCP_OPTION  = ? ,  APPOINTREP_ACCP  = ? , APPOINTREP_REJ_OPTION  = ? , APPOINTREP_REJECT  = ?, "
						+" APPOINTREP_CANCEL_OPTION  = ?, APPOINTREP_CANCEL  = ? WHERE APPOINTREP_CODE = ?  " ;
 		
			default:return " FRAMEWORK COULD NOT EXECUTE THE QUERY NUMBER SPECIFIED"; 
		}
	
		
	}
	
}
