 /**
 * @author Pradeep Kumar Sahoo
 *
 */
package org.paradyne.sql.recruitment;

import org.paradyne.lib.SqlBase;

public class CandDataBankModelSql extends SqlBase {
	
	public String getQuery(int code){
		
			switch(code){
			
			case 1 : return "INSERT INTO HRMS_REC_CAND_DATABANK (CAND_CODE,CAND_FIRST_NAME, CAND_MID_NAME, CAND_LAST_NAME, CAND_DOB, CAND_GENDER, " +
					"CAND_MART_STATUS, CAND_EXP_YEAR, CAND_EXP_MONTH, CAND_CURR_CTC, CAND_EXPC_CTC,CAND_RES_PHONE, " +
					"CAND_MOB_PHONE, CAND_OFF_PHONE, CAND_EMAIL_ID,CAND_EMPLOYED, CAND_RELOCATION,CAND_DOYOUKNOW, CAND_REF_EMPID,CAND_REF_TYPE, " + 
					" CAND_RESUME,CAND_PHOTO,CAND_OTHER_INFO,CAND_POSTING_DATE,CAND_SHORT_STATUS,CAND_PASSPORT_NO,CAND_PAN_NO,CAND_TITLE_CODE, " + 
					" CAND_COMPANY,CAND_POSITION,CAND_LOCATION,CAND_POSTRESUME_EMPID, NOTICE_PERIOD) " +
					" values ((SELECT NVL(MAX(CAND_CODE),0)+1 FROM HRMS_REC_CAND_DATABANK),?,?,?,TO_DATE(?,'DD-MM-YYYY'),?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,TO_DATE(?,'DD-MM-YYYY'),'N',?,?,?, ?, ?,?,?, ?) ";
			
			case 2: return "INSERT INTO HRMS_REC_CD_REFDTL (CAND_CODE, CAND_REFNAME, CAND_PROFES, CAND_CONTACT, CAND_COMMENTS) " +
					"VALUES (?,?,?,?,?)";
			
			case 3 : return "INSERT INTO HRMS_REC_CD_QUADTL (CAND_CODE, CAND_QUA_CODE, CAND_SPEC_CODE, CAND_ESTB_NAME, CAND_YEAR_PASS, CAND_PERC_MARKS,CAND_DTL_CODE) " +
					"VALUES (?,?,?,?,?,?,(SELECT NVL(MAX(CAND_DTL_CODE),0)+1 FROM HRMS_REC_CD_QUADTL))";
			
			case 4 : return "INSERT INTO HRMS_REC_CD_EXPDTL (CAND_CODE, CAND_EMPLOYER_NAME, CAND_EMP_PORF, " +
					"CAND_JOIN_DATE, CAND_RELV_DATE, CAND_JOB_DESC,CAND_INDUS_TYPE, CAND_SPEC_ACHV, " +
					" CAND_CTC, HRMS_REC_CD_EXPDTL.CAND_DTL_CODE) VALUES (?,?,?,TO_DATE(?,'DD-MM-YYYY'),TO_DATE(?,'DD-MM-YYYY'),?,?,?,?,(SELECT NVL(MAX(HRMS_REC_CD_EXPDTL.CAND_DTL_CODE),0)+1 FROM HRMS_REC_CD_EXPDTL))";
			
			case 5 : return "INSERT INTO HRMS_REC_CD_SKILLFUNCDTL (CAND_CODE, CAND_FIELD_TYPE, CAND_SF_CODE," +
					" CAND_EXP) VALUES (?,?,?,?)";
			
			case 6 : return "INSERT INTO HRMS_REC_CD_CERTDTL (CAND_DTL_CODE, CAND_CODE, CAND_QUA_CODE, CAND_SPEC_CODE," +
			" CAND_ESTB_TYPE, CAND_YEAR_PASS, CAND_PERC_MARKS) VALUES (HRMS_REC_CD_CERTDTL_SEQ.NEXTVAL,?,?,?,?,?,?)";
			
			case 7:return "INSERT INTO HRMS_REC_CD_ADDRESSDTL(CAND_DTL_CODE,CAND_CODE,CAND_ADD_CITY,CAND_ADD_STATE,CAND_ADD_COUNTRY,CAND_ADD_PINCODE,CAND_ADD,CAND_ADD_TYPE)"
						+" VALUES((SELECT NVL(MAX(CAND_DTL_CODE),0)+1 FROM HRMS_REC_CD_ADDRESSDTL),?,?,?,?,?,?,?)";
			
			case 8:return "INSERT INTO HRMS_REC_CD_ADDRESSDTL(CAND_DTL_CODE,CAND_CODE,CAND_ADD_CITY,CAND_ADD_STATE,CAND_ADD_COUNTRY,CAND_ADD_PINCODE,CAND_ADD,CAND_ADD_TYPE)"
			+" VALUES((SELECT NVL(MAX(CAND_DTL_CODE),0)+1 FROM HRMS_REC_CD_ADDRESSDTL),?,?,?,?,?,?,?)";
			
			case 9:return "UPDATE HRMS_REC_CAND_DATABANK SET CAND_FIRST_NAME=?, CAND_MID_NAME=?, CAND_LAST_NAME=?, CAND_DOB=TO_DATE(?,'DD-MM-YYYY'), CAND_GENDER=?, " +
					"CAND_MART_STATUS=?, CAND_EXP_YEAR=?, CAND_EXP_MONTH=?, CAND_CURR_CTC=?, CAND_EXPC_CTC=?,CAND_RES_PHONE=?, " +
					"CAND_MOB_PHONE=?, CAND_OFF_PHONE=?, CAND_EMAIL_ID=?,CAND_EMPLOYED=?, CAND_RELOCATION=?,CAND_DOYOUKNOW=?, CAND_REF_EMPID=?, " + 
					" CAND_POSTING_DATE=TO_DATE(?,'DD-MM-YYYY'),CAND_RESUME=?,CAND_PHOTO=?,CAND_OTHER_INFO=?,CAND_PASSPORT_NO=?,CAND_PAN_NO=?, " + 
					" CAND_TITLE_CODE=?, CAND_COMPANY=?, CAND_POSITION=?, CAND_LOCATION=?, CAND_POSTRESUME_EMPID=?, NOTICE_PERIOD = ? WHERE CAND_CODE=? ";
			
			case 10:return "UPDATE HRMS_REC_CAND_DATABANK SET CAND_REF_EMPID=? WHERE CAND_CODE=? ";
			
			default : return "hiiiiiiiiiiiiiiiiii";
		}
	}
}