package org.paradyne.sql.recruitment;
import org.paradyne.lib.SqlBase;
/**
 * Date:18-07-2009
 * @author Pradeep Kumar Sahoo
 *
 */
public class CandidateStatusModelSql extends SqlBase {
		public String getQuery(int id){
			switch (id) {
			
			case 1:return   "INSERT INTO HRMS_REC_APPREP_FILTERS(APPREP_CODE,APPREP_REQ_CODE,APPREP_CANDIDATE_CODE,APPREP_POSITION_CODE,APPREP_DATEOPTION, "
							+" APPREP_REQDATE_FROM,APPREP_REQDATE_TO,APPREP_REQSTATUS,APPREP_NAME,APPREP_REPOPTION,APPREP_USEREMPID)"
							+" VALUES((SELECT NVL(MAX(APPREP_CODE),0)+1 FROM HRMS_REC_APPREP_FILTERS),?,?,?,?,TO_DATE(?,'DD-MM-YYYY'),TO_DATE(?,'DD-MM-YYYY'),?,?,?,?)";		
			
			case 2:return "INSERT INTO HRMS_REC_APPREP_SORT(APPREP_CODE,SORT_BY,SORT_BY_ORDER,SORT_THENBY,SORT_THENBY_ORDER,SORT_THENBY1,SORT_THENBY1_ORDER)"
							+" VALUES(?,?,?,?,?,?,?)";
			
			case 3:return "INSERT INTO HRMS_REC_APPREP_COLDEF(APPREP_CODE,COL_CANDNAME,COL_EMAIL,COL_SEARCHSTAT,COL_SCREENSTAT,COL_TESTRESULT,"
						+" COL_INTSTAT,COL_INTROUND,COL_MAKEOFFERSTAT,COL_OFFERSTATUS,COL_APPTSTATUS,COL_CONVEMP) values(?,?,?,?,?,?,?,?,?,?,?,?)";	
			
			case 4:return " INSERT INTO HRMS_REC_APPREP_ADV(APPREP_CODE,ADV_SCREENSTAT_OPTION,ADV_INTROUND_OPTION,ADV_INTROUND,ADV_APPTSTATUS_OPTION,ADV_OFFERSTATUS_OPTION)"
						+" VALUES(?,?,?,?,?,?)";	
			
			case 5:return "INSERT INTO HRMS_REC_APPREP_REQS(APPREP_REQS_CODE,APPREP_CODE) VALUES(?,?)";
			
			case 6:return " UPDATE HRMS_REC_APPREP_FILTERS SET APPREP_REQ_CODE=?,APPREP_CANDIDATE_CODE=?,APPREP_POSITION_CODE=?,APPREP_DATEOPTION=?, "
							+" APPREP_REQDATE_FROM=TO_DATE(?,'DD-MM-YYYY'),APPREP_REQDATE_TO=TO_DATE(?,'DD-MM-YYYY'),APPREP_REQSTATUS=?,APPREP_REPOPTION=?,APPREP_USEREMPID=? "
							+" WHERE APPREP_CODE=?";
			
			case 7:return "	UPDATE HRMS_REC_APPREP_SORT SET SORT_BY=?,SORT_BY_ORDER=?,SORT_THENBY=?,SORT_THENBY_ORDER=?,SORT_THENBY1=?,SORT_THENBY1_ORDER=?"
							+" WHERE APPREP_CODE=?";
			case 8:return  "UPDATE HRMS_REC_APPREP_COLDEF SET COL_CANDNAME=?,COL_EMAIL=?,COL_SEARCHSTAT=?,COL_SCREENSTAT=?,COL_TESTRESULT=?,"
						+" COL_INTSTAT=?,COL_INTROUND=?,COL_MAKEOFFERSTAT=?,COL_OFFERSTATUS=?,COL_APPTSTATUS=?,COL_CONVEMP=? WHERE APPREP_CODE=?";
			
			case 9:return "UPDATE HRMS_REC_APPREP_ADV SET ADV_SCREENSTAT_OPTION=?,ADV_INTROUND_OPTION=?,ADV_INTROUND=?,ADV_APPTSTATUS_OPTION=?,ADV_OFFERSTATUS_OPTION=?"
							+" WHERE APPREP_CODE=?";
			
			case 10:return "SELECT REQS_CODE,REQS_NAME,CAND_CODE,CAND_FIRST_NAME||' '||CAND_MID_NAME||' '||CAND_LAST_NAME,RANK_ID,RANK_NAME,APPREP_DATEOPTION,"//CASE WHEN APPREP_DATEOPTION='O' THEN 'On'"
						+"	TO_CHAR(APPREP_REQDATE_FROM,'DD-MM-YYYY'),TO_CHAR(APPREP_REQDATE_TO,'DD-MM-YYYY'),REQS_STATUS,CASE WHEN APPREP_REPOPTION='P' THEN 'Pdf' WHEN "
						+" APPREP_REPOPTION='X' THEN 'Xls' WHEN APPREP_REPOPTION='T' THEN 'Txt' END,APPREP_NAME"
						+"  FROM HRMS_REC_APPREP_FILTERS LEFT JOIN HRMS_REC_REQS_HDR " 
						+"  ON (HRMS_REC_APPREP_FILTERS.APPREP_REQ_CODE=HRMS_REC_REQS_HDR.REQS_CODE)"
						+"  LEFT JOIN HRMS_REC_CAND_DATABANK ON(HRMS_REC_CAND_DATABANK.CAND_CODE=HRMS_REC_APPREP_FILTERS.APPREP_CANDIDATE_CODE)"
						+"  LEFT JOIN HRMS_RANK ON(HRMS_RANK.RANK_ID=HRMS_REC_APPREP_FILTERS.APPREP_POSITION_CODE)"
						+"  WHERE APPREP_CODE=?";
			
			case 11:return "SELECT REQS_CODE,REQS_NAME FROM HRMS_REC_REQS_HDR INNER JOIN HRMS_REC_APPREP_REQS"
						+" ON (HRMS_REC_APPREP_REQS.APPREP_REQS_CODE=HRMS_REC_REQS_HDR.REQS_CODE)WHERE APPREP_CODE=?";
			
			case 12:return "SELECT SORT_BY,SORT_BY_ORDER,SORT_THENBY,SORT_THENBY_ORDER,SORT_THENBY1,SORT_THENBY1_ORDER  FROM HRMS_REC_APPREP_SORT"
						+" WHERE APPREP_CODE=?";
			
			case 13:return "SELECT COL_CANDNAME,COL_EMAIL,COL_SEARCHSTAT,COL_SCREENSTAT,COL_TESTRESULT,COL_INTSTAT,COL_INTROUND,COL_MAKEOFFERSTAT,COL_OFFERSTATUS,COL_APPTSTATUS,COL_CONVEMP,COL_MOBILENO "
						+" FROM HRMS_REC_APPREP_COLDEF WHERE APPREP_CODE=?";
			
			case 14:return "SELECT ADV_SCREENSTAT_OPTION,ADV_INTROUND_OPTION,ADV_INTROUND,ADV_OFFERSTATUS_OPTION,ADV_APPTSTATUS_OPTION FROM HRMS_REC_APPREP_ADV WHERE APPREP_CODE=?";
						
			default:return " Query does not exist";
			
			}
		}

}
