/**
 * 
 */
package org.paradyne.sql.recruitment;

import org.paradyne.lib.SqlBase;

/**
 * @author prakashs
 *
 */
public class EmployeeRequisitionModelSql extends SqlBase {

	public String getQuery(int code) {

		switch (code) {

		case 1:
			return " INSERT INTO HRMS_REC_REQS_HDR (HRMS_REC_REQS_HDR.REQS_CODE, HRMS_REC_REQS_HDR.REQS_NAME, HRMS_REC_REQS_HDR.REQS_DATE, HRMS_REC_REQS_HDR.REQS_POSITION, HRMS_REC_REQS_HDR.REQS_STATUS, HRMS_REC_REQS_HDR.REQS_APPROVAL_STATUS, HRMS_REC_REQS_HDR.REQS_DIVISION,"
					+ "	HRMS_REC_REQS_HDR.REQS_BRANCH, HRMS_REC_REQS_HDR.REQS_DEPT, HRMS_REC_REQS_HDR.REQS_HIRING_MANAGER, HRMS_REC_REQS_HDR.REQS_RECTYPE_INT, HRMS_REC_REQS_HDR.REQS_RECTYPE_EXT, "
					+ "	HRMS_REC_REQS_HDR.REQS_APPLIED_BY, HRMS_REC_REQS_HDR.REQS_VACAN_COMPEN, HRMS_REC_REQS_HDR.REQS_VACAN_EXPMIN, HRMS_REC_REQS_HDR.REQS_VACAN_EXPMAX, HRMS_REC_REQS_HDR.REQS_VACAN_TYPE, "
					+ " HRMS_REC_REQS_HDR.REQS_VACAN_CONTRACT, HRMS_REC_REQS_HDR.REQS_VACAN_CONTYPE, HRMS_REC_REQS_HDR.REQS_JOBDESC_NAME, HRMS_REC_REQS_HDR.REQS_JOB_DESCRIPTION, HRMS_REC_REQS_HDR.REQS_ROLE_RESPON,"
					+ " HRMS_REC_REQS_HDR.REQS_SPECIAL_REQ, HRMS_REC_REQS_HDR.REQS_PERSONEL_REQ, HRMS_REC_REQS_HDR.REQS_APPR_CODE, HRMS_REC_REQS_HDR.REQS_LEVEL, HRMS_REC_REQS_HDR.REQS_REPLACE_EMP, HRMS_REC_REQS_HDR.REQS_JOB_DESC_CODE)"
					+ "   values ((SELECT NVL(MAX(HRMS_REC_REQS_HDR.REQS_CODE),0)+1 FROM HRMS_REC_REQS_HDR), ?,to_date(?,'dd-mm-yyyy'),?,'O','B',?,?,?,?,?,?,?,?,?,?,"
					+ "?,?,?,?,?,?,?,?,'0',1,?,?)";

		case 2:
			return "INSERT INTO HRMS_REC_REQS_VACDTL (HRMS_REC_REQS_VACDTL.VACAN_DTL_CODE, HRMS_REC_REQS_VACDTL.REQS_CODE, HRMS_REC_REQS_VACDTL.VACAN_NUMBERS, HRMS_REC_REQS_VACDTL.VACAN_REQ_DATE)"
					+ " VALUES (HRMS_REC_REQS_VACDTL_SEQ.NEXTVAL,?,?,to_date(?,'dd-mm-yyyy'))";

		case 3:
			return " UPDATE HRMS_EMP_REQ SET  HRMS_EMP_REQ.EMP_REQ_DATE=TO_DATE(?,'DD-MM-YYYY'), HRMS_EMP_REQ.EMP_REQ_DIV=?, HRMS_EMP_REQ.EMP_REQ_BRN=?, HRMS_EMP_REQ.EMP_REQ_DEPT=?, HRMS_EMP_REQ.EMP_REQ_APPLIED=?, HRMS_EMP_REQ.EMP_REQ_HIR_MANAGER=?, HRMS_EMP_REQ.EMP_REQ_EXCTC=?, "
					+ " HRMS_EMP_REQ.EMP_REQ_IMMREQ=?, HRMS_EMP_REQ.EMP_REQ_IMMDUEDT=TO_DATE(?,'DD-MM-YYYY'), HRMS_EMP_REQ.EMP_REQ_FTRREQ=?, HRMS_EMP_REQ.EMP_REQ_FTRDT=TO_DATE(?,'DD-MM-YYYY'), HRMS_EMP_REQ.EMP_REQ_EXPFROM=?,  "
					+ " HRMS_EMP_REQ.EMP_REQ_EXPTO=?, HRMS_EMP_REQ.EMP_REQ_COMMENTS=? , HRMS_EMP_REQ.EMP_REQ_APPROVER=?  WHERE HRMS_EMP_REQ.EMP_REQ_CODE=?";

		case 4:
			return " INSERT INTO HRMS_REC_REQS_QUA_DTL(HRMS_REC_REQS_QUA_DTL.REQS_QUA_CODE, HRMS_REC_REQS_QUA_DTL.REQS_SPECIALIZATION_CODE, HRMS_REC_REQS_QUA_DTL.REQS_QUA_CUTOFF, HRMS_REC_REQS_QUA_DTL.REQS_QUA_OPTION, HRMS_REC_REQS_QUA_DTL.REQS_QUA_TYPE, HRMS_REC_REQS_QUA_DTL.REQS_CODE) VALUES(?,?,?,?,?,?)";

		case 5:
			return "INSERT INTO HRMS_REC_REQS_SKILL_FUNC_DTL(HRMS_REC_REQS_SKILL_FUNC_DTL.REQS_SKILL_FUNC_CODE, HRMS_REC_REQS_SKILL_FUNC_DTL.REQS_SKILL_FUNC_TYPE, HRMS_REC_REQS_SKILL_FUNC_DTL.REQS_SKILL_FUNC_EXP, HRMS_REC_REQS_SKILL_FUNC_DTL.REQS_SKILL_FUNC_OPTION, HRMS_REC_REQS_SKILL_FUNC_DTL.REQS_CODE, HRMS_REC_REQS_SKILL_FUNC_DTL.REQS_FIELD_TYPE) VALUES(?,?,?,?,?,?)";

		case 6:
			return "INSERT INTO HRMS_REC_REQS_CERT_DTL(HRMS_REC_REQS_CERT_DTL.REQS_CERTI_TYPE, HRMS_REC_REQS_CERT_DTL.REQS_CERTI_NAME, HRMS_REC_REQS_CERT_DTL.REQS_CERTI_ISSUED_BY, HRMS_REC_REQS_CERT_DTL.REQS_CERTI_VALID_TILL, HRMS_REC_REQS_CERT_DTL.REQS_CERTI_OPTION, HRMS_REC_REQS_CERT_DTL.REQS_CODE) VALUES(?,?,?,?,?,?)";

		case 7:
			return " UPDATE HRMS_REC_REQS_VACDTL SET HRMS_REC_REQS_VACDTL.VACAN_NUMBERS=?, HRMS_REC_REQS_VACDTL.VACAN_REQ_DATE=TO_DATE(?,'DD-MM-YYYY') WHERE HRMS_REC_REQS_VACDTL.VACAN_DTL_CODE=? AND HRMS_REC_REQS_VACDTL.REQS_CODE=?";

		case 8:
			return " UPDATE HRMS_REC_REQS_HDR SET HRMS_REC_REQS_HDR.REQS_NAME=?, HRMS_REC_REQS_HDR.REQS_DATE=TO_DATE(?,'DD-MM-YYYY'), HRMS_REC_REQS_HDR.REQS_POSITION=?, HRMS_REC_REQS_HDR.REQS_DIVISION=?,"
					+ "	HRMS_REC_REQS_HDR.REQS_BRANCH=?, HRMS_REC_REQS_HDR.REQS_DEPT=?, HRMS_REC_REQS_HDR.REQS_HIRING_MANAGER=?, HRMS_REC_REQS_HDR.REQS_RECTYPE_INT=?, HRMS_REC_REQS_HDR.REQS_RECTYPE_EXT=?, "
					+ "	HRMS_REC_REQS_HDR.REQS_APPLIED_BY=?, HRMS_REC_REQS_HDR.REQS_VACAN_COMPEN=?, HRMS_REC_REQS_HDR.REQS_VACAN_EXPMIN=?, HRMS_REC_REQS_HDR.REQS_VACAN_EXPMAX=?, HRMS_REC_REQS_HDR.REQS_VACAN_TYPE=?, "
					+ " HRMS_REC_REQS_HDR.REQS_VACAN_CONTRACT=?, HRMS_REC_REQS_HDR.REQS_VACAN_CONTYPE=?, HRMS_REC_REQS_HDR.REQS_JOBDESC_NAME=?, HRMS_REC_REQS_HDR.REQS_JOB_DESCRIPTION=?, HRMS_REC_REQS_HDR.REQS_ROLE_RESPON=?,"
					+ " HRMS_REC_REQS_HDR.REQS_SPECIAL_REQ=?, HRMS_REC_REQS_HDR.REQS_PERSONEL_REQ=?, HRMS_REC_REQS_HDR.REQS_REPLACE_EMP=?, HRMS_REC_REQS_HDR.REQS_JOB_DESC_CODE=? WHERE HRMS_REC_REQS_HDR.REQS_CODE=?";

			//"EMP_REQ_DIV=?,EMP_REQ_BRN=?,EMP_REQ_DEPT=?,EMP_REQ_DESG=?,EMP_REQ_IMMREQ=?,EMP_REQ_FTRREQ=?,EMP_REQ_IMMDT=TO_DATE(?,'DD-MM-YYYY'),EMP_REQ_FTRDT=TO_DATE(?,'DD-MM-YYYY'),EMP_REQ_SKILL=?,"+
			//	"EMP_REQ_JOBDESC=?,EMP_REQ_QUAL=?,EMP_REQ_EXPFROM=?,EMP_REQ_EXPTO=?,EMP_REQ_DESQUAL=?,EMP_REQ_HIR_MANAGER=?,EMP_REQ_COMMENTS=?,EMP_REQ_DATE=TO_DATE(?,'DD-MM-YYYY'),EMP_REQ_APPROVER=? WHERE EMP_REQ_CODE=?";

		case 9:
			return "DELETE FROM HRMS_REC_REQS_VACDTL WHERE HRMS_REC_REQS_VACDTL.VACAN_DTL_CODE=? AND HRMS_REC_REQS_VACDTL.REQS_CODE=?";

		case 10:
			return " UPDATE HRMS_REC_REQS_QUA_DTL SET HRMS_REC_REQS_QUA_DTL.REQS_QUA_CODE=?, HRMS_REC_REQS_QUA_DTL.REQS_SPECIALIZATION_CODE=?, HRMS_REC_REQS_QUA_DTL.REQS_QUA_CUTOFF=?, HRMS_REC_REQS_QUA_DTL.REQS_QUA_OPTION=?, HRMS_REC_REQS_QUA_DTL.REQS_QUA_TYPE=? WHERE HRMS_REC_REQS_QUA_DTL..REQS_QUA_DTL_CODE=? AND HRMS_REC_REQS_QUA_DTL.REQS_CODE=?";

		case 11:
			return " UPDATE HRMS_REC_REQS_SKILL_FUNC_DTL SET HRMS_REC_REQS_SKILL_FUNC_DTL.REQS_SKILL_FUNC_CODE=?, HRMS_REC_REQS_SKILL_FUNC_DTL.REQS_SKILL_FUNC_TYPE=?, HRMS_REC_REQS_SKILL_FUNC_DTL.REQS_SKILL_FUNC_EXP=?, HRMS_REC_REQS_SKILL_FUNC_DTL.REQS_SKILL_FUNC_OPTION=? , HRMS_REC_REQS_SKILL_FUNC_DTL.REQS_FIELD_TYPE=? WHERE HRMS_REC_REQS_SKILL_FUNC_DTL.REQS_FUN_DTL_CODE=? AND HRMS_REC_REQS_SKILL_FUNC_DTL.REQS_CODE=?";

		case 12:
			return " UPDATE HRMS_REC_REQS_CERT_DTL SET HRMS_REC_REQS_CERT_DTL.REQS_CERTI_TYPE=?, HRMS_REC_REQS_CERT_DTL.REQS_CERTI_NAME=?, HRMS_REC_REQS_CERT_DTL.REQS_CERTI_ISSUED_BY=?, HRMS_REC_REQS_CERT_DTL.REQS_CERTI_VALID_TILL=?, HRMS_REC_REQS_CERT_DTL.REQS_CERTI_OPTION =? WHERE HRMS_REC_REQS_CERT_DTL.REQS_CERT_DTL_CODE=? AND HRMS_REC_REQS_CERT_DTL.REQS_CODE=?";

		case 13:
			return " DELETE FROM HRMS_REC_REQS_QUA_DTL WHERE HRMS_REC_REQS_QUA_DTL.REQS_QUA_DTL_CODE=? AND HRMS_REC_REQS_QUA_DTL.REQS_CODE=?";

		case 14:
			return " DELETE FROM HRMS_REC_REQS_SKILL_FUNC_DTL WHERE HRMS_REC_REQS_SKILL_FUNC_DTL.REQS_FUN_DTL_CODE=? AND HRMS_REC_REQS_SKILL_FUNC_DTL.REQS_CODE=?";

		case 15:
			return " DELETE FROM HRMS_REC_REQS_CERT_DTL WHERE HRMS_REC_REQS_CERT_DTL.REQS_CERT_DTL_CODE=? AND HRMS_REC_REQS_CERT_DTL.REQS_CODE=?";

		case 16:
			return " DELETE FROM HRMS_REC_REQS_CERT_DTL WHERE HRMS_REC_REQS_CERT_DTL.REQS_CODE=?";

		case 17:
			return " DELETE FROM HRMS_REC_REQS_SKILL_FUNC_DTL WHERE HRMS_REC_REQS_SKILL_FUNC_DTL.REQS_CODE=? ";

		case 18:
			return " DELETE FROM HRMS_REC_REQS_QUA_DTL WHERE HRMS_REC_REQS_QUA_DTL.REQS_CODE=? ";

		case 19:
			return " DELETE FROM HRMS_REC_REQS_VACDTL WHERE HRMS_REC_REQS_VACDTL.REQS_CODE=? ";

		case 20:
			return " DELETE FROM HRMS_REC_REQS_HDR WHERE HRMS_REC_REQS_HDR.REQS_CODE=?";

		case 21:
			return " UPDATE HRMS_REC_REQS_HDR SET HRMS_REC_REQS_HDR.REQS_APPR_CODE=?, HRMS_REC_REQS_HDR.REQS_APPROVAL_STATUS=?, HRMS_REC_REQS_HDR.REQS_ALTER_APPROVER=? WHERE HRMS_REC_REQS_HDR.REQS_CODE=?";

		case 22:
			return " UPDATE HRMS_JOB_DESCRIPTION SET HRMS_JOB_DESCRIPTION.JOB_DESC_DESC=?, HRMS_JOB_DESCRIPTION.JOB_DESC_ROLE_RESP=? WHERE HRMS_JOB_DESCRIPTION.JOB_DESC_CODE =? ";

		case 23:
			return " INSERT INTO HRMS_JOB_DESCRIPTION(HRMS_JOB_DESCRIPTION.JOB_DESC_CODE, HRMS_JOB_DESCRIPTION.JOB_DESC_DESC, HRMS_JOB_DESCRIPTION.JOB_DESC_ROLE_RESP) "
					+ " VALUES(?,?,?)";

		default:
			return "This is default case";
		}
	}

}
