package org.paradyne.sql.recruitment;
import org.paradyne.lib.SqlBase;
/**
 * 
 * @author Pradeep Sahoo
 * Date:03/Aug/2009
 *
 */

public class ManpowerRequisitionAnalysisModelSql extends SqlBase {
	public String getQuery(int id){
		switch (id) {
		case 1:return "INSERT INTO HRMS_REC_MPRREP_FILTERS(MPRREP_CODE,MPRREP_REQS_CODE,MPRREP_POSITION_CODE,MPRREP_DATE_OPT,MPRREP_FRM_DATE,MPRREP_TO_DATE,"
					  +" MPRREP_REP_OPT,MPRREP_USER_NAME,MPRREP_STATUS,MPRREP_USER_ID)VALUES((SELECT NVL(MAX(MPRREP_CODE), 0)+1 FROM HRMS_REC_MPRREP_FILTERS),"	
					  +" ?,?,?,TO_DATE(?,'DD-MM-YYYY'),TO_DATE(?,'DD-MM-YYYY'),?,?,?,?)";
		
		case 2:return "INSERT INTO HRMS_REC_MPRREP_SORT(MPRREP_CODE,SORT_BY,SORT_BY_ORDER,SORT_THENBY,SORT_THENBY_ORDER,SORT_THENBY1,SORT_THENBY_OREDR1)"
					  +" VALUES(?,?,?,?,?,?,?)";
		
		case 3:return "INSERT INTO HRMS_REC_MPRREP_COLDEF(MPRREP_CODE,COL_REQS_DATE,COL_VACANCIES,COL_VAC_STATUS,COL_REQBY_DATE,COL_OVERDUE,COL_OPENVAC_STATUS,COL_POSITION,COL_REQS_STAT,COL_APPRV_STAT, "
						+"COL_HIRING_MANAGER, COL_APPROVER_NAME, COL_RECRUITER_NAME ) "
					  +" VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)";
		
		case 4:return "INSERT INTO HRMS_REC_MPRREP_ADV(MPRREP_CODE,ADV_VAC_OPT,ADV_VAC_VAL,ADV_OVER_OPT,ADV_OVER_VAL,ADV_REQS_APPRVL_STAT) VALUES(?,?,?,?,?,?)";
		
		case 5:return "INSERT INTO HRMS_REC_MPRREP_REQS(REQS_CODE,MPRREP_CODE) VALUES(?,?)"; 
		
		case 6:return "UPDATE HRMS_REC_MPRREP_FILTERS SET MPRREP_REQS_CODE=?,MPRREP_POSITION_CODE=?,MPRREP_DATE_OPT=?,MPRREP_FRM_DATE=TO_DATE(?,'DD-MM-YYYY')" 
					  +",MPRREP_TO_DATE=TO_DATE(?,'DD-MM-YYYY'),MPRREP_REP_OPT=?,MPRREP_STATUS=? WHERE MPRREP_CODE=?";
		
		case 7:return "UPDATE HRMS_REC_MPRREP_SORT SET SORT_BY=?,SORT_BY_ORDER=?,SORT_THENBY=?,SORT_THENBY_ORDER=?,SORT_THENBY1=?,SORT_THENBY_OREDR1=?"
						+" WHERE MPRREP_CODE=?";
		
		case 8:return "UPDATE HRMS_REC_MPRREP_COLDEF SET COL_REQS_DATE=?,COL_VACANCIES=?,COL_VAC_STATUS=?,COL_REQBY_DATE=?,COL_OVERDUE=?,COL_OPENVAC_STATUS=?, "
						+" COL_POSITION=?,COL_REQS_STAT=?,COL_APPRV_STAT=?, COL_HIRING_MANAGER=?, COL_APPROVER_NAME=?, COL_RECRUITER_NAME=? WHERE MPRREP_CODE=?";
		
		case 9:return "UPDATE HRMS_REC_MPRREP_ADV SET ADV_VAC_OPT=?,ADV_VAC_VAL=?,ADV_OVER_OPT=?,ADV_OVER_VAL=? ,ADV_REQS_APPRVL_STAT=? WHERE MPRREP_CODE=?";
		
		case 10:return "SELECT HRMS_REC_REQS_HDR.REQS_CODE,HRMS_REC_REQS_HDR.REQS_NAME FROM HRMS_REC_REQS_HDR INNER JOIN HRMS_REC_MPRREP_REQS "
					+" ON(HRMS_REC_REQS_HDR.REQS_CODE=HRMS_REC_MPRREP_REQS.REQS_CODE) WHERE  MPRREP_CODE=?"	;
		
		default:return "Query does not exist.";
		}
	}

}
