/**
 * 
 */
package org.paradyne.sql.recruitment;

import org.paradyne.lib.SqlBase;

/**
 * @author aa0540
 *
 */
public class OfferDetailsModelSql extends SqlBase {
	public String getQuery(int id){
		switch (id) {
			case 1 : return "SELECT REQS_NAME, RANK_NAME, DIV_NAME, CENTER_NAME, DEPT_NAME "
							+" ,RANK_ID,DIV_ID,CENTER_ID,DEPT_ID FROM HRMS_REC_REQS_HDR "
							+"INNER JOIN HRMS_RANK ON (HRMS_REC_REQS_HDR.REQS_POSITION = HRMS_RANK.RANK_ID) " 
							+"INNER JOIN HRMS_DIVISION ON (HRMS_REC_REQS_HDR.REQS_DIVISION = HRMS_DIVISION.DIV_ID) " 
							+"INNER JOIN HRMS_CENTER ON (HRMS_REC_REQS_HDR.REQS_BRANCH = HRMS_CENTER.CENTER_ID) " 
							+"INNER JOIN HRMS_DEPT ON (HRMS_REC_REQS_HDR.REQS_DEPT = HRMS_DEPT.DEPT_ID) "
							+"WHERE REQS_CODE = ?";
			
			case 2 : return "SELECT OFFER_CAND_CODE, CAND_FIRST_NAME||' '||CAND_MID_NAME||' '||CAND_LAST_NAME NAME, "
							+"TO_CHAR(OFFER_JOIN_DATE, 'DD-MM-YYYY'), TO_CHAR(SYSDATE, 'DD-MM-YYYY'), "
							+"TO_CHAR(OFFER_DATE, 'DD-MM-YYYY'), OFFER_CURR_CTC, OFFER_NEG_CTC, OFFER_STATUS, "
							+"OFFER_JD, OFFER_ROLES_RESP, OFFER_EMP_TYPE, TYPE_NAME, OFFER_HIRE_MANAGER, "
							+"HIREMGR.EMP_FNAME||' '||HIREMGR.EMP_MNAME||' '||HIREMGR.EMP_LNAME, "
							+"TO_CHAR(OFFER_EXP_JOINDATE, 'DD-MM-YYYY'), OFFER_REPORT_TO, "
							+"REPTO.EMP_FNAME||' '||REPTO.EMP_MNAME||' '||REPTO.EMP_LNAME, OFFER_JOIN_FORM, "
							+"OFFER_GRADE, CADRE_NAME, OFFER_TEMPLATE, DECODE(OFFER_PROBATION, 'Y', 'true', 'N', 'false'), "
							+"OFFER_PROB_MONTHS, OFFER_SIGN_AUTH, SIGN.EMP_FNAME||' '||SIGN.EMP_MNAME||' '||SIGN.EMP_LNAME, "
							+"R2.RANK_NAME, OFFER_REMARKS, OFFER_CONSTRAINTS, DECODE(OFFER_BG_REQ, 'Y', 'true', 'N', 'false'), "
							+"OFFER_OFFERED_CTC, "
							+"DECODE(OFFER_STATUS, 'I ', 'Issued', 'OA', 'Accepted', 'OR', 'Rejected', 'C ', 'Canceled'), "
							+"HRMS_LETTERTEMPLATE_HDR.TEMPLATE_NAME, "
							+" OFFER_DIVISION, OFFER_BRANCH, OFFER_DEPT, OFFER_POSITION,RANK_NAME, DIV_NAME, CENTER_NAME, DEPT_NAME, "
							+" OFFER_ADMIN_REPORTING_TO, ADMINREPTO.EMP_FNAME||' '||ADMINREPTO.EMP_MNAME||' '||ADMINREPTO.EMP_LNAME, OFFER_ATTACHED_ANNEXURE, "
							+" CAND_EMAIL_ID, NVL(OFFER_CAND_COMMENT,''), OFFER_LETTER_AUTO_ID "
							+"FROM HRMS_REC_OFFER " 
							+"INNER JOIN HRMS_REC_CAND_DATABANK ON (HRMS_REC_CAND_DATABANK.CAND_CODE = HRMS_REC_OFFER.OFFER_CAND_CODE) "
							+"LEFT JOIN HRMS_EMP_TYPE ON (HRMS_EMP_TYPE.TYPE_ID = OFFER_EMP_TYPE) " 
							+"LEFT JOIN HRMS_EMP_OFFC HIREMGR ON (HIREMGR.EMP_ID = HRMS_REC_OFFER.OFFER_HIRE_MANAGER) "
							+"LEFT JOIN HRMS_EMP_OFFC REPTO ON (REPTO.EMP_ID = HRMS_REC_OFFER.OFFER_REPORT_TO) "
							+"LEFT JOIN HRMS_CADRE ON (HRMS_CADRE.CADRE_ID = HRMS_REC_OFFER.OFFER_GRADE) "
							+"LEFT JOIN HRMS_EMP_OFFC SIGN ON (SIGN.EMP_ID = HRMS_REC_OFFER.OFFER_SIGN_AUTH) "
							+"LEFT JOIN HRMS_RANK R2 ON (SIGN.EMP_RANK = R2.RANK_ID) "
							+"LEFT JOIN HRMS_LETTERTEMPLATE_HDR ON (HRMS_LETTERTEMPLATE_HDR.TEMPLATE_ID = OFFER_TEMPLATE) "
							+"LEFT JOIN HRMS_EMAILTEMPLATE_HDR ON (HRMS_EMAILTEMPLATE_HDR.TEMPLATE_ID = OFFER_EMAIL_TEMPLATE) " +
							 " INNER JOIN HRMS_RANK r1 ON (r1.RANK_ID = HRMS_REC_OFFER.OFFER_POSITION) "  
							+" INNER JOIN HRMS_DIVISION ON (HRMS_DIVISION.DIV_ID = HRMS_REC_OFFER.OFFER_DIVISION)  "
							+" INNER JOIN HRMS_CENTER ON (HRMS_CENTER.CENTER_ID = HRMS_REC_OFFER.OFFER_BRANCH)  "
							+" INNER JOIN HRMS_DEPT ON (HRMS_DEPT.DEPT_ID = HRMS_REC_OFFER.OFFER_DEPT) "
							+" LEFT JOIN HRMS_EMP_OFFC ADMINREPTO ON (ADMINREPTO.EMP_ID = HRMS_REC_OFFER.OFFER_ADMIN_REPORTING_TO) "
							+" WHERE OFFER_CODE = ?"; 
			
			/*case 3 : return "INSERT INTO HRMS_REC_OFFER (OFFER_CODE, OFFER_REQS_CODE, OFFER_CAND_CODE, OFFER_STATUS, "
							+" OFFER_JD, OFFER_ROLES_RESP, OFFER_EMP_TYPE, OFFER_HIRE_MANAGER, OFFER_EXP_JOINDATE, "
							+" OFFER_REPORT_TO, OFFER_JOIN_FORM, OFFER_GRADE, OFFER_TEMPLATE, OFFER_PROBATION, "
							+" OFFER_PROB_MONTHS, OFFER_SIGN_AUTH, OFFER_REMARKS, OFFER_CONSTRAINTS, OFFER_APPR_STATUS, "
							+" OFFER_BG_REQ, OFFER_JOIN_DATE, OFFER_CURR_CTC, OFFER_NEG_CTC, OFFER_OFFERED_CTC, "
							+" OFFER_DATE,OFFER_EMAIL_TEMPLATE,OFFER_DIVISION, OFFER_BRANCH, OFFER_DEPT, OFFER_POSITION, "
							+" OFFER_ADMIN_REPORTING_TO, OFFER_KEEP_INFORMED, OFFER_ATTACHED_ANNEXURE) "
							+" VALUES ((SELECT NVL(MAX(OFFER_CODE), 0)+1 FROM HRMS_REC_OFFER), ?, ?, ?, ?, "
							+"?, ?, ?, TO_DATE(?, 'DD-MM-YYYY'), ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, TO_DATE(?, 'DD-MM-YYYY'), "
							+"?, ?, ?, TO_DATE(?, 'DD-MM-YYYY'),?,?,?,?,?,?,?,?)";*/
			
			case 3 : return "INSERT INTO HRMS_REC_OFFER (OFFER_CODE, OFFER_REQS_CODE, OFFER_CAND_CODE, OFFER_STATUS, "
							+" OFFER_JD, OFFER_ROLES_RESP, OFFER_EMP_TYPE, OFFER_HIRE_MANAGER, OFFER_EXP_JOINDATE, "
							+" OFFER_REPORT_TO, OFFER_JOIN_FORM, OFFER_GRADE, OFFER_TEMPLATE, OFFER_PROBATION, "
							+" OFFER_PROB_MONTHS, OFFER_SIGN_AUTH, OFFER_REMARKS, OFFER_CONSTRAINTS, OFFER_APPR_STATUS, "
							+" OFFER_BG_REQ, OFFER_JOIN_DATE, OFFER_CURR_CTC, OFFER_NEG_CTC, OFFER_OFFERED_CTC, "
							+" OFFER_DATE,OFFER_DIVISION, OFFER_BRANCH, OFFER_DEPT, OFFER_POSITION, "
							+" OFFER_ADMIN_REPORTING_TO, OFFER_KEEP_INFORMED, OFFER_ATTACHED_ANNEXURE, OFFER_LETTER_AUTO_ID) "
							+" VALUES ((SELECT NVL(MAX(OFFER_CODE), 0)+1 FROM HRMS_REC_OFFER), ?, ?, ?, ?, "
							+"?, ?, ?, TO_DATE(?, 'DD-MM-YYYY'), ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, TO_DATE(?, 'DD-MM-YYYY'), "
							+"?, ?, ?, TO_DATE(?, 'DD-MM-YYYY'),?,?,?,?,?,?,?,?)";
			
			/*case 4 : return "UPDATE HRMS_REC_OFFER SET OFFER_STATUS = ?, OFFER_JD = ?, OFFER_ROLES_RESP = ?, "
							+"OFFER_EMP_TYPE = ?, OFFER_HIRE_MANAGER = ?, OFFER_EXP_JOINDATE = TO_DATE(?, 'DD-MM-YYYY'), "
							+"OFFER_REPORT_TO = ?, OFFER_JOIN_FORM = ?, OFFER_GRADE = ?, OFFER_TEMPLATE = ?, OFFER_PROBATION = ?, "
							+"OFFER_PROB_MONTHS = ?, OFFER_SIGN_AUTH = ?, OFFER_REMARKS = ?, OFFER_CONSTRAINTS = ?, "
							+"OFFER_APPR_STATUS = ?, OFFER_BG_REQ = ?, OFFER_JOIN_DATE = TO_DATE(?, 'DD-MM-YYYY'), OFFER_CURR_CTC = ?, "
							+"OFFER_NEG_CTC = ?, OFFER_OFFERED_CTC = ?, OFFER_DATE = TO_DATE(?, 'DD-MM-YYYY'),OFFER_EMAIL_TEMPLATE = ?, " +
							 " OFFER_DIVISION = ?, OFFER_BRANCH = ?, OFFER_DEPT = ?, OFFER_POSITION = ?";
							//+"WHERE OFFER_CODE = ?";*/	
			
			case 4 : return "UPDATE HRMS_REC_OFFER SET OFFER_STATUS = ?, OFFER_JD = ?, OFFER_ROLES_RESP = ?, "
								+"OFFER_EMP_TYPE = ?, OFFER_HIRE_MANAGER = ?, OFFER_EXP_JOINDATE = TO_DATE(?, 'DD-MM-YYYY'), "
								+"OFFER_REPORT_TO = ?, OFFER_JOIN_FORM = ?, OFFER_GRADE = ?, OFFER_TEMPLATE = ?, OFFER_PROBATION = ?, "
								+"OFFER_PROB_MONTHS = ?, OFFER_SIGN_AUTH = ?, OFFER_REMARKS = ?, OFFER_CONSTRAINTS = ?, "
								+"OFFER_APPR_STATUS = ?, OFFER_BG_REQ = ?, OFFER_JOIN_DATE = TO_DATE(?, 'DD-MM-YYYY'), OFFER_CURR_CTC = ?, "
								+"OFFER_NEG_CTC = ?, OFFER_OFFERED_CTC = ?, OFFER_DATE = TO_DATE(?, 'DD-MM-YYYY'), " +
								" OFFER_DIVISION = ?, OFFER_BRANCH = ?, OFFER_DEPT = ?, OFFER_POSITION = ?";
								//+"WHERE OFFER_CODE = ?";
			
			case 5 : return "INSERT INTO HRMS_REC_APPOINT (APPOINT_CODE, APPOINT_REQS_CODE, APPOINT_CAND_CODE, APPOINT_STATUS, "
							+"APPOINT_JD, APPOINT_ROLES_RESP, APPOINT_EMP_TYPE, APPOINT_HIRE_MANAGER, APPOINT_EXP_JOINDATE, "
							+"APPOINT_REPORT_TO, APPOINT_JOIN_FORM, APPOINT_GRADE, APPOINT_TEMPLATE, APPOINT_PROBATION, "
							+"APPOINT_PROB_MONTHS, APPOINT_SIGN_AUTH, APPOINT_REMARKS, APPOINT_CONSTRAINTS, APPOINT_APPR_STATUS, "
							+"APPOINT_BG_REQ, APPOINT_JOIN_DATE, APPOINT_CURR_CTC, APPOINT_NEG_CTC, APPOINT_OFFERED_CTC, "
							+"APPOINT_DATE, APPOINT_DUE_DATE,APPOINT_DIVISION, APPOINT_BRANCH, APPOINT_DEPT, APPOINT_POSITION,APPOINT_ADMIN_REPORTING_TO) VALUES ((SELECT NVL(MAX(APPOINT_CODE), 0)+1 FROM HRMS_REC_APPOINT), ?, ?, ?, ?, "
							+"?, ?, ?, TO_DATE(?, 'DD-MM-YYYY'), ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, TO_DATE(?, 'DD-MM-YYYY'), "
							+"?, ?, ?, TO_DATE(?, 'DD-MM-YYYY'), TO_DATE(TO_CHAR(SYSDATE, 'DD-MM-YYYY'), 'DD-MM-YYYY'),?,?,?,?,?)";
	
			default: return "";
		}
	}
}
