package org.paradyne.sql.recruitment;

import org.paradyne.lib.SqlBase;

public class OfferAnalysisReportModelSql extends SqlBase {

	public String getQuery(int id) {
		// TODO Auto-generated method stub
		switch(id)
		{
		
			case 1: return "INSERT INTO HRMS_REC_OFFERREP_FILTERS ( OFFERREP_CODE, OFFERREP_REQ_CODE, OFFERREP_POSITION_CODE, "
						+" OFFERREP_DATEOPTION, OFFERREP_REQDATE_FROM, OFFERREP_REQSTATUS, OFFERREP_REPOPTION, OFFERREP_NAME," 
						+" OFFERREP_REQDATE_TO,OFFERREP_USEREMPID, OFFERREP_RADIO_OPTION, OFFERREP_SELECTED_REQ) "
						+" VALUES ((SELECT NVL(MAX(OFFERREP_CODE),0)+1 FROM HRMS_REC_OFFERREP_FILTERS), ?,? , ? ,TO_DATE(?,'DD-MM-YYYY') ,? ,? , ?,TO_DATE(?,'DD-MM-YYYY') ,? ,?, ? )";
			
			case 2: return "  INSERT INTO HRMS_REC_OFFERREP_SORT (OFFREP_CODE, SORT_BY, SORT_BY_ORDER,SORT_THENBY, SORT_THENBY_ORDER, SORT_THENBY1, "
						 +" SORT_THENBY1_ORDER) VALUES ( (SELECT NVL(MAX(OFFERREP_CODE),0) FROM HRMS_REC_OFFERREP_FILTERS), ?,?,?,?,?,?) ";
			
			case 3: return " INSERT INTO HRMS_REC_OFFERREP_COLDEF ( OFFREP_CODE, COL_REQNAME,COL_POSITION, "
				   		  +"  COL_REQDATE,COL_NUMVAC,COL_OFFER_DUE, COL_OFFER_ISSUE, COL_OFFER_ACCP, COL_OFFER_REJECT, COL_OFFER_CANCEL )" 
				   		  +"  VALUES ( (SELECT NVL(MAX(OFFERREP_CODE),0) FROM HRMS_REC_OFFERREP_FILTERS) , ? ,? , ?, ?, ?, ?, ?,? ,? )  ";
						
			case 4: return "  INSERT INTO HRMS_REC_OFFERREP_ADV ( OFFREP_CODE, OFFREP_NOOFVAC_OPTION, OFFREP_NOOFVAC, OFFREP_DUE_OPTION, "
						+" OFFREP_DUE ,   OFFREP_ISSUE_OPTION, OFFREP_ISSUE, OFFREP_ACCP_OPTION,  OFFREP_ACCP, OFFREP_REJ_OPTION, OFFREP_REJECT, "
						+" OFFREP_CANCEL_OPTION, OFFREP_CANCEL) VALUES ((SELECT NVL(MAX(OFFERREP_CODE),0) FROM HRMS_REC_OFFERREP_FILTERS) ,? ,? ,? , ?, ?,? ,? ,? ,? ,? ,? ,? ) ";
			
			case 5: return "UPDATE HRMS_REC_OFFERREP_FILTERS SET  OFFERREP_REQ_CODE = ? , OFFERREP_POSITION_CODE =? , "
						+" OFFERREP_DATEOPTION =? , OFFERREP_REQDATE_FROM = TO_DATE(?,'DD-MM-YYYY') , OFFERREP_REQSTATUS =? , OFFERREP_REPOPTION =? , OFFERREP_NAME =?  ," 
						+" OFFERREP_REQDATE_TO =TO_DATE(?,'DD-MM-YYYY')  ,OFFERREP_USEREMPID =? , OFFERREP_RADIO_OPTION =?  , OFFERREP_SELECTED_REQ =?   "
						+" WHERE OFFERREP_CODE =? "; 
			
			case 6: return " UPDATE HRMS_REC_OFFERREP_SORT  SET  SORT_BY  = ?, SORT_BY_ORDER  = ? ,SORT_THENBY  = ? , SORT_THENBY_ORDER  = ? , SORT_THENBY1  = ? , "
						+" SORT_THENBY1_ORDER  = ? WHERE OFFREP_CODE = ? ";
			
			case 7: return "  UPDATE HRMS_REC_OFFERREP_COLDEF  SET  COL_REQNAME = ? ,COL_POSITION = ? , "
				   		  +"  COL_REQDATE = ? ,COL_NUMVAC = ? ,COL_OFFER_DUE = ? , COL_OFFER_ISSUE = ? , COL_OFFER_ACCP = ? , COL_OFFER_REJECT = ?, COL_OFFER_CANCEL = ? " 
				   		  +" WHERE OFFREP_CODE = ? ";
						
			case 8: return " UPDATE  HRMS_REC_OFFERREP_ADV SET OFFREP_NOOFVAC_OPTION = ? , OFFREP_NOOFVAC = ? , OFFREP_DUE_OPTION  = ? , "
						+" OFFREP_DUE  = ?, OFFREP_ISSUE_OPTION  = ? , OFFREP_ISSUE  = ? , OFFREP_ACCP_OPTION  = ? ,  OFFREP_ACCP  = ? , OFFREP_REJ_OPTION  = ? , OFFREP_REJECT  = ?, "
						+" OFFREP_CANCEL_OPTION  = ?, OFFREP_CANCEL  = ? WHERE OFFREP_CODE = ?  " ;
 		
			default:return " FRAMEWORK COULD NOT EXECUTE THE QUERY NUMBER SPECIFIED"; 
		}
	
		
	}
	
}
