package org.paradyne.sql.recruitment;

import org.paradyne.lib.SqlBase;

public class OpenVacReportModelSql extends SqlBase {

	public String getQuery(int id) {
		// TODO Auto-generated method stub
		switch(id)
		{
		
			case 1: return "INSERT INTO HRMS_REC_VACREP_FILTERS ( VACREP_CODE, VACREP_REQ_CODE, VACREP_RECRUITER_CODE, " 
                  +"  VACREP_POSITION_CODE, VACREP_DATEOPTION, VACREP_REQDATE_FROM,VACREP_REQSTATUS, VACREP_REPOPTION, VACREP_NAME, "
                  +" VACREP_REQDATE_TO, VACREP_USEREMPID, VACREP_HIRINGMGR_CODE,VACREP_RADIO_OPTION) VALUES (( SELECT NVL(MAX(VACREP_CODE),0)+1 FROM HRMS_REC_VACREP_FILTERS) ,? , ?, "
                  +" ? ,? ,TO_DATE(?,'DD-MM-YYYY') ,? ,? ,? ,TO_DATE(?,'DD-MM-YYYY') ,? ,? ,?)";
			
			case 2: return "  INSERT INTO HRMS_REC_VACREP_SORT (VACREP_CODE, SORT_BY, SORT_BY_ORDER,SORT_THENBY, SORT_THENBY_ORDER, SORT_THENBY1, "
						+" SORT_THENBY1_ORDER) VALUES ( ( SELECT NVL(MAX(VACREP_CODE),0)FROM HRMS_REC_VACREP_FILTERS), ?,?,?,?,?,?) ";
			
			case 3: return " INSERT INTO HRMS_REC_VACREP_COLDEF (VACREP_CODE, COL_REQNAME, COL_POSITION, COL_REQDATE, COL_HIRINGMAN, COL_TOTALNOVAC, "
					 +" COL_RECNAME, COL_REQBYDATE, COL_ASSIGNVAC, COL_OPENVAC, COL_CLOSEVAC,COL_CLOSED_DATE, COL_OVERDUE_DAY,COL_APPRVRNAME) VALUES (( SELECT NVL(MAX(VACREP_CODE),0)FROM HRMS_REC_VACREP_FILTERS) ,? ,? , ?, ?, ?,? ,? ,?,? ,? ,? ,?,?)";
						
			case 4: return " INSERT INTO HRMS_REC_VACREP_ADV (VACREP_CODE, ADV_TOTALNOVAC_OPTION, ADV_TOTALNOVAC, ADV_ASSIGNVAC_OPTION, ADV_ASSIGNVAC, ADV_OPENVAC_OPTION,ADV_OPENVAC, ADV_CLOSEVAC_OPTION, ADV_CLOSEVAC, ADV_REQBYDATE_OPTION, ADV_REQBYDATE_FROM, ADV_REQBYDATE_TO)" +
					" VALUES (( SELECT NVL(MAX(VACREP_CODE),0)FROM HRMS_REC_VACREP_FILTERS),? ,? ,? ,? ,? ,? ,? ,? ,? ,TO_DATE(?,'DD-MM-YYYY'),TO_DATE(?,'DD-MM-YYYY') )";
			
			case 5: return " INSERT INTO HRMS_REC_VACREP_REQS (VACREP_CODE, VACREP_REQS_CODE) VALUES (( SELECT NVL(MAX(VACREP_CODE),0)FROM HRMS_REC_VACREP_FILTERS) ,? ) ";
			
			case 6: return "UPDATE HRMS_REC_VACREP_FILTERS SET VACREP_REQ_CODE = ?, VACREP_RECRUITER_CODE = ? , " 
                    +"  VACREP_POSITION_CODE = ? , VACREP_DATEOPTION = ? , VACREP_REQDATE_FROM = TO_DATE(?,'DD-MM-YYYY') ,VACREP_REQSTATUS = ? , VACREP_REPOPTION = ? , VACREP_NAME = ?, "
                    +" VACREP_REQDATE_TO = TO_DATE(?,'DD-MM-YYYY') , VACREP_USEREMPID = ?, VACREP_HIRINGMGR_CODE = ? ,VACREP_RADIO_OPTION = ? WHERE VACREP_CODE = ?";
			
			case 7: return " UPDATE HRMS_REC_VACREP_SORT  SET  SORT_BY  = ?, SORT_BY_ORDER  = ? ,SORT_THENBY  = ? , SORT_THENBY_ORDER  = ? , SORT_THENBY1  = ? , "
						+" SORT_THENBY1_ORDER  = ? WHERE VACREP_CODE = ? ";
			
			case 8: return " UPDATE  HRMS_REC_VACREP_COLDEF SET  COL_REQNAME = ? , COL_POSITION = ?, COL_REQDATE = ?, COL_HIRINGMAN = ?, COL_TOTALNOVAC = ? , "
					 +" COL_RECNAME = ? , COL_REQBYDATE = ?, COL_ASSIGNVAC = ? , COL_OPENVAC = ? , COL_CLOSEVAC = ?,COL_CLOSED_DATE = ?, COL_OVERDUE_DAY = ? ,COL_APPRVRNAME=? WHERE VACREP_CODE = ? ";
						
			case 9: return " UPDATE HRMS_REC_VACREP_ADV SET  ADV_TOTALNOVAC_OPTION = ?, ADV_TOTALNOVAC = ? , ADV_ASSIGNVAC_OPTION = ?, ADV_ASSIGNVAC = ?," 
					+" ADV_OPENVAC_OPTION = ? ,ADV_OPENVAC = ? , ADV_CLOSEVAC_OPTION = ? , ADV_CLOSEVAC = ?, ADV_REQBYDATE_OPTION = ?, ADV_REQBYDATE_FROM = TO_DATE(?,'DD-MM-YYYY') , ADV_REQBYDATE_TO = TO_DATE(?,'DD-MM-YYYY')  WHERE VACREP_CODE = ?" ;
		 
			case 10: return " UPDATE HRMS_REC_VACREP_REQS SET  VACREP_REQS_CODE = ? WHERE VACREP_CODE = ?";
			
			default:return " FRAMEWORK COULD NOT EXECUTE THE QUERY NUMBER SPECIFIED"; 
		}
	
		
	}
	
}
