package org.paradyne.sql.recruitment;

import org.paradyne.lib.SqlBase;

public class PartnerPostResumeModelSql extends SqlBase {
	public String getQuery(int id) {
		switch (id) {
		case 1:
			return "INSERT INTO HRMS_REC_CAND_DATABANK (CAND_CODE, CAND_FIRST_NAME, CAND_LAST_NAME, "
					+ "CAND_EMAIL_ID, CAND_MOB_PHONE, CAND_EXP_YEAR, CAND_EXP_MONTH, CAND_CURR_CTC, "
					+ "CAND_EXPC_CTC, CAND_RELOCATION, CAND_RESUME, CAND_DOB, CAND_GENDER, CAND_MART_STATUS, "
					+ "CAND_POSTING_DATE, CAND_SHORT_STATUS, CAND_REF_TYPE, CAND_REQUISITION_CODE, CAND_POSTRESUME_EMPID, CAND_POSTRESUME_REQUISITIONID) "
					+" VALUES ((SELECT NVL(MAX(CAND_CODE), 0)+1 FROM HRMS_REC_CAND_DATABANK), ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, "
					+ "TO_DATE(?, 'DD-MM-YYYY'), ?, ?, TO_DATE(TO_CHAR(SYSDATE, 'DD-MM-YYYY'), 'DD-MM-YYYY'),?,?,?,?,?)";
			//last parameter is Refer Type --direct or Referral. 

		case 2:
			return "INSERT INTO HRMS_REC_CD_ADDRESSDTL (CAND_DTL_CODE, CAND_CODE, CAND_ADD_CITY, "
					+ "CAND_ADD_STATE, CAND_ADD_COUNTRY, CAND_ADD_TYPE) VALUES ((SELECT NVL(MAX(CAND_DTL_CODE),0)+1 "
					+ "FROM HRMS_REC_CD_ADDRESSDTL), ?, ?, ?, (SELECT LOCATION_PARENT_CODE FROM HRMS_LOCATION "
					+ "WHERE LOCATION_CODE = ?), 'C')";

		case 3:
			return "INSERT INTO HRMS_REC_CAND_POSTING (POST_CODE, POST_REQS_CODE, POST_CAND_CODE, "
					+ "POST_RESUME_SOURCE, POST_POSTING_DATE) VALUES((SELECT NVL(MAX(POST_CODE),0)+1 "
					+ "FROM HRMS_REC_CAND_POSTING), ?, ?, ?, TO_DATE(TO_CHAR(SYSDATE, 'DD-MM-YYYY'), 'DD-MM-YYYY'))";
			//+"FROM HRMS_REC_CAND_POSTING), ?, ?, 'D', TO_DATE(TO_CHAR(SYSDATE, 'DD-MM-YYYY'), 'DD-MM-YYYY'))"; original sql

		case 4:
			return "INSERT INTO HRMS_REC_RESUME_BANK(RESUME_CODE, RESUME_REQS_CODE, RESUME_CAND_CODE, RESUME_REC_EMPID, "
					+ "RESUME_APPR_EMPID, RESUME_FORWARD_DATE, RESUME_STATUS) VALUES((SELECT NVL(MAX(RESUME_CODE), 0)+1 "
					+ "FROM HRMS_REC_RESUME_BANK), ?, ?, ?, (SELECT REQS_HIRING_MANAGER FROM HRMS_REC_REQS_HDR WHERE "
					+ "REQS_CODE = ?), TO_DATE(TO_CHAR(SYSDATE, 'DD-MM-YYYY'), 'DD-MM-YYYY'), ?)";

		default:
			return "";
		}
	}
}
