package org.paradyne.sql.recruitment;

import org.paradyne.lib.SqlBase;

public class PrejoiningActivitiesModelSql extends SqlBase {
	
	public String getQuery(int code){
		
		switch(code){
		
		
		case 1: return "INSERT INTO HRMS_REC_PREJOIN (PREJOIN_CODE,PREJOIN_REQS_CODE,PREJOIN_CAND_CODE,PREJOIN_REPORTERCODE,PREJOIN_OFFERDATE,PREJOIN_JOINDATE,PREJOIN_CHECK_LIST,PREJOIN_STATUS,PREJOIN_ASSIGNERCODE) " +
				"VALUES ((SELECT NVL(MAX(PREJOIN_CODE),0)+1 FROM HRMS_REC_PREJOIN),?,?,?,TO_DATE(?,'DD-MM-YYYY'),TO_DATE(?,'DD-MM-YYYY'),?,?,?)";
		
		case 2 : return "INSERT INTO HRMS_REC_PREJOIN_DTL (PREJOIN_DTL_CODE,PREJOIN_CODE,CHECKLIST_CODE,PREJOIN_DTL_TARDATE,PREJOIN_DTL_RESPERSON,PREJOIN_DTL_ACTREQUIRED,PREJOIN_DTL_ACTSTATUS)" +
				" VALUES ((SELECT NVL(MAX(PREJOIN_DTL_CODE),0)+1 FROM HRMS_REC_PREJOIN_DTL),?,?,TO_DATE(?,'DD-MM-YYYY'),?,?,?)";
		
		case 3 : return " UPDATE HRMS_REC_PREJOIN SET PREJOIN_REQS_CODE=?,PREJOIN_CAND_CODE=?,PREJOIN_REPORTERCODE=?,PREJOIN_OFFERDATE=TO_DATE(?,'DD-MM-YYYY'),PREJOIN_JOINDATE=TO_DATE(?,'DD-MM-YYYY'),PREJOIN_CHECK_LIST=?,PREJOIN_STATUS=? "
						+" ,PREJOIN_ASSIGNERCODE=?  WHERE PREJOIN_CODE=?";
		
		//case 4: ""
		
		default : return "hiiiiiiiiiiiiiiiiii";
		}
		}

}
