/**
 * 
 */
package org.paradyne.sql.recruitment;

import org.paradyne.lib.SqlBase;

/**
 * @author pradeep
 * @date Jan 03, 2009
 * @description RequisitionApprovalModelSql serves as sql for Manpower Requisition Approval form
 */
public class RequisitionApprovalModelSql extends SqlBase {
public String getQuery(int code){
		
		switch(code){
		
		case 1 : return "SELECT HRMS_REC_REQS_HDR.REQS_CODE, TO_CHAR(HRMS_REC_REQS_HDR.REQS_DATE, 'DD-MM-YYYY') APP_DATE, HRMS_REC_REQS_HDR.REQS_POSITION, HRMS_RANK.RANK_NAME, " 
						+"HRMS_REC_REQS_HDR.REQS_APPLIED_BY,  APP_BY.EMP_FNAME||' '||APP_BY.EMP_MNAME||' '||APP_BY.EMP_LNAME APP_BY, "
						+"HRMS_REC_REQS_HDR.REQS_HIRING_MANAGER, "
						+"HIRING_MGR.EMP_FNAME||' '||HIRING_MGR.EMP_MNAME||' '||HIRING_MGR.EMP_LNAME HIRING_MGR, "
						+"HRMS_REC_REQS_HDR.REQS_NAME, HRMS_REC_REQS_HDR.REQS_LEVEL "
						+"FROM HRMS_REC_REQS_HDR "
						+"INNER JOIN HRMS_RANK ON (REQS_POSITION = RANK_ID) "
						+"INNER JOIN HRMS_EMP_OFFC APP_BY ON (REQS_APPLIED_BY = APP_BY.EMP_ID) "
						+"INNER JOIN HRMS_EMP_OFFC HIRING_MGR ON (REQS_HIRING_MANAGER = HIRING_MGR.EMP_ID) "
						+"WHERE HRMS_REC_REQS_HDR.REQS_APPROVAL_STATUS = ? AND (HRMS_REC_REQS_HDR.REQS_APPR_CODE = ? OR HRMS_REC_REQS_HDR.REQS_ALTER_APPROVER =? )ORDER BY HRMS_REC_REQS_HDR.REQS_DATE DESC";
		
		case 2 : return "UPDATE HRMS_REC_REQS_HDR SET HRMS_REC_REQS_HDR.REQS_LEVEL = ?, HRMS_REC_REQS_HDR.REQS_APPR_CODE = ?, HRMS_REC_REQS_HDR.REQS_APPROVAL_STATUS=? WHERE HRMS_REC_REQS_HDR.REQS_CODE = ?";
		
		case 3: return "UPDATE HRMS_REC_REQS_HDR SET HRMS_REC_REQS_HDR.REQS_APPROVAL_STATUS = ? WHERE HRMS_REC_REQS_HDR.REQS_CODE = ?";
		
		case 4: return "INSERT INTO HRMS_REC_REQS_PATH (HRMS_REC_REQS_PATH.PATH_CODE, HRMS_REC_REQS_PATH.PATH_APPR_DATE, HRMS_REC_REQS_PATH.PATH_REQ_CODE, HRMS_REC_REQS_PATH.PATH_APPROVER_CODE,  "
					   +"HRMS_REC_REQS_PATH.PATH_REMARK, HRMS_REC_REQS_PATH.PATH_STATUS, HRMS_REC_REQS_PATH.PATH_APPLIED_BY) VALUES((SELECT NVL(MAX(HRMS_REC_REQS_PATH.PATH_CODE),0)+1 "
					   +"FROM HRMS_REC_REQS_PATH WHERE HRMS_REC_REQS_PATH.PATH_REQ_CODE = ?), TO_DATE(TO_CHAR(SYSDATE,'DD-MM-YYYY'),'DD-MM-YYYY'), ?,  "
					   +" ?, ?,?,?)";
		
		default : return "";
		
		}
	}
}
