package org.paradyne.sql.recruitment;

import org.paradyne.lib.SqlBase;
/**
 *@modified By @author Prajakta.Bhandare
 *@date 15 April 2013
 */
public class SchInterviewAnalysisModelSql extends SqlBase {

	public String getQuery(int id) {
		switch(id)
		{
		//Query to insert filter details criteria
			case 1: return "INSERT INTO HRMS_REC_SCHDREP_FILTERS (SCHDREP_CODE, SCHDREP_REQ_CODE, SCHDREP_HIRINGMGR_CODE, "
						  +" SCHDREP_POSITION_CODE, SCHDREP_DATEOPTION, SCHDREP_SCHD_FROMDATE,SCHDREP_REPOPTION, SCHDREP_NAME, "
						  +" SCHDREP_SCHD_TODATE, SCHDREP_USEREMPID, SCHDREP_SELECTED_REQ,SCHDREP_REP_TYPE,SCHDREP_RADIO_STATUS,SCHDREP_INTFROMDATE,"
						  +" SCHDREP_INTTODATE,SCHDREP_INTDATEOPTION) "
						  +" VALUES (( SELECT NVL(MAX(SCHDREP_CODE),0)+1 FROM HRMS_REC_SCHDREP_FILTERS) ,? ,? , ?  ,? "
						  +" ,TO_DATE(?,'DD-MM-YYYY') ,? ,? ,TO_DATE(?,'DD-MM-YYYY')  ,? ,?,?,?,TO_DATE(?,'DD-MM-YYYY'),TO_DATE(?,'DD-MM-YYYY'),?)";
			
			case 2: return "  INSERT INTO HRMS_REC_SCHDREP_SORT ( SCHDREP_CODE, SORT_BY, SORT_BY_ORDER, "
						  +" SORT_THENBY, SORT_THENBY_ORDER, SORT_THENBY1, SORT_THENBY1_ORDER)  "
					      +" VALUES ((SELECT NVL(MAX(SCHDREP_CODE),0) FROM HRMS_REC_SCHDREP_FILTERS),? ,?,?,? ,? ,? )";
			
			//Query to insert column definition criteria
			case 3: return " INSERT INTO HRMS_REC_SCHDREP_COLDEF ( SCHDREP_CODE, COL_CANDI_NAME, COL_EMAILID, " 
						   +" COL_CONTACT_NO, COL_ROUND_TYPE, COL_INTERVIEW_DATE, COL_INTERVIEW_TIME, COL_INTERVIEW_VENUE, COL_INTERVIEWER, " 
						   +" COL_RECRUITER, COL_SCH_STATUS,COL_INTERVIEW_STATUS) VALUES ((SELECT NVL(MAX(SCHDREP_CODE),0) FROM HRMS_REC_SCHDREP_FILTERS) ,? , ?,? "
						   +" ,? , ?,? , ?,? ,?, ?, ?)";
						
			case 4: return " INSERT INTO HRMS_REC_SCHDREP_ADV ( SCHDREP_CODE, ADV_SCH_STATUS, ADV_INTERVIEWER, "
						 +" ADV_CANDI_CODE) VALUES ( (SELECT NVL(MAX(SCHDREP_CODE),0) FROM HRMS_REC_SCHDREP_FILTERS),?,?,?) ";
			 
			//Query to update filter details criteria
			case 5 : return " UPDATE HRMS_REC_SCHDREP_FILTERS SET  SCHDREP_REQ_CODE= ?, SCHDREP_HIRINGMGR_CODE= ?, "
			 			+" SCHDREP_POSITION_CODE= ?, SCHDREP_DATEOPTION= ?, SCHDREP_SCHD_FROMDATE= TO_DATE(?,'DD-MM-YYYY'), "
			 			+" SCHDREP_REPOPTION= ?, SCHDREP_NAME= ?, SCHDREP_SCHD_TODATE=TO_DATE(?,'DD-MM-YYYY'), SCHDREP_USEREMPID= ?, " 
			 			+" SCHDREP_SELECTED_REQ= ?,SCHDREP_REP_TYPE= ?,SCHDREP_RADIO_STATUS =?,SCHDREP_INTFROMDATE=TO_DATE(?,'DD-MM-YYYY'),SCHDREP_INTTODATE=TO_DATE(?,'DD-MM-YYYY'),SCHDREP_INTDATEOPTION=? WHERE SCHDREP_CODE = ?";
			
			case 6: return " UPDATE HRMS_REC_SCHDREP_SORT SET SORT_BY = ?, SORT_BY_ORDER = ?, SORT_THENBY = ?, SORT_THENBY_ORDER = ?," 
					+" SORT_THENBY1= ?, SORT_THENBY1_ORDER = ? WHERE SCHDREP_CODE = ? ";
			
			//Query to update column definition criteria
			case 7: return "  UPDATE HRMS_REC_SCHDREP_COLDEF SET COL_CANDI_NAME = ?, COL_EMAILID = ?,  "
						+" COL_CONTACT_NO = ?, COL_ROUND_TYPE = ?, COL_INTERVIEW_DATE = ?, COL_INTERVIEW_TIME = ?, "
						+" COL_INTERVIEW_VENUE = ?, COL_INTERVIEWER = ?, COL_RECRUITER = ?, COL_SCH_STATUS = ? ,COL_INTERVIEW_STATUS=?"
						+" WHERE  SCHDREP_CODE = ? ";
						
			case 8: return " UPDATE HRMS_REC_SCHDREP_ADV SET  ADV_SCH_STATUS = ?, ADV_INTERVIEWER = ?, "
						+" ADV_CANDI_CODE  = ? WHERE SCHDREP_CODE = ?" ; 
			
			default:return " FRAMEWORK COULD NOT EXECUTE THE QUERY NUMBER SPECIFIED"; 
		}
	
		
	}
	
}
