package org.paradyne.sql.recruitment;

import org.paradyne.lib.SqlBase;

public class SchTestAnalysisModelSql extends SqlBase {

	public String getQuery(int id) {
		// TODO Auto-generated method stub
		switch(id)
		{
		
			case 1: return "INSERT INTO HRMS_REC_TESTREP_FILTERS (TESTREP_CODE, TESTREP_REQ_CODE, TESTREP_HIRINGMGR_CODE," 
							+" TESTREP_POSITION_CODE, TESTREP_DATEOPTION, TESTREP_SCHD_FROMDATE, "
							+" TESTREP_REPOPTION, TESTREP_NAME, TESTREP_SCHD_TODATE, "
							+" TESTREP_USEREMPID, TESTREP_SELECTED_REQ, TESTREP_REP_TYPE,TESTREP_RADIO_STATUS) "
						    +" VALUES (( SELECT NVL(MAX(TESTREP_CODE),0)+1 FROM HRMS_REC_TESTREP_FILTERS) ,? ,? , ?  ,? "
						    +" ,TO_DATE(?,'DD-MM-YYYY') ,? ,? ,TO_DATE(?,'DD-MM-YYYY')  ,? ,?,?, ?)";
			
			case 2: return "  INSERT INTO HRMS_REC_TESTREP_SORT ( TESTREP_CODE, SORT_BY, SORT_BY_ORDER, "
						   +" SORT_THENBY, SORT_THENBY_ORDER, SORT_THENBY1, SORT_THENBY1_ORDER) "
						   +" VALUES (( SELECT NVL(MAX(TESTREP_CODE),0) FROM HRMS_REC_TESTREP_FILTERS),? ,?,?,? ,? ,? )";
			
			case 3: return "  INSERT INTO HRMS_REC_TESTREP_COLDEF (TESTREP_CODE, COL_CANDI_NAME, COL_EMAILID,  "
							+" COL_CONTACT_NO, COL_TEST_TYPE, COL_TEST_DATE,COL_TEST_TIME, COL_TEST_VENUE, COL_USERID,COL_PASSWORD , "
							+" COL_RECRUITER, COL_SCH_STATUS,COL_ROUND_TYPE)VALUES  ( ( SELECT NVL(MAX(TESTREP_CODE),0) FROM HRMS_REC_TESTREP_FILTERS) ,? , ?,? "
							+" ,? , ?,? , ?,? ,?, ?,?,?)";
						
			case 4: return " INSERT INTO HRMS_REC_TESTREP_ADV (TESTREP_CODE, ADV_SCH_STATUS, ADV_CANDI_CODE) "
						+"	VALUES (( SELECT NVL(MAX(TESTREP_CODE),0) FROM HRMS_REC_TESTREP_FILTERS), ?, ?) ";
			 
			case 5 : return " UPDATE HRMS_REC_TESTREP_FILTERS SET TESTREP_REQ_CODE = ?, TESTREP_HIRINGMGR_CODE = ?," 
							+" TESTREP_POSITION_CODE = ?, TESTREP_DATEOPTION = ?, TESTREP_SCHD_FROMDATE= TO_DATE(?,'DD-MM-YYYY'), "
							+" TESTREP_REPOPTION = ?, TESTREP_NAME = ?, TESTREP_SCHD_TODATE= TO_DATE(?,'DD-MM-YYYY'), "
							+" TESTREP_USEREMPID = ?, TESTREP_SELECTED_REQ = ?, TESTREP_REP_TYPE = ?,TESTREP_RADIO_STATUS = ? WHERE TESTREP_CODE = ?";
			
			case 6: return " UPDATE HRMS_REC_TESTREP_SORT SET  SORT_BY = ?, SORT_BY_ORDER = ?, "
						   +" SORT_THENBY = ?, SORT_THENBY_ORDER = ?, SORT_THENBY1 = ?, SORT_THENBY1_ORDER = ? WHERE TESTREP_CODE = ? ";
			
			case 7: return "  UPDATE HRMS_REC_TESTREP_COLDEF SET  COL_CANDI_NAME = ?, COL_EMAILID = ?,  "
							+" COL_CONTACT_NO = ?, COL_TEST_TYPE = ?, COL_TEST_DATE = ?,COL_TEST_TIME = ?, COL_TEST_VENUE = ?, COL_USERID = ?,COL_PASSWORD = ? , "
							+" COL_RECRUITER = ?, COL_SCH_STATUS = ?,COL_ROUND_TYPE = ? "
							+" WHERE  TESTREP_CODE = ? ";
						
			case 8: return " UPDATE HRMS_REC_TESTREP_ADV SET ADV_SCH_STATUS = ?, ADV_CANDI_CODE = ?  "
						+"	  WHERE TESTREP_CODE = ?" ; 
			
			default:return " FRAMEWORK COULD NOT EXECUTE THE QUERY NUMBER SPECIFIED"; 
		}
	
		
	}
	
}
