package org.paradyne.sql.Training;

import org.paradyne.lib.SqlBase;

public class ConsultantMasterModelSql extends SqlBase {
	public String getQuery(int id){
	switch (id)
	{
	case 1: return "  INSERT INTO HRMS_CONSULTANT (CONS_CODE,CONS_COMPNAME,CONS_CONPER,CONS_DEPT,CONS_DESG,CONS_ADDR1,CONS_ADDR2,CONS_ADDR3,CONS_CITY,CONS_PINCODE,CONS_PHONENO,CONS_MOBILE,CONS_FAX,CONS_EMAIL,CONS_CTYPE,CONS_CHARGES,CONS_REMARK)" 
						+" VALUES((SELECT NVL(MAX(CONS_CODE),0)+1 FROM HRMS_CONSULTANT),UPPER(?),?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

	case 2: return  " DELETE FROM HRMS_CONSULTANT WHERE CONS_CODE=?"; 
	
	case 3: return " UPDATE HRMS_CONSULTANT SET CONS_COMPNAME=?,CONS_CONPER=?,CONS_DEPT=?,CONS_DESG=?,CONS_ADDR1=?,CONS_ADDR2=?,CONS_ADDR3=?,CONS_CITY=?,CONS_PINCODE=?,CONS_PHONENO=?,CONS_MOBILE=?,CONS_FAX=?,CONS_EMAIL=?,CONS_CTYPE=?,CONS_CHARGES=?,CONS_REMARK=? WHERE CONS_CODE=?";

	case 4: return " SELECT CONS_CODE,CONS_COMPNAME,CONS_CONPER,CONS_CITY FROM HRMS_CONSULTANT ";
	
	 case 5: return "SELECT NVL(CONS_ADDR1,'  '),NVL(CONS_ADDR2,'   '),NVL(CONS_ADDR3,'   ')," +
	 		"NVL(CONS_MOBILE,0),NVL(CONS_FAX,0),NVL(CONS_CHARGES,0) FROM HRMS_CONSULTANT where cons_code=?";
		 
	//case 6:return "SELECT CCA_CODE,TO_CHAR(EQUI_SAL_FROM,'DD-MM-YYYY'),TO_CHAR(EQUI_SAL_TO,'DD-MM-YYYY'),CCA_AMT FROM HRMS_PAY_CCA_PARAMETER order by cca_code";
	 
	 case 6: return " SELECT CONS_CODE,CONS_COMPNAME,CONS_CONPER  FROM HRMS_CONSULTANT  ORDER BY  CONS_CODE";

	default : return "Framework could not EXECUTE the query number specified";			

	}
 }
}
	
