package org.paradyne.sql.Training;

import org.paradyne.lib.SqlBase;

public class TrainingTypeMasterModelSql extends SqlBase {
	public String getQuery(int id){
		switch (id)
		{
		case 1: return "  INSERT INTO TRN_TRAINING_TYPE (TRAINING_ID, TRAINING_NAME, TRAINING_DESC, RECORD_CREATEDBY, RECORD_CREATEDON)" 
							+" VALUES((SELECT NVL(MAX(TRAINING_ID),0)+1 FROM TRN_TRAINING_TYPE),?,?,?,SYSDATE)";
		
		case 2: return  " UPDATE TRN_TRAINING_TYPE SET TRAINING_NAME=? ,TRAINING_DESC=?, RECORD_CREATEDBY=?, RECORD_CREATEDON=SYSDATE WHERE TRAINING_ID=?"; 

		case 3: return  " DELETE FROM TRN_TRAINING_TYPE WHERE TRAINING_ID=?"; 
		case 4: return  "SELECT TRAINING_ID, TRAINING_NAME, TRAINING_DESC,  TO_CHAR(TRN_TRAINING_TYPE.RECORD_CREATEDON,'DD-MM-YYYY') ,EMP_FNAME||''||EMP_LNAME FROM  TRN_TRAINING_TYPE " +
						" INNER JOIN HRMS_EMP_OFFC ON(EMP_ID= TRN_TRAINING_TYPE.RECORD_CREATEDBY)"; 
		
		case 5: return  "SELECT TRAINING_ID, TRAINING_NAME, TRAINING_DESC,  TO_CHAR(TRN_TRAINING_TYPE.RECORD_CREATEDON,'DD-MM-YYYY') ,EMP_FNAME||''||EMP_LNAME FROM  TRN_TRAINING_TYPE " +
		" INNER JOIN HRMS_EMP_OFFC ON(EMP_ID= TRN_TRAINING_TYPE.RECORD_CREATEDBY) WHERE TRAINING_ID = ?"; 

		default : return "Framework could not EXECUTE the query number specified";			

		}
	 }

}
