package org.paradyne.sql.admin.transfer;
import org.paradyne.lib.SqlBase;
/*
 * 
 * author:Pradeep Kumar
 */
public class TransferApprovalModelSql extends SqlBase  {
	
	public String getQuery(int id){
		switch(id){
		
		case 1: return "  SELECT DISTINCT TRANSFER_CODE,HRMS_TRANSFER.EMP_ID, "
						 +" HRMS_TITLE.TITLE_NAME||' '||HRMS_EMP_OFFC.EMP_FNAME || ' ' || HRMS_EMP_OFFC.EMP_MNAME || ' ' || HRMS_EMP_OFFC.EMP_LNAME, NVL(TO_CHAR(TRANSFER_APPLICATION_DATE,'DD-MM-YYYY'),' '),"

                         +" NVL(OLDCENT.CENTER_NAME,' '),NVL(NEWCENT.CENTER_NAME,' '), "
                         +" HRMS_TRANSFER.TRANSFER_STATUS,EMP_TOKEN "

                         +" FROM HRMS_TRANSFER  "
                         +" INNER JOIN 	HRMS_EMP_OFFC ON(HRMS_TRANSFER.EMP_ID=HRMS_EMP_OFFC.EMP_ID)"   
                        // +" INNER JOIN HRMS_TRANSFER_PATH ON(HRMS_TRANSFER_PATH.TRANSFER_ID=HRMS_TRANSFER.TRANSFER_CODE) "   
                         +" LEFT JOIN HRMS_CENTER OLDCENT ON(OLDCENT.CENTER_ID=HRMS_TRANSFER.TRANSFER_OLD_CENTER) "  
                         +" LEFT JOIN HRMS_CENTER NEWCENT ON(NEWCENT.CENTER_ID=HRMS_TRANSFER.TRANSFER_NEW_CENTER)  " 
                         +" LEFT JOIN HRMS_TITLE ON(HRMS_TITLE.TITLE_CODE=HRMS_EMP_OFFC.EMP_TITLE_CODE)  "
                         +" WHERE  HRMS_TRANSFER.TRANSFER_APPROVED_BY = ? AND TRANSFER_STATUS = ? ORDER BY NVL(TO_CHAR(TRANSFER_APPLICATION_DATE,'DD-MM-YYYY'),' ') DESC ";
				//+"  WHERE HRMS_TRANSFER.TRANSFER_PROPOSED_BY = ?  ORDER BY HRMS_TRANSFER.EMP_ID " ;
		
		
		case 2: return " UPDATE HRMS_TRANSFER_PATH SET APPR_COMMENT= ?,TRANSFER_APPR_DATE = TO_DATE(?,'DD-MM-YYYY') WHERE TRANSFER_ID = ? AND TRANSFER_APPR_ID = ?  AND TRANSFER_ALT_APPRV_ID=?";
		
		case 3:return " INSERT INTO HRMS_TRANSFER_PATH(TRANSFER_PATH_ID,TRANSFER_ID,TRANSFER_APPR_ID)"
						+"  VALUES((SELECT NVL(MAX(TRANSFER_PATH_ID),0)+1 FROM HRMS_TRANSFER_PATH),?,?)";
		
		case 4:return " UPDATE HRMS_TRANSFER SET TRANSFER_PROPOSED_BY =?, TRANSFER_STATUS= ? WHERE TRANSFER_CODE = ? " ; 
		
		case 5:return "UPDATE HRMS_EMP_OFFC SET EMP_DEPT=?,EMP_DIV=?,EMP_CENTER=?,EMP_STATUS=? WHERE EMP_ID =?";
		
		case 6:return "INSERT INTO HRMS_TRANSFER_PATH (TRANSFER_PATH_ID,TRANSFER_ID,TRANSFER_APPR_ID,TRANSFER_APPR_DATE,APPR_COMMENT,TRANSFER_PATH_STATUS,TRANSFER_ALT_APPRV_ID) VALUES((SELECT NVL(MAX(TRANSFER_PATH_ID),0)+1 FROM HRMS_TRANSFER_PATH),?,?,TO_DATE(?,'DD-MM-YYYY'),?,?,?)";
		
		case 7:return "UPDATE HRMS_TRANSFER SET TRANSFER_STATUS= ? WHERE TRANSFER_CODE = ? ";
		
		case 8:return "UPDATE HRMS_TRANSFER SET TRANSFER_APPROVED_BY= ?,TRANSFER_LEVEL=?,TRANSFER_ALT_APPRV_ID=?  WHERE TRANSFER_CODE = ? ";
		
		
		
		default: return " Query could not find ";
		
		}

 }
	
 }
