package org.paradyne.sql.admin.transfer;
import org.paradyne.lib.SqlBase;
/**
 * 
 * 
 * @author Pradeep Kumar
 *
 */

public class TransferModelSql extends SqlBase {
	public String getQuery(int id){
		switch(id){
		
		case 1:return " INSERT INTO HRMS_TRANSFER(TRANSFER_CODE,EMP_ID,TRANSFER_TYPE,TRANSFER_OLD_CENTER,TRANSFER_NEW_CENTER,TRANSFER_DETAILS,TRANSFER_APPROVED_BY, "
				+" TRANSFER_RELIEVER_EMPID,TRANSFER_RELIEVER_REQUIRED,TRANSFER_APPLICATION_DATE,TRANSFER_RELIEVING_DATE,TRANSFER_STATUS,TRANSFER_RESULT,TRANSFER_UNIT,TRANSFER_DIVISION,TRANSFER_DEPT,TRANSFER_OLD_DIV,TRANSFER_OLD_DEPT,TRANSFER_ALT_APPRV_ID) "
				+" VALUES(?,?,?,?,?,?,?,?,?,TO_DATE(?,'DD-MM-YYYY'),TO_DATE(?,'DD-MM-YYYY'),'P',?,?,?,?,?,?,?)";	
		
		
		case 2:return "UPDATE HRMS_TRANSFER SET EMP_ID = ? ,TRANSFER_TYPE = ?,TRANSFER_NEW_CENTER =?,TRANSFER_DETAILS = ?,TRANSFER_APPLICATION_DATE =TO_DATE(?,'DD-MM-YYYY'),"
				+" TRANSFER_RELIEVING_DATE=TO_DATE(?,'DD-MM-YYYY'),TRANSFER_RELIEVER_REQUIRED= ?,TRANSFER_RELIEVER_EMPID = ?,TRANSFER_RESULT=?,TRANSFER_UNIT=?,TRANSFER_DIVISION=?,TRANSFER_DEPT=?,TRANSFER_APPROVED_BY=?,TRANSFER_ALT_APPRV_ID=? WHERE TRANSFER_CODE = ? ";
		
		case 3:return " DELETE FROM HRMS_TRANSFER WHERE TRANSFER_CODE = ? AND TRANSFER_STATUS='P'";
		
		case 4:return " SELECT TRANSFER_CODE,HRMS_TRANSFER.EMP_ID,EMP_TOKEN,(HRMS_TITLE.TITLE_NAME||' '||HRMS_EMP_OFFC.EMP_FNAME || ' ' || HRMS_EMP_OFFC.EMP_MNAME || ' ' || HRMS_EMP_OFFC.EMP_LNAME),HRMS_RANK.RANK_NAME,TRANSFER_TYPE,"

				+" HRMS_DEPT.DEPT_NAME,HRMS_CENTER.CENTER_NAME ,NEWCENT.CENTER_NAME,CASE WHEN TRANSFER_STATUS='P' THEN 'Pending' WHEN TRANSFER_STATUS='A' THEN 'Approved' WHEN TRANSFER_STATUS='R' THEN 'Rejected' ELSE 'Recommended' END  ,TO_CHAR(TRANSFER_APPLICATION_DATE,'DD-MM-YYYY'), "
				+" TO_CHAR(TRANSFER_RELIEVING_DATE,'DD-MM-YYYY'),TRANSFER_RELIEVER_REQUIRED,(RELTITLE.TITLE_NAME||' '||RELNAME.EMP_FNAME || ' ' || RELNAME.EMP_MNAME || ' ' || RELNAME.EMP_LNAME),"
				+" TRANSFER_DETAILS,TRANSFER_RESULT,NVL(TRANSFER_UNIT,''),TRANSFER_LEVEL,NEWDEPT.DEPT_ID,NEWDEPT.DEPT_NAME,NEWDIV.DIV_ID,NEWDIV.DIV_NAME,HRMS_DIVISION.DIV_NAME,NEWCENT.CENTER_ID FROM HRMS_TRANSFER "

				//+" (APPRV.EMP_FNAME || ' ' || APPRV.EMP_MNAME || ' ' || APPRV.EMP_LNAME),TRANSFER_DETAILS,HRMS_TRANSFER_PATH.TRANSFER_APPR_ID,TRANSFER_RESULT FROM HRMS_TRANSFER "
				+" INNER JOIN HRMS_EMP_OFFC ON(HRMS_TRANSFER.EMP_ID=HRMS_EMP_OFFC.EMP_ID)"
				+" LEFT JOIN HRMS_TITLE ON(HRMS_TITLE.TITLE_CODE=HRMS_EMP_OFFC.EMP_TITLE_CODE)"
			//	+" LEFT JOIN HRMS_TITLE TITLE ON(TITLE.TITLE_CODE=HRMS_EMP_OFFC.EMP_TITLE_CODE)"
				+" LEFT JOIN HRMS_RANK ON(HRMS_RANK.RANK_ID=HRMS_EMP_OFFC.EMP_RANK)"
			//	+" LEFT JOIN HRMS_TRANSFER_PATH ON(HRMS_TRANSFER.TRANSFER_CODE=HRMS_TRANSFER_PATH.TRANSFER_ID)"
				+" LEFT JOIN HRMS_CENTER ON(HRMS_CENTER.CENTER_ID=HRMS_TRANSFER.TRANSFER_OLD_CENTER) "
				+" LEFT JOIN HRMS_CENTER NEWCENT ON(NEWCENT.CENTER_ID=HRMS_TRANSFER.TRANSFER_NEW_CENTER)"
				+" LEFT JOIN HRMS_DEPT ON(HRMS_DEPT.DEPT_ID=HRMS_TRANSFER.TRANSFER_OLD_DEPT)"
				+" LEFT JOIN HRMS_DEPT NEWDEPT ON(NEWDEPT.DEPT_ID=HRMS_TRANSFER.TRANSFER_DEPT)"
				+" LEFT JOIN HRMS_DIVISION ON(HRMS_DIVISION.DIV_ID=HRMS_TRANSFER.TRANSFER_OLD_DIV)"
				+" LEFT JOIN HRMS_DIVISION NEWDIV ON(NEWDIV.DIV_ID=HRMS_TRANSFER.TRANSFER_DIVISION)"
				+" LEFT JOIN HRMS_EMP_OFFC  RELNAME ON(RELNAME.EMP_ID=HRMS_TRANSFER.TRANSFER_RELIEVER_EMPID)"
				+" LEFT JOIN HRMS_TITLE RELTITLE ON(RELTITLE.TITLE_CODE=RELNAME.EMP_TITLE_CODE)"
				
			//	+" LEFT JOIN HRMS_EMP_OFFC PROPOSED ON(PROPOSED.EMP_ID=HRMS_TRANSFER.TRANSFER_APPROVED_BY) "
				//+" LEFT JOIN HRMS_TITLE PROPOSEDTITLE ON(PROPOSEDTITLE.TITLE_CODE=PROPOSED.EMP_TITLE_CODE)"
				+" WHERE TRANSFER_CODE = ? ";
		
		case 5:return " SELECT TRANSFER_CODE FROM HRMS_TRANSFER WHERE EMP_ID = ? ";
		
		case 6:return " INSERT INTO HRMS_TRANSFER_PATH(TRANSFER_PATH_ID,TRANSFER_ID,TRANSFER_APPR_ID)"
					+"  VALUES((SELECT NVL(MAX(TRANSFER_PATH_ID),0)+1 FROM HRMS_TRANSFER_PATH),(SELECT MAX(TRANSFER_CODE) FROM HRMS_TRANSFER),?)";	
		
		
		case 7:return " INSERT INTO HRMS_TRANSFER_PATH(TRANSFER_PATH_ID,TRANSFER_ID,TRANSFER_APPR_ID) VALUES((SELECT NVL(MAX(TRANSFER_PATH_ID),0)+1 FROM HRMS_TRANSFER_PATH),(SELECT MAX(TRANSFER_CODE) FROM HRMS_TRANSFER),?)";
		
		case 8:return " UPDATE HRMS_TRANSFER SET TRANSFER_APPROVED_BY =?, TRANSFER_STATUS= ? WHERE TRANSFER_CODE = ? " ; 
		
		case 9:return " UPDATE HRMS_TRANSFER SET TRANSFER_STATUS= ? WHERE TRANSFER_CODE= ?";// TRANSFER_APPR_DATE = TO_DATE(SYSDATE,'DD-MM-YYYY') WHERE TRANSFER_ID = ? " ;
				
		case 10:return " SELECT DISTINCT TITLE_NAME||' '||EMP_FNAME || ' ' || EMP_MNAME || ' ' || EMP_LNAME,TO_CHAR(TRANSFER_APPR_DATE,'DD-MM-YYYY')"
						+" ,HRMS_TRANSFER_PATH.APPR_COMMENT,CASE WHEN TRANSFER_PATH_STATUS='P' THEN 'Pending' WHEN TRANSFER_PATH_STATUS='A' THEN 'Approved' WHEN TRANSFER_STATUS='R' THEN 'Rejected' ELSE ' ' END, TRANSFER_PATH_ID FROM " 
						+" HRMS_EMP_OFFC "
						+" INNER JOIN HRMS_TRANSFER_PATH ON(HRMS_EMP_OFFC.EMP_ID=HRMS_TRANSFER_PATH.TRANSFER_APPR_ID)"
						+" LEFT JOIN HRMS_TITLE ON(HRMS_TITLE.TITLE_CODE=HRMS_EMP_OFFC.EMP_TITLE_CODE)"
						+" inner join hrms_transfer on(hrms_transfer.transfer_code=hrms_transfer_path.transfer_id)"
					/*	+" INNER JOIN HRMS_TRANSFER ON(HRMS_TRANSFER_PATH.TRANSFER_ID=HRMS_TRANSFER.TRANSFER_CODE)"
						+" INNER JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=HRMS_TRANSFER_PATH.TRANSFER_APPR_ID)"
						+" LEFT JOIN HRMS_TITLE ON(HRMS_TITLE.TITLE_CODE=HRMS_EMP_OFFC.EMP_TITLE_CODE)"*/
						+" WHERE TRANSFER_CODE=? AND TRANSFER_APPR_DATE IS NOT NULL ORDER BY TRANSFER_PATH_ID";
		
		case 11:return "SELECT TITLE_NAME||' '||HRMS_EMP_OFFC.EMP_FNAME || ' ' || HRMS_EMP_OFFC.EMP_MNAME || ' ' || HRMS_EMP_OFFC.EMP_LNAME, "
						+" NVL(HRMS_DEPT.DEPT_NAME,' '),NVL(HRMS_DESG.DESG_NAME,' '),NVL(HRMS_CENTER.CENTER_NAME,' '),CASE WHEN TRANSFER_STATUS='P' THEN 'Pending' WHEN TRANSFER_STATUS='A' THEN 'Approved' WHEN TRANSFER_STATUS='R' THEN 'Rejected' ELSE 'Recommended' END  "
						+" FROM HRMS_TRANSFER "
						+" INNER JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=HRMS_TRANSFER.EMP_ID)"
						+" LEFT JOIN HRMS_DESG ON(HRMS_DESG.DESG_ID=HRMS_EMP_OFFC.EMP_DESG)"
						+" LEFT JOIN HRMS_CENTER ON(HRMS_CENTER.CENTER_ID=HRMS_TRANSFER.TRANSFER_OLD_CENTER)" 
						+" LEFT JOIN HRMS_DEPT ON(HRMS_DEPT.DEPT_ID=HRMS_EMP_OFFC.EMP_DEPT)"
						+" LEFT JOIN HRMS_TITLE ON(HRMS_TITLE.TITLE_CODE=HRMS_EMP_OFFC.EMP_TITLE_CODE)"
						+" WHERE HRMS_TRANSFER.TRANSFER_CODE=? AND ROWNUM=1 " ;
		
		
		case 12:return " SELECT  CASE WHEN TRANSFER_TYPE='intra' THEN 'Intra-Departmental' WHEN TRANSFER_TYPE='mut' THEN 'Mutual Transfer' " 
						+" WHEN TRANSFER_TYPE='trf' THEN 'Transfer On Promotion' WHEN TRANSFER_TYPE='mut' THEN 'Mutual Transfer' " 
						+" WHEN TRANSFER_TYPE='Temp' THEN 'Temporary Attachment' END ," 
						+ " TITLE_NAME||' '||EMP_FNAME || ' ' || EMP_MNAME || ' ' || EMP_LNAME,TO_CHAR(TRANSFER_APPR_DATE,'DD-MM-YYYY')"
						+" ,NEWCENT.CENTER_NAME,HRMS_TRANSFER_PATH.APPR_COMMENT FROM " 
						+" HRMS_TRANSFER_PATH "
						+" INNER JOIN HRMS_TRANSFER ON(HRMS_TRANSFER_PATH.TRANSFER_ID=HRMS_TRANSFER.TRANSFER_CODE)"
						+" INNER JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=HRMS_TRANSFER_PATH.TRANSFER_APPR_ID)"
						+" LEFT JOIN HRMS_CENTER NEWCENT ON(NEWCENT.CENTER_ID=HRMS_TRANSFER.TRANSFER_NEW_CENTER)"
						+" LEFT JOIN HRMS_TITLE ON(HRMS_TITLE.TITLE_CODE=HRMS_EMP_OFFC.EMP_TITLE_CODE)"
						+" WHERE HRMS_TRANSFER_PATH.TRANSFER_ID=? AND TRANSFER_APPR_DATE IS NOT NULL ";

		
		
		case 13 :return " SELECT TO_CHAR(HRMS_EMP_OFFC.EMP_FNAME || ' ' || HRMS_EMP_OFFC.EMP_MNAME || ' ' || HRMS_EMP_OFFC.EMP_LNAME) FROM HRMS_TRANSFER "
						+" INNER JOIN HRMS_TRANSFER_PATH ON(HRMS_TRANSFER_PATH.TRANSFER_APPR_ID=HRMS_TRANSFER.TRANSFER_APPROVED_BY)"
						+"  INNER JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=HRMS_TRANSFER_PATH.TRANSFER_APPR_ID)"
						+" WHERE HRMS_TRANSFER.TRANSFER_CODE= ? AND ROWNUM=1 ";
								 
		case 14 :return "UPDATE HRMS_TRANSFER_PATH SET APPR_COMMENT= ?,TRANSFER_APPR_DATE = TO_DATE(?,'DD-MM-YYYY') WHERE TRANSFER_APPR_ID = ? ";
		
		case 15 :return "DELETE FROM HRMS_TRANSFER_PATH WHERE TRANSFER_ID = ?";
		
		case 16 :return " SELECT EMP_TOKEN FROM HRMS_EMP_OFFC WHERE EMP_ID = ?";
		
		case 17:return " SELECT MAX(TRANSFER_CODE) FROM HRMS_TRANSFER ";
		
		case 18:return " SELECT EMP_ID, EMP_TOKEN,(HRMS_TITLE.TITLE_NAME||' '||HRMS_EMP_OFFC.EMP_FNAME || ' ' || HRMS_EMP_OFFC.EMP_MNAME || ' ' || HRMS_EMP_OFFC.EMP_LNAME),"
						+" HRMS_RANK.RANK_NAME, "
						+" HRMS_DEPT.DEPT_NAME,HRMS_CENTER.CENTER_ID,HRMS_CENTER.CENTER_NAME,HRMS_DIVISION.DIV_NAME,HRMS_DIVISION.DIV_ID,HRMS_DEPT.DEPT_ID FROM HRMS_EMP_OFFC "
						+" LEFT JOIN HRMS_CENTER ON (HRMS_EMP_OFFC.EMP_CENTER=HRMS_CENTER.CENTER_ID) "
						+" LEFT JOIN HRMS_DEPT ON(HRMS_DEPT.DEPT_ID=HRMS_EMP_OFFC.EMP_DEPT)"
						+" LEFT JOIN HRMS_TITLE ON(HRMS_TITLE.TITLE_CODE=HRMS_EMP_OFFC.EMP_TITLE_CODE)"
						+" LEFT JOIN HRMS_RANK ON(HRMS_RANK.RANK_ID=HRMS_EMP_OFFC.EMP_RANK)"
						+" LEFT JOIN HRMS_DIVISION ON(HRMS_DIVISION.DIV_ID=HRMS_EMP_OFFC.EMP_DIV)"
						+" WHERE EMP_ID= ? ";
		
		case 19:return "SELECT HRMS_EMP_OFFC.EMP_ID FROM HRMS_EMP_OFFC "
						+" INNER JOIN HRMS_TRANSFER ON(HRMS_TRANSFER.EMP_ID=HRMS_EMP_OFFC.EMP_ID) WHERE TRANSFER_APPROVED_BY = ? ";
		
		case 20:return "SELECT EMP_TOKEN FROM HRMS_EMP_OFFC WHERE EMP_ID = ?";	
		
		case 21:return " SELECT NVL(LEAVE_NAME,' ') ,NVL(LEAVE_OPENING_BALANCE,0),NVL(LEAVE_CLOSING_BALANCE,0) FROM HRMS_LEAVE "
						+" LEFT JOIN HRMS_LEAVE_BALANCE ON(HRMS_LEAVE.LEAVE_ID=HRMS_LEAVE_BALANCE.LEAVE_CODE AND EMP_ID = ?) ORDER BY LEAVE_ID";
		
		case 22:return " SELECT NVL(PUNISH_NAME,' '), NVL(TO_CHAR(PUNISH_WEF,'DD-MM-YYYY'),' '), NVL(PUNISH_PERIOD,0) "
						+" FROM HRMS_PUNISH INNER JOIN HRMS_PUNISHMENT ON (HRMS_PUNISH.DISCP_ID = HRMS_PUNISHMENT.PUNISH_ID)" 
						+" WHERE EMP_ID = ? ORDER BY HRMS_PUNISH.PUNISH_ID";
		case 23:return " SELECT TRANSFER_CODE FROM HRMS_TRANSFER WHERE EMP_ID=? ";
		
		case 24:return "SELECT TO_CHAR(SYSDATE,'DD-MM-YYYY') FROM DUAL ";
		
		case 25:return "UPDATE HRMS_EMP_OFFC SET EMP_CENTER=?,EMP_DEPT=?,EMP_DIV=? WHERE EMP_ID =?";
		
		case 26:return "UPDATE HRMS_TRANSFER SET TRANSFER_LOCK= ? WHERE TRANSFER_CODE = ? ";
		
		
			

		default: return "Query could not find";

		
		
		}
}
}	
