package org.paradyne.sql.admin.master;

import org.paradyne.lib.SqlBase;

public class CadreModelSql extends SqlBase {
	
	public String getQuery(int id) {
		switch(id) {
		case 1: return " INSERT INTO HRMS_CADRE (CADRE_ID,CADRE_NAME,CADRE_DESC,CADRE_ABBR,CADRE_PARENT_ID,CADRE_IS_ACTIVE ) " 
						+"VALUES(NVL((SELECT MAX(CADRE_ID) FROM HRMS_CADRE ),0)+1,?,?,?,?,?)";		
		
		case 2: return " UPDATE HRMS_CADRE SET CADRE_NAME=?,CADRE_DESC=?,CADRE_ABBR=?,CADRE_PARENT_ID=?,CADRE_IS_ACTIVE=? WHERE CADRE_ID=?";
		
		case 3: return " DELETE FROM HRMS_CADRE WHERE CADRE_ID=?";
		
		case 4: return " SELECT HRMS_CADRE.CADRE_ID,HRMS_CADRE.CADRE_NAME ,nvl(C1.CADRE_NAME,' '),NVL(HRMS_CADRE.CADRE_DESC,' '),NVL(HRMS_CADRE.CADRE_ABBR,' '),NVL(HRMS_CADRE.CADRE_PARENT_ID,0),HRMS_CADRE.CADRE_IS_ACTIVE" +
						 ",CADRE_COMPETENCY_DTL,COMPENTENCY_CODE  FROM HRMS_CADRE" 
		 				+" LEFT JOIN HRMS_CADRE C1 ON (C1.CADRE_ID= HRMS_CADRE.CADRE_PARENT_ID)"
		 				+" LEFT JOIN HRMS_CADRE_DTL  ON (C1.CADRE_ID= HRMS_CADRE_DTL.CADRE_ID)"
		 				+" WHERE HRMS_CADRE.CADRE_ID=?"
		 				+" ORDER BY HRMS_CADRE.CADRE_ID ";
		
		case 5: return  " SELECT CADRE_ID,CADRE_NAME,CADRE_DESC,CADRE_ABBR,CADRE_PARENT_ID,DECODE(HRMS_CADRE.CADRE_IS_ACTIVE,'Y','YES','N','NO') FROM HRMS_CADRE ORDER BY CADRE_ID ";
		case 6: return  " SELECT  CADRE_ID,CADRE_NAME,NVL(CADRE_DESC,' '), DECODE(HRMS_CADRE.CADRE_IS_ACTIVE,'Y','YES','N','NO') FROM HRMS_CADRE ORDER BY upper(CADRE_NAME)";
		//Updated by Anantha Lakshmi
		case 7 : return " INSERT INTO HRMS_CADRE_DTL (CADRE_ID,CADRE_COMPETENCY_DTL,COMPENTENCY_CODE) VALUES ( ? ,? ,(SELECT NVL(MAX(COMPENTENCY_CODE),0)+1 FROM HRMS_CADRE_DTL))";
		case 8: return " DELETE FROM HRMS_CADRE_DTL WHERE CADRE_ID=?";
		default : return "Framework could not the query number specified";			
		}
	}
}