/**
 * 
 */
package org.paradyne.sql.admin.master;

import org.paradyne.lib.SqlBase;


public class CenterModelSql extends SqlBase{

	public String getQuery(int id){
		switch(id){
		case 1:return " INSERT INTO HRMS_CENTER (CENTER_ID,CENTER_NAME,CENTER_LOCATION,CENTER_ADDRESS1,CENTER_ADDRESS2,CENTER_ADDRESS3,CENTER_CITY,CENTER_PINCODE,CENTER_FAX,CENTER_TELEPHONE,CENTER_ESI,CENTER_PT,CENTER_PF,CENTER_ABBR,IS_ACTIVE,CENTER_ZONE,CENTER_ISSITE) " 
						+ " VALUES((SELECT NVL(MAX(CENTER_ID),0)+1 FROM HRMS_CENTER ),?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
		
		case 2:return " UPDATE HRMS_CENTER SET CENTER_NAME=?,CENTER_LOCATION=?,"
			+ " CENTER_ADDRESS1=?,CENTER_ADDRESS2=?,CENTER_ADDRESS3=?,CENTER_CITY=?,"
			+ " CENTER_PINCODE=?,CENTER_FAX=?,CENTER_TELEPHONE=?,CENTER_ESI=?,CENTER_PT=?,"
			+ " CENTER_PF=?,CENTER_ABBR=?,IS_ACTIVE=?,CENTER_ZONE=?,CENTER_ISSITE=? "
			+ " WHERE CENTER_ID=?";
		
		case 3:return " DELETE FROM HRMS_CENTER WHERE CENTER_ID=? ";
		
		case 4:return " SELECT CENTER_ID,CENTER_NAME,CENTER_LOCATION,LOCATION_NAME,CENTER_ADDRESS1,CENTER_ADDRESS2,"
					+ " CENTER_ADDRESS3,CENTER_PINCODE,CENTER_FAX,CENTER_TELEPHONE,CENTER_ESI,CENTER_PT,CENTER_PF,CENTER_ABBR,"
					+ " HRMS_CENTER.IS_ACTIVE,HRMS_CENTER.CENTER_ZONE,CENTER_ISSITE FROM HRMS_CENTER"
		            + " LEFT JOIN HRMS_LOCATION ON (HRMS_CENTER.CENTER_LOCATION=HRMS_LOCATION.LOCATION_CODE) WHERE CENTER_ID=? ";
		
		case 5:return " SELECT CENTER_ID,CENTER_NAME,CENTER_LOCATION,LOCATION_NAME,CENTER_ADDRESS1,CENTER_ADDRESS2,CENTER_ADDRESS3,CENTER_CITY,CENTER_PINCODE,CENTER_FAX,CENTER_TELEPHONE,CENTER_ESI,CENTER_PT,CENTER_PF,HRMS_CENTER.IS_ACTIVE,HRMS_CENTER.CENTER_ZONE,CENTER_ISSITE FROM HRMS_CENTER"
		            + " LEFT JOIN HRMS_LOCATION ON (HRMS_CENTER.CENTER_LOCATION=HRMS_LOCATION.LOCATION_CODE) WHERE CENTER_ID=? ";
		
		case 6:return " SELECT CENTER_ID,SUBSTR(CENTER_NAME,1,20),CENTER_ADDRESS1||' '||CENTER_ADDRESS2||' '||CENTER_ADDRESS3,CASE WHEN IS_ACTIVE='Y' THEN 'Yes' ELSE 'No' END FROM HRMS_CENTER ORDER BY upper(CENTER_NAME)";
		
		default:return " FRAMEWORK COULD NOT THE QUERY NUMBER SPECIFIED";
		}
	}
}
