package org.paradyne.sql.admin.master;

import org.paradyne.lib.SqlBase;

/**
 * 
 * @author pradeep kumar
 * @modified by Reeba
 * @modified by Anantha
 */
public class DivisionModelSql extends SqlBase {

	public String getQuery(int id) {
		switch (id) {
		// esi code & is active field add
		case 1:
			return "INSERT INTO HRMS_DIVISION (DIV_ID,DIV_NAME,DIV_DESC,DIV_CITY_ID,DIV_ADDRESS1,DIV_ADDRESS2," +
					"DIV_ADDRESS3,DIV_PINCODE,DIV_TELEPHONE,DIV_WEBSITE,DIV_ABBR ,"+
					" IS_ACTIVE,DIV_EMAIL, DIV_COMMENCEMENT_DATE," +
					" DIV_LEGAL_STATUS, DIV_OWNERSHIP,  DIV_REG_NO,  DIV_EXPIRY_DATE,  DIV_TITLE_OF_ACT," +
					" DIV_EMPLOYER_NAME,  DIV_EMPLOYER_DESG,  DIV_EMPLOYER_MOBILE, DIV_EMPLOYER_FAX," +
					" DIV_MANAGER_NAME,  DIV_MANAGER_DESG, DIV_MANAGER_TELEPHONE, " +
					" DIV_MANAGER_MOBILE,   DIV_MANAGER_FAX, DIV_MANAGER_EMAIL,DIV_LOGO,DIV_EMPLOYER_TELPHONE, DIV_EMPLOYER_EMAIL,DIV_DISPLAY_NAME)"
					+ " VALUES((SELECT NVL(MAX(DIV_ID),0)+1 FROM HRMS_DIVISION ),?,?,?,?,?,?,?,?,?,?,?,?,TO_DATE(?,'DD-MM-YYYY'),?,?,?,TO_DATE(?,'DD-MM-YYYY'),?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
		case 2:
			return "UPDATE HRMS_DIVISION SET DIV_NAME=?,DIV_DESC=?,DIV_CITY_ID=?,DIV_ADDRESS1=?,DIV_ADDRESS2=?,DIV_ADDRESS3=?,"
					+ " DIV_PINCODE=?,DIV_TELEPHONE=?,DIV_WEBSITE=?, "
					+ " DIV_ABBR=? ,IS_ACTIVE=? ,DIV_EMAIL=?, DIV_COMMENCEMENT_DATE=TO_DATE(?,'DD-MM-YYYY'), DIV_LEGAL_STATUS=?, DIV_OWNERSHIP=?,  DIV_REG_NO=?,  DIV_EXPIRY_DATE=TO_DATE(?,'DD-MM-YYYY'),  DIV_TITLE_OF_ACT=?, DIV_EMPLOYER_NAME=?,  DIV_EMPLOYER_DESG=?,  DIV_EMPLOYER_MOBILE=?, DIV_EMPLOYER_FAX=?, DIV_MANAGER_NAME=?,  DIV_MANAGER_DESG=?, DIV_MANAGER_TELEPHONE=?,  DIV_MANAGER_MOBILE=?,   DIV_MANAGER_FAX=?, DIV_MANAGER_EMAIL=?, DIV_LOGO=? ,DIV_EMPLOYER_TELPHONE=?, DIV_EMPLOYER_EMAIL=? ,DIV_DISPLAY_NAME=? WHERE DIV_ID=? ";
	
			
		case 3:
			return " DELETE FROM HRMS_DIVISION WHERE DIV_ID = ? ";

			// esi code & is active field add
		case 4:
			return " SELECT DIV_ID,DIV_NAME,DIV_DESC,LOCATION_NAME,DIV_CITY_ID,DIV_ADDRESS1,DIV_ADDRESS2,DIV_ADDRESS3,DIV_PINCODE,"
					+ " DIV_TELEPHONE,DIV_WEBSITE,"
					+ " NVL(DIV_ABBR,''),IS_ACTIVE ,DIV_COMMENCEMENT_DATE,"
					+ " LMS_LEGALSTAT_OF_ESTBLSHMNT.LEGALSTATUS_OF_ESTBLSHMNT, LMS_OWNERSHIP.OWNERSHIP_NAME, " 
					+ " DIV_REG_NO, DIV_EXPIRY_DATE,LMS_TITLE_OF_ACTS.TITLE_OF_ACT, DIV_EMPLOYER_NAME, " 
					+ " DIV_EMPLOYER_DESG, DIV_EMPLOYER_MOBILE, DIV_EMPLOYER_FAX, DIV_MANAGER_NAME,"
					+ " DIV_MANAGER_DESG, DIV_MANAGER_TELEPHONE,DIV_MANAGER_MOBILE,DIV_MANAGER_FAX," 
					+ " DIV_MANAGER_EMAIL, NVL(DIV_LOGO,' ') "
					+ " ,DIV_DISPLAY_NAME FROM HRMS_DIVISION "
					+ " LEFT JOIN LMS_LEGALSTAT_OF_ESTBLSHMNT ON(LMS_LEGALSTAT_OF_ESTBLSHMNT.LEGAL_STATUS_ID=HRMS_DIVISION.DIV_LEGAL_STATUS)"
					+ " LEFT JOIN LMS_OWNERSHIP ON(LMS_OWNERSHIP.OWNERSHIP_ID=HRMS_DIVISION.DIV_OWNERSHIP )" 
					+ " LEFT JOIN LMS_TITLE_OF_ACTS ON(LMS_TITLE_OF_ACTS.TITLE_OF_ACT_ID=HRMS_DIVISION.DIV_TITLE_OF_ACT)"
					+ " LEFT JOIN HRMS_LOCATION ON (HRMS_LOCATION.LOCATION_CODE=HRMS_DIVISION.DIV_CITY_ID)"
					+ " LEFT JOIN HRMS_LOCATION loc ON (loc.LOCATION_CODE=HRMS_DIVISION.DIV_CIT_CITY)"
					+ " LEFT JOIN HRMS_BANK ON (HRMS_BANK.BANK_MICR_CODE=HRMS_DIVISION.DIV_BANK)"
					+ " WHERE DIV_ID=? ";

		case 5:
			return "  SELECT DIV_ID,DIV_NAME,LOCATION_NAME,DIV_ADDRESS1,DIV_ADDRESS2,DIV_ADDRESS3,DIV_CITY_ID,"
					+ " DIV_PINCODE,DIV_TELEPHONE,DIV_WEBSITE,DIV_PTAX_REG,DIV_PANNO,DIV_TANNO,DIV_ESI_ZONE"
					+ " FROM HRMS_DIVISION"
					+ " LEFT JOIN HRMS_LOCATION ON (HRMS_LOCATION.LOCATION_CODE=HRMS_DIVISION.DIV_CITY_ID)"
					+ " ORDER BY DIV_ID";

		case 6:
			return " SELECT DIV_ID,DIV_NAME,NVL(DIV_DESC,' '),CASE WHEN IS_ACTIVE='Y' THEN 'Yes' ELSE 'No' END FROM HRMS_DIVISION ORDER BY DIV_NAME ";

		default:
			return " Query is not specified ";
		}

	}
}
