package org.paradyne.sql.admin.master;

import org.paradyne.lib.SqlBase;


public class DonationMasterModelSql extends SqlBase {
	
	public String getQuery(int id) {
		switch(id) {
		case 1: return " INSERT INTO HRMS_DONATION (DONATION_ID,DONATION_NAME,DONATION_PER,DONATION_IS_ACTIVE	) " 
						+ " VALUES((SELECT NVL(MAX(DONATION_ID),0)+1 FROM HRMS_DONATION ),?,?,?)";//added
		
		case 2: return " UPDATE HRMS_DONATION SET DONATION_NAME=?,DONATION_PER=?,DONATION_IS_ACTIVE=? WHERE DONATION_ID=?";
		
		case 3: return " DELETE FROM HRMS_DONATION WHERE DONATION_ID=?";
		
		case 4: return " SELECT  HRMS_DONATION.DONATION_ID,nvl(HRMS_DONATION.DONATION_NAME,''),nvl(HRMS_DONATION.DONATION_PER,'') FROM HRMS_DONATION WHERE HRMS_DONATION.DONATION_ID=?";
		
		case 5: return " SELECT HRMS_DONATION.DONATION_ID,nvl(HRMS_DONATION.DONATION_NAME,''),nvl(HRMS_DONATION.DONATION_PER,'') FROM HRMS_DONATION ORDER BY HRMS_DONATION.DONATION_ID";
		
		case 6: return " SELECT  HRMS_DONATION.DONATION_ID,SUBSTR(HRMS_DONATION.DONATION_NAME,0,20),nvl(HRMS_DONATION.DONATION_PER,''),DECODE(HRMS_DONATION.DONATION_IS_ACTIVE,'Y','Yes','N','No') FROM HRMS_DONATION ORDER BY HRMS_DONATION.DONATION_ID";
		
		default : return "Framework could not the query number specified";			
		}
	}
}

