/**
 * 
 */
package org.paradyne.sql.admin.master;

import org.paradyne.lib.SqlBase;

public class OnsitePostingModelSql extends SqlBase {

	public String getQuery(int id) {
		switch (id) {
		case 1:
			return " INSERT INTO HRMS_ONSITE_POSTING(ONSITE_POSTING_ID, ONSITE_POSTING_TYPE,  ONSITE_POSTING_CODE, "
					+ " ONSITE_POSTING_ABBR, ONSITE_POSTING_NAME, ONSITE_POSTING_LOCATION, ONSITE_POSTING_ADDRESS_1,  ONSITE_POSTING_ADDRESS_2, "
					+ "  ONSITE_POSTING_ADDRESS_3,ONSITE_POSTING_PHONE, ONSITE_POSTING_EMAIL, IS_ACTIVE)"
					+ " VALUES((SELECT NVL(MAX(ONSITE_POSTING_ID),0)+1 FROM HRMS_ONSITE_POSTING) ,?,?,?,?,?,?,?,?,?,?,? )";

		case 2:
			return "UPDATE HRMS_ONSITE_POSTING SET  ONSITE_POSTING_TYPE=?, "
					+ " ONSITE_POSTING_CODE=?,  ONSITE_POSTING_ABBR=?, ONSITE_POSTING_NAME=?,ONSITE_POSTING_LOCATION=?, ONSITE_POSTING_ADDRESS_1=?, "
					+ " ONSITE_POSTING_ADDRESS_2=?,"
					+ " ONSITE_POSTING_ADDRESS_3=?,ONSITE_POSTING_PHONE=?, ONSITE_POSTING_EMAIL=?, IS_ACTIVE = ?"
					+ " WHERE  ONSITE_POSTING_ID=?";

		case 3:
			return " DELETE FROM HRMS_ONSITE_POSTING WHERE ONSITE_POSTING_ID = ? ";

		case 4:
			return " SELECT  ONSITE_POSTING_ID, DECODE(ONSITE_POSTING_TYPE,'C','Client','V','Vendor','P','Partner'), ONSITE_POSTING_CODE, "
					+ " ONSITE_POSTING_ABBR, ONSITE_POSTING_NAME, DECODE(IS_ACTIVE,'Y','YES','N','NO','NO') FROM HRMS_ONSITE_POSTING ORDER BY  ONSITE_POSTING_ID ";

		case 6:
			return "";

		default:
			return " FRAMEWORK COULD NOT THE QUERY NUMBER SPECIFIED";
		}
	}
}
