package org.paradyne.sql.admin.master;

import org.paradyne.lib.SqlBase;
/**
 * @author pranali 
 * Date 26-04-07
 */
public class PayScaleModelSql extends SqlBase {
	
	public String getQuery(int id) 
	{
		switch(id)
		{
						
			
			case 1: return " INSERT INTO HRMS_PAYSCALE (PAYSC_ID,PAYSC_NAME,PAYSC_START_AMT,PAYSC_INCR_AMT1,PAYSC_FINAL_AMT1,PAYSC_INCR_AMT2,PAYSC_FINAL_AMT2,PAYSC_INCR_AMT3,PAYSC_FINAL_AMT3,PAYSC_COMMISION,PAYSC_INCR_AMT4,PAYSC_FINAL_AMT4,PAYSC_INCR_AMT5,PAYSC_FINAL_AMT5) " 
				           +"VALUES((SELECT NVL(MAX(PAYSC_ID),0)+1 FROM HRMS_PAYSCALE ),?,?,?,?,?,?,?,?,?,?,?,?,?)";
			
			case 2: return " UPDATE HRMS_PAYSCALE SET PAYSC_NAME=?,PAYSC_START_AMT=?,PAYSC_INCR_AMT1=?,PAYSC_FINAL_AMT1=?,PAYSC_INCR_AMT2=?,PAYSC_FINAL_AMT2=?,PAYSC_INCR_AMT3=?,PAYSC_FINAL_AMT3=?,PAYSC_COMMISION=?,PAYSC_INCR_AMT4=?,PAYSC_FINAL_AMT4=?,PAYSC_INCR_AMT5=?,PAYSC_FINAL_AMT5 WHERE PAYSC_ID=?";
			
			case 3: return " DELETE FROM HRMS_PAYSCALE WHERE PAYSC_ID=?";
			
			case 4: return " SELECT PAYSC_ID,NVL(PAYSC_NAME,' '),NVL(PAYSC_START_AMT,'0'),NVL(PAYSC_INCR_AMT1,'0'),NVL(PAYSC_FINAL_AMT1,'0'),NVL(PAYSC_INCR_AMT2,'0'),NVL(PAYSC_FINAL_AMT2,'0'),NVL(PAYSC_INCR_AMT3,'0'),NVL(PAYSC_FINAL_AMT3,'0'),NVL(PAYSC_COMMISION,' '),NVL(PAYSC_INCR_AMT4,'0'),NVL(PAYSC_FINAL_AMT4,'0'),NVL(PAYSC_INCR_AMT5,'0'),NVL(PAYSC_FINAL_AMT5,'0') FROM HRMS_PAYSCALE WHERE PAYSC_ID=?";
			
			case 5: return " SELECT PAYSC_ID,NVL(PAYSC_NAME,' '),NVL(PAYSC_START_AMT,'0'),NVL(PAYSC_INCR_AMT1,'0'),NVL(PAYSC_FINAL_AMT1,'0'),NVL(PAYSC_INCR_AMT2,'0'),NVL(PAYSC_FINAL_AMT2,'0'),NVL(PAYSC_INCR_AMT3,'0'),NVL(PAYSC_FINAL_AMT3,'0'),NVL(PAYSC_COMMISION,' '),NVL(PAYSC_INCR_AMT4,'0'),NVL(PAYSC_FINAL_AMT4,'0'),NVL(PAYSC_INCR_AMT5,'0'),NVL(PAYSC_FINAL_AMT5,'0') FROM HRMS_PAYSCALE ORDER BY PAYSC_ID " ;
			
			default : return "Framework could not the query number specified";
			
		}
	}
	

}
