/**
 * 
 */
package org.paradyne.sql.admin.master;

import org.paradyne.lib.SqlBase;



/**
 * @author ritac
 *
 */
public class PFParameterModelSql extends SqlBase {

	public String getQuery(int id) 
	{
		switch(id)
		{
		case 1: return "INSERT INTO HRMS_PF_CONF(PF_CODE,PF_DATE,PF_PERCENTAGE,PF_EMPLOYEE,PF_EMP_FAMILY,PF_COMPANY,PF_CMP_FAMILY,PF_DEBIT_CODE,PF_FORMULA,PF_ADMIN_CHARGES,PF_EDLI_EMPCONT,PF_EDLI_ADMIN_CHARGES," 
					+" 	PF_DEDUCT_EMOL_AMT,PF_DEDUCT_CRITERIA,PF_EMOL_NO_MAX_LIMIT_CHK,PF_EMOL_MAX_LIMIT)"
					+" VALUES ((SELECT NVL(MAX(PF_CODE),0)+1 FROM HRMS_PF_CONF ),TO_DATE(?,'DD-MM-YYYY'),?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
		
		case 2:return "UPDATE HRMS_PF_CONF SET PF_DATE=TO_DATE(?,'DD-MM-YYYY'),PF_PERCENTAGE=?,PF_EMPLOYEE=?,PF_EMP_FAMILY=?,PF_COMPANY=?,PF_CMP_FAMILY=?,PF_DEBIT_CODE=?,PF_FORMULA=?,PF_ADMIN_CHARGES=?,PF_EDLI_EMPCONT=?,PF_EDLI_ADMIN_CHARGES=?,"
					+" PF_DEDUCT_EMOL_AMT=?,PF_DEDUCT_CRITERIA=?,PF_EMOL_NO_MAX_LIMIT_CHK=?,PF_EMOL_MAX_LIMIT=? WHERE PF_CODE =?";
		
		case 3:return "DELETE FROM HRMS_PF_CONF WHERE PF_CODE=? ";
		
		case 4: return " SELECT PF_CODE,TO_CHAR(PF_DATE,'DD-MM-YYYY'), " +
						"NVL(PF_PERCENTAGE,'') FROM HRMS_PF_CONF ORDER BY PF_CODE ";
		
		case 5 : return "UPDATE HRMS_SALARY_CONF SET CONF_EPF=?, CONF_GPF=?, CONF_VPF=?, CONF_PFTRUST=?";
		
		case 6 : return "INSERT INTO HRMS_PFTRUST_CONF (PFT_CODE, PFT_DEDUCTION, PFT_MAX_DEDUCTION, PFT_DEBIT_CODE, PFT_LOAN_MINLIMIT, PFT_LOAN_MAXLIMIT, PFT_LOAN_CODE,PFT_INTEREST,PFT_EFFECTIVE_DATE)"
						+ " VALUES(?,?,?,?,?,?,?,?,TO_DATE(?,'DD-MM-YYYY'))";
		
		case 7 : return "UPDATE HRMS_PFTRUST_CONF SET PFT_DEDUCTION=?, PFT_MAX_DEDUCTION=?, PFT_DEBIT_CODE=?, PFT_LOAN_MINLIMIT=?, PFT_LOAN_MAXLIMIT=?, PFT_LOAN_CODE=?,"
						+" PFT_INTEREST=?,PFT_EFFECTIVE_DATE=TO_DATE(?,'DD-MM-YYYY') WHERE PFT_CODE=?";
		
		case 8 : return "INSERT INTO HRMS_GPF_CONF (GPF_CODE, GPF_DEDUCTION, GPF_DEBIT_CODE) VALUES(?,?,?)";
		
		case 9 : return "UPDATE HRMS_GPF_CONF SET GPF_DEDUCTION=?, GPF_DEBIT_CODE=? WHERE GPF_CODE=?";
		
		case 10 : return "INSERT INTO HRMS_VPF_CONF (VPF_CODE, VPF_DEDUCTION, VPF_DEDUCTION_TYPE, VPF_DEBIT_CODE, VPF_MAX_DEDUCTION) VALUES(?,?,?,?,?)";
		
		case 11 : return "UPDATE HRMS_VPF_CONF SET VPF_DEDUCTION=?, VPF_DEDUCTION_TYPE=?, VPF_DEBIT_CODE=?, VPF_MAX_DEDUCTION=? WHERE VPF_CODE=?";
		
		case 12 : return "DELETE FROM HRMS_PFTRUST_CONF WHERE PFT_CODE=?";
		
		case 13 : return "DELETE FROM HRMS_GPF_CONF WHERE GPF_CODE=?";
		
		case 14 : return "DELETE FROM HRMS_VPF_CONF WHERE VPF_CODE=?";
		
		case 15 : return "UPDATE HRMS_SALARY_MISC SET SAL_EPF_FLAG=?, SAL_VPF_FLAG=?, SAL_GPF_FLAG=?, SAL_PFTRUST_FLAG=? WHERE EMP_ID=?";
		
		case 16 : return "INSERT INTO HRMS_SALARY_MISC(EMP_ID, SAL_EPF_FLAG, SAL_VPF_FLAG, SAL_GPF_FLAG, SAL_PFTRUST_FLAG) VALUES(?,?,?,?,?)";
		
		default: return  "hiiiiiiii";
		
		
		case 17 : return "SELECT ROWNUM AS S_No,"+
					" TO_CHAR(HRMS_PF_CONF.PF_DATE,'DD-MM-YYYY') AS EFFECTIVE_DATE,"+
					" NVL(HRMS_PF_CONF.PF_PERCENTAGE,'') AS PF_PERCENTAGE,"+
					//" NVL(HRMS_PF_CONF.PF_TYPE,'') AS PF_TYPE,"+
					" NVL(HRMS_PF_CONF.PF_EMPLOYEE,'') AS EMPLOYEE_PF,"+
					" NVL(HRMS_PF_CONF.PF_EMP_FAMILY,'') AS EMPLOYEE_FAMILY_PF,"+ 
					" NVL(HRMS_PF_CONF.PF_COMPANY,'') AS PENSION_FUND,"+
					" NVL(HRMS_PF_CONF.PF_CMP_FAMILY,'') AS COMPANY_FUND,"+
					" HRMS_DEBIT_HEAD.DEBIT_NAME AS DEBIT_NAME,"+
					" HRMS_PF_CONF.PF_FORMULA AS PF_FORMULA, "+
					" NVL(HRMS_PF_CONF.PF_DEDUCT_EMOL_AMT,0) AS DEDUCT_PF_EMOLUMENT_AMT,"+
					" DECODE(HRMS_PF_CONF.PF_EMOL_NO_MAX_LIMIT_CHK, 'Y','YES','N','NO','NO') AS  MAX_LIMIT_CHECK_EMOLUMENTS,"+ 
					" HRMS_PF_CONF.PF_EMOL_MAX_LIMIT AS  MAXIMUM_LIMIT_ON_PF_EMOLUMENTS,"+
					" NVL(HRMS_PF_CONF.PF_EDLI_EMPCONT,0) AS EDLI_EMPLOYEE_CONTRIBUTION,"+
					" NVL(HRMS_PF_CONF.PF_ADMIN_CHARGES,0) AS PF_ADMIN_CHARGE,"+
					" NVL(HRMS_PF_CONF.PF_EDLI_ADMIN_CHARGES,0) AS PF_EDLI_ADMIN_CHARGE"+
					" FROM HRMS_PF_CONF"+
					" LEFT JOIN HRMS_DEBIT_HEAD ON(HRMS_DEBIT_HEAD.DEBIT_CODE=HRMS_PF_CONF.PF_DEBIT_CODE)" +
					" ORDER BY HRMS_PF_CONF.PF_DATE";
		
		}
		
	}

}
