/* Reeba Joseph 06 OCT 2009 */

package org.paradyne.sql.admin.master;

import org.paradyne.lib.SqlBase;

public class ShiftModelSql extends SqlBase {
	public String getQuery(int id) {
		switch(id) {
			case 1 :
				return " INSERT INTO HRMS_SHIFT(SHIFT_ID, SHIFT_NAME, SFT_START_TIME, SFT_IN_LM_AFTER_TIME, SFT_IN_HD_AFTER_TIME, SFT_BREAK_TIME_START, " +
				" SFT_BREAK_TIME_END, SFT_OUT_HD_BEFORE_TIME, SFT_OUT_EL_BEFORE_TIME, SFT_END_TIME, SFT_WORK_HRS, SFT_EXTRAWORK_START, SFT_PT_ISENABLED, " +
				" SFT_PT_DURATION, SFT_PT_PERIODICITY, SFT_PT_LM_HD_ISADJUSTED, SFT_LM_ISENABLED, SFT_LM_NUMBER_ISENABLED, SFT_ADJUST_LM_COUNT, " +
				" SFT_ADJUST_LM_LEVDAYS, SFT_ADJUST_LM_LEVTYPE, SFT_LM_HRS_ISENABLED, SFT_LM_REGL_ISENABLED, SFT_DED_REGL_LM_LEVTYPE, " +
				" SFT_DED_LM_IN_SLABS_OF, SFT_DED_NONREGL_LM_LEVTYPE, SFT_EXTRAWORK_LM_ISADJUSTED, SFT_EXTRAWORK_FOR_LM, SFT_EXTRAWORK_FOR_LM_OF, " +
				" SFT_HD_ISENABLED, SFT_DED_HD_LEVTYPE, SFT_EXTRAWORK_HD_ISADJUSTED, SFT_EXTRAWORK_FOR_HD, SFT_EXTRAWORK_FOR_HD_OF, " +
				" SFT_VARIABLE_WO_ISENABLED, SFT_WO_PER_MONTH, SFT_FIXED_WO_ISENABLED, SFT_NIGHT_FLAG, SHIFT_WEEK_1, SHIFT_WEEK_2, SHIFT_WEEK_3, " +
				" SHIFT_WEEK_4, SHIFT_WEEK_5, SHIFT_WEEK_6, SFT_MARK_ABSENT_AFTER, SFT_FLEXITIME_ALLOWED, SFT_FLEXI_LATE_MARK, SFT_FLEXI_HALFDAY_MARK, SFT_WAIVEOFF_LATE_MARK, " +
				" SFT_OT_ISENABLED, SFT_OT_DURATION_FLAG, SFT_OT_REG_FORMULA, SFT_OT_WEEKLY_FORMULA, SFT_OT_DOUBLE_FORMULA,SFT_FLEXI_MARK_ABSENT_BEFORE) " +
				" VALUES(?, ?, TO_DATE(?, 'HH24:MI'), TO_DATE(?, 'HH24:MI'), TO_DATE(?, 'HH24:MI'), TO_DATE(?, 'HH24:MI'), TO_DATE(?, 'HH24:MI'), " +
				" TO_DATE(?, 'HH24:MI'), TO_DATE(?, 'HH24:MI'), TO_DATE(?, 'HH24:MI'), TO_DATE(?, 'HH24:MI'), TO_DATE(?, 'HH24:MI'), ?, " +
				" TO_DATE(?, 'HH24:MI'), ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, TO_DATE(?, 'HH24:MI'), ?, ?, ?, ?, TO_DATE(?, 'HH24:MI'), ?, ?, ?, ?, ?, " +
				" ?, ?, ?, ?, ?, ?, TO_DATE(?, 'HH24:MI'), ?, TO_DATE(?, 'HH24:MI'), TO_DATE(?, 'HH24:MI'), ?, ?,?,?,?,?,TO_DATE(?, 'HH24:MI')) ";

			case 2 :
				return " UPDATE HRMS_SHIFT SET SHIFT_NAME = ?, SFT_START_TIME = TO_DATE(?, 'HH24:MI'), SFT_IN_LM_AFTER_TIME = TO_DATE(?, 'HH24:MI'), " +
				" SFT_IN_HD_AFTER_TIME = TO_DATE(?, 'HH24:MI'), SFT_BREAK_TIME_START = TO_DATE(?, 'HH24:MI'), SFT_BREAK_TIME_END = TO_DATE(?, 'HH24:MI'), " +
				" SFT_OUT_HD_BEFORE_TIME = TO_DATE(?, 'HH24:MI'), SFT_OUT_EL_BEFORE_TIME = TO_DATE(?, 'HH24:MI'), SFT_END_TIME = TO_DATE(?, 'HH24:MI'), " +
				" SFT_WORK_HRS = TO_DATE(?, 'HH24:MI'), SFT_EXTRAWORK_START = TO_DATE(?, 'HH24:MI'), SFT_PT_ISENABLED = ?, " +
				" SFT_PT_DURATION = TO_DATE(?, 'HH24:MI'), SFT_PT_PERIODICITY = ?, SFT_PT_LM_HD_ISADJUSTED = ?, SFT_LM_ISENABLED = ?, " +
				" SFT_LM_NUMBER_ISENABLED = ?, SFT_ADJUST_LM_COUNT = ?, SFT_ADJUST_LM_LEVDAYS = ?, SFT_ADJUST_LM_LEVTYPE = ?, SFT_LM_HRS_ISENABLED = ?, " +
				" SFT_LM_REGL_ISENABLED = ?, SFT_DED_REGL_LM_LEVTYPE = ?, SFT_DED_LM_IN_SLABS_OF = ?, SFT_DED_NONREGL_LM_LEVTYPE = ?, " +
				" SFT_EXTRAWORK_LM_ISADJUSTED = ?, SFT_EXTRAWORK_FOR_LM = TO_DATE(?, 'HH24:MI'), SFT_EXTRAWORK_FOR_LM_OF = ?, SFT_HD_ISENABLED = ?, " +
				" SFT_DED_HD_LEVTYPE = ?, SFT_EXTRAWORK_HD_ISADJUSTED = ?, SFT_EXTRAWORK_FOR_HD = TO_DATE(?, 'HH24:MI'), SFT_EXTRAWORK_FOR_HD_OF = ?, " +
				" SFT_VARIABLE_WO_ISENABLED = ?, SFT_WO_PER_MONTH = ?, SFT_FIXED_WO_ISENABLED = ?, SFT_NIGHT_FLAG = ?, SHIFT_WEEK_1 = ?, SHIFT_WEEK_2 = ?, " +
				" SHIFT_WEEK_3 = ?, SHIFT_WEEK_4 = ?, SHIFT_WEEK_5 = ?, SHIFT_WEEK_6 = ?, SFT_MARK_ABSENT_AFTER = TO_DATE(?, 'HH24:MI'), SFT_FLEXITIME_ALLOWED = ?,"+ 
				" SFT_FLEXI_LATE_MARK = TO_DATE(?, 'HH24:MI'), SFT_FLEXI_HALFDAY_MARK = TO_DATE(?, 'HH24:MI'), SFT_WAIVEOFF_LATE_MARK = ?, " + 
				" SFT_OT_ISENABLED = ?, SFT_OT_DURATION_FLAG = ?, SFT_OT_REG_FORMULA = ?, SFT_OT_WEEKLY_FORMULA = ?, SFT_OT_DOUBLE_FORMULA = ?, SFT_FLEXI_MARK_ABSENT_BEFORE = TO_DATE(?, 'HH24:MI') " + 
				" WHERE SHIFT_ID = ? ";

			case 3 :
				return " DELETE FROM HRMS_SHIFT WHERE SHIFT_ID = ? ";

			case 4 :
				return " SELECT SHIFT_ID, SHIFT_NAME, TO_CHAR(SFT_START_TIME, 'HH24:MI'), TO_CHAR(SFT_END_TIME, 'HH24:MI'), ' ', ' ', ' ', ' ', ' ', " +
				" SHIFT_WEEK_1, SHIFT_WEEK_2, SHIFT_WEEK_3, SHIFT_WEEK_4, SHIFT_WEEK_5, SHIFT_WEEK_6 " +
				" FROM HRMS_SHIFT WHERE SHIFT_ID = ? ";

			case 5 :
				return " SELECT SHIFT_ID, SHIFT_NAME, TO_CHAR(SHIFT_START_TIME, 'HH24:MI'), TO_CHAR(SHIFT_END_TIME, 'HH24:MI'), " +
				" TO_CHAR(SHIFT_FIRST_HALF_DAY, 'HH24:MI'), TO_CHAR(SHIFT_SECOND_HALF_DAY, 'HH24:MI'), TO_CHAR(SHIFT_OT_START_TIME, 'HH24:MI'), " +
				" TO_CHAR(SHIFT_WORK_HOURS, 'HH24:MI'), SHIFT_NIGHT_FLAG FROM HRMS_SHIFT ";

			case 6 :
				return " SELECT * FROM HRMS_SHIFT WHERE SHIFT_ID = ? ";

			case 7 :
				return " SELECT SHIFT_ID, SHIFT_NAME, TO_CHAR(SFT_START_TIME, 'HH24:MI'), TO_CHAR(SFT_IN_LM_AFTER_TIME, 'HH24:MI'), " +
				" TO_CHAR(SFT_IN_HD_AFTER_TIME, 'HH24:MI'), TO_CHAR(SFT_BREAK_TIME_START, 'HH24:MI'), TO_CHAR(SFT_BREAK_TIME_END, 'HH24:MI'), " +
				" TO_CHAR(SFT_OUT_HD_BEFORE_TIME,'HH24:MI'), TO_CHAR(SFT_OUT_EL_BEFORE_TIME, 'HH24:MI'), TO_CHAR(SFT_END_TIME,'HH24:MI'), " +
				" TO_CHAR(SFT_WORK_HRS, 'HH24:MI'), TO_CHAR(SFT_EXTRAWORK_START, 'HH24:MI'), NVL(SFT_PT_ISENABLED, 'N'), " +
				" TO_CHAR(SFT_PT_DURATION, 'HH24:MI'), NVL(SFT_PT_PERIODICITY, ' '), NVL(SFT_PT_LM_HD_ISADJUSTED, 'N'), NVL(SFT_LM_ISENABLED, 'N'), " +
				" NVL(SFT_LM_NUMBER_ISENABLED, 'N'), SFT_ADJUST_LM_COUNT, SFT_ADJUST_LM_LEVDAYS, NVL(SFT_ADJUST_LM_LEVTYPE, ' '), " +
				" NVL(SFT_LM_HRS_ISENABLED, 'N'), NVL(SFT_LM_REGL_ISENABLED, 'N'), NVL(SFT_DED_REGL_LM_LEVTYPE, ' '), SFT_DED_LM_IN_SLABS_OF, " +
				" NVL(SFT_DED_NONREGL_LM_LEVTYPE, ' '), NVL(SFT_EXTRAWORK_LM_ISADJUSTED, 'N'), TO_CHAR(SFT_EXTRAWORK_FOR_LM, 'HH24:MI'), " +
				" NVL(SFT_EXTRAWORK_FOR_LM_OF, ' '), NVL(SFT_HD_ISENABLED, 'N'), NVL(SFT_DED_HD_LEVTYPE, ' '), NVL(SFT_EXTRAWORK_HD_ISADJUSTED, 'N'), " +
				" TO_CHAR(SFT_EXTRAWORK_FOR_HD, 'HH24:MI'), NVL(SFT_EXTRAWORK_FOR_HD_OF, ' '), NVL(SFT_VARIABLE_WO_ISENABLED, 'N'), SFT_WO_PER_MONTH, " +
				" NVL(SFT_FIXED_WO_ISENABLED, 'N'), NVL(SFT_NIGHT_FLAG, ' ') " +
				" FROM HRMS_SHIFT WHERE SHIFT_ID = ? ";
				
			case 8 :
				return " SELECT TO_CHAR(SFT_DTL_START_TIME, 'HH24:MI') AS SFT_DTL_START_TIME, " +
				" TO_CHAR(SFT_DTL_IN_LM_AFTER_TIME, 'HH24:MI') AS SFT_DTL_IN_LM_AFTER_TIME, " +
				" TO_CHAR(SFT_DTL_IN_HD_AFTER_TIME, 'HH24:MI') AS SFT_DTL_IN_HD_AFTER_TIME, " +
				" TO_CHAR(SFT_DTL_BREAK_TIME_START, 'HH24:MI') AS SFT_DTL_BREAK_TIME_START, " +
				" TO_CHAR(SFT_DTL_BREAK_TIME_END, 'HH24:MI') AS SFT_DTL_BREAK_TIME_END, " +
				" TO_CHAR(SFT_DTL_OUT_HD_BEFORE_TIME, 'HH24:MI') AS SFT_DTL_OUT_HD_BEFORE_TIME, " +
				" TO_CHAR(SFT_DTL_OUT_EL_BEFORE_TIME, 'HH24:MI') AS SFT_DTL_OUT_EL_BEFORE_TIME, " +
				" TO_CHAR(SFT_DTL_END_TIME, 'HH24:MI') AS SFT_DTL_END_TIME, TO_CHAR(SFT_DTL_WORK_HRS, 'HH24:MI') AS SFT_DTL_WORK_HRS, " +
				" TO_CHAR(SFT_DTL_EXTRAWORK_START, 'HH24:MI') AS SFT_DTL_EXTRAWORK_START, SFT_DTL_NIGHT_FLAG " +
				" FROM HRMS_SHIFT_DTL " +
				" WHERE HRMS_SHIFT_DTL.SHIFT_ID = ? AND SFT_DTL_EXCEPTIONAL_DAY = ? ";
				
			case 9 :
				return " INSERT INTO HRMS_SHIFT_DTL (SHIFT_ID, SFT_DTL_EXCEPTIONAL_DAY, SFT_DTL_START_TIME, SFT_DTL_IN_LM_AFTER_TIME, " +
				" SFT_DTL_IN_HD_AFTER_TIME, SFT_DTL_BREAK_TIME_START, SFT_DTL_BREAK_TIME_END, SFT_DTL_OUT_HD_BEFORE_TIME, SFT_DTL_OUT_EL_BEFORE_TIME, " +
				" SFT_DTL_END_TIME, SFT_DTL_WORK_HRS, SFT_DTL_EXTRAWORK_START, SFT_DTL_NIGHT_FLAG) " +
				" VALUES (?, ?, TO_DATE(?, 'HH24:MI'), TO_DATE(?, 'HH24:MI'), TO_DATE(?, 'HH24:MI'), TO_DATE(?, 'HH24:MI'), TO_DATE(?, 'HH24:MI'), " +
				" TO_DATE(?, 'HH24:MI'), TO_DATE(?, 'HH24:MI'), TO_DATE(?, 'HH24:MI'), TO_DATE(?, 'HH24:MI'), TO_DATE(?, 'HH24:MI'), ?) ";
				
			case 10 :
				return " DELETE FROM HRMS_SHIFT_DTL WHERE SHIFT_ID = ? AND SFT_DTL_EXCEPTIONAL_DAY = ? ";
				
			case 11 :
				return " DELETE FROM HRMS_SHIFT_DTL WHERE SHIFT_ID = ? ";

			default:
				return "FRAMEWORK COULD NOT FIND QUERY NUMBER SPECIFIED";
		}
	}
}