package org.paradyne.sql.admin.master;
import org.paradyne.lib.SqlBase;
/*
 * author:Pradeep Kumar Sahoo
 * Date:20-05-2008
 */
public class TDSMasterModelSql extends SqlBase {
	
	
	public String getQuery(int id) {
		switch(id) {
		
		case 1: return "INSERT INTO HRMS_TAX_PARAMETER(TDS_CODE,TDS_EFF_DATE,TDS_DEBIT_CODE,TDS_EDU_CESS,TDS_SURCHARGE,TDS_SRCITIZEN_AGE,TDS_SURCHARGE_LIMIT_AMT,TDS_HRAEXEMPT_PAIDCOND1,TDS_HRAEXEMPT_PAIDCOND2,TDS_HRAEXEMPT_PAIDCOND3,TDS_HRAEXEMPT_UNPAIDCOND1,TDS_HRAEXEMPT_UNPAIDCOND2,TDS_HRAEXEMPT_UNPAIDCOND3,TDS_HRA_CREDITCODE,TDS_BASIC_CREDITCODE,TDS_DA_CREDITCODE,TDS_HRAEXEMPT_INVCODE,TDS_REBATEMAX_AMOUNT,TDS_EMPPF_INVCODE," +
		" TDS_SIGNING_AUTH,TDS_HRAEXEMPT_COND1MET,TDS_INV_VERIFICATION_DATE,TDS_FINANCIALYEAR_FROM, " +
		" TDS_FINANCIALYEAR_TO,TDS_LEAVE_ENCASH_LIMIT, TDS_LEAVE_ENC_SALARY_FORMULA, TDS_MONTHS_ENCASH_SAL,TDS_EMPLEAVE_ENC_INVCODE ,TDS_GRATUITY_LIMIT, TDS_GRATUITY_EXEMPT_INVCODE, TDS_GRATUITY_CREDIT_CODE ,TDS_LTA_LIMIT, TDS_LTA_EXEMPT_INVCODE, TDS_LTA_CREDIT_CODE,TDS_TRANS_ALLW_LIMIT, TDS_TRANS_ALLW_EXPT_CODE, TDS_VEH_CAPACITY_LESS, TDS_VEH_CAPACITY_GREATER, TDS_VEH_ADDN_EXPT, TDS_VEH_ALLW_EXPT_CODE, TDS_DONATION_EXPT_CODE,TDS_INV_DEC_CUTOFF_DATE, TDS_MONTH_INV_DEC_PERIOD_FROM, TDS_MONTH_INV_DEC_PERIOD_TO,  " +
		" TDS_HRA_UNPAID_EXEMPT_INVCODE, TDS_ACCOM_PERQ_CODE, ACCOM_PERQ_CENT_OWNED_HIGHER, ACCOM_PERQ_CENT_OWNED_LESS, " + 
		" ACCOM_PERQ_CENT_RENTED_HIGHER, ACCOM_PERQ_CENT_RENTED_LESS, TRANS_ALLW_LIMIT_DISABILITY, TRANS_ALLW_CREDIT_CODE, " + 
		" DISABILITY_INVCODE, TDS_STD_INTEREST_RATE, TDS_COMPANY_LOAN_PERQ_CODE,TDS_MIN_LOAN_AMT," +
		" TDS_LOCK_FLAG,TDS_DONATION_GROSS_PERCENT, TDS_DONATION_APPL_INVESTMENT,TDS_REBATE_ENABLE,"
		+" TDS_REBATE_AMOUNT,TDS_REBATE_INCOME_LIMIT ) " +
		" VALUES((SELECT NVL(MAX(TDS_CODE),0)+1 FROM  HRMS_TAX_PARAMETER),TO_DATE(?,'DD-MM-YYYY'),?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,TO_DATE(?,'DD-MM-YYYY')," +
		" ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,TO_DATE(?,'DD-MM-YYYY'),?,?,?," +
		" ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ";

		
		case 2:return " UPDATE  HRMS_TAX_PARAMETER SET TDS_EFF_DATE=TO_DATE(?,'DD-MM-YYYY'),TDS_DEBIT_CODE=?,TDS_EDU_CESS=?,TDS_SURCHARGE=?,"
		 				+" TDS_SRCITIZEN_AGE=?,TDS_SURCHARGE_LIMIT_AMT=?,TDS_HRAEXEMPT_PAIDCOND1=?,"
						+" TDS_HRAEXEMPT_PAIDCOND2=?,TDS_HRAEXEMPT_PAIDCOND3=?,TDS_HRAEXEMPT_UNPAIDCOND1=?,TDS_HRAEXEMPT_UNPAIDCOND2=?,TDS_HRAEXEMPT_UNPAIDCOND3=? ," 
						+" TDS_HRA_CREDITCODE=?,TDS_BASIC_CREDITCODE=?,TDS_DA_CREDITCODE=?,TDS_HRAEXEMPT_INVCODE=?,TDS_REBATEMAX_AMOUNT=?,TDS_EMPPF_INVCODE=?,"
						+" TDS_SIGNING_AUTH=?,TDS_HRAEXEMPT_COND1MET=? ,TDS_INV_VERIFICATION_DATE=TO_DATE(?,'DD-MM-YYYY'), TDS_REIMBURSEMENT_DATE=TO_DATE(?,'DD-MM-YYYY'),"
						+" TDS_FINANCIALYEAR_FROM=?, TDS_FINANCIALYEAR_TO=?, TDS_LEAVE_ENCASH_LIMIT=?, TDS_LEAVE_ENC_SALARY_FORMULA=?, TDS_MONTHS_ENCASH_SAL=?,"
						+" TDS_EMPLEAVE_ENC_INVCODE=?  ,TDS_GRATUITY_LIMIT=?, TDS_GRATUITY_EXEMPT_INVCODE=?, TDS_GRATUITY_CREDIT_CODE=? ,TDS_LTA_LIMIT=?,"
						+" TDS_LTA_EXEMPT_INVCODE=?, TDS_LTA_CREDIT_CODE =?,TDS_TRANS_ALLW_LIMIT =? , TDS_TRANS_ALLW_EXPT_CODE =? ,"
						+" TDS_VEH_CAPACITY_LESS =? , TDS_VEH_CAPACITY_GREATER =? , TDS_VEH_ADDN_EXPT =? , TDS_VEH_ALLW_EXPT_CODE =? ,"
						+" TDS_DONATION_EXPT_CODE =? ,TDS_INV_DEC_CUTOFF_DATE =TO_DATE(?,'DD-MM-YYYY') ,"
						+" TDS_MONTH_INV_DEC_PERIOD_FROM = ? , TDS_MONTH_INV_DEC_PERIOD_TO =?,  "
						+" TDS_HRA_UNPAID_EXEMPT_INVCODE = ? ,TDS_ACCOM_PERQ_CODE = ? ,ACCOM_PERQ_CENT_OWNED_HIGHER = ?, "
						+" ACCOM_PERQ_CENT_OWNED_LESS = ? ,ACCOM_PERQ_CENT_RENTED_HIGHER = ? ,ACCOM_PERQ_CENT_RENTED_LESS = ?, "
						+" TRANS_ALLW_LIMIT_DISABILITY = ? ,TRANS_ALLW_CREDIT_CODE = ? ,DISABILITY_INVCODE = ?, "
						+" TDS_STD_INTEREST_RATE = ? ,TDS_COMPANY_LOAN_PERQ_CODE = ?, TDS_MIN_LOAN_AMT = ?,"
						+" TDS_LOCK_FLAG = ? ,TDS_DONATION_GROSS_PERCENT=?, TDS_DONATION_APPL_INVESTMENT=?,"
						+" TDS_REBATE_ENABLE= ?,TDS_REBATE_AMOUNT=?,TDS_REBATE_INCOME_LIMIT=?"
						+" WHERE TDS_CODE = ? ";
		
		case 3:return " DELETE FROM  HRMS_TAX_PARAMETER WHERE TDS_CODE = ? " ;
		
		case 4:return "SELECT NVL(TDS_SRCITIZEN_AGE,''),NVL(TDS_SURCHARGE_LIMIT_AMT,'') ,"
						+" NVL(TDS_HRAEXEMPT_PAIDCOND1,' '),NVL(TDS_HRAEXEMPT_PAIDCOND2,' '),NVL(TDS_HRAEXEMPT_PAIDCOND3,' '),NVL(TDS_HRAEXEMPT_UNPAIDCOND1,' '),"
						+" NVL(TDS_HRAEXEMPT_UNPAIDCOND2,' '),NVL(TDS_HRAEXEMPT_UNPAIDCOND3,' '),NVL(TDS_HRA_CREDITCODE,''),NVL(HRMS_CREDIT_HEAD.CREDIT_NAME,' '),"
						+" NVL(TDS_BASIC_CREDITCODE,''),NVL(BASIC.CREDIT_NAME,' '),"
						+" NVL(TDS_DA_CREDITCODE,''),NVL(DA.CREDIT_NAME,' '),NVL(TDS_HRAEXEMPT_INVCODE,''),"
						+" NVL(HRMS_TAX_INVESTMENT.INV_NAME,' '),NVL(TDS_REBATEMAX_AMOUNT,''),PROVIDENT.INV_CODE,NVL(PROVIDENT.INV_NAME,' '),"
						+" TDS_SIGNING_AUTH,EMP_FNAME||' '||EMP_MNAME||' '||EMP_LNAME ,EMP_TOKEN,NVL(TDS_HRAEXEMPT_COND1MET,' ')," 
						+" TO_CHAR(TDS_INV_VERIFICATION_DATE,'DD-MM-YYYY'), TO_CHAR(TDS_REIMBURSEMENT_DATE,'DD-MM-YYYY') ,"
						+" TDS_FINANCIALYEAR_FROM, TDS_FINANCIALYEAR_TO ,"
						+" NVL(TDS_LEAVE_ENCASH_LIMIT,0),NVL(TDS_LEAVE_ENC_SALARY_FORMULA,''),NVL(TDS_MONTHS_ENCASH_SAL,''),"
						+" NVL(TDS_EMPLEAVE_ENC_INVCODE,''),NVL(LEAVEENCASH.INV_NAME,' '), "
						+" TDS_GRATUITY_LIMIT, TDS_GRATUITY_EXEMPT_INVCODE, HRMS_TAX_PARAMETER.TDS_GRATUITY_CREDIT_CODE,NVL(GRATUITY.CREDIT_NAME,' '), "
						+" T1.INV_NAME ,TDS_LTA_LIMIT, TDS_LTA_EXEMPT_INVCODE, TDS_LTA_CREDIT_CODE,T2.INV_NAME, "
						+" NVL(C2.CREDIT_NAME,' ')," 
						+" TDS_TRANS_ALLW_LIMIT, TDS_TRANS_ALLW_EXPT_CODE,T3.INV_NAME, TDS_VEH_CAPACITY_LESS, TDS_VEH_CAPACITY_GREATER, "
						+" TDS_VEH_ADDN_EXPT, TDS_VEH_ALLW_EXPT_CODE,T4.INV_NAME, TDS_DONATION_EXPT_CODE,T5.INV_NAME,"
						+" TO_CHAR(TDS_INV_DEC_CUTOFF_DATE,'DD-MM-YYYY'),TDS_MONTH_INV_DEC_PERIOD_FROM, TDS_MONTH_INV_DEC_PERIOD_TO," 
						+" HRMS_TAX_PARAMETER.TDS_MIN_LOAN_AMT  "
						+" FROM  HRMS_TAX_PARAMETER "
						+" LEFT JOIN HRMS_CREDIT_HEAD ON (HRMS_TAX_PARAMETER.TDS_HRA_CREDITCODE=HRMS_CREDIT_HEAD.CREDIT_CODE)"
						+" LEFT JOIN HRMS_CREDIT_HEAD C1 ON (HRMS_TAX_PARAMETER.TDS_HRA_CREDITCODE=C1.CREDIT_CODE)"
						+" LEFT JOIN HRMS_CREDIT_HEAD BASIC ON(HRMS_TAX_PARAMETER.TDS_BASIC_CREDITCODE=BASIC.CREDIT_CODE)"
						+" LEFT JOIN HRMS_CREDIT_HEAD DA ON(HRMS_TAX_PARAMETER.TDS_DA_CREDITCODE=DA.CREDIT_CODE) "
						+" LEFT JOIN HRMS_TAX_INVESTMENT ON(HRMS_TAX_INVESTMENT.INV_CODE=HRMS_TAX_PARAMETER.TDS_HRAEXEMPT_INVCODE) "
						+" LEFT JOIN HRMS_TAX_INVESTMENT LEAVEENCASH  ON(LEAVEENCASH.INV_CODE=HRMS_TAX_PARAMETER.TDS_EMPLEAVE_ENC_INVCODE) "
						+" INNER JOIN HRMS_TAX_INVESTMENT PROVIDENT ON(PROVIDENT.INV_CODE=HRMS_TAX_PARAMETER.TDS_EMPPF_INVCODE)"
						+" LEFT JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=HRMS_TAX_PARAMETER.TDS_SIGNING_AUTH) "
						+" LEFT JOIN HRMS_CREDIT_HEAD GRATUITY ON (HRMS_TAX_PARAMETER.TDS_GRATUITY_CREDIT_CODE=GRATUITY.CREDIT_CODE)"
						+"  LEFT JOIN HRMS_TAX_INVESTMENT T1 ON (HRMS_TAX_PARAMETER.TDS_GRATUITY_EXEMPT_INVCODE=T1.INV_CODE) "
						+" LEFT JOIN HRMS_TAX_INVESTMENT T2 ON (HRMS_TAX_PARAMETER.TDS_LTA_EXEMPT_INVCODE=T2.INV_CODE) "
						+" LEFT JOIN HRMS_TAX_INVESTMENT T3 ON (HRMS_TAX_PARAMETER.TDS_TRANS_ALLW_EXPT_CODE=T3.INV_CODE) "
						+" LEFT JOIN HRMS_TAX_INVESTMENT T4 ON (HRMS_TAX_PARAMETER.TDS_VEH_ALLW_EXPT_CODE=T4.INV_CODE) "
						+" LEFT JOIN HRMS_TAX_INVESTMENT T5 ON (HRMS_TAX_PARAMETER.TDS_DONATION_EXPT_CODE=T5.INV_CODE) "
						+"  LEFT JOIN HRMS_CREDIT_HEAD C2 ON (HRMS_TAX_PARAMETER.TDS_LTA_CREDIT_CODE=C2.CREDIT_CODE)"
						+" WHERE TDS_CODE=?";
		
		case 5:return "SELECT NVL(HRMS_TAX_PARAMETER.TDS_SRCITIZEN_AGE,''), NVL(HRMS_TAX_PARAMETER.TDS_SURCHARGE_LIMIT_AMT,'') ,"
					+" NVL(HRMS_TAX_PARAMETER.TDS_HRAEXEMPT_PAIDCOND1,' '), NVL(HRMS_TAX_PARAMETER.TDS_HRAEXEMPT_PAIDCOND2,' '),"
					+" NVL(TDS_HRAEXEMPT_PAIDCOND3,' '), NVL(TDS_HRAEXEMPT_UNPAIDCOND1,' '),"
					+" NVL(TDS_HRAEXEMPT_UNPAIDCOND2,' '), NVL(TDS_HRAEXEMPT_UNPAIDCOND3,' '),"
					+" NVL(TDS_HRA_CREDITCODE,''), NVL(HRMS_CREDIT_HEAD.CREDIT_NAME,' '), NVL(TDS_BASIC_CREDITCODE,''),"
					+" NVL(BASIC.CREDIT_NAME,' '), NVL(TDS_DA_CREDITCODE,''), NVL(DA.CREDIT_NAME,' '),"
					+" NVL(TDS_HRAEXEMPT_INVCODE,''), NVL(HRMS_TAX_INVESTMENT.INV_NAME,' '), NVL(TDS_REBATEMAX_AMOUNT,''),"
					+" PROVIDENT.INV_CODE,NVL(PROVIDENT.INV_NAME,' '), TO_CHAR(TDS_EFF_DATE,'DD-MM-YYYY'), "
					+" TDS_DEBIT_CODE,NVL(HRMS_DEBIT_HEAD.DEBIT_NAME,' '),TDS_EDU_CESS,TDS_SURCHARGE, " 
					+" TDS_CODE,TDS_SIGNING_AUTH,EMP_FNAME||' '||EMP_MNAME||' '||EMP_LNAME ,EMP_TOKEN,NVL(TDS_HRAEXEMPT_COND1MET,' '),"
					+" TO_CHAR(TDS_INV_VERIFICATION_DATE,'DD-MM-YYYY'), TO_CHAR(TDS_REIMBURSEMENT_DATE,'DD-MM-YYYY'), "
					+" TDS_FINANCIALYEAR_FROM, TDS_FINANCIALYEAR_TO ,"
					+" NVL(TDS_LEAVE_ENCASH_LIMIT,0),NVL(TDS_LEAVE_ENC_SALARY_FORMULA,''),NVL(TDS_MONTHS_ENCASH_SAL,''),"
					+" NVL(TDS_EMPLEAVE_ENC_INVCODE,''),NVL(LeaveEncash.INV_NAME,' '), " 
					+" TDS_GRATUITY_LIMIT, TDS_GRATUITY_EXEMPT_INVCODE, HRMS_TAX_PARAMETER.TDS_GRATUITY_CREDIT_CODE,NVL(GRATUITY.CREDIT_NAME,' '),"
					+" T1.INV_NAME, "
					+" TDS_LTA_LIMIT, TDS_LTA_EXEMPT_INVCODE, TDS_LTA_CREDIT_CODE,T2.INV_NAME, "
					+" NVL(C2.CREDIT_NAME,' '),"
					+" TDS_TRANS_ALLW_LIMIT, TDS_TRANS_ALLW_EXPT_CODE,T3.INV_NAME, TDS_VEH_CAPACITY_LESS, TDS_VEH_CAPACITY_GREATER, "
					+" TDS_VEH_ADDN_EXPT, TDS_VEH_ALLW_EXPT_CODE,T4.INV_NAME, TDS_DONATION_EXPT_CODE,T5.INV_NAME,"
					+" TO_CHAR(TDS_INV_DEC_CUTOFF_DATE,'DD-MM-YYYY'),TDS_MONTH_INV_DEC_PERIOD_FROM, TDS_MONTH_INV_DEC_PERIOD_TO,  "
					+" NVL(HRMS_TAX_PARAMETER.TDS_HRA_UNPAID_EXEMPT_INVCODE,''),NVL(HRAUnpaidExe.INV_NAME,' '), "
					+" NVL(HRMS_TAX_PARAMETER.TDS_ACCOM_PERQ_CODE,''),NVL(HRMS_PERQUISITE_HEAD.PERQ_NAME,' '), "
					+" NVL(HRMS_TAX_PARAMETER.ACCOM_PERQ_CENT_OWNED_HIGHER,''),NVL(HRMS_TAX_PARAMETER.ACCOM_PERQ_CENT_OWNED_LESS,''), "
					+" NVL(HRMS_TAX_PARAMETER.ACCOM_PERQ_CENT_RENTED_HIGHER,''),NVL(HRMS_TAX_PARAMETER.ACCOM_PERQ_CENT_RENTED_LESS,''), "
					+" NVL(HRMS_TAX_PARAMETER.TRANS_ALLW_LIMIT_DISABILITY,''), "
					+" NVL(HRMS_TAX_PARAMETER.TRANS_ALLW_CREDIT_CODE,''), "
					+" NVL(Trans.CREDIT_NAME,' '), "
					+" NVL(HRMS_TAX_PARAMETER.DISABILITY_INVCODE,''), "
					+" NVL(Disability.INV_NAME,' '), "
					+" NVL(HRMS_TAX_PARAMETER.TDS_STD_INTEREST_RATE,''), "
					+" NVL(HRMS_TAX_PARAMETER.TDS_COMPANY_LOAN_PERQ_CODE,'') ,"
					+" NVL(LoanInterest.PERQ_NAME,' '), "
					+" NVL(HRMS_TAX_PARAMETER.TDS_MIN_LOAN_AMT,''), "
					+" NVL(HRMS_TAX_PARAMETER.TDS_LOCK_FLAG,''),NVL(HRMS_TAX_PARAMETER.TDS_DONATION_GROSS_PERCENT,''),"
					+" NVL(TDS_REBATE_ENABLE,'N'),"
					+" NVL(TDS_REBATE_AMOUNT,''),"
					+" NVL(TDS_REBATE_INCOME_LIMIT,'')"
					+" FROM  HRMS_TAX_PARAMETER "
					+" LEFT JOIN HRMS_CREDIT_HEAD ON (HRMS_TAX_PARAMETER.TDS_HRA_CREDITCODE=HRMS_CREDIT_HEAD.CREDIT_CODE)"
					+" LEFT JOIN HRMS_CREDIT_HEAD C1 ON (HRMS_TAX_PARAMETER.TDS_HRA_CREDITCODE=C1.CREDIT_CODE)"
					+" LEFT JOIN HRMS_CREDIT_HEAD BASIC ON(HRMS_TAX_PARAMETER.TDS_BASIC_CREDITCODE=BASIC.CREDIT_CODE)"
					+" LEFT JOIN HRMS_CREDIT_HEAD DA ON(HRMS_TAX_PARAMETER.TDS_DA_CREDITCODE=DA.CREDIT_CODE) "
					+" LEFT JOIN HRMS_TAX_INVESTMENT ON(HRMS_TAX_INVESTMENT.INV_CODE=HRMS_TAX_PARAMETER.TDS_HRAEXEMPT_INVCODE) "
					+" LEFT JOIN HRMS_TAX_INVESTMENT HRAUnpaidExe ON(HRAUnpaidExe.INV_CODE=HRMS_TAX_PARAMETER.TDS_HRA_UNPAID_EXEMPT_INVCODE) "
					+" LEFT JOIN HRMS_PERQUISITE_HEAD ON(HRMS_PERQUISITE_HEAD.PERQ_CODE=HRMS_TAX_PARAMETER.TDS_ACCOM_PERQ_CODE) "
					+" LEFT JOIN HRMS_CREDIT_HEAD Trans ON (Trans.CREDIT_CODE = HRMS_TAX_PARAMETER.TRANS_ALLW_CREDIT_CODE) "
					+" LEFT JOIN HRMS_TAX_INVESTMENT Disability ON (Disability.INV_CODE = HRMS_TAX_PARAMETER.DISABILITY_INVCODE) "
					+" LEFT JOIN HRMS_PERQUISITE_HEAD LoanInterest ON (HRMS_TAX_PARAMETER.TDS_COMPANY_LOAN_PERQ_CODE = LoanInterest.PERQ_CODE) " 
					+" LEFT JOIN HRMS_TAX_INVESTMENT  LeaveEncash  ON(LeaveEncash.INV_CODE=HRMS_TAX_PARAMETER.TDS_EMPLEAVE_ENC_INVCODE) "
					+" INNER JOIN HRMS_TAX_INVESTMENT PROVIDENT ON(PROVIDENT.INV_CODE=HRMS_TAX_PARAMETER.TDS_EMPPF_INVCODE)"
					+" INNER JOIN HRMS_DEBIT_HEAD ON (HRMS_TAX_PARAMETER.TDS_DEBIT_CODE=HRMS_DEBIT_HEAD.DEBIT_CODE)"
					+" LEFT JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=HRMS_TAX_PARAMETER.TDS_SIGNING_AUTH) "
					+" LEFT JOIN HRMS_CREDIT_HEAD GRATUITY ON (HRMS_TAX_PARAMETER.TDS_GRATUITY_CREDIT_CODE=GRATUITY.CREDIT_CODE)"
					+" LEFT JOIN HRMS_TAX_INVESTMENT T1 ON (HRMS_TAX_PARAMETER.TDS_GRATUITY_EXEMPT_INVCODE=T1.INV_CODE) "
					+" LEFT JOIN HRMS_TAX_INVESTMENT T2 ON (HRMS_TAX_PARAMETER.TDS_LTA_EXEMPT_INVCODE=T2.INV_CODE) "
					+" LEFT JOIN HRMS_TAX_INVESTMENT T3 ON (HRMS_TAX_PARAMETER.TDS_TRANS_ALLW_EXPT_CODE=T3.INV_CODE) "
					+" LEFT JOIN HRMS_TAX_INVESTMENT T4 ON (HRMS_TAX_PARAMETER.TDS_VEH_ALLW_EXPT_CODE=T4.INV_CODE) "
					+" LEFT JOIN HRMS_TAX_INVESTMENT T5 ON (HRMS_TAX_PARAMETER.TDS_DONATION_EXPT_CODE=T5.INV_CODE) "
					+" LEFT JOIN HRMS_CREDIT_HEAD C2 ON (HRMS_TAX_PARAMETER.TDS_LTA_CREDIT_CODE=C2.CREDIT_CODE)"
					+" WHERE HRMS_TAX_PARAMETER.TDS_CODE=?";
		
		case 6: return "SELECT  RTRIM (xmlagg (xmlelement (e, HRMS_TAX_INVESTMENT.INV_NAME,';' )).extract ('//text()'), ',')  Name "
						+" from HRMS_TAX_PARAMETER LEFT JOIN HRMS_TAX_INVESTMENT "
						+" ON HRMS_TAX_INVESTMENT.INV_CODE IN "
						+" (	SELECT * FROM  THE(  SELECT CAST(STR2TBL(TDS_DONATION_APPL_INVESTMENT)"
						+"  AS MYTABLETYPE ) from  HRMS_TAX_PARAMETER where HRMS_TAX_PARAMETER.TDS_CODE = ? )"
						+" ) WHERE HRMS_TAX_PARAMETER.TDS_CODE = ?";
		
		default : return "Query number not specified." ;
		}
		
		
	}		

}
