/**
 * 
 */
package org.paradyne.sql.TravelManagement.TravelPlan;

import org.paradyne.lib.SqlBase;

/**
 * @author aa0417
 *
 */
public class TravelApplicationModelSql extends SqlBase {

	
	public String getQuery(int id) {
		// TODO Auto-generated method stub
		switch(id)
		{
			case 1: return "    INSERT INTO HRMS_TMS_TRAVEL_APP ( TRAVEL_APP_ID, TRAVEL_APP_EMPID, TRAVEL_APP_APPDATE, "
						 +"  TRAVEL_APP_STATUS, TRAVEL_APP_REQUEST, TRAVEL_APP_APPFOR,TRAVEL_APP_GUEST, TRAVEL_APP_PURPOSE, TRAVEL_APP_ACCOMMODATION,"
						 +"   TRAVEL_APP_TRAVEL_ARRG, TRAVEL_APP_LOCAL_ALLOW, TRAVEL_APP_LOCATION_TYPE, TRAVEL_APP_START_DATE, TRAVEL_APP_END_DATE, TRAVEL_APP_ADVANCE, " 
						 +"  TRAVEL_APP_PAYMODE, TRAVEL_APP_SETTLE_DATE, TRAVEL_APP_IDPROOF, TRAVEL_APP_IDNUMBER, TRAVEL_APP_COMMENTS,  "
						 +"  TRAVEL_APP_APPROVER, TRAVEL_APP_ALTER_APPROVER,TRAVEL_APP_FOOD_TYPE,TRAVEL_CANCEL_APPROVER, TRAVEL_CANCEL_ALTER_APPROVER,TRAVEL_APP_POLICY_ID)  "
						 +"  VALUES ( (SELECT NVL(MAX(TRAVEL_APP_ID),0)+1 FROM HRMS_TMS_TRAVEL_APP),? ,TO_DATE(?,'DD-MM-YYYY') , "
						 +"  ? ,? , ?,  ?,? ,? ,  ?,? ,? ,  TO_DATE(?,'DD-MM-YYYY') ,TO_DATE(?,'DD-MM-YYYY')  ,? "
						 +"  ,?,TO_DATE(?,'DD-MM-YYYY')  ,? ,  ? ,? ,? ,? ,?,?,?,?)"; 
			
			case 2: return " DELETE FROM HRMS_TMS_APPJOUR_DTL WHERE APPJOUR_DTL_TRAPPID = ?"; 
			
			case 3: return " DELETE FROM HRMS_TMS_APPLOCAL_DTL WHERE APPLOCAL_DTL_TRAPPID = ? "; 
			
			case 4: return " DELETE  FROM HRMS_TMS_APPLODG_DTL WHERE APPLODG_DTL_TRAPPID = ? "; 
			
			case 5: return " DELETE  FROM HRMS_TMS_TRAVEL_APP WHERE TRAVEL_APP_ID = ? "; 
			
			case 6: return "UPDATE HRMS_TMS_TRAVEL_APP SET  TRAVEL_APP_EMPID = ?, TRAVEL_APP_APPDATE = TO_DATE(?,'DD-MM-YYYY') ,"
			 +"  TRAVEL_APP_STATUS= ?, TRAVEL_APP_REQUEST= ?, TRAVEL_APP_APPFOR= ?,TRAVEL_APP_GUEST= ?, TRAVEL_APP_PURPOSE = ? , TRAVEL_APP_ACCOMMODATION = ? ,"
			 +"   TRAVEL_APP_TRAVEL_ARRG = ? , TRAVEL_APP_LOCAL_ALLOW = ? , TRAVEL_APP_LOCATION_TYPE = ? , TRAVEL_APP_START_DATE = TO_DATE(?,'DD-MM-YYYY'), TRAVEL_APP_END_DATE= TO_DATE(?,'DD-MM-YYYY'), TRAVEL_APP_ADVANCE = ?, " 
			 +"  TRAVEL_APP_PAYMODE = ? , TRAVEL_APP_SETTLE_DATE= TO_DATE(?,'DD-MM-YYYY'), TRAVEL_APP_IDPROOF = ?, TRAVEL_APP_IDNUMBER = ?, TRAVEL_APP_COMMENTS = ?, "
			 +"  TRAVEL_APP_APPROVER = ? , TRAVEL_APP_ALTER_APPROVER = ? ,TRAVEL_APP_FOOD_TYPE = ? ,TRAVEL_CANCEL_APPROVER = ?, TRAVEL_CANCEL_ALTER_APPROVER =? ,TRAVEL_APP_POLICY_ID = ? WHERE TRAVEL_APP_ID = ?  ";
			
            case 7: return " DELETE FROM HRMS_TMS_APPJOUR_DTL_TRACK WHERE APPJOUR_DTL_TRAPPID = ? AND APPJOUR_DTL_MODIFIED_BY =? "; 
			
			case 8: return " DELETE FROM HRMS_TMS_APPLOCAL_DTL_TRACK WHERE APPLOCAL_DTL_TRAPPID = ? AND APPLOCAL_DTL_MODIFIED_BY = ?  "; 
			
			case 9: return " DELETE  FROM HRMS_TMS_APPLODG_DTL_TRACK WHERE APPLODG_DTL_TRAPPID = ? AND APPLOCAL_DTL_MODIFIED_BY = ?"; 
			 
			case 10: return "UPDATE HRMS_TMS_TRAVEL_APP SET  TRAVEL_APP_EMPID = ?, TRAVEL_APP_APPDATE = TO_DATE(?,'DD-MM-YYYY') ,"
			 +"  TRAVEL_APP_STATUS= ?, TRAVEL_APP_REQUEST= ?, TRAVEL_APP_APPFOR= ?,TRAVEL_APP_GUEST= ?, TRAVEL_APP_PURPOSE = ? , TRAVEL_APP_ACCOMMODATION = ? ,"
			 +"   TRAVEL_APP_TRAVEL_ARRG = ? , TRAVEL_APP_LOCAL_ALLOW = ? , TRAVEL_APP_LOCATION_TYPE = ? , TRAVEL_APP_START_DATE = TO_DATE(?,'DD-MM-YYYY'), TRAVEL_APP_END_DATE= TO_DATE(?,'DD-MM-YYYY'), TRAVEL_APP_ADVANCE = ?, " 
			 +"  TRAVEL_APP_PAYMODE = ? , TRAVEL_APP_SETTLE_DATE= TO_DATE(?,'DD-MM-YYYY'), TRAVEL_APP_IDPROOF = ?, TRAVEL_APP_IDNUMBER = ? ,TRAVEL_APP_FOOD_TYPE = ?  WHERE TRAVEL_APP_ID = ?  ";
			 
			case 11: return "    INSERT INTO HRMS_TMS_TRAVEL_APP ( TRAVEL_APP_ID, TRAVEL_APP_EMPID, TRAVEL_APP_APPDATE, "
			 +"  TRAVEL_APP_STATUS, TRAVEL_APP_REQUEST, TRAVEL_APP_APPFOR,TRAVEL_APP_GUEST, TRAVEL_APP_PURPOSE, TRAVEL_APP_ACCOMMODATION,"
			 +"   TRAVEL_APP_TRAVEL_ARRG, TRAVEL_APP_LOCAL_ALLOW, TRAVEL_APP_LOCATION_TYPE, TRAVEL_APP_START_DATE, TRAVEL_APP_END_DATE, TRAVEL_APP_ADVANCE, " 
			 +"  TRAVEL_APP_PAYMODE, TRAVEL_APP_SETTLE_DATE, TRAVEL_APP_IDPROOF, TRAVEL_APP_IDNUMBER, TRAVEL_APP_COMMENTS,  "
			 +"  TRAVEL_APP_FOOD_TYPE,TRAVEL_APP_POLICY_ID)  "
			 +"  VALUES ( (SELECT NVL(MAX(TRAVEL_APP_ID),0)+1 FROM HRMS_TMS_TRAVEL_APP),? ,TO_DATE(?,'DD-MM-YYYY') , "
			 +"  ? ,? , ?,  ?,? ,? ,  ?,? ,? ,  TO_DATE(?,'DD-MM-YYYY') ,TO_DATE(?,'DD-MM-YYYY')  ,? "
			 +"  ,?,TO_DATE(?,'DD-MM-YYYY')  ,? ,  ? ,? ,?,? )"; 
			
			case 12: return "UPDATE HRMS_TMS_TRAVEL_APP SET  TRAVEL_APP_EMPID = ?, TRAVEL_APP_APPDATE = TO_DATE(?,'DD-MM-YYYY') ,"
			 +"  TRAVEL_APP_STATUS= ?, TRAVEL_APP_REQUEST= ?, TRAVEL_APP_APPFOR= ?,TRAVEL_APP_GUEST= ?, TRAVEL_APP_PURPOSE = ? , TRAVEL_APP_ACCOMMODATION = ? ,"
			 +"   TRAVEL_APP_TRAVEL_ARRG = ? , TRAVEL_APP_LOCAL_ALLOW = ? , TRAVEL_APP_LOCATION_TYPE = ? , TRAVEL_APP_START_DATE = TO_DATE(?,'DD-MM-YYYY'), TRAVEL_APP_END_DATE= TO_DATE(?,'DD-MM-YYYY'), TRAVEL_APP_ADVANCE = ?, " 
			 +"  TRAVEL_APP_PAYMODE = ? , TRAVEL_APP_SETTLE_DATE= TO_DATE(?,'DD-MM-YYYY'), TRAVEL_APP_IDPROOF = ?, TRAVEL_APP_IDNUMBER = ?, TRAVEL_APP_COMMENTS = ?, "
			 +"  TRAVEL_APP_FOOD_TYPE = ?,TRAVEL_APP_POLICY_ID =?  WHERE TRAVEL_APP_ID = ?  ";
			
			default:return "Framework could not EXECUTE the query number specified"; 
		}
	
		
	}
	
}
