/**
 * 
 */
package org.paradyne.sql.extraWorkBenefits;

import org.paradyne.lib.SqlBase;

/**
 * @author AA0623
 * 
 */
public class ExtraWorkApplicationModelSql extends SqlBase {
	public String getQuery(int queryID) {
		switch (queryID) {

		case 1:
			return " SELECT  HRMS_EMP_OFFC.EMP_TOKEN,  HRMS_EMP_OFFC.EMP_FNAME||' '||HRMS_EMP_OFFC.EMP_MNAME||' '||HRMS_EMP_OFFC.EMP_LNAME, "
					+ " TO_CHAR(HRMS_EXTRAWORK_APPL_HDR.EXTRAWORK_APPL_DATE,'DD-MM-YYYY'),HRMS_EXTRAWORK_APPL_HDR.EMP_ID, "
					+ " HRMS_EXTRAWORK_APPL_HDR.EXTRAWORK_APPL_CODE,HRMS_EXTRAWORK_APPL_HDR.EXTRAWORK_APPL_STATUS "
					+ " FROM HRMS_EXTRAWORK_APPL_HDR "
					+ " INNER JOIN HRMS_EMP_OFFC ON (HRMS_EMP_OFFC.EMP_ID  = HRMS_EXTRAWORK_APPL_HDR.EMP_ID) "
					+ " WHERE HRMS_EXTRAWORK_APPL_HDR.EXTRAWORK_APPL_STATUS=? AND HRMS_EXTRAWORK_APPL_HDR.EMP_ID=? "
					+ " ORDER BY EXTRAWORK_APPL_CODE DESC";

		case 2:
			return " SELECT EMP_TOKEN, (EMP_FNAME||' '||EMP_MNAME||' '||EMP_LNAME) EMP_NAME, CENTER_NAME, DEPT_NAME, RANK_NAME, "
					+ " EMP_ID FROM HRMS_EMP_OFFC "
					+ " LEFT JOIN HRMS_TITLE ON(HRMS_TITLE.TITLE_CODE = HRMS_EMP_OFFC.EMP_TITLE_CODE ) "
					+ " INNER JOIN HRMS_CENTER ON (HRMS_CENTER.CENTER_ID = HRMS_EMP_OFFC. EMP_CENTER ) "
					+ " INNER JOIN HRMS_RANK ON (HRMS_RANK.RANK_ID = HRMS_EMP_OFFC. EMP_RANK ) "
					+ " INNER JOIN HRMS_DEPT ON (HRMS_DEPT.DEPT_ID = HRMS_EMP_OFFC. EMP_DEPT ) "
					+ " WHERE EMP_ID = ?";

		case 3:
			return " INSERT INTO HRMS_EXTRAWORK_APPL_HDR(EXTRAWORK_APPL_CODE, EMP_ID, EXTRAWORK_APPL_DATE, EXTRAWORK_APPL_APPROVER, EXTRAWORK_APPL_COMMENTS, EXTRAWORK_APPL_ALT_APPROVER,EXTRAWORK_APPL_STATUS) "
					+ " VALUES(?, ?, TO_DATE(?, 'DD-MM-YYYY'), ?, ?, ?, ?) ";

		case 4:
			return " INSERT INTO HRMS_EXTRAWORK_APPL_DTL(EXTRAWORK_APPL_CODE, EXTRAWORK_PURPOSE, EXTRAWORK_DATE, EXTRAWORK_STARTTIME, EXTRAWORK_ENDTIME ,EXTRAWORK_DAY_TYPE, EMP_ID,EXTRAWORK_APPL_STATUS, EXTRAWORK_DAY) "
					+ " VALUES(?, ?, TO_DATE(?, 'DD-MM-YYYY'), ?, ? ,?, ?, ?, ?) ";

		case 5:
			return " UPDATE HRMS_EXTRAWORK_APPL_HDR SET EMP_ID = ?, EXTRAWORK_APPL_DATE = TO_DATE(?, 'DD-MM-YYYY'), EXTRAWORK_APPL_APPROVER = ?, "
					+ " EXTRAWORK_APPL_COMMENTS = ?, EXTRAWORK_APPL_ALT_APPROVER = ?, EXTRAWORK_APPL_STATUS=? WHERE EXTRAWORK_APPL_CODE = ? ";

		case 6:
			return " INSERT INTO HRMS_EXTRAWORK_APPL_DTL(EXTRAWORK_APPL_CODE, EXTRAWORK_PURPOSE, EXTRAWORK_DATE, EXTRAWORK_STARTTIME, EXTRAWORK_ENDTIME,EXTRAWORK_DAY_TYPE, EMP_ID,EXTRAWORK_APPL_STATUS, EXTRAWORK_DAY) "
					+ " VALUES(?, ?, TO_DATE(?, 'DD-MM-YYYY'), ?, ?,?, ? , ?, ?) ";

		case 7:
			return " SELECT NVL(EXTRAWORK_APPL_STATUS,'P'),EXTRAWORK_APPL_LEVEL FROM HRMS_EXTRAWORK_APPL_HDR WHERE EXTRAWORK_APPL_CODE=? ";

		case 8:
			return " SELECT HRMS_EMP_OFFC.EMP_TOKEN, "
					+ " HRMS_EMP_OFFC.EMP_FNAME||' '||HRMS_EMP_OFFC.EMP_MNAME||' '||HRMS_EMP_OFFC.EMP_LNAME, "
					+ " HRMS_CENTER.CENTER_NAME,DEPT_NAME,HRMS_RANK.RANK_NAME,HRMS_EMP_OFFC.EMP_ID "
					+ " FROM HRMS_EMP_OFFC "
					+ " INNER JOIN HRMS_RANK ON HRMS_RANK.RANK_ID = HRMS_EMP_OFFC.EMP_RANK "
					+ " INNER JOIN HRMS_CENTER ON HRMS_CENTER.CENTER_ID = HRMS_EMP_OFFC.EMP_CENTER "
					+ " INNER JOIN HRMS_DEPT ON (HRMS_DEPT.DEPT_ID = HRMS_EMP_OFFC. EMP_DEPT ) "
					+ " WHERE HRMS_EMP_OFFC.EMP_ID=?"
					+ " ORDER BY HRMS_EMP_OFFC.EMP_ID ";

		default:
			return "QUERY NOT FOUND";

		}
	}
}