/**
 * 
 */
package org.paradyne.sql.extraWorkBenefits;

import org.paradyne.lib.SqlBase;

/**
 * @author AA0623
 *
 */
public class ExtraWorkApprovalModelSql extends SqlBase {
	public String getQuery(int id) {
		switch (id) {

		case 1:
			return " SELECT EXTRAWORK_APPL_CODE,HRMS_EXTRAWORK_APPL_HDR.EMP_ID,EMP_FNAME||' '||EMP_MNAME||' '||EMP_LNAME,TO_CHAR(EXTRAWORK_APPL_DATE,'DD-MM-YYYY'),"
					+ "	 EXTRAWORK_APPL_STATUS,EXTRAWORK_APPL_LEVEL,HRMS_EMP_OFFC.EMP_TOKEN "
					+ "	 FROM HRMS_EXTRAWORK_APPL_HDR "
					+ "	 INNER JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=HRMS_EXTRAWORK_APPL_HDR.EMP_ID)"
					+ "	 WHERE  EXTRAWORK_APPL_STATUS=?  AND (EXTRAWORK_APPL_APPROVER=? OR EXTRAWORK_APPL_ALT_APPROVER=? ) ORDER BY EXTRAWORK_APPL_CODE DESC ";			
		case 2:
			return "UPDATE HRMS_EXTRAWORK_APPL_HDR  SET EXTRAWORK_APPL_LEVEL=? ,EXTRAWORK_APPL_APPROVER=? ,EXTRAWORK_APPL_ALT_APPROVER=? WHERE EXTRAWORK_APPL_CODE=? ";
		
		case 3:
			return " UPDATE HRMS_EXTRAWORK_APPL_HDR SET EXTRAWORK_APPL_STATUS=? WHERE EXTRAWORK_APPL_CODE=?";

		case 4:
			return " UPDATE HRMS_EXTRAWORK_APPL_DTL  SET EXTRAWORK_APPL_STATUS=? WHERE EXTRAWORK_APPL_CODE=? ";

		case 5:
			return "UPDATE HRMS_EXTRAWORK_APPL_DTL  SET EXTRAWORK_APPROVED_BY=?  WHERE EXTRAWORK_APPL_CODE=? ";
		
		case 6:
			return "	INSERT INTO HRMS_EXTRAWORK_APPL_PATH(EXTRAWORK_APPL_CODE,EXTRAWORK_APPROVER,EXTRAWORK_APPROVER_STATUS,EXTRAWORK_APPROVE_DATE,EXTRAWORK_APPROVER_REMARK) "
					+ " VALUES(?,?,?,SYSDATE,?) ";
			
		case 7:
			return " UPDATE HRMS_EXTRAWORK_APPL_HDR SET EXTRAWORK_APPL_STATUS=?,EXTRAWORK_APPL_LEVEL=? ,EXTRAWORK_APPL_APPROVER=? WHERE EXTRAWORK_APPL_CODE=?";

		case 8:
			return " UPDATE HRMS_EXTRAWORK_APPL_DTL  SET EXTRAWORK_APPL_STATUS=?, EXTRAWORK_APPROVED_BY=? WHERE EXTRAWORK_APPL_CODE=? ";

			
		default:
			return "QUERY NOT FOUND";

		}
	}
}
