/**
 *Bhushan Dasare
 *Dec 28, 2007
**/

package org.paradyne.sql.budget;

import org.paradyne.lib.SqlBase;

public class BudgetExpenModelSql extends SqlBase 
{
	public String getQuery(int id)
	{
		try 
		{
			switch(id)
			{
				case 1 : return " SELECT BDGT_AMOUNT FROM HRMS_BDGTPLAN_DTL WHERE BDGT_HD_CODE = ? ";
				
				case 2 : return " SELECT * FROM HRMS_BDGTPLAN WHERE TO_DATE(?,'DD-MM-YYYY') BETWEEN BDGT_FROM_DATE AND BDGT_TO_DATE ";
				
				case 3 : return " SELECT * FROM HRMS_BDGTEXP WHERE BDGT_EDATE = TO_DATE(?,'DD-MM-YYYY') ";
				
				case 4 : return " INSERT INTO HRMS_BDGTEXP VALUES((SELECT NVL(MAX(BDGT_ECODE),0)+1 FROM HRMS_BDGTEXP), TO_DATE(?,'DD-MM-YYYY'), ?) ";
				
				case 5 : return " SELECT NVL(MAX(BDGT_ECODE),0) FROM HRMS_BDGTEXP ";
				
				case 6 : return " INSERT INTO HRMS_BDGTEXP_DTL VALUES(?, ?, ?, ?) ";
				
				case 7 : return " UPDATE HRMS_BDGTPLAN_DTL SET HRMS_BDGTPLAN_DTL.BDGT_BALANCE = (NVL(?,0) - NVL(?,0)) " + 
				" WHERE BDGT_HD_CODE = ? AND HRMS_BDGTPLAN_DTL.BDGTPLAN_CODE = (SELECT BDGTPLAN_CODE " +
				" FROM HRMS_BDGTPLAN  WHERE TO_DATE(?,'DD-MM-YYYY') BETWEEN BDGT_FROM_DATE AND BDGT_TO_DATE AND ROWNUM = 1) ";
				
				case 8 : return " UPDATE HRMS_BDGTEXP SET BDGT_EDATE = TO_DATE(?,'DD-MM-YYYY'), BDGT_EDETAILS = ? WHERE BDGT_ECODE = ? ";
				
				case 9 : return " UPDATE HRMS_BDGTEXP_DTL SET BDGT_EAMOUNT = ?, BDGT_PAIDTO = ? WHERE BDGT_HD_CODE = ? AND BDGT_ECODE = ? AND BDGT_EAMOUNT > 0 ";
				
				case 10 : return " DELETE FROM HRMS_BDGTEXP WHERE BDGT_ECODE = ? ";
				
				case 11 : return " DELETE FROM HRMS_BDGTEXP_DTL WHERE BDGT_ECODE = ? ";
				
				case 12 : return " SELECT HRMS_BDGT_HD.BDGT_HD_CODE, BDGT_HD_NAME, BDGT_AMOUNT, " +
				" (BDGT_AMOUNT - BDGT_BALANCE) EXPAMT, BDGT_BALANCE " +
				" FROM HRMS_BDGTPLAN_DTL " +
				" INNER JOIN HRMS_BDGTPLAN ON(HRMS_BDGTPLAN.BDGTPLAN_CODE = HRMS_BDGTPLAN_DTL.BDGTPLAN_CODE) " +
				" INNER JOIN HRMS_BDGT_HD ON(HRMS_BDGT_HD.BDGT_HD_CODE = HRMS_BDGTPLAN_DTL.BDGT_HD_CODE) " + 
				" WHERE TO_DATE(?,'DD-MM-YYYY') BETWEEN BDGT_FROM_DATE AND BDGT_TO_DATE AND  " +
				" (BDGT_AMOUNT - BDGT_BALANCE) > 0 AND BDGT_HD_CODE IN (SELECT BDGT_HD_CODE FROM HRMS_BDGTEXP_DTL WHERE BDGT_ECODE = ?) " +
				" ORDER BY BDGT_HD_CODE ";
				
				case 13 : return " SELECT NVL(BDGT_PAIDTO,' '),BDGT_EAMOUNT FROM HRMS_BDGTEXP_DTL WHERE BDGT_ECODE = ? ORDER BY BDGT_HD_CODE";
				
				case 14 : return " SELECT TO_CHAR(BDGT_EDATE,'DD-MM-YYYY'), BDGT_EDETAILS FROM HRMS_BDGTEXP WHERE BDGT_ECODE = ? ";
				
				//case 15 : return "update HRMS_BDGTPLAN_DTL set BDGT_AMOUNT=? where BDGTPLAN_CODE=(select )";
				
				case 15 : return " UPDATE HRMS_BDGTPLAN_DTL SET HRMS_BDGTPLAN_DTL.BDGT_BALANCE = ? " + 
							" WHERE BDGT_HD_CODE = ? AND HRMS_BDGTPLAN_DTL.BDGTPLAN_CODE = (SELECT BDGTPLAN_CODE " +
							" FROM HRMS_BDGTPLAN  WHERE TO_DATE(?,'DD-MM-YYYY') BETWEEN BDGT_FROM_DATE AND BDGT_TO_DATE AND ROWNUM = 1) ";
				
				
				default : return "";
			}
		}
		catch (Exception e) 
		{
			e.printStackTrace();
			return null;
		}
	}
}