package org.paradyne.sql.conference;

import org.paradyne.lib.SqlBase;

public class ConferenceBookingModelSql extends SqlBase {
	
	public String getQuery (int id){
		switch (id){
			
			case 1 : return "SELECT ACCESSORY_CODE, ACCESSORY_NAME,0 FROM HRMS_CONF_ACCESORIES ORDER BY ACCESSORY_CODE";
			
			case 2 : return "INSERT INTO HRMS_CONF_HDR (CONF_CODE, CONF_DATE, CONF_ROOMNO, " 
							+" CONF_FROM_TIME, CONF_TO_TIME, CONF_BOOKEDBY, CONF_PURPOSE, CONF_PARTICIPANT, CONF_STATUS, CONF_APPROVER, CONF_LEVEL,CONF_MAX_PARTICIPANT,CONF_MIN_PARTICIPANT,CONF_APPLN_DATE,CONF_DRAFT_BY, CONF_ALT_APPROVER, CONF_KEEP_INFORM, CONF_OTHER_EMAIL) "
							+" VALUES ((SELECT NVL(MAX(CONF_CODE),0)+1 FROM HRMS_CONF_HDR), "
							+" TO_DATE(?,'DD-MM-YYYY'), ?, ?, ?, ?, ?, ?, ?, ?, 1,?,?, TO_DATE(?, 'DD-MM-YYYY'),?,?,?,?)";
			
			case 3 : return "INSERT INTO HRMS_CONF_DTL (CONF_CODE, CONF_ACC_CODE, CONF_ACC_QTY, CONF_ACC_REQUIRED_FLAG) "
							+"VALUES (?, ?, ?, ?)";
			
			case 4 : return "DELETE FROM HRMS_CONF_DTL WHERE CONF_CODE = ?";
			
			case 5 : return "DELETE FROM HRMS_CONF_HDR WHERE CONF_CODE = ?";
			
			case 6 : return "UPDATE HRMS_CONF_HDR SET CONF_DATE = TO_DATE(?, 'DD-MM-YYYY'), CONF_FROM_TIME = ?, CONF_TO_TIME = ?, "
							+" CONF_BOOKEDBY = ?, CONF_PURPOSE = ?, CONF_ROOMNO = ?, CONF_PARTICIPANT = ?, CONF_STATUS = ?, "
							+" CONF_APPROVER=?, CONF_MAX_PARTICIPANT=?,CONF_MIN_PARTICIPANT=?,CONF_APPLN_DATE=TO_DATE(?, 'DD-MM-YYYY'), CONF_LEVEL=1, CONF_ALT_APPROVER=?, CONF_KEEP_INFORM=?, CONF_OTHER_EMAIL=? WHERE CONF_CODE = ?";
			
			case 7 : return "DELETE FROM HRMS_CONF_DTL WHERE CONF_CODE = ?";
			
			case 8 : return "INSERT INTO HRMS_CONF_DTL (CONF_CODE, CONF_ACC_CODE, CONF_ACC_QTY, CONF_ACC_REQUIRED_FLAG) "
							+" VALUES (?, ?, ?, ?)";
			
			case 9 : return "SELECT VENUE_CODE, VENUE_NAME FROM HRMS_CONF_VENUE ORDER BY VENUE_CODE";
			
			case 10 :return "SELECT ACCESSORY_CODE,ACCESSORY_NAME,NVL(CONF_ACC_QTY,0),NVL(CONF_ACC_REQUIRED_FLAG,'N')  " 
							+" FROM HRMS_CONF_ACCESORIES "
							+" LEFT JOIN HRMS_CONF_DTL ON "
							+" (HRMS_CONF_ACCESORIES.ACCESSORY_CODE = HRMS_CONF_DTL.CONF_ACC_CODE AND CONF_CODE=?) "
							+" ORDER BY ACCESSORY_CODE";
			
			case 11: return "SELECT CONF_CODE, CONF_DATE, CONF_FROM_TIME, CONF_TO_TIME, CONF_ROOMNO, HRMS_CONF_VENUE.VENUE_NAME  "
							+ " FROM HRMS_CONF_HDR "
							+ " INNER JOIN HRMS_CONF_VENUE ON (HRMS_CONF_VENUE.VENUE_CODE = CONF_ROOMNO)"
							+ " WHERE CONF_STATUS = 'A' AND CONF_DATE = TO_DATE(?,'DD-MM-YYYY') AND " 
							+ " ((CONF_FROM_TIME <= ? AND CONF_TO_TIME >= ?) OR (CONF_FROM_TIME <= ?" 
							+ " AND CONF_TO_TIME >= ?)) AND CONF_ROOMNO = ? ";
			
			case 12: return "SELECT CONF_CODE, CONF_DATE, CONF_FROM_TIME, CONF_TO_TIME, CONF_ROOMNO, HRMS_CONF_VENUE.VENUE_NAME  "
							+ " FROM HRMS_CONF_HDR "
							+" INNER JOIN HRMS_CONF_VENUE ON (HRMS_CONF_VENUE.VENUE_CODE = CONF_ROOMNO)"
							+ " WHERE CONF_STATUS = 'A' AND CONF_DATE = TO_DATE(?,'DD-MM-YYYY') AND " 
							+ " ((CONF_FROM_TIME <= ? AND CONF_TO_TIME >= ?) OR (CONF_FROM_TIME <= ?" 
							+ " AND CONF_TO_TIME >= ?)) AND CONF_ROOMNO = ? AND CONF_CODE NOT IN (?)";
			
			case 13 : return "SELECT CONF_CODE, TO_CHAR(CONF_DATE, 'DD-MM-YYYY'), CONF_FROM_TIME , CONF_TO_TIME, CONF_BOOKEDBY, "
							+ "(HRMS_EMP_OFFC.EMP_FNAME ||' '|| HRMS_EMP_OFFC.EMP_MNAME ||' '|| HRMS_EMP_OFFC.EMP_LNAME) NAME, "
							+ " NVL(CONF_PARTICIPANT, ' '), NVL(CONF_PURPOSE,' '),CONF_ROOMNO, HRMS_CONF_VENUE.VENUE_NAME, DECODE(CONF_STATUS, 'P', 'Pending', 'A', 'Approved', 'R', 'Rejected', 'B', 'SentBack','W','Withdrawn','C', 'Cancelled'),"
							+ " CONF_MAX_PARTICIPANT,CONF_MIN_PARTICIPANT FROM HRMS_CONF_HDR "
							+ " INNER JOIN HRMS_EMP_OFFC ON (HRMS_EMP_OFFC.EMP_ID = HRMS_CONF_HDR.CONF_BOOKEDBY) "
							+ " INNER JOIN HRMS_CONF_VENUE ON (HRMS_CONF_VENUE.VENUE_CODE = CONF_ROOMNO) "
							//+"LEFT JOIN HRMS_TITLE ON (HRMS_EMP_OFFC.EMP_TITLE_CODE = HRMS_TITLE.TITLE_CODE) "
							+ " WHERE CONF_CODE = ? "
							+ " ORDER BY CONF_CODE";
			
			case 14 : return "SELECT ACCESSORY_CODE, ACCESSORY_NAME, NVL(CONF_ACC_QTY,0) "
							+ " FROM HRMS_CONF_ACCESORIES "
							+ " LEFT JOIN HRMS_CONF_DTL ON (HRMS_CONF_ACCESORIES.ACCESSORY_CODE = HRMS_CONF_DTL.CONF_ACC_CODE " 
							+ " AND CONF_CODE=?) WHERE  CONF_ACC_REQUIRED_FLAG = 'Y' "
							+ " ORDER BY ACCESSORY_CODE";
			
			case 15: return "SELECT CONF_CODE, " 
							+" HRMS_EMP_OFFC.EMP_FNAME||' '||HRMS_EMP_OFFC.EMP_MNAME||' '||HRMS_EMP_OFFC.EMP_LNAME EMP_NAME, "
							+" TO_CHAR(HRMS_CONF_HDR.CONF_DATE,'DD-MM-YYYY'), "
							+" HRMS_CONF_HDR.CONF_STATUS, " 
							+" HRMS_CONF_HDR.CONF_BOOKEDBY EMPID, HRMS_EMP_OFFC.EMP_TOKEN, HRMS_CONF_HDR.CONF_FROM_TIME,"
							+" HRMS_CONF_HDR.CONF_TO_TIME, CONF_APPROVER FROM HRMS_CONF_HDR "
							+" INNER JOIN HRMS_EMP_OFFC ON (HRMS_EMP_OFFC.EMP_ID = HRMS_CONF_HDR.CONF_BOOKEDBY) " 
							+" INNER JOIN HRMS_CONF_VENUE ON (HRMS_CONF_VENUE.VENUE_CODE = HRMS_CONF_HDR.CONF_ROOMNO) " 
							+" WHERE HRMS_CONF_HDR.CONF_STATUS IN(?) AND HRMS_CONF_HDR.CONF_BOOKEDBY = ? "
							+" ORDER BY HRMS_CONF_HDR.CONF_DATE DESC, HRMS_CONF_HDR.CONF_CODE DESC ";
			
			case 16 : return "SELECT CONF_CODE, HRMS_EMP_OFFC.EMP_TOKEN,"
							 + " HRMS_EMP_OFFC.EMP_FNAME||' '||HRMS_EMP_OFFC.EMP_MNAME||' '||HRMS_EMP_OFFC.EMP_LNAME EMP_NAME," 
							 + " HRMS_CONF_VENUE.VENUE_NAME, TO_CHAR(HRMS_CONF_HDR.CONF_DATE,'DD-MM-YYYY')," 
							 + " HRMS_CONF_HDR.CONF_FROM_TIME, HRMS_CONF_HDR.CONF_TO_TIME," 
							 + " HRMS_CONF_HDR.CONF_BOOKEDBY, HRMS_CONF_HDR.CONF_ROOMNO , HRMS_CONF_HDR.CONF_PURPOSE ," 
							 + " TO_CHAR(HRMS_CONF_HDR.CONF_APPLN_DATE,'DD-MM-YYYY')"
							 + " FROM HRMS_CONF_HDR"  
							 + " INNER JOIN HRMS_EMP_OFFC ON (HRMS_EMP_OFFC.EMP_ID = HRMS_CONF_HDR.CONF_BOOKEDBY)" 
							 + " INNER JOIN HRMS_CONF_VENUE ON (HRMS_CONF_VENUE.VENUE_CODE = HRMS_CONF_HDR.CONF_ROOMNO)" 
							 + " WHERE HRMS_CONF_HDR.CONF_CODE =?";
			
			case 17 : return "UPDATE HRMS_CONF_HDR SET CONF_STATUS='C' WHERE CONF_CODE=?";
			
			case 18 : return "UPDATE HRMS_CONF_PATH SET CONF_STATUS='R'"
							 + " WHERE CONF_CODE =? AND CONF_APPROVER = ?";
			default : return "";
		}
	}

}
