/**
 * 
 */
package org.paradyne.sql.common;

import org.paradyne.lib.SqlBase;

/**
 * @author debajanid
 *
 */
public class MenuManagementModelSql extends SqlBase {
	
	public String getQuery(int id){
		switch(id){
		case 1:return " INSERT INTO HRMS_MENU (MENU_CODE,MENU_NAME,MENU_LINK,MENU_PARENT_CODE,MENU_TARGET,MENU_TABORDER,MENU_ALT_MESSAGE,MENU_PLACEINMENU) " 
						+"VALUES((SELECT NVL(MAX(MENU_CODE),0)+1 FROM HRMS_MENU ),?,?,?,?,?,?,?)";
		
		case 2:return " UPDATE HRMS_MENU SET MENU_NAME=?,MENU_LINK=?,MENU_PARENT_CODE=?,MENU_TARGET=?,MENU_TABORDER=?,MENU_ALT_MESSAGE=?,MENU_PLACEINMENU=? WHERE MENU_CODE=?";
		
		case 3:return " DELETE FROM HRMS_MENU WHERE MENU_CODE=? ";
		
		case 4:return " SELECT HRMS_MENU.MENU_CODE, HRMS_MENU.MENU_NAME, HRMS_MENU.MENU_LINK, HRMS_MENU.MENU_PARENT_CODE, M1.MENU_NAME, " 
					+ "	HRMS_MENU.MENU_TARGET, HRMS_MENU.MENU_ALT_MESSAGE, HRMS_MENU.MENU_PLACEINMENU, HRMS_MENU.MENU_TABORDER "
					+ "	FROM HRMS_MENU "
					+ "	LEFT JOIN HRMS_MENU M1 ON(M1.MENU_CODE = HRMS_MENU.MENU_PARENT_CODE) "
					+ "	WHERE HRMS_MENU.MENU_CODE= ?";
		
		case 5:return " SELECT HRMS_MENU.MENU_CODE, HRMS_MENU.MENU_NAME, HRMS_MENU.MENU_LINK, HRMS_MENU.MENU_PARENT_CODE, M1.MENU_NAME, "
					+ " DECODE( SUBSTR(M4.MENU_NAME ||'->'|| M3.MENU_NAME ||'->'||"
					+ " M2.MENU_NAME||'->'|| M1.MENU_NAME,0,6),'->->->'"
					+ " , ''||'->'||NVL(M1.MENU_NAME,'MAIN MENU'),M4.MENU_NAME ||'->'|| M3.MENU_NAME ||'->'|| M2.MENU_NAME||'->'|| M1.MENU_NAME), "		
					+ "	HRMS_MENU.MENU_TARGET, HRMS_MENU.MENU_ALT_MESSAGE, HRMS_MENU.MENU_PLACEINMENU, HRMS_MENU.MENU_TABORDER "
					+ "	FROM HRMS_MENU "
					+ "	LEFT JOIN HRMS_MENU M1 ON(M1.MENU_CODE = HRMS_MENU.MENU_PARENT_CODE) "
					+ " LEFT JOIN HRMS_MENU  M2 ON (M2.MENU_CODE =M1.MENU_PARENT_CODE) "
					+ " LEFT JOIN HRMS_MENU  M3 ON (M3.MENU_CODE =M2.MENU_PARENT_CODE) "
					+ " LEFT JOIN HRMS_MENU  M4 ON (M4.MENU_CODE =M3.MENU_PARENT_CODE) "
					+ "	ORDER BY HRMS_MENU.MENU_TABORDER,HRMS_MENU.MENU_CODE ";
		
		
		
		default:return " FRAMEWORK COULD NOT THE QUERY NUMBER SPECIFIED";
		}
	}
	
	

}
