package org.paradyne.sql.common;

import org.paradyne.lib.SqlBase;

/**
 * @author reebaj 
 * @since 02/06/2008
 *
 */
public class ProfileAccessModelSql extends SqlBase {
	
	public String getQuery(int queryID){
			
			switch(queryID){
			
			case 1: return " SELECT HRMS_CENTER.CENTER_ID,HRMS_CENTER.CENTER_NAME FROM HRMS_CENTER " 
							 +" ORDER BY HRMS_CENTER.CENTER_ID  ";

			case 2: return " SELECT HRMS_DEPT.DEPT_ID,HRMS_DEPT.DEPT_NAME FROM HRMS_DEPT "
							 +" ORDER BY HRMS_DEPT.DEPT_ID ";

			case 3: return " SELECT HRMS_DIVISION.DIV_ID,HRMS_DIVISION.DIV_NAME FROM HRMS_DIVISION " 
							 +" ORDER BY HRMS_DIVISION.DIV_ID ";

			case 4: return " SELECT HRMS_EMP_TYPE.TYPE_ID,HRMS_EMP_TYPE.TYPE_NAME FROM HRMS_EMP_TYPE " 
			 				 +" ORDER BY HRMS_EMP_TYPE.TYPE_ID ";
			
			case 5: return " INSERT INTO HRMS_PROFILE_ACC_HDR (PROFILE_CODE,PROFILE_NAME,CREATION_DATE,PROFILE_DIV_FLAG,PROFILE_DEPT_FLAG,PROFILE_CNT_FLAG,PROFILE_EMPTYPE_FLAG) "
			 				 +" VALUES((SELECT NVL(MAX(PROFILE_CODE),0)+1 FROM HRMS_PROFILE_ACC_HDR ),?, SYSDATE,?,?,?,?)";
			
			case 6: return " INSERT INTO HRMS_PROFILE_CENTER(PROFILE_CODE,CENTER_CODE)"
							 +" VALUES ((SELECT MAX(PROFILE_CODE) FROM HRMS_PROFILE_ACC_HDR),?)";
			
			case 7: return " INSERT INTO HRMS_PROFILE_DEPT(PROFILE_CODE,DEPT_CODE) "
							 +" VALUES ((SELECT MAX(PROFILE_CODE) FROM HRMS_PROFILE_ACC_HDR),?)";
			
			case 8: return " INSERT INTO HRMS_PROFILE_DIVISION(PROFILE_CODE,DIV_CODE) "
			 				 +" VALUES (?,?)";
			
			case 9: return " INSERT INTO HRMS_PROFILE_EMPTYPE(PROFILE_CODE,PROFILE_EMPTYPE) "
							 +" VALUES ((SELECT MAX(PROFILE_CODE) FROM HRMS_PROFILE_ACC_HDR),?)";
			
			case 10: return " DELETE FROM HRMS_PROFILE_CENTER WHERE PROFILE_CODE =(SELECT MAX(PROFILE_CODE) FROM HRMS_PROFILE_ACC_HDR)";
			
			case 11: return " DELETE FROM HRMS_PROFILE_DEPT WHERE PROFILE_CODE =(SELECT MAX(PROFILE_CODE) FROM HRMS_PROFILE_ACC_HDR)";
			
			case 12: return " DELETE FROM HRMS_PROFILE_DIVISION WHERE PROFILE_CODE =(SELECT MAX(PROFILE_CODE) FROM HRMS_PROFILE_ACC_HDR)";
			
			case 13: return " DELETE FROM HRMS_PROFILE_EMPTYPE WHERE PROFILE_CODE =(SELECT MAX(PROFILE_CODE) HRMS_PROFILE_ACC_HDR)";
			
			case 14: return " DELETE FROM HRMS_PROFILE_HDR WHERE PROFILE_CODE =(SELECT MAX(PROFILE_CODE) HRMS_PROFILE_ACC_HDR)";
			
			case 15:return "SELECT PROFILE_CODE,CENTER_CODE FROM HRMS_PROFILE_CENTER "
							+" WHERE PROFILE_CODE =? ORDER BY CENTER_CODE";
			
			case 16:return "SELECT PROFILE_CODE,DEPT_CODE FROM HRMS_PROFILE_DEPT "
							+" WHERE PROFILE_CODE =? ORDER BY DEPT_CODE ";
			
			case 17:return "SELECT PROFILE_CODE,DIV_CODE FROM HRMS_PROFILE_DIVISION "
							+" WHERE PROFILE_CODE =? ORDER BY DIV_CODE ";
			
			case 18:return "SELECT PROFILE_CODE,PROFILE_EMPTYPE FROM HRMS_PROFILE_EMPTYPE "
							+" WHERE PROFILE_CODE =? ORDER BY PROFILE_EMPTYPE ";
			
			case 19: return " INSERT INTO HRMS_PROFILE_CENTER(PROFILE_CODE,CENTER_CODE)"
			 				+" VALUES (?,?)";

			case 20: return " INSERT INTO HRMS_PROFILE_DEPT(PROFILE_CODE,DEPT_CODE) "
						 	+" VALUES (?,?)";
			
			case 21: return " INSERT INTO HRMS_PROFILE_DIVISION(PROFILE_CODE,DIV_CODE) "
							+" VALUES (?,?)";
			
			case 22: return " INSERT INTO HRMS_PROFILE_EMPTYPE(PROFILE_CODE,PROFILE_EMPTYPE) "
						 	+" VALUES (?,?)";
			
			case 23: return " DELETE FROM HRMS_PROFILE_CENTER WHERE PROFILE_CODE = ?";
			
			case 24: return " DELETE FROM HRMS_PROFILE_DEPT WHERE PROFILE_CODE = ?";
			
			case 25: return " DELETE FROM HRMS_PROFILE_DIVISION WHERE PROFILE_CODE = ?";
			
			case 26: return " DELETE FROM HRMS_PROFILE_EMPTYPE WHERE PROFILE_CODE = ?";
			
			case 27: return " UPDATE HRMS_PROFILE_ACC_HDR SET PROFILE_NAME =?, UPDATION_DATE=SYSDATE , "
			 				+ " PROFILE_DIV_FLAG=?,PROFILE_DEPT_FLAG=?,PROFILE_CNT_FLAG=?,PROFILE_EMPTYPE_FLAG=? WHERE PROFILE_CODE = ?";
			
			case 28: return " INSERT INTO HRMS_PROFILE_DTL(PROFILE_CODE,MENU_CODE,PROFILE_INSERT_FLAG, "
							+" PROFILE_UPDATE_FLAG,PROFILE_DELETE_FLAG,PROFILE_VIEW_FLAG,PROFILE_GENERAL_FLAG) "
			 				+" VALUES ((SELECT MAX(PROFILE_CODE) FROM HRMS_PROFILE_HDR),?,?,?,?,?,?)";
			
			
			case 29: return " DELETE FROM HRMS_PROFILE_DTL WHERE PROFILE_CODE = ?";
			
			case 30: return " DELETE FROM HRMS_PROFILE_ACC_HDR WHERE PROFILE_CODE = ?";
			
			case 31: return " DELETE FROM HRMS_PROFILE_PAYBILL WHERE PROFILE_CODE = ?";
			
			
			default: return "QUERY NOT FOUND";
			}
		}
}
