/**
 * 
 */
package org.paradyne.sql.common;

import org.paradyne.lib.SqlBase;

/**
 * @author reebaj 
 * @since 06/05/2008
 *
 */
public class ProfileMode1Sql extends SqlBase {
	
	public String getQuery(int queryID){
			
			switch(queryID){
			
			case 1: return " SELECT HRMS_CENTER.CENTER_ID,HRMS_CENTER.CENTER_NAME FROM HRMS_CENTER " 
							 +" ORDER BY HRMS_CENTER.CENTER_ID  ";

			case 2: return " SELECT HRMS_EMP_TYPE.TYPE_ID,HRMS_EMP_TYPE.TYPE_NAME FROM HRMS_EMP_TYPE " 
							 +" ORDER BY HRMS_EMP_TYPE.TYPE_ID ";

			case 3: return " SELECT HRMS_PAYBILL.PAYBILL_ID,HRMS_PAYBILL.PAYBILL_GROUP FROM HRMS_PAYBILL " 
							 +" ORDER BY HRMS_PAYBILL.PAYBILL_ID ";

			case 4: return " INSERT INTO HRMS_PROFILE_HDR (PROFILE_CODE,PROFILE_NAME) "
							 +" VALUES((SELECT NVL(MAX(PROFILE_CODE),0)+1 FROM HRMS_PROFILE_HDR ),?)";
			
			case 5: return " INSERT INTO HRMS_PROFILE_CENTER(PROFILE_CODE,CENTER_CODE)"
							 +" VALUES ((SELECT MAX(PROFILE_CODE) FROM HRMS_PROFILE_HDR),?)";
			
			case 6: return " INSERT INTO HRMS_PROFILE_PAYBILL(PROFILE_CODE,PAYBILL_NO) "
							 +" VALUES ((SELECT MAX(PROFILE_CODE) FROM HRMS_PROFILE_HDR),?)";
			
			case 7: return " INSERT INTO HRMS_PROFILE_EMPTYPE(PROFILE_CODE,PROFILE_EMPTYPE) "
							 +" VALUES ((SELECT MAX(PROFILE_CODE) FROM HRMS_PROFILE_HDR),?)";
			
			case 8: return " DELETE FROM HRMS_PROFILE_CENTER WHERE PROFILE_CODE =(SELECT MAX(PROFILE_CODE) FROM HRMS_PROFILE_HDR)";
			
			case 9: return " DELETE FROM HRMS_PROFILE_PAYBILL WHERE PROFILE_CODE =(SELECT MAX(PROFILE_CODE) FROM HRMS_PROFILE_HDR)";
			
			case 10: return " DELETE FROM HRMS_PROFILE_EMPTYPE WHERE PROFILE_CODE =(SELECT MAX(PROFILE_CODE) FROM HRMS_PROFILE_HDR)";
			
			case 11: return " DELETE FROM HRMS_PROFILE_HDR WHERE PROFILE_CODE =(SELECT MAX(PROFILE_CODE) FROM HRMS_PROFILE_HDR)";
			
			case 12:return "SELECT PROFILE_CODE,CENTER_CODE FROM HRMS_PROFILE_CENTER "
							+" WHERE PROFILE_CODE =? ORDER BY CENTER_CODE";
			
			case 13:return "SELECT PROFILE_CODE,PAYBILL_NO FROM HRMS_PROFILE_PAYBILL "
							+" WHERE PROFILE_CODE =? ORDER BY PAYBILL_NO ";
			
			case 14:return "SELECT PROFILE_CODE,PROFILE_EMPTYPE FROM HRMS_PROFILE_EMPTYPE "
							+" WHERE PROFILE_CODE =? ORDER BY PROFILE_EMPTYPE ";
			
			case 15: return " INSERT INTO HRMS_PROFILE_CENTER(PROFILE_CODE,CENTER_CODE)"
			 				+" VALUES (?,?)";

			case 16: return " INSERT INTO HRMS_PROFILE_PAYBILL(PROFILE_CODE,PAYBILL_NO) "
						 	+" VALUES (?,?)";
			
			case 17: return " INSERT INTO HRMS_PROFILE_EMPTYPE(PROFILE_CODE,PROFILE_EMPTYPE) "
						 	+" VALUES (?,?)";
			
			case 18: return " DELETE FROM HRMS_PROFILE_CENTER WHERE PROFILE_CODE = ?";
			
			case 19: return " DELETE FROM HRMS_PROFILE_PAYBILL WHERE PROFILE_CODE = ?";
			
			case 20: return " DELETE FROM HRMS_PROFILE_EMPTYPE WHERE PROFILE_CODE = ?";
			
			case 21: return " UPDATE HRMS_PROFILE_HDR SET PROFILE_NAME =? WHERE PROFILE_CODE = ?";
			
			case 22: return " INSERT INTO HRMS_PROFILE_DTL(PROFILE_CODE,MENU_CODE,PROFILE_INSERT_FLAG, "
							+" PROFILE_UPDATE_FLAG,PROFILE_DELETE_FLAG,PROFILE_VIEW_FLAG,PROFILE_GENERAL_FLAG) "
			 				+" VALUES ((SELECT MAX(PROFILE_CODE) FROM HRMS_PROFILE_HDR),?,?,?,?,?,?)";
			
			
			case 23: return " DELETE FROM HRMS_PROFILE_DTL WHERE PROFILE_CODE = ?";
			
			default: return "QUERY NOT FOUND";
			}
		}
}
