package org.paradyne.sql.common;

import org.paradyne.lib.SqlBase;

public class ReportingStructureModelSql extends SqlBase {
	public String getQuery(int id) {
		switch (id) {
		case 1:
			return "SELECT HRMS_EMP_OFFC.EMP_ID, HRMS_EMP_OFFC.EMP_TOKEN, HRMS_EMP_OFFC.EMP_FNAME||' '||HRMS_EMP_OFFC.EMP_MNAME|| ' ' || HRMS_EMP_OFFC.EMP_LNAME NAME, "
					+ "REPORTINGDTL_ALTER_EMP_ID, ALTERNATE.EMP_TOKEN, ALTERNATE.EMP_FNAME||' '||ALTERNATE.EMP_MNAME|| ' ' || ALTERNATE.EMP_LNAME ALTERNATE_NAME "
					+ "FROM HRMS_REPORTING_STRUCTUREDTL "
					+ "INNER JOIN  HRMS_EMP_OFFC ON (HRMS_EMP_OFFC.EMP_ID = HRMS_REPORTING_STRUCTUREDTL.REPORTINGDTL_EMP_ID) "
					+ "LEFT JOIN  HRMS_EMP_OFFC ALTERNATE ON (ALTERNATE.EMP_ID = REPORTINGDTL_ALTER_EMP_ID) "
					+ "WHERE REPORTINGHDR_CODE = ? "
					+ "ORDER BY REPORTINGDTL_CODE";

		case 2:
			return "INSERT INTO HRMS_REPORTING_STRUCTUREHDR (REPORTINGHDR_CODE, REPORTINGHDR_DEPT_ID, "
					+ "REPORTINGHDR_BRN_ID, REPORTINGHDR_EMP_ID, REPORTINGHDR_DESG_ID, REPORTINGHDR_TYPE, REPORTINGHDR_SAME_AS, REPORTINGHDR_ISDEFAULT) "
					+ "VALUES ((SELECT NVL(MAX(REPORTINGHDR_CODE),0)+1 FROM HRMS_REPORTING_STRUCTUREHDR), ?, ?, ?, ?, ?, ?, ?) ";

			/*
			 * case 3 : return "SELECT REPORTINGHDR_CODE FROM
			 * HRMS_REPORTING_STRUCTUREHDR " +"WHERE REPORTINGHDR_DEPT_ID = ?
			 * AND REPORTINGHDR_TYPE = ? AND REPORTINGHDR_BRN_ID IS NULL " +"AND
			 * REPORTINGHDR_DESG_ID IS NULL";
			 */

		case 3:
			return "SELECT REPORTINGHDR_CODE FROM HRMS_REPORTING_STRUCTUREHDR "
					+ "WHERE REPORTINGHDR_DEPT_ID = ? AND REPORTINGHDR_BRN_ID = ? "
					+ "AND REPORTINGHDR_EMP_ID = ? AND REPORTINGHDR_DESG_ID = ? AND REPORTINGHDR_TYPE = ? ";

		case 4:
			return "SELECT REPORTINGHDR_CODE FROM HRMS_REPORTING_STRUCTUREHDR "
					+ "WHERE REPORTINGHDR_EMP_ID = ? AND REPORTINGHDR_TYPE = ?";

		case 5:
			return "SELECT NVL(MAX (REPORTINGHDR_CODE),0) FROM HRMS_REPORTING_STRUCTUREHDR";

		case 6:
			return "INSERT INTO HRMS_REPORTING_STRUCTUREDTL (REPORTINGDTL_CODE, REPORTINGHDR_CODE, REPORTINGDTL_EMP_ID, "
					+ "REPORTINGDTL_ALTER_EMP_ID) VALUES ((SELECT NVL(MAX(REPORTINGDTL_CODE),0)+1 "
					+ "FROM HRMS_REPORTING_STRUCTUREDTL WHERE REPORTINGHDR_CODE = ?), ?, ?, ?)";

			/*
			 * case 7 : return "DELETE FROM HRMS_REPORTING_STRUCTUREDTL "
			 * +"WHERE REPORTINGHDR_CODE = ? AND REPORTINGDTL_EMP_ID = ?";
			 */

		case 7:
			return "DELETE FROM HRMS_REPORTING_STRUCTUREDTL "
					+ "WHERE REPORTINGHDR_CODE = ? ";

		case 8:
			return "SELECT REPORTINGHDR_CODE, REPORTINGHDR_DEPT_ID, HRMS_DEPT.DEPT_NAME, REPORTINGHDR_BRN_ID, "
					+ "HRMS_CENTER.CENTER_NAME, REPORTINGHDR_DESG_ID, NVL(HRMS_RANK.RANK_NAME,' '), REPORTINGHDR_EMP_ID, "
					+ "(HRMS_EMP_OFFC.EMP_FNAME||' '||HRMS_EMP_OFFC.EMP_MNAME|| ' ' || HRMS_EMP_OFFC.EMP_LNAME)NAME, "
					+ "DECODE(REPORTINGHDR_TYPE, 'Leave','Leave','Requi','Requisition', 'Cash','Cash Voucher', 'Train', 'Training', "
					+ "'Tran', 'Transfer', 'Sugg', 'Suggestion', 'Help', 'Help Desk', 'LTC', 'LTC Advance', 'Festi', 'Festival Advance', "
					+ "'Other', 'Other Advance', 'Deput', 'Deputation', 'HBA', 'HBA', 'GPF', 'GPF', 'CTF', 'Children Tution Fee', "
					+ "'Medi', 'Medical Advance', 'TYD', 'Travel', 'Appra', 'Appraisal', 'Confere', 'Conference', 'Loan', 'Loan', "
					+ "'Asset', 'Asset', 'Purchase', 'Purchase', 'Cash Process', 'Cash Process', 'Recruitment', 'Recruitment')TYPE "
					+ "FROM HRMS_REPORTING_STRUCTUREHDR "
					+ "LEFT JOIN HRMS_DEPT ON (HRMS_DEPT.DEPT_ID = REPORTINGHDR_DEPT_ID) "
					+ "LEFT JOIN HRMS_CENTER ON (HRMS_CENTER.CENTER_ID = REPORTINGHDR_BRN_ID) "
					+ "INNER JOIN HRMS_EMP_OFFC ON (HRMS_EMP_OFFC.EMP_ID = REPORTINGHDR_EMP_ID) "
					+ "INNER JOIN HRMS_RANK ON(HRMS_RANK.RANK_ID=HRMS_EMP_OFFC.EMP_RANK) "
					+ "LEFT JOIN HRMS_TITLE ON (HRMS_EMP_OFFC.EMP_TITLE_CODE = HRMS_TITLE.TITLE_CODE) "
					+ "WHERE REPORTINGHDR_TYPE = ? "
					+ "ORDER BY REPORTINGHDR_CODE";

		case 9:
			return "SELECT REPORTINGHDR_CODE, REPORTINGHDR_EMP_ID, "
					+ "(HRMS_EMP_OFFC.EMP_FNAME||' '||HRMS_EMP_OFFC.EMP_MNAME|| ' ' || HRMS_EMP_OFFC.EMP_LNAME)NAME, "
					+ "DECODE(REPORTINGHDR_TYPE, 'L','Leave','R','Requisition', 'C','Cash Voucher', 'T', 'Training' ) "
					+ "FROM HRMS_REPORTING_STRUCTUREHDR "
					+ "INNER JOIN HRMS_EMP_OFFC ON (HRMS_EMP_OFFC.EMP_ID = REPORTINGHDR_EMP_ID) "
					+ "WHERE REPORTINGHDR_TYPE = ? AND REPORTINGHDR_EMP_ID IS NOT NULL";

		case 10:
			return "UPDATE HRMS_REPORTING_STRUCTUREDTL SET REPORTINGDTL_CODE = ? "
					+ "WHERE REPORTINGHDR_CODE = ? AND REPORTINGDTL_EMP_ID = ?";

		case 11:
			return "SELECT REPORTINGHDR_CODE FROM HRMS_REPORTING_STRUCTUREHDR "
					+ "WHERE REPORTINGHDR_BRN_ID = ? AND REPORTINGHDR_TYPE = ? AND REPORTINGHDR_DESG_ID IS NULL "
					+ "AND REPORTINGHDR_DEPT_ID IS NULL";

		case 12:
			return "SELECT REPORTINGHDR_CODE FROM HRMS_REPORTING_STRUCTUREHDR "
					+ "WHERE REPORTINGHDR_DESG_ID = ? AND REPORTINGHDR_TYPE = ? AND REPORTINGHDR_DEPT_ID IS NULL "
					+ "AND REPORTINGHDR_BRN_ID IS NULL";

		case 13:
			return "SELECT REPORTINGHDR_CODE FROM HRMS_REPORTING_STRUCTUREHDR "
					+ "WHERE REPORTINGHDR_DEPT_ID = ? AND REPORTINGHDR_BRN_ID = ? AND REPORTINGHDR_TYPE = ? "
					+ "AND REPORTINGHDR_DESG_ID IS NULL";

		case 14:
			return "SELECT REPORTINGHDR_CODE FROM HRMS_REPORTING_STRUCTUREHDR "
					+ "WHERE REPORTINGHDR_DEPT_ID = ? AND REPORTINGHDR_DESG_ID = ? AND REPORTINGHDR_TYPE = ? "
					+ "AND REPORTINGHDR_BRN_ID IS NULL";

		case 15:
			return "SELECT REPORTINGHDR_CODE FROM HRMS_REPORTING_STRUCTUREHDR "
					+ "WHERE REPORTINGHDR_BRN_ID = ? AND REPORTINGHDR_DESG_ID = ? AND REPORTINGHDR_TYPE = ? "
					+ "AND REPORTINGHDR_DEPT_ID IS NULL";

		case 16:
			return "SELECT REPORTINGHDR_CODE FROM HRMS_REPORTING_STRUCTUREHDR "
					+ "WHERE REPORTINGHDR_DEPT_ID = ? AND REPORTINGHDR_BRN_ID = ? AND REPORTINGHDR_DESG_ID = ? AND REPORTINGHDR_TYPE = ?";

		case 17:
			return " UPDATE HRMS_REPORTING_STRUCTUREHDR SET REPORTINGHDR_ISDEFAULT = ? , REPORTINGHDR_SAME_AS ='null' WHERE REPORTINGHDR_TYPE = ? ";

		case 18:
			return " SELECT REPORTINGHDR_ISDEFAULT,REPORTINGHDR_SAME_AS FROM HRMS_REPORTING_STRUCTUREHDR WHERE REPORTINGHDR_TYPE = ? ";

		case 19:
			return " UPDATE HRMS_REPORTING_STRUCTUREHDR SET REPORTINGHDR_SAME_AS = ? , REPORTINGHDR_ISDEFAULT = 'N' where REPORTINGHDR_TYPE = ? ";

		case 20:
			return " INSERT INTO HRMS_REPORTING_STRUCTUREHDR (REPORTINGHDR_CODE,REPORTINGHDR_SAME_AS,REPORTINGHDR_TYPE,REPORTINGHDR_ISDEFAULT )values((SELECT NVL(MAX(REPORTINGHDR_CODE),0)+1 FROM HRMS_REPORTING_STRUCTUREHDR),?,?,'N')";

		case 21:
			return " SELECT * FROM HRMS_REPORTING_STRUCTUREHDR WHERE REPORTINGHDR_TYPE = ? ";

		case 22:
			return " UPDATE HRMS_REPORTING_STRUCTUREHDR SET REPORTINGHDR_SAME_AS ='null' WHERE REPORTINGHDR_TYPE = ? ";

		case 23:
			return " UPDATE HRMS_REPORTING_STRUCTUREHDR SET REPORTINGHDR_ISDEFAULT = 'N', REPORTINGHDR_SAME_AS ='null' ";

		case 24:
			return "  INSERT INTO HRMS_REPORTING_STRUCTUREHDR (REPORTINGHDR_CODE,REPORTINGHDR_ISDEFAULT,REPORTINGHDR_TYPE,REPORTINGHDR_SAME_AS )values((SELECT NVL(MAX(REPORTINGHDR_CODE),0)+1 FROM HRMS_REPORTING_STRUCTUREHDR),?,?,'null' )";

		case 25:
			return " UPDATE HRMS_REPORTING_STRUCTUREHDR SET REPORTINGHDR_ISDEFAULT = 'N' ";

		case 26:
			return " SELECT DECODE(REPORTINGHDR_TYPE, 'Leave','Leave','Requi','Requisition', 'Cash','Cash Voucher', 'Train', 'Training', "
					+ " 'Tran', 'Transfer', 'Sugg', 'Suggestion', 'Help', 'Help Desk', 'LTC', 'LTC Advance', 'Festi', 'Festival Advance', "
					+ " 'Other', 'Other Advance', 'Deput', 'Deputation', 'HBA', 'HBA', 'GPF', 'GPF', 'CTF', 'Children Tution Fee', "
					+ " 'Medi', 'Medical Advance', 'TYD', 'Travel', 'Appra', 'Appraisal', 'Confere', 'Conference', 'Loan', 'Loan', "
					+ "'Asset', 'Asset', 'Purchase', 'Purchase', 'Cash Process', 'Cash Process', 'Recruitment', 'Recruitment', 'ExtraDayBenefit', 'ExtraDayBenefit', 'Outdoor', 'Outdoor Visit','Resign','Resignation')TYPE "
					+ " FROM HRMS_REPORTING_STRUCTUREHDR where HRMS_REPORTING_STRUCTUREHDR.REPORTINGHDR_ISDEFAULT ='Y' ";

		case 27:
			return "UPDATE HRMS_REPORTING_STRUCTUREHDR SET REPORTINGHDR_DEPT_ID = ?, REPORTINGHDR_BRN_ID = ?, "
					+ "REPORTINGHDR_EMP_ID = ?, REPORTINGHDR_DESG_ID = ?, REPORTINGHDR_SAME_AS = ?, REPORTINGHDR_ISDEFAULT = ? "
					+ "WHERE REPORTINGHDR_CODE = ?";

		case 28:
			return "DELETE FROM HRMS_REPORTING_STRUCTUREHDR WHERE REPORTINGHDR_CODE = ?";

		case 29:
			return "SELECT DISTINCT DECODE(REPORTINGHDR_TYPE, 'Leave', 'Leave', 'Requi', 'Requisition', "
					+ "'Cash', 'Cash Voucher', 'Train', 'Training', 'Tran', 'Transfer', 'Sugg', 'Suggestion', "
					+ "'Help', 'Help Desk', 'LTC', 'LTC Advance', 'Festi', 'Festival Advance', 'Other', 'Other Advance', "
					+ "'Deput', 'Deputation', 'HBA', 'HBA', 'GPF', 'GPF', 'CTF', 'Children Tution Fee', 'Medi', 'Medical Advance', "
					+ "'TYD', 'Travel', 'Appra', 'Appraisal', 'Confere', 'Conference', 'Loan', 'Loan', 'Asset', 'Asset', "
					+ "'Purchase', 'Purchase', 'Cash Process', 'Cash Process', 'Recruitment', 'Recruitment', 'ExtraDayBenefit', 'ExtraDayBenefit', 'Outdoor', 'Outdoor Visit','Resign','Resignation') TYPE, REPORTINGHDR_TYPE "
					+ "FROM HRMS_REPORTING_STRUCTUREHDR "
					+ "WHERE REPORTINGHDR_TYPE != ?";

		case 30:
			return "UPDATE HRMS_REPORTING_STRUCTUREHDR SET REPORTINGHDR_ISDEFAULT = 'N' "
					+ "REPORTINGHDR_SAME_AS = 'null' "
					+ "WHERE REPORTINGHDR_TYPE = ?";

		default:
			return "";
		}
	}

}
