package org.paradyne.sql.TravelManagement.TravelProcess;

import org.paradyne.lib.SqlBase;

/**
 * @author AA0563
 * 
 */
public class TmsTravelPolicyModelSql extends SqlBase {

	public String getQuery(int id) {
		switch (id) {
		case 1:
			return "  INSERT INTO TMS_TRAVEL_POLICY(POLICY_ID, POLICY_NAME,POLICY_ISADVANCE, MAX_DAYS_SETTLE_TRAVEL_CLAIM, POLICY_EFFECTIVE_DATE,"
					+ "  POLICY_STATUS,POLICY_CREATE_DATE, POLICY_PAY_MODE_CHEQUE, POLICY_PAY_MODE_CASH, POLICY_PAY_MODE_TRANSFER, POLICY_PAY_MODE_IN_SALARY,MIN_ADVANCE_DAYS_FOR_TRAVEL, TRAVEL_TYPE_SELF, TRAVEL_TYPE_TEAM, TRAVEL_TYPE_GUEST,POLICY_TRAVEL_CURRENCY ) "
					+ " VALUES ((SELECT NVL(MAX(POLICY_ID),0)+1 FROM TMS_TRAVEL_POLICY) ,?,?,?, TO_DATE(?,'DD-MM-YYYY'), "
					+ " ? , TO_DATE(SYSDATE,'DD-MM-YYYY'),?,?,?,?,?,?,?,?,?) ";

		case 2:
			return " SELECT NVL(EXP_CATEGORY_NAME,' '),  DECODE(EXP_CATEGORY_UNIT,'D','Per Day','T','Per Travel','K','Per Kilometer') , EXP_CATEGORY_ID ,EXP_CATEGORY_UNIT  FROM HRMS_TMS_EXP_CATEGORY "
					+ " WHERE EXP_CATEGORY_STATUS ='A' ORDER BY EXP_CATEGORY_ID,EXP_CATEGORY_NAME ";
		case 3:
			return " SELECT NVL(JOURNEY_NAME,' ') ,NVL(JOURNEY_CLASS_NAME,' ') ,JOURNEY_ID FROM HRMS_TMS_JOURNEY "
					+ " ORDER BY JOURNEY_LEVEL,JOURNEY_ID ";

		case 4:
			return " UPDATE TMS_TRAVEL_POLICY SET POLICY_NAME =?, POLICY_ISADVANCE=?, MAX_DAYS_SETTLE_TRAVEL_CLAIM=?, "
					+ " POLICY_EFFECTIVE_DATE =TO_DATE(?,'DD-MM-YYYY'), POLICY_STATUS =?, POLICY_CREATE_DATE = TO_DATE(SYSDATE,'DD-MM-YYYY'), "
					+" POLICY_PAY_MODE_CHEQUE=?, POLICY_PAY_MODE_CASH=?, POLICY_PAY_MODE_TRANSFER=?, POLICY_PAY_MODE_IN_SALARY=?, MIN_ADVANCE_DAYS_FOR_TRAVEL=?, TRAVEL_TYPE_SELF=?, TRAVEL_TYPE_TEAM=?, TRAVEL_TYPE_GUEST=?, POLICY_TRAVEL_CURRENCY=? "
					+ "  WHERE POLICY_ID =? ";
		case 5:
			return " SELECT DISTINCT CADRE_NAME ,CADRE_ID  FROM  HRMS_CADRE ORDER BY CADRE_ID,CADRE_NAME ";

		case 6:
			return "UPDATE  TMS_POLICY_EXPENSE_DTL SET POLICY_EXP_CAT_ID=?,POLICY_EXP_ENT_AMT,DIV_DESC=?,DIV_CITY_ID=?,DIV_ADDRESS1=?,DIV_ADDRESS2=?,DIV_ADDRESS3=?,"
					+ " DIV_PINCODE=?,DIV_TELEPHONE=?,DIV_WEBSITE=?,DIV_PTAX_REG=?,DIV_PANNO=?,DIV_TANNO=?,DIV_BANK=?,DIV_ACCOUNT_NUMBER=?"
					+ " WHERE DIV_ID=? ";

		default:
			return "Framework could not EXECUTE the query number specified";
		}

	}

}
