/**
 * 
 */
package org.paradyne.sql.TravelManagement.TravelProcess;

import org.paradyne.lib.SqlBase;

/**
 * @author AA0651
 *
 */
public class TmsTrvlDeskModelSql extends SqlBase {
	public String getQuery(int id) {

		switch (id) {

		case 1:
			return "INSERT INTO TMS_SCH_DTL(SCH_DESK_ID, SCHDTL_CODE, SCHDTL_TRAVEL_ASSIGN,"
			+ " SCHDTL_LOCAL_ASSIGN,SCHDTL_LODGE_ASSIGN, SCHDTL_SUBSCHLAR_ECODE)"
			+ " VALUES(?, ?, ?, ?, ? ,?)";
			
		case 2:
			return "UPDATE TMS_SCH_DESK SET DESK_TRAVEL_ASSIGN=?, DESK_LODGE_ASSIGN=?, DESK_LOCAL_ASSIGN=?,"
			+ " DESK_STATUS=?,DESK_SCH_ECODE=?,DESK_ASSGN_DATE=? WHERE DESK_ID=?";
			
		case 3:
			return "INSERT INTO TMS_MONITORING (TMS_MONITOR_ID,APPL_CODE,MTR_TVL_AVA_STATUS, MTR_ACC_AVSTATUS,"
			+ " MTR_LOCAL_AVSTATUS,APPL_ID) VALUES(?,?,?,?,?,?)";
			
		case 4:
			return "UPDATE TMS_MONITORING SET MTR_TVL_AVA_STATUS=?, MTR_ACC_AVSTATUS=?, MTR_LOCAL_AVSTATUS=? "
			+ " WHERE APPL_CODE= ? AND APPL_ID=?";
			
		case 5:
			return " INSERT INTO TMS_SCH_DESK (DESK_ID,DESK_APPL_ID,DESK_APPL_CODE,DESK_STATUS)  "
					+ "VALUES((SELECT NVL(MAX(DESK_ID),0)+1 FROM TMS_SCH_DESK ),?,?,?)";
			
		case 6:
			return "SELECT DESK_ID,DESK_APPL_ID,DESK_APPL_CODE,APPL_INITIATOR ,NVL(C2.EMP_FNAME,' ' )||' '||NVL(C2.EMP_MNAME,' ')||' '||NVL(C2.EMP_LNAME,' ') AS INITIATOR_NAME, HRMS_TITLE.TITLE_NAME||' '||NVL(C1.EMP_FNAME,' ')||'  '||NVL(C1.EMP_MNAME,' ')||'  '||NVL(C1.EMP_LNAME,' ') AS NAME,"
				+ " DESK_STATUS, TO_CHAR(TMS_APPLICATION.APPL_DATE,'DD-MM-YYYY') ,TO_CHAR(TMS_APP_TOUR_DTL.TOUR_TRAVEL_STARTDT,'DD-MM-YYYY'), DESK_TRAVEL_ASSIGN, DESK_LOCAL_ASSIGN,"
				+ " DESK_LODGE_ASSIGN,APPL_FOR_FLAG,NVL(APPL_TRVL_ID,' '), TMS_APP_EMPDTL.APPL_EMP_CODE,TMS_APP_TOUR_DTL.TOUR_TRAVEL_REQ_NAME,TMS_APP_EMPDTL.APPL_EMP_TRAVEL_APPLSTATUS "
				+ " FROM TMS_SCH_DESK "
				+ " LEFT JOIN   TMS_APPLICATION ON(TMS_SCH_DESK.DESK_APPL_ID=TMS_APPLICATION.APPL_ID)"
				+ " INNER JOIN   TMS_APP_EMPDTL ON(TMS_APPLICATION.APPL_ID=TMS_APP_EMPDTL.APPL_ID AND TMS_SCH_DESK.DESK_APPL_CODE=TMS_APP_EMPDTL.APPL_CODE) "
				+ " INNER JOIN HRMS_EMP_OFFC C1 ON(TMS_APP_EMPDTL.APPL_EMP_CODE=C1.EMP_ID) "
				+ " LEFT JOIN   HRMS_EMP_OFFC C2 ON(C2.EMP_ID=TMS_APPLICATION.APPL_INITIATOR) "
				+ " LEFT JOIN   HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=TMS_APP_EMPDTL.APPL_EMP_CODE) "
				+ " LEFT JOIN HRMS_TITLE  ON(HRMS_TITLE.TITLE_CODE=HRMS_EMP_OFFC.EMP_TITLE_CODE)  "
				+ " INNER JOIN   TMS_APP_TOUR_DTL ON(TMS_SCH_DESK.DESK_APPL_ID=TMS_APP_TOUR_DTL.APPL_ID) "
				+ " LEFT JOIN  HRMS_CENTER ON(HRMS_EMP_OFFC.EMP_CENTER=HRMS_CENTER.CENTER_ID)  "
				+ " INNER JOIN  TMS_SCH_DTL ON(TMS_SCH_DESK.DESK_ID=TMS_SCH_DTL.SCH_DESK_ID) "
				+ " WHERE DESK_STATUS=?"	
				+ " AND DESK_ID IN (SELECT DISTINCT SCH_DESK_ID FROM TMS_SCH_DTL "
				+ " WHERE SCHDTL_SUBSCHLAR_ECODE=?"				
				+ " AND (SCHDTL_TRAVEL_ASSIGN='Y' OR SCHDTL_LOCAL_ASSIGN='Y' OR SCHDTL_LODGE_ASSIGN='Y'))"
				+ " UNION"
				+ "  SELECT DISTINCT DESK_ID, DESK_APPL_ID , DESK_APPL_CODE, APPL_INITIATOR,NVL(EMP_FNAME ||' '||EMP_MNAME||' '||EMP_LNAME ,'') AS INITITOR_NAME ,"
				+ " NVL(GUEST_NAME,''), DESK_STATUS,TO_CHAR(TMS_APPLICATION.APPL_DATE,'DD-MM-YYYY') ,TO_CHAR(TMS_APP_TOUR_DTL.TOUR_TRAVEL_STARTDT,'DD-MM-YYYY'),"
				+ " DESK_TRAVEL_ASSIGN, DESK_LOCAL_ASSIGN, DESK_LODGE_ASSIGN,APPL_FOR_FLAG,NVL(APPL_TRVL_ID,' '),0, TMS_APP_TOUR_DTL.TOUR_TRAVEL_REQ_NAME,"
				+ " TMS_APP_GUEST_DTL.GUEST_TRAVEL_APPLSTATUS "
				+ " FROM TMS_SCH_DESK "
				+ " LEFT JOIN   TMS_APPLICATION ON(TMS_SCH_DESK.DESK_APPL_ID=TMS_APPLICATION.APPL_ID ) "
				+ " INNER JOIN   TMS_APP_GUEST_DTL ON(TMS_APP_GUEST_DTL.APPL_ID=TMS_APPLICATION.APPL_ID AND TMS_SCH_DESK.DESK_APPL_CODE=TMS_APP_GUEST_DTL.APPL_CODE)"
				+ " INNER JOIN   TMS_APP_TOUR_DTL ON(TMS_SCH_DESK.DESK_APPL_ID=TMS_APP_TOUR_DTL.APPL_ID)  "
				+ " INNER JOIN   HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=TMS_APPLICATION.APPL_INITIATOR)   "
				+ " LEFT JOIN  HRMS_CENTER ON(HRMS_EMP_OFFC.EMP_CENTER=HRMS_CENTER.CENTER_ID) "
				+ " INNER JOIN  TMS_SCH_DTL ON(TMS_SCH_DESK.DESK_ID=TMS_SCH_DTL.SCH_DESK_ID) "
				+ " WHERE DESK_STATUS=?"
				+ " AND DESK_ID IN (SELECT DISTINCT SCH_DESK_ID FROM TMS_SCH_DTL "
				+ " WHERE SCHDTL_SUBSCHLAR_ECODE=?"
				+ " AND (SCHDTL_TRAVEL_ASSIGN='Y' OR SCHDTL_LOCAL_ASSIGN='Y' OR SCHDTL_LODGE_ASSIGN='Y'))";
			
		case 7:
			return "INSERT INTO TMS_SUGG_TRAVELLING (TVLNG_GROUP_CODE,TVLNG_JOURN_CODE,TVLNG_DTL_CODE,"
				+ " TVLNG_SOURCE, TVLNG_DESTINATION, TVLNG_DATE, TVLNG_TIME, TVLNG_MODE, TVLNG_ID_NO, TVLNG_TCK_NO,"
				+ " TVLNG_COST, TVLNG_REJ_FLAG, TVLNG_SEL_FLAG, TVLNG_ORDER, TVLNG_DETAILS,MONITOR_ID) VALUES(1,?,?,?,?,TO_DATE(?,'DD-MM-YYYY'),?,?,?,?,?,'N','Y',1,?,?)";
			
		case 8:
			return "INSERT INTO TMS_SUGG_ACCOM (ACCOM_LODGE_CODE, ACCOM_CITY, ACCOM_FROMDATE, ACCOM_TODATE, ACCOM_CHECKIN,"
				+ " ACCOM_CHECKOUT, ACCOM_HOTELTYPE, ACCOM_ROOMTYPE, ACCOM_ADDRESS, ACCOM_BOOKING_AMT, ACCOM_SEL_FLAG,"
				+ " ACCOM_LODGEDTL_CODE, ACCOM_GROUP_CODE, ACCOM_ORDER, ACCOM_REJ_FLAG, ACCOM_DETAILS,MONITOR_ID) "
				+ " VALUES(?,?,TO_DATE(?,'DD-MM-YYYY'),TO_DATE(?,'DD-MM-YYYY'),?,?,?,?,?,?,'Y',?,1,1,'N',?,?)";
			
		case 9:
			return "INSERT INTO TMS_SUGG_LOC_CONV(LOCCONV_CONV_CODE, LOCCONV_SOURCE, LOCCONV_DATE," 
				+ " LOCCONV_TRAVELMODE, LOCCONV_TARIFFCOST, LOCCONV_SEL_FLAG, " 
				+ " LOCCONV_GROUP_CODE, LOCCONV_DTL_CODE, LOCCONV_ORDER, LOCCONV_FROM_TIME, LOCCONV_TO_TIME, " 
				+ " LOCCONV_REJ_FLAG, LOCCONV_DETAILS,MONITOR_ID) VALUES(?,?,TO_DATE(?,'DD-MM-YYYY'),?,?,'Y',1,?,1,?,?,'N',?,?)";
		case 10:
			return "INSERT INTO TMS_MONITORING (TMS_MONITOR_ID, APPL_CODE, MTR_TVL_AVA_STATUS,"
					+ " MTR_ACC_AVSTATUS, MTR_LOCAL_AVSTATUS,APPL_ID,MTR_TVL_BOOKING_DATE, MTR_ACC_BOOKING_DATE,"
					+ " MTR_LOC_BOOKING_DATE) VALUES(?,?,?,?,?,?,SYSDATE,SYSDATE,SYSDATE)";
			
		case 11 : return " INSERT INTO TMS_COMMENTS_TRAIL(COMMENTS_ID, COMMENTS_APP_ID, COMMENTS_APP_CODE, COMMENTS_APP_STATE,"
					+ " COMMENTS_EMPID, COMMENTS_DESC, COMMENTS_DATE, COMMENTS_LEVEL)VALUES((SELECT NVL(MAX(COMMENTS_ID),0)+1 "
					+ " FROM TMS_COMMENTS_TRAIL),?,?,?,?,?,SYSDATE,?)";
		
		
		case 12 : return "UPDATE TMS_APP_JOURNEY_DTL SET JOURNEY_UPLOAD_FILE=? WHERE JOURNEY_CODE=?";
		
		case 13 : return "UPDATE TMS_APP_LODGE_DTL SET LODGE_UPLOAD_FILE=? WHERE LODGE_CODE=?";
		
		case 14 : return "UPDATE TMS_APP_CONV_DTL SET CONV_UPLOAD_FILE=? WHERE CONV_CODE=?";
			
		

		default:
			return " Framework could not find query number specified";

		}

	}

}
