package org.paradyne.sql.TravelManagement.TravelProcess;

import org.paradyne.lib.SqlBase;
public class TravelApplicationModelSql extends SqlBase {

	public String getQuery(int id) {
		// TODO Auto-generated method stub
		switch (id) {

		//N-new, P-pending, A-approved, R-rejected
		//	case 1: return "INSERT INTO TMS_APPLICATION(APPL_ID, APPL_FOR_FLAG, APPL_DATE, APPL_STATUS, APPL_INITIATOR, APPL_ACCOMPAINED) VALUES((SELECT NVL(MAX(APPL_ID),0)+1 FROM TMS_APPLICATION),?,TO_DATE(?,'DD-MM-YYYY'),'N',?,?)  "; 
		case 1:
			return "INSERT INTO TMS_APPLICATION(APPL_ID, APPL_FOR_FLAG, APPL_DATE, APPL_STATUS, APPL_INITIATOR, APPL_ACCOMPAINED,APPL_KEEP_INFO) VALUES(?,?,TO_DATE(?,'DD-MM-YYYY'),'N',?,?,?)  ";
		case 2:
			return " SELECT REPORTINGHDR_EMP_ID,REPORTINGDTL_EMP_ID AS APPROVER,REPORTINGDTL_ALTER_EMP_ID AS ALT_APPROVER FROM HRMS_REPORTING_STRUCTUREHDR"
					+ " INNER JOIN HRMS_REPORTING_STRUCTUREDTL ON(HRMS_REPORTING_STRUCTUREDTL.REPORTINGHDR_CODE = HRMS_REPORTING_STRUCTUREHDR.REPORTINGHDR_CODE)"
					+ " WHERE HRMS_REPORTING_STRUCTUREHDR.REPORTINGHDR_TYPE='TYD'"
					+ " AND REPORTINGHDR_EMP_ID= ? ORDER BY REPORTINGDTL_CODE";

		case 3:
			return " SELECT REPORTINGHDR_DEPT_ID,REPORTINGDTL_EMP_ID AS APPROVER,REPORTINGDTL_ALTER_EMP_ID AS ALT_APPROVER FROM HRMS_REPORTING_STRUCTUREHDR"
					+ " INNER JOIN HRMS_REPORTING_STRUCTUREDTL ON(HRMS_REPORTING_STRUCTUREDTL.REPORTINGHDR_CODE = HRMS_REPORTING_STRUCTUREHDR.REPORTINGHDR_CODE)"
					+ " WHERE HRMS_REPORTING_STRUCTUREHDR.REPORTINGHDR_TYPE='TYD'"
					+ " AND HRMS_REPORTING_STRUCTUREHDR.REPORTINGHDR_DEPT_ID=? ORDER BY REPORTINGDTL_CODE";

		case 4:
			return "SELECT REPORTINGHDR_BRN_ID,REPORTINGDTL_EMP_ID AS APPROVER,REPORTINGDTL_ALTER_EMP_ID AS ALT_APPROVER FROM HRMS_REPORTING_STRUCTUREHDR"
					+ " INNER JOIN HRMS_REPORTING_STRUCTUREDTL ON(HRMS_REPORTING_STRUCTUREDTL.REPORTINGHDR_CODE = HRMS_REPORTING_STRUCTUREHDR.REPORTINGHDR_CODE)"
					+ " WHERE HRMS_REPORTING_STRUCTUREHDR.REPORTINGHDR_TYPE='TYD'"
					+ " AND HRMS_REPORTING_STRUCTUREHDR.REPORTINGHDR_BRN_ID=? ORDER BY REPORTINGDTL_CODE";

		case 5:
			return " SELECT REPORTINGHDR_DESG_ID,REPORTINGDTL_EMP_ID AS APPROVER,REPORTINGDTL_ALTER_EMP_ID AS ALT_APPROVER FROM HRMS_REPORTING_STRUCTUREHDR"
					+ " INNER JOIN HRMS_REPORTING_STRUCTUREDTL ON(HRMS_REPORTING_STRUCTUREDTL.REPORTINGHDR_CODE = HRMS_REPORTING_STRUCTUREHDR.REPORTINGHDR_CODE)"
					+ " WHERE HRMS_REPORTING_STRUCTUREHDR.REPORTINGHDR_TYPE='TYD'"
					+ " AND HRMS_REPORTING_STRUCTUREHDR.REPORTINGHDR_DESG_ID=? ORDER BY REPORTINGDTL_CODE";

		case 6:
			return " SELECT NVL(MAX(APPL_ID),0) FROM TMS_APPLICATION ";

		case 7:
			return " INSERT INTO TMS_APP_EMPDTL(APPL_ID, APPL_CODE, APPL_EMP_CODE, APPL_EMP_CONTACT, APPL_EMP_TRAVEL_APPLSTATUS, APPL_EMP_MAIN_APPROVER, APPL_EMP_ALT_APPROVER, "
					+ " APPL_EMP_ADVANCE_AMT, APPL_EMP_PAY_MODE, APPL_EMP_EXP_SETT_DATE, APPL_EMP_ID_PROOF, APPL_EMP_ID_NUMBER, APPL_EMP_ID_COMMENTS,APPL_EMP_AGE,APPL_TRVL_ID) "
					+ " VALUES(?,(SELECT NVL(MAX(APPL_CODE),0)+1 FROM TMS_APP_EMPDTL),?,?,'N',?,?,?,?,TO_DATE(?,'DD-MM-YYYY'),?,?,?,?,NVL('TRVL_'||?||'_'||(SELECT NVL(MAX(APPL_CODE),0)+1 FROM TMS_APP_EMPDTL),' '))";

		case 8:
			return "INSERT INTO TMS_APP_GUEST_DTL(APPL_ID, APPL_CODE, GUEST_NAME, GUEST_AGE, GUEST_CONTACT, GUEST_TRAVEL_APPLSTATUS, GUEST_ADVANCE_AMT, GUEST_PAY_MODE, GUEST_EXPECTED_SET_DATE, GUEST_ID_PROOF, GUEST_ID_NUMBER, GUEST_ID_COMMENTS,APPL_EMP_MAIN_APPROVER, APPL_EMP_ALT_APPROVER,APPL_TRVL_ID)"
					+ " VALUES(?,(SELECT NVL(MAX(APPL_CODE),0)+1 FROM TMS_APP_GUEST_DTL)"
					+ " ,?,?,?,'N',0,?,TO_DATE(?,'DD-MM-YYYY'),?,?,?,?,?,NVL('TRVL_'||?||'_'||(SELECT NVL(MAX(APPL_CODE),0)+1 FROM TMS_APP_GUEST_DTL),' '))";

		case 9:
			return "SELECT EMP_DEPT,EMP_CENTER, EMP_RANK FROM HRMS_EMP_OFFC WHERE EMP_ID=?";

		case 10:
			return " SELECT  JOURNEY_CODE ,JOURNEY_FROM, JOURNEY_TO, HRMS_TMS_JOURNEY_CLASS.CLASS_ID, JOURNEY_NAME||'-'||CLASS_NAME, TO_CHAR(JOURNEY_DATE,'DD-MM-YYYY'), JOURNEY_TIME,CLASS_LEVEL,JOURNEY_LEVEL,TMS_APP_JOURNEY_DTL.JOURNEY_STATUS"//JOURNEY_LEVEL
					+ " FROM TMS_APP_JOURNEY_DTL"
					+ " INNER JOIN HRMS_TMS_JOURNEY_CLASS ON(HRMS_TMS_JOURNEY_CLASS.CLASS_ID=TMS_APP_JOURNEY_DTL.JOURNEY_MODECLASS)"
					+ " INNER JOIN HRMS_TMS_JOURNEY_MODE ON(HRMS_TMS_JOURNEY_MODE.JOURNEY_ID=HRMS_TMS_JOURNEY_CLASS.CLASS_JOURNEY_ID)"
					+ " WHERE APPL_ID=? ";//ORDER BY JOURNEY_DATE";

		case 11:
			return " SELECT LODGE_CODE, LODGE_HOTELTYPE,HOTEL_TYPE_NAME, LODGE_ROOMTYPE,ROOM_TYPE_NAME,'',NVL(LODGE_CITY,' '), LODGE_PRE_LOCATION, TO_CHAR(LODGE_FROMDATE,'DD-MM-YYYY'), TO_CHAR(LODGE_TODATE,'DD-MM-YYYY'), LODGE_FROMTIME, LODGE_TOTIME,ROOM_LEVEL,HOTEL_LEVEL,TMS_APP_LODGE_DTL.LODGE_STATUS FROM TMS_APP_LODGE_DTL"//HOTEL_LEVEL ,  CITY_NAME
					+ " INNER JOIN HRMS_TMS_HOTEL_TYPE ON(HRMS_TMS_HOTEL_TYPE.HOTEL_TYPE_ID=TMS_APP_LODGE_DTL.LODGE_HOTELTYPE)"
					+ " INNER JOIN HRMS_TMS_ROOM_TYPE ON(HRMS_TMS_ROOM_TYPE.ROOM_TYPE_ID=TMS_APP_LODGE_DTL.LODGE_ROOMTYPE)"
					//+" INNER JOIN HRMS_TMS_CITY ON(HRMS_TMS_CITY.CITY_ID=TMS_APP_LODGE_DTL.LODGE_CITY)"
					+ " WHERE APPL_ID=? ";//ORDER BY LODGE_FROMDATE, LODGE_TODATE

		case 12:
			return " SELECT CONV_CODE, CONV_CITY, CONV_TRAVELDTL, CONV_MEDIUM, TO_CHAR(CONV_FROMDATE,'DD-MM-YYYY'), TO_CHAR(CONV_TODATE,'DD-MM-YYYY'), CONV_FROMTIME, CONV_TOTIME,TMS_APP_CONV_DTL.CONV_STATUS FROM TMS_APP_CONV_DTL  "
					+ " WHERE APPL_ID=? ";//ORDER BY CONV_FROMDATE, CONV_TODATE

		case 13:
			return " SELECT APPL_FOR_FLAG, APPL_ACCOMPAINED,TO_CHAR(APPL_DATE,'DD-MM-YYYY'), APPL_STATUS, APPL_INITIATOR,EMP_FNAME||' '||EMP_MNAME||' '||EMP_LNAME,EMP_TOKEN,EMP_CADRE,APPL_APPLCANT_COMMENTS FROM TMS_APPLICATION"
					+ " LEFT JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID = TMS_APPLICATION.APPL_INITIATOR)"
					+ " LEFT JOIN HRMS_CADRE ON(HRMS_CADRE.CADRE_ID=HRMS_EMP_OFFC.EMP_CADRE)"
					+ " WHERE APPL_ID=? ";

		case 14:
			return " SELECT APPL_ID, APPL_CODE,EMP_TOKEN, EMP_FNAME||' '||EMP_MNAME||' '||EMP_LNAME AS APPLICANT,CENTER_NAME AS BRANCH,DEPT_NAME,RANK_NAME,CADRE_NAME,"
					+ " APPL_EMP_AGE AS AGE ,APPL_EMP_CONTACT,HRMS_EMP_OFFC.EMP_ID,EMP_CENTER,EMP_DEPT,EMP_RANK FROM TMS_APP_EMPDTL"
					+ " INNER JOIN HRMS_EMP_OFFC ON(TMS_APP_EMPDTL.APPL_EMP_CODE = HRMS_EMP_OFFC.EMP_ID)"
					+ " LEFT JOIN HRMS_CENTER ON(HRMS_CENTER.CENTER_ID=HRMS_EMP_OFFC.EMP_CENTER)"
					+ " LEFT JOIN HRMS_DEPT ON(HRMS_DEPT.DEPT_ID=HRMS_EMP_OFFC.EMP_DEPT)"
					+ " LEFT JOIN HRMS_RANK ON(HRMS_RANK.RANK_ID=HRMS_EMP_OFFC.EMP_RANK)"
					+ " LEFT JOIN HRMS_CADRE ON(HRMS_CADRE.CADRE_ID=HRMS_EMP_OFFC.EMP_CADRE)"
					+ " LEFT JOIN HRMS_EMP_ADDRESS ON(HRMS_EMP_ADDRESS.EMP_ID=HRMS_EMP_OFFC.EMP_ID AND ADD_TYPE='L')"
					+ " WHERE APPL_ID=? ";

		case 15:
			return " SELECT APPL_ID, APPL_CODE, GUEST_NAME AS APPLICANT, GUEST_AGE, GUEST_CONTACT FROM TMS_APP_GUEST_DTL WHERE APPL_ID=? ";

		case 16:
			return " UPDATE TMS_APP_EMPDTL SET APPL_EMP_CONTACT=?,APPL_EMP_AGE=? WHERE APPL_ID=? AND APPL_CODE=?  ";

		case 17:
			return " UPDATE TMS_APP_GUEST_DTL SET GUEST_NAME=?, GUEST_AGE=?, GUEST_CONTACT=? WHERE APPL_ID=? AND APPL_CODE=?";

		case 18:
			return " DELETE FROM TMS_APP_EMPDTL WHERE APPL_ID=? AND APPL_CODE=?";

		case 19:
			return " DELETE FROM TMS_APP_GUEST_DTL WHERE APPL_ID=? AND APPL_CODE=?";

		case 20:
			return " INSERT INTO TMS_APP_TOUR_DTL(APPL_ID,TOUR_ID, TOUR_TRAVEL_STARTDT, TOUR_TRAVEL_ENDDT, TOUR_TRAVEL_REQ_NAME, TOUR_TRAVEL_PURPOSE, "
					+ " TOUR_FOOD_TYPE,TOUR_TRAVEL_TYPE, TOUR_TRAVEL_ARR_DONE, TOUR_ACCOM_ARR_DONE, TOUR_CONV_ARR_DONE,APPL_CODE, TOUR_CUSTOMER, TOUR_PROJECT)"
					+ " VALUES(?,(SELECT NVL(MAX(TOUR_ID),0)+1 FROM TMS_APP_TOUR_DTL),TO_DATE(?,'DD-MM-YYYY'),TO_DATE(?,'DD-MM-YYYY'),?,?,?,?,?,?,?,?,?,?)";

		case 21:
			return " INSERT INTO TMS_APP_JOURNEY_DTL(APPL_ID,JOURNEY_CODE, JOURNEY_FROM, JOURNEY_TO, JOURNEY_MODECLASS, JOURNEY_DATE, JOURNEY_TIME,APPL_CODE) "
					+ " VALUES(?,(SELECT NVL(MAX(JOURNEY_CODE),0)+1 FROM TMS_APP_JOURNEY_DTL),?,?,?,TO_DATE(?,'DD-MM-YYYY'),?,?) ";
			//
		case 22:
			return " INSERT INTO TMS_APP_LODGE_DTL(APPL_ID, LODGE_CODE, LODGE_HOTELTYPE, LODGE_ROOMTYPE, LODGE_CITY, LODGE_PRE_LOCATION, LODGE_FROMDATE, LODGE_TODATE, LODGE_FROMTIME, LODGE_TOTIME,APPL_CODE)"
					+ " VALUES(?,(SELECT NVL(MAX(LODGE_CODE),0)+1 FROM TMS_APP_LODGE_DTL), ?,?,?,?,TO_DATE(?,'DD-MM-YYYY'),TO_DATE(?,'DD-MM-YYYY'),?,?,?)";
			//Conveyance details
		case 23:
			return " INSERT INTO TMS_APP_CONV_DTL(APPL_ID, CONV_CODE, CONV_CITY, CONV_TRAVELDTL, CONV_MEDIUM,CONV_FROMDATE, CONV_TODATE, CONV_FROMTIME, CONV_TOTIME,APPL_CODE)"
					+ " VALUES(?,(SELECT NVL(MAX(CONV_CODE),0)+1 FROM TMS_APP_CONV_DTL),?,?,?,TO_DATE(?,'DD-MM-YYYY'),TO_DATE(?,'DD-MM-YYYY'),?,?,?)";
			//Tour details
		case 24:
			return " SELECT APPL_ID,TOUR_ID, TO_CHAR(TOUR_TRAVEL_STARTDT,'DD-MM-YYYY'), TO_CHAR(TOUR_TRAVEL_ENDDT,'DD-MM-YYYY'), TOUR_TRAVEL_REQ_NAME, TOUR_TRAVEL_PURPOSE,PURPOSE_NAME, NVL(TOUR_FOOD_TYPE,' '),TOUR_TRAVEL_TYPE,LOCATION_TYPE_NAME,"
					+ " LOCATION_TYPE_NAME,TOUR_TRAVEL_ARR_DONE, TOUR_ACCOM_ARR_DONE, TOUR_CONV_ARR_DONE FROM TMS_APP_TOUR_DTL "
					+ " INNER JOIN HRMS_TMS_PURPOSE ON(HRMS_TMS_PURPOSE.PURPOSE_ID = TMS_APP_TOUR_DTL.TOUR_TRAVEL_PURPOSE)"
					+ " INNER JOIN HRMS_TMS_LOCATION_TYPE ON(HRMS_TMS_LOCATION_TYPE.LOCATION_TYPE_ID = TMS_APP_TOUR_DTL.TOUR_TRAVEL_TYPE)"
					+ " WHERE APPL_ID=? ";

		case 25:
			return " SELECT FOOD_TYPE_ID, FOOD_TYPE_NAME FROM HRMS_TMS_FOOD_TYPE WHERE FOOD_TYPE_ID=?";

		case 26:
			return " UPDATE TMS_APPLICATION SET APPL_FOR_FLAG=?, APPL_DATE=TO_DATE(?,'DD-MM-YYYY'), APPL_INITIATOR=?, APPL_ACCOMPAINED=?,APPL_KEEP_INFO=? WHERE APPL_ID=?";

		case 27:
			return " UPDATE TMS_APP_TOUR_DTL SET TOUR_TRAVEL_STARTDT=TO_DATE(?,'DD-MM-YYYY'), TOUR_TRAVEL_ENDDT=TO_DATE(?,'DD-MM-YYYY'), TOUR_TRAVEL_REQ_NAME=?,"
					+ " TOUR_TRAVEL_PURPOSE=?, TOUR_FOOD_TYPE=?, TOUR_TRAVEL_TYPE=?, TOUR_TRAVEL_ARR_DONE=?, TOUR_ACCOM_ARR_DONE=?,"
					+ " TOUR_CONV_ARR_DONE=? WHERE APPL_ID=? AND TOUR_ID=? ";

		case 28:
			return " DELETE FROM TMS_APP_JOURNEY_DTL WHERE APPL_ID=? AND JOURNEY_CODE=? ";

		case 29:
			return " DELETE FROM TMS_APP_LODGE_DTL WHERE APPL_ID=? AND LODGE_CODE=?";

		case 30:
			return " DELETE FROM TMS_APP_CONV_DTL WHERE APPL_ID=? AND  CONV_CODE=?";

		case 31:
			return " UPDATE TMS_APP_JOURNEY_DTL SET JOURNEY_FROM=?, JOURNEY_TO=?, JOURNEY_MODECLASS=?, JOURNEY_DATE=TO_DATE(?,'DD-MM-YYYY'), JOURNEY_TIME=? WHERE APPL_ID=? AND JOURNEY_CODE=? ";

		case 32:
			return " UPDATE TMS_APP_LODGE_DTL SET LODGE_TOTIME=?, LODGE_TODATE=TO_DATE(?,'DD-MM-YYYY'), LODGE_ROOMTYPE=?, LODGE_PRE_LOCATION=?,LODGE_HOTELTYPE=?, LODGE_FROMTIME=?, "
					+ " LODGE_FROMDATE=TO_DATE(?,'DD-MM-YYYY'), LODGE_CITY=? WHERE APPL_ID=? AND LODGE_CODE=?";

		case 33:
			return " UPDATE TMS_APP_CONV_DTL SET CONV_TRAVELDTL=?, CONV_TOTIME=?, CONV_TODATE=TO_DATE(?,'DD-MM-YYYY'), CONV_MEDIUM=?, CONV_FROMTIME=?, CONV_FROMDATE=TO_DATE(?,'DD-MM-YYYY'), CONV_CITY=? WHERE  APPL_ID=? AND CONV_CODE=?";

		case 34:
			return " SELECT APPL_CODE,APPL_EMP_CODE,EMP_FNAME||' '||EMP_MNAME||' '||EMP_LNAME AS APPLICANT,APPL_EMP_ADVANCE_AMT,APPL_EMP_PAY_MODE,NVL(TO_CHAR(APPL_EMP_EXP_SETT_DATE,'DD-MM-YYYY'),''), APPL_EMP_ID_PROOF, NVL(APPL_EMP_ID_NUMBER,' '), NVL(APPL_EMP_ID_COMMENTS,' '),EMP_CADRE,EMP_DEPT,EMP_CENTER,EMP_DESG,NVL(APPL_TRVL_ID,' '),CURRENCY_ABBR,APPL_CURRENCY_ID"
					+ " FROM TMS_APP_EMPDTL"
					+ " INNER JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID = TMS_APP_EMPDTL.APPL_EMP_CODE)"
					+ " LEFT JOIN HRMS_CURRENCY ON(HRMS_CURRENCY.CURRENCY_ID = TMS_APP_EMPDTL.APPL_CURRENCY_ID)"
					+ " WHERE APPL_ID=?";
			//+" ORDER BY APPL_ID";

		case 35:
			return " SELECT APPL_CODE,GUEST_NAME AS APPLICANT,GUEST_ADVANCE_AMT,GUEST_PAY_MODE,NVL(TO_CHAR(GUEST_EXPECTED_SET_DATE,'DD-MM-YYYY'),''),"
					+ " GUEST_ID_PROOF, NVL(GUEST_ID_NUMBER,' '), NVL(GUEST_ID_COMMENTS,' '),CURRENCY_ABBR,APPL_CURRENCY_ID FROM TMS_APP_GUEST_DTL"
					+ " LEFT JOIN HRMS_CURRENCY ON(HRMS_CURRENCY.CURRENCY_ID = TMS_APP_GUEST_DTL.APPL_CURRENCY_ID)"
					+ " WHERE APPL_ID=?";

		case 36:
			return " UPDATE TMS_APP_EMPDTL SET APPL_EMP_PAY_MODE=?, APPL_EMP_ID_PROOF=?, APPL_EMP_ID_NUMBER=?, APPL_EMP_ID_COMMENTS=?, APPL_EMP_EXP_SETT_DATE=TO_DATE(?,'DD-MM-YYYY'), APPL_EMP_ADVANCE_AMT=?,APPL_CURRENCY_ID=? WHERE APPL_ID=? AND  APPL_CODE=? ";

		case 37:
			return "  UPDATE TMS_APP_GUEST_DTL SET GUEST_PAY_MODE=?, GUEST_ID_PROOF=?, GUEST_ID_NUMBER=?, GUEST_ID_COMMENTS=?, GUEST_EXPECTED_SET_DATE=TO_DATE(?,'DD-MM-YYYY'),GUEST_ADVANCE_AMT=?,APPL_CURRENCY_ID=? WHERE APPL_ID=? AND  APPL_CODE=?  ";

			//CHANGE STATUS
		case 38:
			return " UPDATE TMS_APP_EMPDTL SET APPL_EMP_TRAVEL_APPLSTATUS=? WHERE APPL_ID=? AND APPL_CODE=?";
			//CHANGE STATUS
		case 39:
			return " UPDATE TMS_APP_GUEST_DTL SET GUEST_TRAVEL_APPLSTATUS=? WHERE APPL_ID=? AND  APPL_CODE=?";
			//Find approver in applicant table
		case 40:
			return " SELECT APPL_EMP_MAIN_APPROVER FROM TMS_APP_EMPDTL WHERE APPL_ID=? AND  APPL_CODE=?";
			//Find approver in guest table
		case 41:
			return " SELECT APPL_EMP_MAIN_APPROVER FROM TMS_APP_GUEST_DTL WHERE APPL_ID=? AND  APPL_CODE=?";
			//Add data in approval table
		case 42:
			return " INSERT INTO TMS_APP_APPROVAL_DTL(APPL_ID,APPL_CODE,APPR_APPROVER_ID,APPR_LEVEL) VALUES(?,(SELECT NVL(MAX(APPL_CODE),0)+1 FROM TMS_APP_APPROVAL_DTL),?,?)";
			//All applications employee+guest new/pending/returned/approved/rejected 
		case 43:
			return " SELECT TMS_APPLICATION.APPL_ID, APPL_CODE,APPL_FOR_FLAG,EMP_FNAME||' '||EMP_MNAME||' '||EMP_LNAME AS APPLICANT,TOUR_TRAVEL_REQ_NAME,"
					+ " TO_CHAR(TOUR_TRAVEL_STARTDT,'DD-MM-YYYY'),NVL(INITIATOR.EMP_FNAME||' '||INITIATOR.EMP_MNAME||' '||INITIATOR.EMP_LNAME,' ') AS INITIATOR,APPL_INITIATOR,APPL_EMP_CODE FROM TMS_APP_EMPDTL"
					+ " INNER JOIN TMS_APPLICATION ON(TMS_APPLICATION.APPL_ID = TMS_APP_EMPDTL.APPL_ID)"
					+ " LEFT JOIN TMS_APP_TOUR_DTL ON(TMS_APP_TOUR_DTL.APPL_ID = TMS_APP_EMPDTL.APPL_ID)"
					+ " LEFT  JOIN HRMS_EMP_OFFC  INITIATOR ON(TMS_APPLICATION.APPL_INITIATOR = INITIATOR.EMP_ID )"
					+ " INNER JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID = TMS_APP_EMPDTL.APPL_EMP_CODE)"
					+ " WHERE APPL_EMP_TRAVEL_APPLSTATUS=?"
					+ " UNION "
					+ " SELECT TMS_APPLICATION.APPL_ID, APPL_CODE,APPL_FOR_FLAG,GUEST_NAME AS APPLICANT,TOUR_TRAVEL_REQ_NAME,TO_CHAR(TOUR_TRAVEL_STARTDT,'DD-MM-YYYY'),"
					+ " INITIATOR.EMP_FNAME||' '||INITIATOR.EMP_MNAME||' '||INITIATOR.EMP_LNAME AS INITIATOR,APPL_INITIATOR,-1 FROM TMS_APP_GUEST_DTL"
					+ " INNER JOIN TMS_APPLICATION ON(TMS_APPLICATION.APPL_ID = TMS_APP_GUEST_DTL.APPL_ID)"
					+ " INNER JOIN TMS_APP_TOUR_DTL ON(TMS_APP_TOUR_DTL.APPL_ID = TMS_APP_GUEST_DTL.APPL_ID)"
					+ " LEFT  JOIN HRMS_EMP_OFFC  INITIATOR ON(TMS_APPLICATION.APPL_INITIATOR = INITIATOR.EMP_ID )"
					+ " WHERE GUEST_TRAVEL_APPLSTATUS=? ORDER BY 1";
			//Only for submit/return
		case 44:
			return "SELECT TMS_APPLICATION.APPL_ID, TMS_APP_EMPDTL.APPL_CODE,APPL_FOR_FLAG,EMP_FNAME||' '||EMP_MNAME||' '||EMP_LNAME AS APPLICANT,NVL(TOUR_TRAVEL_REQ_NAME,' '),"
					+ " NVL(TO_CHAR(TOUR_TRAVEL_STARTDT,'DD-MM-YYYY'),' '),NVL(INITIATOR.EMP_FNAME||' '||INITIATOR.EMP_MNAME||' '||INITIATOR.EMP_LNAME,' ') AS INITIATOR,APPL_INITIATOR,APPL_EMP_CODE,NVL(APPL_TRVL_ID,' ') "
					+ " FROM TMS_APP_EMPDTL"
					+ " INNER JOIN TMS_APPLICATION ON(TMS_APPLICATION.APPL_ID = TMS_APP_EMPDTL.APPL_ID)"
					+ " LEFT JOIN TMS_APP_TOUR_DTL ON(TMS_APP_TOUR_DTL.APPL_ID = TMS_APP_EMPDTL.APPL_ID AND TMS_APP_TOUR_DTL.APPL_CODE = TMS_APP_EMPDTL.APPL_CODE)"
					+ " LEFT  JOIN HRMS_EMP_OFFC  INITIATOR ON(TMS_APPLICATION.APPL_INITIATOR = INITIATOR.EMP_ID )"
					+ " INNER JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID = TMS_APP_EMPDTL.APPL_EMP_CODE)"
					+ " WHERE APPL_EMP_TRAVEL_APPLSTATUS IN (?) AND (TMS_APPLICATION.APPL_INITIATOR = ? OR TMS_APP_EMPDTL.APPL_EMP_CODE=?)"
					+ " UNION "
					+ " SELECT TMS_APPLICATION.APPL_ID, TMS_APP_GUEST_DTL.APPL_CODE,APPL_FOR_FLAG,GUEST_NAME AS APPLICANT,NVL(TOUR_TRAVEL_REQ_NAME,' '),NVL(TO_CHAR(TOUR_TRAVEL_STARTDT,'DD-MM-YYYY'),' '),"
					+ " INITIATOR.EMP_FNAME||' '||INITIATOR.EMP_MNAME||' '||INITIATOR.EMP_LNAME AS INITIATOR,APPL_INITIATOR,-1,NVL(APPL_TRVL_ID,' ') "
					+ " FROM TMS_APP_GUEST_DTL"
					+ " INNER JOIN TMS_APPLICATION ON(TMS_APPLICATION.APPL_ID = TMS_APP_GUEST_DTL.APPL_ID)"
					+ " LEFT JOIN TMS_APP_TOUR_DTL ON(TMS_APP_TOUR_DTL.APPL_ID = TMS_APP_GUEST_DTL.APPL_ID AND TMS_APP_TOUR_DTL.APPL_CODE = TMS_APP_GUEST_DTL.APPL_CODE)"
					+ " LEFT  JOIN HRMS_EMP_OFFC  INITIATOR ON(TMS_APPLICATION.APPL_INITIATOR = INITIATOR.EMP_ID )"
					+ " WHERE GUEST_TRAVEL_APPLSTATUS IN(?) AND (TMS_APPLICATION.APPL_INITIATOR = ?)"
					+ " ORDER BY 1 DESC ,2 DESC";

		case 45:
			return " SELECT EMP_TOKEN, EMP_FNAME||' '||EMP_MNAME||' '||EMP_LNAME,EMP_CADRE FROM HRMS_EMP_OFFC WHERE EMP_ID=? ";

		case 46:
			return 	" SELECT TMS_TRAVEL_POLICY.POLICY_ID,POLICY_GRAD_ID,CADRE_NAME,POLICY_NAME,TO_CHAR(POLICY_EFFECTIVE_DATE,'DD-MM-YYYY'),POLICY_STATUS , DECODE(POLICY_ISADVANCE,'N','No','Y','Yes'), "
					+" NVL(MAX_DAYS_SETTLE_TRAVEL_CLAIM,'0'), POLICY_PAY_MODE_CHEQUE, POLICY_PAY_MODE_CASH, POLICY_PAY_MODE_TRANSFER, "
					+" POLICY_PAY_MODE_IN_SALARY,NVL(MIN_ADVANCE_DAYS_FOR_TRAVEL,'0'), "
					+" NVL(TRAVEL_TYPE_SELF,'N'), NVL(TRAVEL_TYPE_TEAM,'N'), NVL(TRAVEL_TYPE_GUEST,'N'), NVL(POLICY_TRAVEL_CURRENCY,'') FROM TMS_TRAVEL_POLICY"
					+ " INNER JOIN  TMS_POLICY_GRADE_DTL ON(TMS_POLICY_GRADE_DTL.POLICY_ID = TMS_TRAVEL_POLICY.POLICY_ID)"
					+ " INNER JOIN HRMS_CADRE ON(HRMS_CADRE.CADRE_ID = TMS_POLICY_GRADE_DTL.POLICY_GRAD_ID)"
					+ " WHERE POLICY_GRAD_ID= ? AND  POLICY_STATUS='A'";// AND   TO_DATE(?,'DD-MM-YYYY')>=POLICY_EFFECTIVE_DATE";// AND

			/*case 47 : return " SELECT HRMS_TMS_EXP_CATEGORY.EXP_CATEGORY_NAME,DECODE(POLICY_EXP_UNIT,'D','Per Day','T','Per Travel'),POLICY_EXP_ENT_AMT, POLICY_EXP_NO_LIMIT FROM TMS_POLICY_EXPENSE_DTL"
							+" INNER JOIN HRMS_TMS_EXP_CATEGORY ON(HRMS_TMS_EXP_CATEGORY.EXP_CATEGORY_ID = TMS_POLICY_EXPENSE_DTL.POLICY_EXP_CAT_ID)" 
							+" WHERE POLICY_ID=? AND EXP_CATEGORY_STATUS='A'";
							//+" ORDER BY EXP_CATEGORY_ID";
			 */

		case 47:
			return " SELECT HRMS_TMS_EXP_CATEGORY.EXP_CATEGORY_NAME,DECODE(POLICY_EXP_UNIT,'D','Per Day','T','Per Travel','K','Per Kilometer'),POLICY_EXP_ENT_AMT_WITHBILL, POLICY_EXP_ENT_AMT_WITHOUTBILL,POLICY_EXP_NO_LIMIT,PROOF_REQ,NVL(GRADE_NAME,'NA') FROM TMS_POLICY_EXPENSE_DTL"
					+ " INNER JOIN HRMS_TMS_EXP_CATEGORY ON(HRMS_TMS_EXP_CATEGORY.EXP_CATEGORY_ID = TMS_POLICY_EXPENSE_DTL.POLICY_EXP_CAT_ID)"
					+" LEFT JOIN HRMS_CITY_GRADE ON(HRMS_CITY_GRADE.GRADE_ID=TMS_POLICY_EXPENSE_DTL.POLICY_CITYGRADE)"
					+ " WHERE POLICY_ID=? AND EXP_CATEGORY_STATUS='A'";


		case 48:
			return " SELECT CLASS_ID,CLASS_JOURNEY_ID,JOURNEY_NAME,CLASS_NAME FROM HRMS_TMS_JOURNEY_CLASS"
					+ " INNER JOIN HRMS_TMS_JOURNEY_MODE ON(HRMS_TMS_JOURNEY_MODE.JOURNEY_ID =  HRMS_TMS_JOURNEY_CLASS.CLASS_JOURNEY_ID )"
					+ " WHERE CLASS_STATUS='A' OR CLASS_ID IN (SELECT DISTINCT POLICY_MAP_TRAVEL FROM TMS_POLICY_MAP_DTL WHERE POLICY_ID=?)"
					+ " ORDER BY JOURNEY_LEVEL,CLASS_LEVEL";//JOURNEY_LEVEL, CLASS_LEVEL";

		case 49:
			return "SELECT ROOM_TYPE_ID,ROOM_HOTEL_TYPE,HOTEL_TYPE_NAME,ROOM_TYPE_NAME FROM HRMS_TMS_ROOM_TYPE"
					+ " INNER JOIN HRMS_TMS_HOTEL_TYPE ON(HRMS_TMS_HOTEL_TYPE.HOTEL_TYPE_ID = HRMS_TMS_ROOM_TYPE.ROOM_HOTEL_TYPE)"
					+ " WHERE HOTEL_TYPE_STATUS='A' AND ROOM_TYPE_STATUS='A' OR ROOM_TYPE_ID IN(SELECT DISTINCT POLICY_MAP_LODGE FROM TMS_POLICY_MAP_DTL WHERE POLICY_ID=?)"
					+ " ORDER BY HOTEL_LEVEL,ROOM_LEVEL";//HOTEL_LEVEL,ROOM_LEVEL";

		case 50:
			return " SELECT POLICY_MAP_GUIDELINES, NVL(POLICY_MAP_EXP_STLMNT_DAYS,0),HRMS_TMS_EXP_CATEGORY.EXP_CATEGORY_NAME,EXPCAT.EXP_CATEGORY_NAME,POLICY_MAP_TRAVEL, POLICY_MAP_LODGE FROM TMS_POLICY_MAP_DTL"
					+ " LEFT JOIN HRMS_TMS_EXP_CATEGORY ON(HRMS_TMS_EXP_CATEGORY.EXP_CATEGORY_ID = TMS_POLICY_MAP_DTL.POLICY_MAP_TRAVEL_MCODE)"
					+ " LEFT JOIN HRMS_TMS_EXP_CATEGORY EXPCAT ON(EXPCAT.EXP_CATEGORY_ID = TMS_POLICY_MAP_DTL.POLICY_MAP_LODGE_MCODE)"
					+ " WHERE POLICY_ID=?";

			//Process Manager
		case 51:
			return " SELECT PMGR_REQ_RD, PMGR_REQ_APPR_RD, PMGR_SCHL_RD, PMGR_TRVL_CONF_RD, PMGR_TRVL_CLAIM_APP_RD, PMGR_TRVL_CLAIM_APPRD_RD, PMGR_SCND_LVL_APPRD_RD, PMGR_TRVL_POLICY_EFFDT, PMGR_SCHL_APPR_RD, PMGR_APPR_MAIN_SCHL FROM TMS_PROCESS_MGR";

		case 52:
			return "SELECT POLICY_MAP_TRAVEL, POLICY_MAP_LODGE,CLASS_LEVEL,ROOM_LEVEL,JOURNEY_LEVEL,HOTEL_LEVEL,JOURNEY_NAME||'-'||CLASS_NAME, HOTEL_TYPE_NAME||'-'||ROOM_TYPE_NAME, NVL(MIN_ADVANCE_DAYS_FOR_TRAVEL,0) FROM TMS_TRAVEL_POLICY "//JOURNEY_LEVEL,HOTEL_LEVEL
					+ " INNER JOIN TMS_POLICY_MAP_DTL ON(TMS_POLICY_MAP_DTL.POLICY_ID = TMS_TRAVEL_POLICY.POLICY_ID)"
					+ " INNER JOIN TMS_POLICY_GRADE_DTL ON(TMS_POLICY_GRADE_DTL.POLICY_ID = TMS_POLICY_MAP_DTL.POLICY_ID AND POLICY_GRAD_ID=?)"
					+ " INNER JOIN HRMS_TMS_JOURNEY_CLASS ON(HRMS_TMS_JOURNEY_CLASS.CLASS_ID=TMS_POLICY_MAP_DTL.POLICY_MAP_TRAVEL)"
					+ " INNER JOIN HRMS_TMS_JOURNEY_MODE ON(HRMS_TMS_JOURNEY_MODE.JOURNEY_ID=HRMS_TMS_JOURNEY_CLASS.CLASS_JOURNEY_ID)"
					+ " INNER JOIN HRMS_TMS_ROOM_TYPE ON(HRMS_TMS_ROOM_TYPE.ROOM_TYPE_ID=TMS_POLICY_MAP_DTL.POLICY_MAP_LODGE)"
					+ " INNER JOIN HRMS_TMS_HOTEL_TYPE ON(HRMS_TMS_HOTEL_TYPE.HOTEL_TYPE_ID = HRMS_TMS_ROOM_TYPE.ROOM_HOTEL_TYPE)"
					+ " WHERE  POLICY_STATUS='A' AND TO_DATE(?,'DD-MM-YYYY')>=POLICY_EFFECTIVE_DATE"
					+ " ORDER BY POLICY_EFFECTIVE_DATE DESC";

		case 53:
			return " SELECT NVL(APPR_DTL_COMMENTS,' ') FROM TMS_APP_APPROVAL_DTL WHERE APPL_ID=? AND APPL_CODE=? ORDER BY APPL_ID,APPL_CODE";

		case 54:
			return " SELECT TMS_APPLICATION.APPL_ID, APPL_CODE,APPL_FOR_FLAG,EMP_FNAME||' '||EMP_MNAME||' '||EMP_LNAME AS APPLICANT,NVL(TOUR_TRAVEL_REQ_NAME,' '),"
					+ " NVL(TO_CHAR(TOUR_TRAVEL_STARTDT,'DD-MM-YYYY'),' '),NVL(INITIATOR.EMP_FNAME||' '||INITIATOR.EMP_MNAME||' '||INITIATOR.EMP_LNAME,' ') AS INITIATOR,APPL_INITIATOR,APPL_EMP_CODE,NVL(APPL_TRVL_ID,' '),APPL_EMP_TRAVEL_APPLSTATUS "
					+ " FROM TMS_APP_EMPDTL"
					+ " INNER JOIN TMS_APPLICATION ON(TMS_APPLICATION.APPL_ID = TMS_APP_EMPDTL.APPL_ID)"
					+ " LEFT JOIN TMS_APP_TOUR_DTL ON(TMS_APP_TOUR_DTL.APPL_ID = TMS_APP_EMPDTL.APPL_ID AND TMS_APP_TOUR_DTL.APPL_CODE = TMS_APP_EMPDTL.APPL_CODE)"
					+ " LEFT  JOIN HRMS_EMP_OFFC  INITIATOR ON(TMS_APPLICATION.APPL_INITIATOR = INITIATOR.EMP_ID )"
					+ " INNER JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID = TMS_APP_EMPDTL.APPL_EMP_CODE)"
					+ " WHERE APPL_EMP_TRAVEL_APPLSTATUS IN ('a','A','CP','AC','H') AND (TMS_APPLICATION.APPL_INITIATOR = ? OR TMS_APP_EMPDTL.APPL_EMP_CODE=?)"
					+ " UNION " //AC - Approved Cancelled list
					+ " SELECT TMS_APPLICATION.APPL_ID, TMS_APP_GUEST_DTL.APPL_CODE,APPL_FOR_FLAG,GUEST_NAME AS APPLICANT,NVL(TOUR_TRAVEL_REQ_NAME,' '),NVL(TO_CHAR(TOUR_TRAVEL_STARTDT,'DD-MM-YYYY'),' '),"
					+ " INITIATOR.EMP_FNAME||' '||INITIATOR.EMP_MNAME||' '||INITIATOR.EMP_LNAME AS INITIATOR,APPL_INITIATOR,-1,NVL(APPL_TRVL_ID,' '),GUEST_TRAVEL_APPLSTATUS "
					+ " FROM TMS_APP_GUEST_DTL"
					+ " INNER JOIN TMS_APPLICATION ON(TMS_APPLICATION.APPL_ID = TMS_APP_GUEST_DTL.APPL_ID)"
					+ " LEFT JOIN TMS_APP_TOUR_DTL ON(TMS_APP_TOUR_DTL.APPL_ID = TMS_APP_GUEST_DTL.APPL_ID AND TMS_APP_TOUR_DTL.APPL_CODE = TMS_APP_GUEST_DTL.APPL_CODE)"
					+ " LEFT  JOIN HRMS_EMP_OFFC  INITIATOR ON(TMS_APPLICATION.APPL_INITIATOR = INITIATOR.EMP_ID )"
					+ " WHERE GUEST_TRAVEL_APPLSTATUS IN('a','A','CP','AC','H') AND (TMS_APPLICATION.APPL_INITIATOR = ?)"
					+ " ORDER BY 1 DESC,2 DESC";

		case 55:
			return " UPDATE TMS_APP_EMPDTL SET APPL_EMP_MAIN_APPROVER=?,APPL_EMP_ALT_APPROVER=? WHERE APPL_ID=? AND APPL_CODE=?";

		case 56:
			return " SELECT APPL_INITIATOR,EMP_CADRE,EMP_DEPT,EMP_CENTER,EMP_DESG FROM TMS_APPLICATION"
					+ " INNER JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID = TMS_APPLICATION.APPL_INITIATOR)"
					+ " WHERE APPL_ID =? AND APPL_FOR_FLAG='G'";

		case 57:
			return " SELECT * FROM TMS_APP_APPROVAL_DTL WHERE APPL_ID=? AND APPL_CODE=?";

		case 58:
			return " SELECT EMP_TOKEN, EMP_FNAME||' '||EMP_MNAME||' '||EMP_LNAME,CENTER_NAME AS BRANCH,DEPT_NAME,RANK_NAME,CADRE_NAME,"
					+ " FLOOR( (SYSDATE - EMP_DOB)/365.24)AS AGE ,ADD_MOBILE,HRMS_EMP_OFFC.EMP_ID,EMP_CENTER,EMP_DEPT,EMP_RANK,HRMS_EMP_OFFC.EMP_CADRE, ADD_MOBILE, APPL_EMP_ADVANCE_AMT, NVL(TO_CHAR(HRMS_EMP_OFFC.EMP_DOB,'DD-MM-YYYY'),' ') AS DOB , NVL(TO_CHAR(HRMS_EMP_OFFC.EMP_REGULAR_DATE,'DD-MM-YYYY'),' ') AS Date_of_joinings FROM HRMS_EMP_OFFC"
					+ " LEFT JOIN HRMS_CENTER ON(HRMS_CENTER.CENTER_ID=HRMS_EMP_OFFC.EMP_CENTER)"
					+ " LEFT JOIN HRMS_DEPT ON(HRMS_DEPT.DEPT_ID=HRMS_EMP_OFFC.EMP_DEPT)"
					+ " LEFT JOIN HRMS_RANK ON(HRMS_RANK.RANK_ID=HRMS_EMP_OFFC.EMP_RANK)"
					+ " LEFT JOIN HRMS_CADRE ON(HRMS_CADRE.CADRE_ID=HRMS_EMP_OFFC.EMP_CADRE)"
					+ " LEFT JOIN HRMS_EMP_ADDRESS ON(HRMS_EMP_ADDRESS.EMP_ID=HRMS_EMP_OFFC.EMP_ID and ADD_TYPE='P')"
					+ " LEFT JOIN TMS_APP_EMPDTL ON(TMS_APP_EMPDTL.APPL_EMP_CODE=HRMS_EMP_OFFC.EMP_ID)"
					+ " WHERE HRMS_EMP_OFFC.EMP_ID= ?";

			//SCHEDULED TRAVEL LIST 
		case 59:
			return "SELECT DESK_ID,DESK_APPL_ID,DESK_APPL_CODE,NVL(APPL_TRVL_ID,' '),APPL_INITIATOR ,NVL(EMP_FNAME||' '||EMP_MNAME||' '||EMP_LNAME,' ') AS INITIATOR, "
					+ " HRMS_TITLE.TITLE_NAME||' '||NVL(C1.EMP_FNAME,' ')||'  '||NVL(C1.EMP_MNAME,' ')||'  '||NVL(C1.EMP_LNAME,' ') AS APPLICANT, TO_CHAR(TMS_APPLICATION.APPL_DATE,'DD-MM-YYYY') ,"
					+ " TO_CHAR(TOUR_TRAVEL_STARTDT,'DD-MM-YYYY'),APPL_FOR_FLAG,DESK_STATUS,TOUR_TRAVEL_REQ_NAME,TMS_APP_EMPDTL.APPL_EMP_CODE FROM TMS_SCH_DESK "
					+ " LEFT JOIN   TMS_APPLICATION ON(TMS_SCH_DESK.DESK_APPL_ID=TMS_APPLICATION.APPL_ID)"
					+ " INNER JOIN   TMS_APP_EMPDTL ON(TMS_SCH_DESK.DESK_APPL_ID=TMS_APP_EMPDTL.APPL_ID AND TMS_SCH_DESK.DESK_APPL_CODE=TMS_APP_EMPDTL.APPL_CODE)"
					+ " INNER JOIN TMS_APP_TOUR_DTL ON(TMS_APP_TOUR_DTL.APPL_ID=TMS_APPLICATION.APPL_ID)"
					+ " INNER JOIN HRMS_EMP_OFFC C1 ON(TMS_APP_EMPDTL.APPL_EMP_CODE=C1.EMP_ID) "
					+ " LEFT JOIN   HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=TMS_APPLICATION.APPL_INITIATOR)"
					+ " LEFT JOIN HRMS_TITLE  ON(HRMS_TITLE.TITLE_CODE=HRMS_EMP_OFFC.EMP_TITLE_CODE)  "
					+ " LEFT JOIN   TMS_APP_JOURNEY_DTL ON(TMS_SCH_DESK.DESK_APPL_ID=TMS_APP_JOURNEY_DTL.APPL_ID)"
					+ " LEFT JOIN  HRMS_CENTER ON(HRMS_EMP_OFFC.EMP_CENTER=HRMS_CENTER.CENTER_ID)  "
					+ " WHERE DESK_STATUS='S' AND (APPL_EMP_CODE=? OR APPL_INITIATOR=?)"
					+ " UNION "
					+ " SELECT DESK_ID,DESK_APPL_ID,DESK_APPL_CODE,NVL(APPL_TRVL_ID,' '),APPL_INITIATOR ,NVL(EMP_FNAME||' '||EMP_MNAME||' '||EMP_LNAME,' ') AS INITIATOR, GUEST_NAME AS APPLICANT, "
					+ " TO_CHAR(TMS_APPLICATION.APPL_DATE,'DD-MM-YYYY') ,TO_CHAR(TOUR_TRAVEL_STARTDT,'DD-MM-YYYY'),APPL_FOR_FLAG,DESK_STATUS,TOUR_TRAVEL_REQ_NAME,0 FROM TMS_SCH_DESK"
					+ " LEFT JOIN   TMS_APPLICATION ON(TMS_SCH_DESK.DESK_APPL_ID=TMS_APPLICATION.APPL_ID) "
					+ " INNER JOIN  TMS_APP_GUEST_DTL ON(TMS_SCH_DESK.DESK_APPL_ID=TMS_APP_GUEST_DTL.APPL_ID AND TMS_SCH_DESK.DESK_APPL_CODE=TMS_APP_GUEST_DTL.APPL_CODE)"
					+ " INNER JOIN TMS_APP_TOUR_DTL ON(TMS_APP_TOUR_DTL.APPL_ID=TMS_APPLICATION.APPL_ID)"
					+ " LEFT JOIN   HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=TMS_APPLICATION.APPL_INITIATOR)"
					+ " LEFT JOIN HRMS_TITLE  ON(HRMS_TITLE.TITLE_CODE=HRMS_EMP_OFFC.EMP_TITLE_CODE)  "
					+ " LEFT JOIN   TMS_APP_JOURNEY_DTL ON(TMS_SCH_DESK.DESK_APPL_ID=TMS_APP_JOURNEY_DTL.APPL_ID)"
					+ " LEFT JOIN  HRMS_CENTER ON(HRMS_EMP_OFFC.EMP_CENTER=HRMS_CENTER.CENTER_ID)  "
					+ " WHERE DESK_STATUS='S' AND TMS_APPLICATION.APPL_INITIATOR = ?"
					+ " ORDER BY 1 DESC,2 DESC";

			//SCHEDULED REJECTED LIST 
		case 60:
			return "SELECT DESK_ID,DESK_APPL_ID,DESK_APPL_CODE,NVL(APPL_TRVL_ID,' '),APPL_INITIATOR ,NVL(EMP_FNAME||' '||EMP_MNAME||' '||EMP_LNAME,' ') AS INITIATOR, "
					+ " HRMS_TITLE.TITLE_NAME||' '||NVL(C1.EMP_FNAME,' ')||'  '||NVL(C1.EMP_MNAME,' ')||'  '||NVL(C1.EMP_LNAME,' ') AS APPLICANT, TO_CHAR(TMS_APPLICATION.APPL_DATE,'DD-MM-YYYY') ,"
					+ " TO_CHAR(TOUR_TRAVEL_STARTDT,'DD-MM-YYYY'),APPL_FOR_FLAG,DESK_STATUS FROM TMS_SCH_DESK "
					+ " LEFT JOIN   TMS_APPLICATION ON(TMS_SCH_DESK.DESK_APPL_ID=TMS_APPLICATION.APPL_ID)"
					+ " INNER JOIN   TMS_APP_EMPDTL ON(TMS_SCH_DESK.DESK_APPL_ID=TMS_APP_EMPDTL.APPL_ID AND TMS_SCH_DESK.DESK_APPL_CODE=TMS_APP_EMPDTL.APPL_CODE)"
					+ " INNER JOIN TMS_APP_TOUR_DTL ON(TMS_APP_TOUR_DTL.APPL_ID=TMS_APPLICATION.APPL_ID)"
					+ " INNER JOIN HRMS_EMP_OFFC C1 ON(TMS_APP_EMPDTL.APPL_EMP_CODE=C1.EMP_ID) "
					+ " LEFT JOIN   HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=TMS_APPLICATION.APPL_INITIATOR)"
					+ " LEFT JOIN HRMS_TITLE  ON(HRMS_TITLE.TITLE_CODE=HRMS_EMP_OFFC.EMP_TITLE_CODE)  "
					+ " LEFT JOIN   TMS_APP_JOURNEY_DTL ON(TMS_SCH_DESK.DESK_APPL_ID=TMS_APP_JOURNEY_DTL.APPL_ID)"
					+ " LEFT JOIN  HRMS_CENTER ON(HRMS_EMP_OFFC.EMP_CENTER=HRMS_CENTER.CENTER_ID)  "
					+ " WHERE DESK_STATUS='R' AND APPL_EMP_CODE=?"
					+ " UNION "
					+ " SELECT DESK_ID,DESK_APPL_ID,DESK_APPL_CODE,NVL(APPL_TRVL_ID,' '),APPL_INITIATOR ,NVL(EMP_FNAME||' '||EMP_MNAME||' '||EMP_LNAME,' ') AS INITIATOR, GUEST_NAME AS APPLICANT, TO_CHAR(TMS_APPLICATION.APPL_DATE,'DD-MM-YYYY') ,TO_CHAR(TOUR_TRAVEL_STARTDT,'DD-MM-YYYY'),APPL_FOR_FLAG,DESK_STATUS FROM TMS_SCH_DESK"
					+ " LEFT JOIN   TMS_APPLICATION ON(TMS_SCH_DESK.DESK_APPL_ID=TMS_APPLICATION.APPL_ID) "
					+ " INNER JOIN  TMS_APP_GUEST_DTL ON(TMS_SCH_DESK.DESK_APPL_ID=TMS_APP_GUEST_DTL.APPL_ID AND TMS_SCH_DESK.DESK_APPL_CODE=TMS_APP_GUEST_DTL.APPL_CODE)"
					+ " INNER JOIN TMS_APP_TOUR_DTL ON(TMS_APP_TOUR_DTL.APPL_ID=TMS_APPLICATION.APPL_ID)"
					+ " LEFT JOIN   HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=TMS_APPLICATION.APPL_INITIATOR)"
					+ " LEFT JOIN HRMS_TITLE  ON(HRMS_TITLE.TITLE_CODE=HRMS_EMP_OFFC.EMP_TITLE_CODE)  "
					+ " LEFT JOIN   TMS_APP_JOURNEY_DTL ON(TMS_SCH_DESK.DESK_APPL_ID=TMS_APP_JOURNEY_DTL.APPL_ID)"
					+ " LEFT JOIN  HRMS_CENTER ON(HRMS_EMP_OFFC.EMP_CENTER=HRMS_CENTER.CENTER_ID)  "
					+ " WHERE DESK_STATUS='R' AND TMS_APPLICATION.APPL_INITIATOR = ?";
			//For draft list
		case 61:
			return "SELECT TMS_APPLICATION.APPL_ID, TMS_APP_EMPDTL.APPL_CODE,APPL_FOR_FLAG,EMP_FNAME||' '||EMP_MNAME||' '||EMP_LNAME AS APPLICANT,NVL(TOUR_TRAVEL_REQ_NAME,' '),"
					+ " NVL(TO_CHAR(TOUR_TRAVEL_STARTDT,'DD-MM-YYYY'),' '),NVL(INITIATOR.EMP_FNAME||' '||INITIATOR.EMP_MNAME||' '||INITIATOR.EMP_LNAME,' ') AS INITIATOR,APPL_INITIATOR,APPL_EMP_CODE,APPL_EMP_TRAVEL_APPLSTATUS "
					+ " FROM TMS_APP_EMPDTL"
					+ " INNER JOIN TMS_APPLICATION ON(TMS_APPLICATION.APPL_ID = TMS_APP_EMPDTL.APPL_ID)"
					+ " LEFT JOIN TMS_APP_TOUR_DTL ON(TMS_APP_TOUR_DTL.APPL_ID = TMS_APP_EMPDTL.APPL_ID  AND TMS_APP_TOUR_DTL.APPL_CODE = TMS_APP_EMPDTL.APPL_CODE )"//AND TMS_APP_TOUR_DTL.APPL_CODE = TMS_APP_EMPDTL.APPL_CODE
					+ " LEFT  JOIN HRMS_EMP_OFFC  INITIATOR ON(TMS_APPLICATION.APPL_INITIATOR = INITIATOR.EMP_ID )"
					+ " INNER JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID = TMS_APP_EMPDTL.APPL_EMP_CODE)"
					+ " WHERE APPL_EMP_TRAVEL_APPLSTATUS IN ('N','W') AND (TMS_APPLICATION.APPL_INITIATOR = ? )"
					+ " UNION "
					+ " SELECT TMS_APPLICATION.APPL_ID, TMS_APP_GUEST_DTL.APPL_CODE,APPL_FOR_FLAG,GUEST_NAME AS APPLICANT,NVL(TOUR_TRAVEL_REQ_NAME,' '),NVL(TO_CHAR(TOUR_TRAVEL_STARTDT,'DD-MM-YYYY'),' '),"
					+ " INITIATOR.EMP_FNAME||' '||INITIATOR.EMP_MNAME||' '||INITIATOR.EMP_LNAME AS INITIATOR,APPL_INITIATOR,-1,GUEST_TRAVEL_APPLSTATUS  "
					+ " FROM TMS_APP_GUEST_DTL"
					+ " INNER JOIN TMS_APPLICATION ON(TMS_APPLICATION.APPL_ID = TMS_APP_GUEST_DTL.APPL_ID)"
					+ " LEFT JOIN TMS_APP_TOUR_DTL ON(TMS_APP_TOUR_DTL.APPL_ID = TMS_APP_GUEST_DTL.APPL_ID  AND TMS_APP_GUEST_DTL.APPL_CODE=TMS_APP_TOUR_DTL.APPL_CODE)"//AND TMS_APP_TOUR_DTL.APPL_CODE = TMS_APP_GUEST_DTL.APPL_CODE
					+ " LEFT  JOIN HRMS_EMP_OFFC  INITIATOR ON(TMS_APPLICATION.APPL_INITIATOR = INITIATOR.EMP_ID )"
					+ " WHERE GUEST_TRAVEL_APPLSTATUS IN('N','W') AND (TMS_APPLICATION.APPL_INITIATOR = ?)"
					+ " ORDER BY 6 DESC";

		case 62:
			return " UPDATE TMS_APPLICATION SET APPL_APPLCANT_COMMENTS=? WHERE APPL_ID=? ";

		case 63:
			return " DELETE FROM TMS_APPLICATION WHERE APPL_ID =?";

		case 64:
			return " UPDATE TMS_APP_GUEST_DTL SET APPL_EMP_MAIN_APPROVER=?, APPL_EMP_ALT_APPROVER=? WHERE APPL_ID=? AND  APPL_CODE=?";

		case 65:
			return " SELECT CURRENCY_ID, CURRENCY_ABBR FROM HRMS_CURRENCY";

		case 66:
			return " INSERT INTO TMS_COMMENTS_TRAIL(COMMENTS_ID, COMMENTS_APP_ID, COMMENTS_APP_CODE, COMMENTS_APP_STATE, COMMENTS_EMPID, COMMENTS_DESC, COMMENTS_DATE, COMMENTS_LEVEL)VALUES((SELECT NVL(MAX(COMMENTS_ID),0)+1 FROM TMS_COMMENTS_TRAIL),?,?,?,?,?,SYSDATE,?)";

		case 67:
			return " DELETE FROM TMS_APP_TOUR_DTL WHERE APPL_ID=?";

			//WDRL - Withdrawal ,CNCL - Cancellation 
		case 68:
			return " SELECT COMMENTS_DATE,COMMENTS_DESC FROM TMS_COMMENTS_TRAIL WHERE COMMENTS_APP_ID=? AND COMMENTS_APP_CODE=? AND COMMENTS_LEVEL='CNCL' ORDER BY COMMENTS_DATE DESC";

		case 69:
			return " UPDATE TMS_APP_APPROVAL_DTL SET APPR_STATUS='' WHERE  APPL_ID=? AND APPL_CODE=?";

		case 70:
			return " SELECT * FROM TMS_APP_TOUR_DTL  INNER JOIN TMS_MONITORING ON(TMS_MONITORING.APPL_ID = TMS_APP_TOUR_DTL.APPL_ID AND TMS_MONITORING.APPL_CODE = TMS_APP_TOUR_DTL.APPL_CODE) WHERE (TOUR_TRAVEL_ARR_DONE='C' OR TOUR_CONV_ARR_DONE='C' OR TOUR_ACCOM_ARR_DONE='C') AND TMS_APP_TOUR_DTL.APPL_ID=? AND TMS_APP_TOUR_DTL.APPL_CODE=?";

			// Queries for deletion of entire application
		case 71:
			return " DELETE FROM  TMS_APP_APPROVAL_DTL WHERE  APPL_ID=? AND APPL_CODE=? ";

		case 72:
			return " DELETE FROM TMS_APP_JOURNEY_DTL WHERE APPL_ID=? AND APPL_CODE=?";

		case 73:
			return " DELETE FROM TMS_APP_LODGE_DTL WHERE APPL_ID=? AND APPL_CODE=?";

		case 74:
			return " DELETE FROM TMS_APP_CONV_DTL  WHERE APPL_ID=? AND APPL_CODE=?";

		case 75:
			return " DELETE FROM TMS_APP_TOUR_DTL WHERE APPL_ID=? AND APPL_CODE=? ";

		case 76:
			return " DELETE FROM TMS_APP_EMPDTL WHERE APPL_ID=? AND APPL_CODE=?  ";

		case 77:
			return " DELETE FROM TMS_APP_GUEST_DTL WHERE APPL_ID=? AND APPL_CODE=?  ";

			//Emp_dtls
		case 78:
			return " SELECT TMS_APPLICATION.APPL_ID, APPL_CODE,APPL_FOR_FLAG,EMP_FNAME||' '||EMP_MNAME||' '||EMP_LNAME AS APPLICANT,NVL(TOUR_TRAVEL_REQ_NAME,' '),"
					+ " NVL(TO_CHAR(TOUR_TRAVEL_STARTDT,'DD-MM-YYYY'),' '),NVL(INITIATOR.EMP_FNAME||' '||INITIATOR.EMP_MNAME||' '||INITIATOR.EMP_LNAME,' ') AS INITIATOR,APPL_INITIATOR,APPL_EMP_CODE,NVL(APPL_TRVL_ID,' '),APPL_EMP_TRAVEL_APPLSTATUS "
					+ " FROM TMS_APP_EMPDTL"
					+ " INNER JOIN TMS_APPLICATION ON(TMS_APPLICATION.APPL_ID = TMS_APP_EMPDTL.APPL_ID)"
					+ " LEFT JOIN TMS_APP_TOUR_DTL ON(TMS_APP_TOUR_DTL.APPL_ID = TMS_APP_EMPDTL.APPL_ID AND TMS_APP_TOUR_DTL.APPL_CODE = TMS_APP_EMPDTL.APPL_CODE)"
					+ " LEFT  JOIN HRMS_EMP_OFFC  INITIATOR ON(TMS_APPLICATION.APPL_INITIATOR = INITIATOR.EMP_ID )"
					+ " INNER JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID = TMS_APP_EMPDTL.APPL_EMP_CODE)"
					+ " WHERE APPL_EMP_TRAVEL_APPLSTATUS IN ('a','A','CP','AC','H') ";

			//Guest_dtls
		case 79:
			return " SELECT TMS_APPLICATION.APPL_ID, TMS_APP_GUEST_DTL.APPL_CODE,APPL_FOR_FLAG,GUEST_NAME AS APPLICANT,NVL(TOUR_TRAVEL_REQ_NAME,' '),NVL(TO_CHAR(TOUR_TRAVEL_STARTDT,'DD-MM-YYYY'),' '),"
					+ " INITIATOR.EMP_FNAME||' '||INITIATOR.EMP_MNAME||' '||INITIATOR.EMP_LNAME AS INITIATOR,APPL_INITIATOR,-1,NVL(APPL_TRVL_ID,' '),GUEST_TRAVEL_APPLSTATUS "
					+ " FROM TMS_APP_GUEST_DTL"
					+ " INNER JOIN TMS_APPLICATION ON(TMS_APPLICATION.APPL_ID = TMS_APP_GUEST_DTL.APPL_ID)"
					+ " LEFT JOIN TMS_APP_TOUR_DTL ON(TMS_APP_TOUR_DTL.APPL_ID = TMS_APP_GUEST_DTL.APPL_ID AND TMS_APP_TOUR_DTL.APPL_CODE = TMS_APP_GUEST_DTL.APPL_CODE)"
					+ " LEFT  JOIN HRMS_EMP_OFFC  INITIATOR ON(TMS_APPLICATION.APPL_INITIATOR = INITIATOR.EMP_ID )"
					+ " WHERE GUEST_TRAVEL_APPLSTATUS IN('a','A','CP','AC','H') ";

			//+" ORDER BY 1 DESC,2 DESC";

		case 80:
			return "SELECT TMS_APPLICATION.APPL_ID, TMS_APP_EMPDTL.APPL_CODE,APPL_FOR_FLAG,EMP_FNAME||' '||EMP_MNAME||' '||EMP_LNAME AS APPLICANT,NVL(TOUR_TRAVEL_REQ_NAME,' '),"
					+ " NVL(TO_CHAR(TOUR_TRAVEL_STARTDT,'DD-MM-YYYY'),' '),NVL(INITIATOR.EMP_FNAME||' '||INITIATOR.EMP_MNAME||' '||INITIATOR.EMP_LNAME,' ') AS INITIATOR,APPL_INITIATOR,APPL_EMP_CODE,NVL(APPL_TRVL_ID,' ') "
					+ " FROM TMS_APP_EMPDTL"
					+ " INNER JOIN TMS_APPLICATION ON(TMS_APPLICATION.APPL_ID = TMS_APP_EMPDTL.APPL_ID)"
					+ " LEFT JOIN TMS_APP_TOUR_DTL ON(TMS_APP_TOUR_DTL.APPL_ID = TMS_APP_EMPDTL.APPL_ID AND TMS_APP_TOUR_DTL.APPL_CODE = TMS_APP_EMPDTL.APPL_CODE)"
					+ " LEFT  JOIN HRMS_EMP_OFFC  INITIATOR ON(TMS_APPLICATION.APPL_INITIATOR = INITIATOR.EMP_ID )"
					+ " INNER JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID = TMS_APP_EMPDTL.APPL_EMP_CODE)"
					+ " WHERE APPL_EMP_TRAVEL_APPLSTATUS IN ('R')";

		case 81:
			return " SELECT TMS_APPLICATION.APPL_ID, TMS_APP_GUEST_DTL.APPL_CODE,APPL_FOR_FLAG,GUEST_NAME AS APPLICANT,NVL(TOUR_TRAVEL_REQ_NAME,' '),NVL(TO_CHAR(TOUR_TRAVEL_STARTDT,'DD-MM-YYYY'),' '),"
					+ " INITIATOR.EMP_FNAME||' '||INITIATOR.EMP_MNAME||' '||INITIATOR.EMP_LNAME AS INITIATOR,APPL_INITIATOR,-1,NVL(APPL_TRVL_ID,' ') "
					+ " FROM TMS_APP_GUEST_DTL"
					+ " INNER JOIN TMS_APPLICATION ON(TMS_APPLICATION.APPL_ID = TMS_APP_GUEST_DTL.APPL_ID)"
					+ " LEFT JOIN TMS_APP_TOUR_DTL ON(TMS_APP_TOUR_DTL.APPL_ID = TMS_APP_GUEST_DTL.APPL_ID AND TMS_APP_TOUR_DTL.APPL_CODE = TMS_APP_GUEST_DTL.APPL_CODE)"
					+ " LEFT  JOIN HRMS_EMP_OFFC  INITIATOR ON(TMS_APPLICATION.APPL_INITIATOR = INITIATOR.EMP_ID )"
					+ " WHERE GUEST_TRAVEL_APPLSTATUS IN('R')";
			//+" ORDER BY 1 DESC ,2 DESC";

			//SCHEDULED TRAVEL LIST 
		case 82:
			return "SELECT DESK_ID,DESK_APPL_ID,DESK_APPL_CODE,NVL(APPL_TRVL_ID,' '),APPL_INITIATOR ,NVL(EMP_FNAME||' '||EMP_MNAME||' '||EMP_LNAME,' ') AS INITIATOR, "
					+ " HRMS_TITLE.TITLE_NAME||' '||NVL(C1.EMP_FNAME,' ')||'  '||NVL(C1.EMP_MNAME,' ')||'  '||NVL(C1.EMP_LNAME,' ') AS APPLICANT, TO_CHAR(TMS_APPLICATION.APPL_DATE,'DD-MM-YYYY') ,"
					+ " TO_CHAR(TOUR_TRAVEL_STARTDT,'DD-MM-YYYY'),APPL_FOR_FLAG,DESK_STATUS,TOUR_TRAVEL_REQ_NAME,TMS_APP_EMPDTL.APPL_EMP_CODE FROM TMS_SCH_DESK "
					+ " LEFT JOIN   TMS_APPLICATION ON(TMS_SCH_DESK.DESK_APPL_ID=TMS_APPLICATION.APPL_ID)"
					+ " INNER JOIN   TMS_APP_EMPDTL ON(TMS_SCH_DESK.DESK_APPL_ID=TMS_APP_EMPDTL.APPL_ID AND TMS_SCH_DESK.DESK_APPL_CODE=TMS_APP_EMPDTL.APPL_CODE)"
					+ " INNER JOIN TMS_APP_TOUR_DTL ON(TMS_APP_TOUR_DTL.APPL_ID=TMS_APPLICATION.APPL_ID)"
					+ " INNER JOIN HRMS_EMP_OFFC C1 ON(TMS_APP_EMPDTL.APPL_EMP_CODE=C1.EMP_ID) "
					+ " LEFT JOIN   HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=TMS_APPLICATION.APPL_INITIATOR)"
					+ " LEFT JOIN HRMS_TITLE  ON(HRMS_TITLE.TITLE_CODE=HRMS_EMP_OFFC.EMP_TITLE_CODE)  "
					+ " LEFT JOIN   TMS_APP_JOURNEY_DTL ON(TMS_SCH_DESK.DESK_APPL_ID=TMS_APP_JOURNEY_DTL.APPL_ID)"
					+ " LEFT JOIN  HRMS_CENTER ON(HRMS_EMP_OFFC.EMP_CENTER=HRMS_CENTER.CENTER_ID)  "
					+ " WHERE DESK_STATUS='S'";

		case 83:
			return "SELECT DESK_ID,DESK_APPL_ID,DESK_APPL_CODE,NVL(APPL_TRVL_ID,' '),APPL_INITIATOR ,NVL(EMP_FNAME||' '||EMP_MNAME||' '||EMP_LNAME,' ') AS INITIATOR, GUEST_NAME AS APPLICANT, "
					+ " TO_CHAR(TMS_APPLICATION.APPL_DATE,'DD-MM-YYYY') ,TO_CHAR(TOUR_TRAVEL_STARTDT,'DD-MM-YYYY'),APPL_FOR_FLAG,DESK_STATUS,TOUR_TRAVEL_REQ_NAME,0 FROM TMS_SCH_DESK"
					+ " LEFT JOIN   TMS_APPLICATION ON(TMS_SCH_DESK.DESK_APPL_ID=TMS_APPLICATION.APPL_ID) "
					+ " INNER JOIN  TMS_APP_GUEST_DTL ON(TMS_SCH_DESK.DESK_APPL_ID=TMS_APP_GUEST_DTL.APPL_ID AND TMS_SCH_DESK.DESK_APPL_CODE=TMS_APP_GUEST_DTL.APPL_CODE)"
					+ " INNER JOIN TMS_APP_TOUR_DTL ON(TMS_APP_TOUR_DTL.APPL_ID=TMS_APPLICATION.APPL_ID)"
					+ " LEFT JOIN   HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID=TMS_APPLICATION.APPL_INITIATOR)"
					+ " LEFT JOIN HRMS_TITLE  ON(HRMS_TITLE.TITLE_CODE=HRMS_EMP_OFFC.EMP_TITLE_CODE)  "
					+ " LEFT JOIN   TMS_APP_JOURNEY_DTL ON(TMS_SCH_DESK.DESK_APPL_ID=TMS_APP_JOURNEY_DTL.APPL_ID)"
					+ " LEFT JOIN  HRMS_CENTER ON(HRMS_EMP_OFFC.EMP_CENTER=HRMS_CENTER.CENTER_ID)  "
					+ " WHERE DESK_STATUS='S'";
			//+" ORDER BY 1 DESC,2 DESC";
		case 84:
			return "SELECT TMS_APPLICATION.APPL_ID, APPL_CODE,APPL_FOR_FLAG,EMP_FNAME||' '||EMP_MNAME||' '||EMP_LNAME AS APPLICANT,NVL(TOUR_TRAVEL_REQ_NAME,' '),"
					+ " NVL(TO_CHAR(TOUR_TRAVEL_STARTDT,'DD-MM-YYYY'),' '),NVL(INITIATOR.EMP_FNAME||' '||INITIATOR.EMP_MNAME||' '||INITIATOR.EMP_LNAME,' ') AS INITIATOR,APPL_INITIATOR,APPL_EMP_CODE,NVL(APPL_TRVL_ID,' ') "
					+ " FROM TMS_APP_EMPDTL"
					+ " INNER JOIN TMS_APPLICATION ON(TMS_APPLICATION.APPL_ID = TMS_APP_EMPDTL.APPL_ID)"
					+ " LEFT JOIN TMS_APP_TOUR_DTL ON(TMS_APP_TOUR_DTL.APPL_ID = TMS_APP_EMPDTL.APPL_ID AND TMS_APP_TOUR_DTL.APPL_CODE = TMS_APP_EMPDTL.APPL_CODE)"
					+ " LEFT  JOIN HRMS_EMP_OFFC  INITIATOR ON(TMS_APPLICATION.APPL_INITIATOR = INITIATOR.EMP_ID )"
					+ " INNER JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID = TMS_APP_EMPDTL.APPL_EMP_CODE)"
					+ " WHERE APPL_EMP_TRAVEL_APPLSTATUS IN ('PC','FC') ";

		case 85:
			return " SELECT TMS_APPLICATION.APPL_ID, TMS_APP_GUEST_DTL.APPL_CODE,APPL_FOR_FLAG,GUEST_NAME AS APPLICANT,NVL(TOUR_TRAVEL_REQ_NAME,' '),NVL(TO_CHAR(TOUR_TRAVEL_STARTDT,'DD-MM-YYYY'),' '),"
					+ " INITIATOR.EMP_FNAME||' '||INITIATOR.EMP_MNAME||' '||INITIATOR.EMP_LNAME AS INITIATOR,APPL_INITIATOR,-1,NVL(APPL_TRVL_ID,' ') "
					+ " FROM TMS_APP_GUEST_DTL"
					+ " INNER JOIN TMS_APPLICATION ON(TMS_APPLICATION.APPL_ID = TMS_APP_GUEST_DTL.APPL_ID)"
					+ " LEFT JOIN TMS_APP_TOUR_DTL ON(TMS_APP_TOUR_DTL.APPL_ID = TMS_APP_GUEST_DTL.APPL_ID AND TMS_APP_TOUR_DTL.APPL_CODE = TMS_APP_GUEST_DTL.APPL_CODE)"
					+ " LEFT  JOIN HRMS_EMP_OFFC  INITIATOR ON(TMS_APPLICATION.APPL_INITIATOR = INITIATOR.EMP_ID )"
					+ " WHERE GUEST_TRAVEL_APPLSTATUS IN('PC','FC')";
		case 86:
			return " SELECT TMS_APPLICATION.APPL_ID, APPL_CODE,APPL_FOR_FLAG,EMP_FNAME||' '||EMP_MNAME||' '||EMP_LNAME AS APPLICANT,NVL(TOUR_TRAVEL_REQ_NAME,' '),"
					+ " NVL(TO_CHAR(TOUR_TRAVEL_STARTDT,'DD-MM-YYYY'),' '),NVL(INITIATOR.EMP_FNAME||' '||INITIATOR.EMP_MNAME||' '||INITIATOR.EMP_LNAME,' ') AS INITIATOR,APPL_INITIATOR,APPL_EMP_CODE,NVL(APPL_TRVL_ID,' ') "
					+ " FROM TMS_APP_EMPDTL"
					+ " INNER JOIN TMS_APPLICATION ON(TMS_APPLICATION.APPL_ID = TMS_APP_EMPDTL.APPL_ID)"
					+ " LEFT JOIN TMS_APP_TOUR_DTL ON(TMS_APP_TOUR_DTL.APPL_ID = TMS_APP_EMPDTL.APPL_ID AND TMS_APP_TOUR_DTL.APPL_CODE = TMS_APP_EMPDTL.APPL_CODE)"
					+ " LEFT  JOIN HRMS_EMP_OFFC  INITIATOR ON(TMS_APPLICATION.APPL_INITIATOR = INITIATOR.EMP_ID )"
					+ " INNER JOIN HRMS_EMP_OFFC ON(HRMS_EMP_OFFC.EMP_ID = TMS_APP_EMPDTL.APPL_EMP_CODE)"
					+ " WHERE APPL_EMP_TRAVEL_APPLSTATUS IN ('CC')";

		case 87:
			return " SELECT TMS_APPLICATION.APPL_ID, TMS_APP_GUEST_DTL.APPL_CODE,APPL_FOR_FLAG,GUEST_NAME AS APPLICANT,NVL(TOUR_TRAVEL_REQ_NAME,' '),NVL(TO_CHAR(TOUR_TRAVEL_STARTDT,'DD-MM-YYYY'),' '),"
					+ " INITIATOR.EMP_FNAME||' '||INITIATOR.EMP_MNAME||' '||INITIATOR.EMP_LNAME AS INITIATOR,APPL_INITIATOR,-1,NVL(APPL_TRVL_ID,' ') "
					+ " FROM TMS_APP_GUEST_DTL"
					+ " INNER JOIN TMS_APPLICATION ON(TMS_APPLICATION.APPL_ID = TMS_APP_GUEST_DTL.APPL_ID)"
					+ " LEFT JOIN TMS_APP_TOUR_DTL ON(TMS_APP_TOUR_DTL.APPL_ID = TMS_APP_GUEST_DTL.APPL_ID AND TMS_APP_TOUR_DTL.APPL_CODE = TMS_APP_GUEST_DTL.APPL_CODE)"
					+ " LEFT  JOIN HRMS_EMP_OFFC  INITIATOR ON(TMS_APPLICATION.APPL_INITIATOR = INITIATOR.EMP_ID )"
					+ " WHERE GUEST_TRAVEL_APPLSTATUS IN('CC')";

			
		case 88:
			return "    SELECT TMS_MONITOR_ID FROM TMS_MONITORING"
					+ " WHERE (MTR_TVL_AVA_STATUS='CD' OR MTR_ACC_AVSTATUS='CD' OR MTR_LOCAL_AVSTATUS='CD')"
					+ " AND  APPL_ID=? AND APPL_CODE=?";
			
		case 89:
			return " UPDATE TMS_APPLICATION SET APPL_STATUS='P' WHERE  APPL_ID=?";
			
		case 90 : return " INSERT INTO TMS_APP_EMPDTL(APPL_ID, APPL_CODE,APPL_EMP_CODE,APPL_EMP_AGE,APPL_EMP_CONTACT,APPL_EMP_ADVANCE_AMT,APPL_EMP_MAIN_APPROVER, APPL_EMP_ALT_APPROVER,APPL_EMP_TRAVEL_APPLSTATUS,APPL_TRVL_ID, APPL_APPROVED_ADVANCE_AMOUNT, APPL_CURRENCY) "
					+" VALUES(?,(SELECT NVL(MAX(APPL_CODE),0)+1 FROM TMS_APP_EMPDTL),?,?,?,?,?,?,?,NVL('TRVL_'||?||'_'||(SELECT NVL(MAX(APPL_CODE),0)+1 FROM TMS_APP_EMPDTL),' '),?,?)";
		
		case 91 : return " INSERT INTO TMS_APP_GUEST_DTL(APPL_ID, APPL_CODE,GUEST_NAME, GUEST_AGE, GUEST_CONTACT,GUEST_ADVANCE_AMT, APPL_EMP_MAIN_APPROVER, APPL_EMP_ALT_APPROVER,GUEST_TRAVEL_APPLSTATUS,APPL_TRVL_ID) "
					+"  VALUES(?,(SELECT NVL(MAX(APPL_CODE),0)+1 FROM TMS_APP_GUEST_DTL),?,?,?,?,?,?,?,NVL('TRVL_'||?||'_'||(SELECT NVL(MAX(APPL_CODE),0)+1 FROM TMS_APP_GUEST_DTL),' ')) ";

		case 92 : return " INSERT INTO TMS_APPLICATION (APPL_ID, APPL_FOR_FLAG, APPL_DATE,  APPL_INITIATOR, APPL_ACCOMPAINED, APPL_APPLCANT_COMMENTS, APPL_KEEP_INFO, TOUR_TRAVEL_STARTDT, TOUR_TRAVEL_ENDDT, TOUR_TRAVEL_REQ_NAME, TOUR_TRAVEL_PURPOSE, TOUR_TRAVEL_TYPE, TOUR_CUSTOMER, TOUR_PROJECT, TOUR_OTHER_CUSTOMER, TOUR_OTHER_PROJECT, APPL_MANAGE_JOURNEY, APPL_MANAGE_ACCOMODATION, APPL_MANAGE_LOCAL_CONV ,APPL_STATUS,APPL_MAIN_APPROVER,APPL_ALTER_APPROVER,APPL_TRAVEL_ID)"
					+ " VALUES(?,?,TO_DATE(?,'DD-MM-YYYY'),?,?,?,?,TO_DATE(?,'DD-MM-YYYY'),TO_DATE(?,'DD-MM-YYYY'),?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

		default:
			return "Framework could not EXECUTE the query number specified";
		}

	}

}
